### ISSUE TITLE
better checks for invalid configs 

### ISSUE THREAD

**Issue by divinity76** [CIDRAM/CIDRAM#10]
talking about this code:

``` php
    /** Attempts to parse the CIDRAM configuration file. */
    $CIDRAM['Config'] =
        (file_exists($CIDRAM['Vault'] . 'config.ini')) ?
        parse_ini_file($CIDRAM['Vault'] . 'config.ini', true) :
        array();
    /** Fallback for any potential parse failure. */
    if (!is_array($CIDRAM['Config'])) {
        $CIDRAM['Config'] = array();
    }
```

1: if the config file don't exist, assume the admin wanted an empty config? ... in my opinion, if the admin want an empty config, he should be explicit about it. it could be a security issue if the admin thought the config file was loaded, but in reality a permission error or whatever caused the config not to be loaded. 

2: if the config file is corrupt, say, some typo, some unclosed string "  in the .ini file, again, do we want to assume the config file was just empty?  ... in my opinion, no, it'd be a security issue if the admin thought the config was loaded, but a syntax error or something caused parse_ini_file to fail. 

ofc, changing this would be backwards-incompatible, but in a good way

**Comment by Maikuolan** [comment]
@dev-101 @DanielRuf If/When you two have a moment to spare, what do you two think about this?

**(2)** makes sense, and probably should be implemented.

Regarding **(1)**, personally, I kind of like the way things are at the moment, because it allows for a quick, easy and lazy way to opt to use the default recommended configuration settings without needing to mess around with files (ie, currently, complete absence of a configuration file will cause the script to rely on the hardcoded defaults, which are the same as the defaults as per the currently included configuration file; this means that currently, users only need to worry about setting up a configuration file if they actually want to deviate from the default recommended configuration settings). That all said, though, divinity76 has a good point regarding this possibly being a security issue (albeit in specific circumstances), but additionally, there is the risk that CIDRAM could behave in ways unexpected by the user if they set a directive in some particular way, and then the configuration file fails to load, causing CIDRAM to default that directive to a value other than the one that they'd set (which could in-turn potentially cause a real headache for debugging in some circumstances).

If we implemented this change, then, that would mean that users would then be required to specifically sort out their configuration files before CIDRAM could work correctly on their systems (meaning, an additional step in the installation process, which could potentially frustrate those users with low technical prowess and/or low PHP knowledge), but with the pay off that this potential debugging headache &#150; as well as any potential related security issues &#150; could be avoided. The other additional consideration, too, is that if we were to eventually implement the installation/configuration wizard/guide/what-have-you idea that we'd discussed earlier, being an additional step in the installation process would become a moot point anyhow.

In any case.. Ideally, I'd like to hear what you two think about this before saying yes or no to this pull request.

**Comment by Maikuolan** [comment]
> ofc, changing this would be backwards-incompatible, but in a good way

Not too worried about that one. It may be slightly so in terms of how CIDRAM is managed/installed/used/etc, but shouldn't be in terms of its dependencies, formatting and overall structure, so.. We could argue that one away if need be (besides, although CIDRAM is _relatively_ stable and is currently being used in active deployment, we're still < `v1.0.0` anyhow, which by the rules of SemVer, technically, would quality it as BETA, and thus, subject to rapid development, so.. I think we're okay on that one). :+1: 

> which could potentially frustrate those users with low technical prowess and/or low PHP knowledge

..In hindsight, possibly also a moot point, in consideration of the frustrations that could be caused by an unannounced problem with the configuration such as the example given ("_some unclosed string " in the .ini file_").

Thinking a little more about this, I'm leaning more towards accepting the PR/suggestion than rejecting it. Still keen to get opinions from others, though, in case there are views/angles/etc that haven't yet been considered.

**Comment by DanielRuf** [comment]
I would be against `die` / `exit` at all and use `trigger_error` and custom exceptions as this is the modern and recommended approach. Adding these checks should be ok and helpful for the setup. `file_exists` and `is_array` are fast enough so imho these checks can stay in this file.

**Comment by dev-101** [comment]
And I am kind of divided here, but slightly leaning towards stricter solution, because those are definitely not "normal" conditions, anyway. Now, it could be handled with die/exit, or custom exception, that is the part I am undecided.

**Comment by DanielRuf** [comment]
`die` / `exit`for logging errors is not recommended anymore and should not be used when you write good code. The right way was always using exceptions or triggering errors using `trigger_error` or log them directly to the error_log using `error_log`. Using `die`, which is also `exit` but just another name, is not very helpful for debugging and checking errors afterwards as these messages do not show up in the logfiles at all ;-)

http://php.net/manual/en/function.trigger-error.php#92016
http://php.net/manual/en/function.error-log.php

But generally thrrowing and catching exceptions is the right way, how they are handled after catching them eg using `trigger_error` and `error_log` with a custom error handler using `set_error_handler` is another part.

http://stackoverflow.com/questions/7063053/php-error-handling-die-vs-trigger-error-vs-throw-exception

**Comment by dev-101** [comment]
> if(!file_exists('config.ini')) {
>   trigger_error ("config.ini file does not exist");
>   exit();
> }

Better?

**Comment by DanielRuf** [comment]
A bit better but `error_log` (not binary safe, message should be encoded before using `error_log`) provides everything we need, it can send the message to the default error_log file of the server, to a custom file or send it via mail. And the function is available in PH 4, 5 and 7.

**Comment by divinity76** [comment]
> Better?

no. `is_readable` is better. `file_exists` check if it can see the file. but don't check if it has permissions to read the file. `is_readable` check both for existence and for permissions to read.

**Comment by DanielRuf** [comment]
> no. is_readable is better. file_exists check if it can see the file. but don't check if it has permissions to read the file. is_readable check both for existence and for permissions to read.

Right

**Comment by divinity76** [comment]
im for trigger_error over die() though  -  and exception over trigger_error.. i never liked the errors, and use an "exception_error_handler" when i can ( http://php.net/manual/en/class.errorexception.php#example )

**Comment by DanielRuf** [comment]
> im for trigger_error over die() though

But keep in mind that depending on the error type it can abruptly stop the execution of the script eg if we trigger a fatal error. We should use `trigger_error` + `error_log` with predefined options (send to default error_log, custom file or email address).

**Comment by dev-101** [comment]
is_writable is not necessary IMHO, usually it will be one-time set via FTP or cPanel, and later admin may decide to modify/remove write permissions.

@divinity76
It was just an example :)

@DanielRuf 
The above will only throw PHP Notice, not Fatal Error.

**Comment by dev-101** [comment]
@DanielRuf 
The above will only throw PHP Notice, not Fatal Error.

**Comment by DanielRuf** [comment]
> is_writable is not necessary IMHO, usually it will be one-time set via FTP or cPanel, and later admin may decide to modify/remove write permissions.

Well it is required to parse the file, otherwise this would fail. And often there are problems with the right permissions for example if people run PHP as CGI which has some more restrictions.

> The above will only throw PHP Notice, not Fatal Error.

Sure, but we should not rely on the default value of PHP and define it directly. PHP API could change this in future (major) releases.

**Comment by DanielRuf** [comment]
> The above will only throw PHP Notice, not Fatal Error.

Sure, but we should not rely on the default value of PHP and definy it directly. PHP API could change this in future (major) releases.

**Comment by dev-101** [comment]
Only in case of users who do not know proper server management, but I am fine with either solution, though.

True about change, but in that case script should be updated as usual. I mean, everything is in the state of constant change, and updates are necessary. That particular change would affect a lot of stuff out there.

error_log() is fine, but it does not do anything about the 'action' that should be done in case of error, correct?

**Comment by divinity76** [comment]
by default, error_log only logs errors yup. (it gets more complicated if you use the extra optional parameters tho)

**Comment by Maikuolan** [comment]
Regarding the way that CIDRAM currently handles errors (ie, with defining the plain-text header and calling `die()`), to put it out there.. We could definitely think about changing this to something better (eg, `trigger_error`/`error_log` + custom exceptions); I'm absolutely open to this idea.

Because CIDRAM is currently still a very young project and because we're currently still < `v1.0.0`, at this time, I'm more interested in improving the script whenever we can find ways to do this than in keeping with old ways of doing things simply for the sake of them being the old ways, so, all suggestions for ways to improve CIDRAM are welcomed and open for discussion. ;-)

**Comment by Maikuolan** [comment]
> But keep in mind that depending on the error type it can abruptly stop the execution of the script eg if we trigger a fatal error. We should use `trigger_error` + `error_log` with predefined options (send to default error_log, custom file or email address).
> 
> Sure, but we should not rely on the default value of PHP and define it directly. PHP API could change this in future (major) releases.

Both these make sense, and I agree.

Considering, too, the wide range of different PHP versions that CIDRAM is currently marked as being compatible with, relying on a default PHP value that could potentially change in the future could be yet another cause of potential debugging headaches.

Anyhow, so far, it's sounding like we're generally leaning towards implementing these suggestions, then (and I tried to ask a few others outside of Github, too; only 3 responses from these, which isn't a lot, but they were all in support of implementing these suggestions), with the only real questions remaining being about the best way to go about doing it.

Currently, everything on the to-do list for `v0.2.0` had been completed, so, if we were to start working on some new changes, it's a suitable time for doing this at the moment. :-)

On that note, for the present time, do you think we should accept the current PR, or would it make more sense to decide on the best ways to handle errors generally first?

(On this, either way works for me).

**Comment by DanielRuf** [comment]
> On that note, for the present time, do you think we should accept the current PR, or would it make more sense to decide on the best ways to handle errors generally first?

The current PR is ok so far but we hsould add some comments about implementing `trigger_error`, `error_log` and so on eg using the `@todo` annotation.

**Comment by Maikuolan** [comment]
Sounds good. :+1: 

I'll approve it now.

I think it's worth leaving this issue open, however, so that we can further discuss these details about implementing `trigger_error`, `error_log`, etc.

**Comment by divinity76** [comment]
in my opinion, the die() error handling is a separate issue unrelated to the PR (even tho i did voice my dislike in the PR)

**Comment by Maikuolan** [comment]
Fair enough.

I'll close this issue now, then. Feel free to start a new issue regarding error handling. :-)
