### ISSUE TITLE
[Question] Best way to include CIDRAM on Nginx? 

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#100]
For a long period of time, I have been a hybrid (Apache+Nginx) user because I was relying on `.htaccess`. But slowly I'm now moving into pure Nginx stack. Even I'm only using Nginx server I still can use `.user.ini` in my apps.

While I was scrolling through the docs of CIDRAM, this line caught my attention:

> If you're using an Apache web server and if you have access to php.ini, you can use the auto_prepend_file directive to prepend CIDRAM whenever any **PHP request is made**.

The "**PHP request is made**" is actually caught my attention. I include CIDRAM in `.user.ini`

In my WordPress setup I'm currently using WP-Rocket cache plugin + [Rocket-Nginx](https://github.com/maximejobin/rocket-nginx). Rocket-Nginx is a Nginx configuration for the WordPress cache plugin WP-Rocket. It enables Nginx to serve directly previously cached files **without calling WordPress or any PHP**.

So, if any previous cache file exist, **Nginx won't call PHP or WordPress**, instead it will serve directly the cache files (massive performance improvements).

So, my question is in this case CIDRAM won't be called, right? If I'm right then what can be done in this scenario? How can I include CIDRAM ?

**Comment by harryqt** [comment]
**Update**: The main reason I wanted to move from Apache to native Nginx because I wanted to use "Rocket-Nginx" because I didn't wanted to call PHP or WordPress for cached pages.

But even if I somehow manage to include CIDRAM, then PHP gets called anyway.
So, looks like I'm back to square one.. hahaha.. 🙃

**Comment by dev-101** [comment]
One way is through your server config, to include php file (apache) or redirect all requests to php (nginx):
https://serverfault.com/questions/599776/nginx-serve-one-specific-php-script-for-all-html-requests

CIDRAM should manage redirect later. I am just posting it here, never tried myself and not sure if it would work.

-------------------------------------------------

Another option is to change nginx config to process all .html as .php and use prepend file as before (but, you probably didn't want that).

**Comment by harryqt** [comment]
Closing this ticket.

As it turns out, if I wants to use "Rocket-Nginx" then CIDRAM can't be used. The whole purpose of Rocket-Nginx is remove PHP calling and CIDRAM relies on PHP. I can't have it both ways.

Another options would be CIDRAM like firewall but on Nginx level. But I hardly think there is any available.

**Comment by Maikuolan** [comment]
Yeah.. I think you're correct there in your thinking. Something at the server-level would be better in this case than something that works at the PHP-level, I think.

Something like [Nginx WAF](https://www.nginx.com/products/nginx-waf/) could be a good idea maybe. I haven't tried myself before though, so I don't have any personal experience with it, plus I don't think there's any free version of it available (other than the trial version, of course), so adopting it would likely incur some costs.

Quite possibly there are other solutions available too, but I would need to do some more research before I could recommend anything specific, I think (i.e., it's been a while since I last checked, so I'm not entirely sure comprehensively what's available insofar as server-level firewalls for Nginx go at the moment).

**Comment by harryqt** [comment]
After turning Google upside down, the closest one I could find is [nginx-ultimate-bad-bot-blocker](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker), although it's just block bad bots, not bad IP's.

For the time being, I'm going to skip Rocket-Nginx and keep using CIDRAM because Firewall is much more important for me.
