### ISSUE TITLE
Log file lost all previous entries of this month

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#127]
Hello.

I use monthy logs. 

logfile='{mm}-{yyyy}.log'

Today June log file is starting from ... today  7th. Everything else is lost somehow (a week ?). The other montly logs 3 months back, seem allright.

ID: 16409
Script Version: CIDRAM v1.13.0
Date/Time: Fri, 07 Jun 2019 09:53:20 +0300

**Comment by 737simpilot** [comment]
It might help to know what server software you're using. Can't say I ever encountered this with running CIDRAM.

**Comment by Maikuolan** [comment]
One possibility that comes to mind, is whether your host implements its own security solutions at the server level, and whether any of these solutions might be a little overzealous in what they deem as a potential threat.

I've seen this happen before a few times before.

A family member's website, that I help manage, had some files deleted like this. Turned out, that the host had some "security" solutions running in the background, that would automatically delete *any* file from an account, no matter what it was, if that file was modified more than X number of times per day (I guess, they thought that it must've looked similar to behaviour exhibited by some types of trojans and backdoors; only way I could rationalise it, anyway). I got pretty annoyed at the host over that, and never managed to resolve the problem with them, but ended up just writing some custom solutions specifically for that website, to avoid the problem arising in the first place (writing multiple, separate files, and concatenating them at a later date, for example). Would've immediately changed hosts if it had've been my own website, but due to that it wasn't my site, and I was merely helping to manage it, the decision wasn't mine to make.

Another time, the host had implemented a file scanner to scan everything on the entire server, was snooping around what was on the account, saw the file, didn't know what it was, and stupidly decided that they would delete it, simply for the reason that they didn't know what it was (and therefore, in their mind, must've been dangerous).

Definitely not normal things to happen, and hopefully not what's happening here, but might be worth checking whether there's anything stupid like that going on at the server, just in case.

Otherwise though, not sure currently what could be causing data to suddenly disappear like that offhandedly.

**Comment by eurobank** [comment]
I'm using Litespeed server on a very-very good hosting for 6 years now. I don't think something is wrong in the hosting / server level. I have done all kind of strange things and never had any problem. ZBBlock included for a couple of years.

Anyway, i will keep an eye to that and see if it happens again. 

Could this problem be related to the "numbering" problem i also saw ?

(the file didn't dissapear, i think it got overwritten by a new one)

**Comment by Maikuolan** [comment]
> Could this problem be related to the "numbering" problem i also saw ?

After I wrote my previous reply, I was thinking of that a little, too.

I'll investigate a little more on my site, to see whether I can replicate it, or something similar.

**Comment by eurobank** [comment]
I'm closing this since it didn't happen again.

**Comment by Maikuolan** [comment]
Okay. :+1:

Glad to hear that it hasn't happened again. I'm still not entirely sure why it happened the first time though. Anyway, hopefully it doesn't happen again in the future, but if it does, feel free to reopen the issue. Meanwhile, if I find anything that could indicate the reason that it happened the first time, I'll see what can be done about it.
