### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#14]
I've managed to get [CIDRAM listed in the plugins database for Wordpress](https://wordpress.org/plugins/cidram/developers/), which I think is a step in the right direction for greater distribution/reach for CIDRAM. :-)

Quick question to the others that've contributed to the project: Do any/all of you have account IDs with Wordpress.org? (Note: It's a different account system to the Wordpress.com website). The reason that I ask this is due to that there's a "[Contributors](https://wordpress.org/plugins/about/faq/)" field provided as part of the syntax for the metadata they derive from plugin READMEs for displaying on each plugin's page within their listings, and it could be good to get some of you listed there if you do (and assuming that you'd like to be listed, of course).

@DanielRuf @divinity76 @m7mdtiger @dev-101 @Gaffnet
(..Not sure the Github usernames for any of the others that've helped out).

**Comment by DanielRuf** [comment]
So far I have no WordPress.org account, I think so.

**Comment by dev-101** [comment]
Thanks Maikuolan, yes I do have an account there, but no, there is no need for mentioning in contrib, as so far very little work was done here in contrast to what I want due to the lack of time. Relax :)

As of WP plugin, a nice add-on for sure, although personally not something I would use, as I execute this kind of scripts at much earlier stage, before WP plugins gets executed.

But sure/hopefully, you will get some attention and contributions from the users this way.

**Comment by Maikuolan** [comment]
Cool, no worries. :-)
