### ISSUE TITLE
wordpress cron & cidram problem

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#147]
ubuntu 18

CIDRAM version used: 2.2.0

SAPI used: fpm-fcgi

PHP version used: 7.2.22-1+ubuntu18.04.1+deb.sury.org+1

---
## Issue
Im running wordpress cron as a server cron
/usr/bin/php /var/www/wp-cron.php >/dev/null 2>&1 every 10 min
i have to run it 
as a plugin i have installed needs it to run

but i get this in the logs every time the cron runs so about 1,000's + of times a day

Script Version: CIDRAM v2.1.0
Date/Time: Fri, 06 Sep 2019 22:25:01 +1200
IP Address: 
Signatures Count: 3
Signatures Reference: botspiders_cidram.inc:L87, module_ua.php:L23
Why Blocked: Invalid IP, Suspected bot detected!, Empty UA!
Reconstructed URI: http://Unknown.Host/

when i turn off the cronjob it doesnt show but when turned on it show in the logs

also I have white listed my server ip's etc but still get this 

any tips to fix this
thanks

**Comment by Maikuolan** [comment]
Hi @bigalownz,

Just replying quickly to let you know that I've seen this issue. I've been a little busy today due to visitors and some other commitments, but I plan to respond to this issue in more detail when I've got a moment, either later tonight or early tomorrow morning. Thanks for your patience. :-)

**Comment by Maikuolan** [comment]
I'm thinking I'll try implementing [wp_doing_cron()](https://developer.wordpress.org/reference/functions/wp_doing_cron/) for the next CIDRAM release, to avoid CIDRAM performing its usual checks when executing as a cronjob. That should, in theory, solve the problem, without users needing to doing anything themselves.

I'm hoping to tag the next version/release either later today or tomorrow at some point, so I'll message here again when it's ready (after which, simply updating to the latest version should solve the problem).

**Comment by Maikuolan** [comment]
Done. :-)

If you update via the WordPress plugins dashboard, simply updating to the latest CIDRAM version (2.2.0) should fix the problem (but note that any customisations, like installed modules and so on will be reverted if updated in that way, due to that the WordPress updater just replaces the entire installation rather than replacing just the changed files).

If you update via the CIDRAM front-end updates page, nothing will be reverted (so, that way is safer for retaining customisations, installed modules, etc), but there's one specific file that you'll need to patch manually, in order for the problem to be properly fixed: "cidram.php". You'll find your copy of the file located in CIDRAM's base directory, alongside the loader, README file, LICENSE file, etc. The copy you'll need to patch it with, you won't find in this particular repository here, but you can find it at the WordPress SVN upstream for CIDRAM <[here](https://plugins.trac.wordpress.org/export/2166911/cidram/tags/2.2.0/cidram.php)>.

**Comment by Maikuolan** [comment]
When you've got a moment, let me know how it goes, and whether any problems persist. Cheers.

**Comment by bigalownz** [comment]
sorry forgot to say I am not using  the cidram wordpress plugin

but cidram as normal with "require(dirname(__FILE__).'/cidram/loader.php'); " line added to wp-load.php

**Comment by Maikuolan** [comment]
Ah, ok.. No problem. :-)

Probably don't need to update anything at CIDRAM then, so disregard previous instructions.

In your `wp-load.php` file, if you check where these lines occur:

```PHP
	define( 'WPINC', 'wp-includes' );
	require_once( ABSPATH . WPINC . '/load.php' );
```

Does your `require(dirname(__FILE__).'/cidram/loader.php');` line occur *before* or *after* those lines?

**Comment by bigalownz** [comment]
its right at the top after < ?php

before
 define( 'WPINC', 'wp-includes' );
	require_once( ABSPATH . WPINC . '/load.php' );

**Comment by Maikuolan** [comment]
Awesome. :-)

So, best solution here, I think, would be to wrap the CIDRAM hook with a check for `DOING_CRON`, like so:

```PHP
if (!defined('DOING_CRON')) {
    require(dirname(__FILE__).'/cidram/loader.php');
}
```

Give that a try and let me know how it goes.

**Comment by bigalownz** [comment]
looks like that fixed it

so far nothing in the logs just waiting for a bad bot to enter site

**Comment by bigalownz** [comment]
just a note

every thing works fine now
thanks for your help

**Comment by Maikuolan** [comment]
Glad to hear it! And you're welcome. :-)
