### ISSUE TITLE
Notice: Undefined variable: BytesRemoved

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#153]
When trying to uninstall a component getting this notice.

> Notice: Undefined variable: BytesRemoved in C:\www\cidramv2\vault\frontend_functions.php on line 1894

![chrome_2019-12-10_19-41-00](https://user-images.githubusercontent.com/18257605/70536592-04010f00-1b85-11ea-99f0-37e8bcc30634.png)

**Comment by Maikuolan** [comment]
Investigating now. Will reply back soon.

**Comment by Maikuolan** [comment]
Found the problem. Working on a fix now.

**Comment by harryqt** [comment]
Wow, that was quick. 😅

One more question, do I need to copy `compat_bunnycdn.php` from v1 to v2? Or cidram can automatically take care of it?

**Comment by Maikuolan** [comment]
CIDRAM can automatically take care of it. :-) :+1:

**Comment by harryqt** [comment]
Well, that's certainly not the case. That is why I asked. Opening another issue.

**Comment by Maikuolan** [comment]
Fixed. :-)

Updating to the latest commit should get rid of that notice.

**Comment by Maikuolan** [comment]
> Well, that's certainly not the case. That is why I asked. Opening another issue after some time.

Normally, after repairing, the `compat_bunnycdn.php` file should reappear in the vault automatically. Do you see it there, or is it missing? And does it show as active/inactive, installed/uninstalled at the front-end updates page?

(If it appears there and shows as active, then it should be working properly. Otherwise, if it doesn't appear there, or isn't showing as active, then there could be something wrong there, so yeah; we should create a new issue for it).

**Comment by Maikuolan** [comment]
(As the BunnyCDN issue is now continued at #154, and the original subject of this issue here has now been resolved, I'll close this issue here now).
