### ISSUE TITLE
No install button for "Empty UA blocker module"

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#157]
I don't use it so no big deal for me but I thought I should let you know.

![chrome_2019-12-14_13-17-42](https://user-images.githubusercontent.com/18257605/70845397-33a96300-1e74-11ea-9a2c-3ad24d85b698.png)

**Comment by Maikuolan** [comment]
I appreciate the attentiveness; Cheers. :-)

In this particular case, it's not a problem. I recently deprecated and removed the empty UA blocker module in favour of adding an option into the optional security extras module to be able to optionally block empty UAs instead.

Basically, it's still showing in the list at the moment, but showing *"Unable to determine"* for the latest version information and not providing the option to install it, because metadata for the module still exists at the downstream (meaning that the updater is aware of its existence, or former existence in this case) but corresponding metadata can't be found at the upstream anymore (due to being removed), meaning that the updater wouldn't be able to install it anyway.

The empty UA blocker module should eventually disappear from the available modules list during automated routine metadata cleanup, but that process is normally triggered after updating one of the modules connected to the particular metadata file to be cleaned up, so it may be a while (no doubt, I'll update my modules again at some point in the future, but I don't have any updates for them pending or planned at this particular time).

**Comment by harryqt** [comment]
Thank you for the explanation, appreciate it.
