### ISSUE TITLE
$InstaBan behaviour change

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#160]
In checking my blocks today I noticed that $InstaBan blocks are being recorded in tracking, but there is nothing in the log. 
Forbid on block is set to 403 as is ban override

my memory is the initial instance was logged ?

**Comment by Maikuolan** [comment]
Might be the current setting for [log_banned_ips](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#log_banned_ips).

> Include blocked requests from banned IPs in the logfiles? True = Yes [Default]; False = No.

Is that configuration directive current set as true or false?

**Comment by mikeruss1** [comment]
yes thats it.

the problem is that with that setting be false, in the case of an $Instaban block, there is no record of the IP being blocked, apart from tracking. Difficult if you want to check a new $Instaban is working.

if you set it to true, the log gets filled with rubbish.

could you review it to see if its possible for the first block only to be logged ? Not urgent.

thanks

**Comment by Maikuolan** [comment]
> yes thats it.

Cool cool. :-)

> could you review it to see if its possible for the first block only to be logged ? Not urgent.

I'll need to think on this a bit, to figure out the best way to proceed, whether possible, etc. I'll leave this issue open and reply back either tomorrow or within the next few days.

**Comment by Maikuolan** [comment]
So.. More than a year later, I know this is late to address this, but.. As a side effect of various other changes implemented over the past year, particularly changes implemented to the auxiliary rules system, I think it may now be possible to achieve the results desired here without the need to implement any further changes.

The first step, if we were to firstly enable `log_banned_ips`, we'll be able to start logging the insta-banned requests.

Then, we just need to deal with this:

> if you set it to true, the log gets filled with rubbish.

The side effects I mentioned.. Since after the time that this issue was first created, the auxiliary rules system now includes the action to suppress logging for any requests matching the given rule (the "don't log" action). It also now includes "infractions" as an available condition. But, the value available for the infractions condition is counted for the number of infractions the given IP address has accumulated, according to the IP tracking system, since *prior* to the particular request being processed.

I'm thinking we could exploit that to allow the desired results of logging the first request from an insta-banned IP address, while not logging any subsequent requests from the given insta-banned IP address.

So, the second step would be to create an auxiliary rule, which matches against the infractions threshold (my own modules specify 1,000 infractions, intentionally a ridiculously high number as a means to ensure the desired result, no matter how high the end-user sets the value for the `infraction_limit` configuration directive, as long as said end-user doesn't set something even more ridiculously high; though, for the sake of creating this new auxiliary rule, I would recommend using a value equal to whatever has been set for `infraction_limit`).

Since we're dealing with a integer/number value instead of a string/text value, we'll need to indicate that to the auxiliary rules system. So, the condition for the new rule should match against `Infractions`, with a value like `>=1000` (replacing the `1000` with whatever `infraction_limit` has been set to; the `>=` tells the auxiliary rules system to treat the value as an integer/number, and match if the value is "greater than or equal to" the integer/number in question).

"Direct string comparison" must be used for this, since it's the only matching method that'll allow us to properly instruct the auxiliary rules system to check the value in terms of "greater than or equal to", instead of as simply in terms of "equal to" (or "not equal to").

And the action for the new rule, of course, will be the "don't log" action.

Once that's been done, the desired result should be achieved (in theory).

But.. TBH, I haven't tested any of this yet, so we won't know for sure until we try it out. '^.^

Let me know whether this seems a decent enough solution or not, and if so, whether it works out or not. :-)

**Comment by mikeruss1** [comment]
OK good - patience is a virtue
will test it along with #199

**Comment by Maikuolan** [comment]
@mikeruss1 How'd it go? :-)

**Comment by mikeruss1** [comment]
still on the list, will get there .....

**Comment by mikeruss1** [comment]
not done a compound maths before with auxiliary rules. To test Infractions >=4
set to = and the value is " …≥,4"
is this correct ?
thanks

**Comment by Maikuolan** [comment]
Yep, correct. :-)

**Comment by mikeruss1** [comment]
thanks done, waiting for bad guys to pass by

for #199 - check understanding
set condition to profile the request
set Why Blocked to *Cloud service*
set other options to disable tracking

it should then do whatever it was going to do, but tracking is off?
 can I ask, what is "Why blocked detailed"?

**Comment by mikeruss1** [comment]
the initial event is logged correctly. All further 10 events are also in the log shown as Banned. Tracking is correct showing 10,000 infractions.
the auxiliary rule is as follows ....
If the following conditions are met, don't log the request.
Infractions = …≥,4
Use direct string comparison to test the conditions.

**Comment by Maikuolan** [comment]
> it should then do whatever it was going to do, but tracking is off?

Yep. :-)

> can I ask, what is "Why blocked detailed"?

Whenever a request is blocked, CIDRAM normally provides two indicators about the reason for the request being blocked; a shorter one, and a longer one.

For example: When the shorter message shows *"Cloud service"*, the longer messages shows *"Your access to this page was denied because your IP address is recognised as belonging to a cloud service, and connecting to this website from cloud services isn't permitted by the website owner."*. When the shorter messages shows *"Malware"*, the longer message shows *"Your access to this page was denied due to malware concerns relating to your IP address."* On some occasions (e.g., some of the modules), the shorter and longer messages can be exactly the same, but typically are different in the case of the default signature files. The *"Why blocked detailed"* refers to the longer message. :-)

> If the following conditions are met, don't log the request.
> Infractions = …≥,4

Might be that comma causing the problem, I suspect. Try getting rid of the comma, so that it'll show as `≥4`, instead of `≥,4`. Let me know how it goes. :-)

**Comment by mikeruss1** [comment]
no change still logging where infractions greater than 4
If the following conditions are met, don't log the request.
Infractions = …≥4
Use direct string comparison to test the conditions.
Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.

the yaml is ....
Log 1 for Instaban:
 Logic: "Any"
 Don't log:
  If matches:
   Infractions:
    - 0xe280a6e289a534

**Comment by Maikuolan** [comment]
Sorry, had forgotten to reply to this earlier.

I'm not quite sure how it ended up like that, but where it says:
```
 - 0xe280a6e289a534
```

Try manually modifying to this:
```
 - >=4
```

..and see how it goes. :-)

**Comment by Maikuolan** [comment]
Issue hasn't been active for a while now, so I'm assuming it's resolved. Marking and closing.
