### ISSUE TITLE
Block Google Gadget

### ISSUE THREAD

**Issue by alamrekane1** [CIDRAM/CIDRAM#168]
Access is blocked when checking url from google gadget
https://support.google.com/webmasters/answer/9012289?hl=en
The reason for the ban
```
IP Address: 78.46.16.x
Signatures Count: 1
Signatures Reference: 78.46.0.0/15, functions.php:L1653, functions.php:L1960
Why Blocked: Generic ("Hetzner Online GmbH", L451: F3, [DE]), Fake Googlebot, IP Server Hetzner!
```
The issue is resolved when Ignore this is enabled
Hetzner Online GmbH

**Comment by Maikuolan** [comment]
Thanks for the information, and for letting us know about this. :+1:

The "Fake Googlebot" message in the block reason is interesting, because that would suggest that the blocked requests are claiming to be from Googlebot, and Googlebot doesn't normally operate from Hetzner (Googlebot has its own, dedicated ranges, owned by Google).

Any idea which "user agent" the requests used by any chance?
