### ISSUE TITLE
Facebook false positive

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#170]
Reported at our Gitter channel (*CC: @737simpilot*):

```
ID: 1581086968-955487-4900087445
Date/Time: Fri, 07 Feb 2020 07:49:28 -0700
IP Address: 2a03:2880:30ff:3::face:b00c
Hostname: fwdproxy-lla-003.fbsv.net
Signatures Count: 1
Signatures Reference: functions.php:L1163
Why Blocked: Fake Facebook external hit!
User Agent: facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
Reconstructed URI:
```

Haven't yet been able to replicate the problem at my end. Creating this issue to ask whether anyone else has experienced anything similar. Seeing as I haven't been able to replicate the problem, I figure that if others have experienced the same problem, I might be able to gather more information about the problem by asking them for details about their experience with it. So, anyone? Cheers. :-)

And, if not, no worries (after all, we're talking about a problem, so strictly speaking, it's a good thing if others haven't experienced it.. :D but yeah.. if anyone has, I'd like to know about it, in order to help get to the bottom of it).

**Comment by 737simpilot** [comment]
Would it help to give you a copy of my installation for testing?

**Comment by 737simpilot** [comment]
Another thing I see is that the Facebook hits are getting logged at AbuseIPDB as a fake Facebook hit.

**Comment by mikeruss1** [comment]
more info ..
facebook registered IDs are on project honeypot as well, I have recorded a bunch of them including ...

https://www.projecthoneypot.org/ip_66.220.149.30

note it has a collection of user ids including facebookexternalhit

**Comment by Maikuolan** [comment]
> Would it help to give you a copy of my installation for testing?

Possibly.. It might help. Hold off on sending it for the moment though; I'll think on it a bit reply back later. Still wrapping my head around the best way to diagnose the cause of this problem at the moment; wondering whether it's the actual installation which has a problem, or whether it might be some network routes that have a problem, or something else.. not sure yet.

> Another thing I see is that the Facebook hits are getting logged at AbuseIPDB as a fake Facebook hit.

I mean.. technically, normal behaviour, and not normally a problem.. but given that these aren't actually fake Facebook hits, a bit of a problem in this case. :-/

I'm *reasonably* sure that AbuseIPDB whitelists Facebook's ranges (just from memory.. haven't double-checked this though; might be wrong), so it *probably* won't be a problem for other users, but we'll probably want to try to remove those submissions at some point, once we figure out exactly what's going on and solve the problem.

> more info ..
> facebook registered IDs are on project honeypot as well, I have recorded a bunch of them including ...
>
> https://www.projecthoneypot.org/ip_66.220.149.30

Interesting.. That one looks like a legitimate Facebook IP address, too. Curious what's going on there, to end up having it being flagged by Project Honeypot. The "C" and "R" flags applied to it represent "comment spammers" (C) and "rule breakers" (R), I think (the former being self-explanatory; the latter referring to bots that break standards, that don't honour `robots.txt`, etc.. or so I assume, at least).

**Comment by 737simpilot** [comment]
The one thing I thought of was with my use of CloudFlare. Before I never bypassed the CIDRAM directory to omit caching in CloudFlare and CIDRAM still worked fine with no issues. So just recently I created a page rule in CloudFlare to omit the CIDRAM directory from being cached just for the hell of it. Probably for the best because you never know and any future issues involving a cache. But despite this I'm still seeing Facebook blocks, and it's only for one website I run as well. I may go into the access log and see if Facebook is hitting my other site and getting a 200 or not. But, I rarely got Facebook hits that I'm aware of until now and these blocks. I do have several months worth of access logs backed up just in case I needed them. I can go back and see if there were any 200's or 403's for Facebook and which sites if that helps weed this issue out. 

Yeah, as to AbuseIPDB, I logged in to see all my reports and saw a bunch of Facebook IPv6 addresses there and I was the only one reporting them. So I deleted those reports. I'll go back in once in a while and delete any others that may end up there as well. I did see one IP from the American telecommunications giant AT&T come up with a fake Facebook hit though which I thought was interesting. Obviously, that's not Facebook and their ASN.

**Comment by Maikuolan** [comment]
> Obviously, that's not Facebook and their ASN.

Yep. :-)

Facebook's own guidelines (which CIDRAM follows) states that to verify whether a Facebook request is legitimate, to simply confirm whether it originates from their ASN. So, from their ASN = legitimate. Not from their ASN = Not legitimate. AT&T = Not their ASN, so, that report can definitely stay. :+1:

**Comment by 737simpilot** [comment]
Okay, looking at January's and the current February log I see that my main site got a one and only Facebook hit on 10 January which was a 200.

On my other site I see that there are at least 37 Facebook hits and all 403 starting from 5 February. 

That is the same site that got one AT&T IPv4 hit that was a fake Facebook bot and another IPv6 AT&T fake Facebook hit.

So me thinks something happened between Jan 10 and Feb 5 to cause these Facebook blocks. 

I have checked to repair the CIDRAM files and nothing was repaired. All checked out.

I have to wonder if a smartphone is in play here somehow.  Because this site that is getting the Facebook blocks is largely browsed with smartphones and knowing how stupid Facebook is  and Apps it could be something network related with a smartphone. Let me check my database for Facebook IPs.

**Comment by 737simpilot** [comment]
And no database matches for the Facebook IP I logged on 5 Feb.

**Comment by Maikuolan** [comment]
TBH, I've still got no idea about this one, and haven't actually encountered the problem at my end at all yet. @737simpilot Anything new at your end these past few months, or should I just go ahead and mark this one as resolved? Thoughts?

**Comment by 737simpilot** [comment]
I should have closed this months ago. What I did was just ban all of Facebook's ASNs in CloudFlare and called it a day. I have no use for Facebook so screw 'em. LOL

**Comment by Maikuolan** [comment]
Sounds good. I'll go ahead and close it then. :-)
