### ISSUE TITLE
Whitelist everything related to Google

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#175]
Full list of Google bots: https://support.google.com/webmasters/answer/1061943?hl=en

All of them should be white listed no matter the case is.

**Comment by Maikuolan** [comment]
Cheers. :-)

I'll take a closer look through the list tomorrow.

**Comment by Dibbyo456** [comment]
Hi, any updates on this..?

**Comment by 737simpilot** [comment]
I would think Google et al would already be whitelisted via rDNS already. https://developers.google.com/search/docs/advanced/crawling/verifying-googlebot?hl=en

Is there something specific not being allowed?

Note what it says, "These values can be spoofed. If you need to verify that the visitor is Googlebot, you should use reverse DNS lookup. "

So this has to be done very carefully. If it's already bypassed it'd be helpful to know what you have there that is not going through.

**Comment by Maikuolan** [comment]
> I would think Google et al would already be whitelisted via rDNS already. 
> https://developers.google.com/search/docs/advanced/crawling/verifying-googlebot?hl=en

Search engine verification covers Googlebot, but not many of the various other user agents mentioned by the article (since they aren't Googlebot, and aren't search engines).

The problem is, for some of those user agents, I've never actually seen any requests from them, neither prior to this issue being created nor since, blocked or otherwise, and I haven't been able to find any publicly accessible access logs, or any other related information from which I would be able to write some effective bypasses or any kind of verification solution for.

I *could* outright whitelist on the basis of just the mentioned user agents *alone*, but the danger in that, is that any endpoint, legitimate or otherwise, could then simply cite any one of those user agents to effectively turn CIDRAM off for themselves entirely. So, if say, a hacker, a spambot, or whatever else discovers about those user agents being whitelisted in CIDRAM, without any kind of verification process in play, they could simply opt to cite that user agent for themselves to ensure that they don't get blocked by CIDRAM. That's why it's best, if at all possible, to include some kind of verification process, or some other kind of data point alongside the whitelisted user agent before whitelisting the request in question.

If anyone really wanted to whitelist those user agents at this point anyway, even if it's just on the basis of a single data point (the user agent alone), I could write a quick module to do that. Just let me know if so. :-)

In any case, I'm happy that the list was linked here, since it provides a kind of reference material in its own right, so that if we ever do encounter any of these, and they end up being unwantedly blocked, we'll immediately have some information available to us about alternative user agents used by the same bot/crawler/etc, some idea about what it is and so on. I'm thinking I'll add the *Info* label to this issue for that reason.

We can keen an eye out for any of the mentioned user agents, I guess, and then deal with it at that time.
