### ISSUE TITLE
Delist 172.93.48.0/21

### ISSUE THREAD

**Issue by mattgconnor** [CIDRAM/CIDRAM#18]
Hi Caleb,

We (SSD Nodes) just acquired 172.93.48.0/21

As you can see here, the registration date is yesterday: https://whois.arin.net/rest/net/NET-172-93-48-0-1

Can we get this range delisted from your blacklist?

Thank you for your time,
Matt

PS I tried looking for your email address to message you directly, I apologize if this is the wrong place.

**Comment by Maikuolan** [comment]
Hi Matt,

No problem about the location; The issues page here is intended for any support matters relating to CIDRAM, so, as long as no confidential information is involved (due to that conversations here can be seen publicly), you've got the right place (and in cases where confidential information is involved, I can provide more secure channels upon request). :-)

<strike>May I ask which signatures appear to be listing this range from what you're able to see? Testing the latest version of the signatures on my end, this range doesn't appear to currently be listed (as far as I'm able to ascertain).</strike>

If someone is using a copy of CIDRAM which currently lists this range, it's possible that their signatures may be outdated.

Kind regards,
Caleb.

**Comment by Maikuolan** [comment]
(In follow-up to my above reply).

Actually, determining which signatures were listing this range won't be necessary now; I've just double-checked through some of the more recent previous versions of the CIDRAM signatures, and I've found that this range was previously listed by the signatures between April 19th 2016 and December 24th 2016 as part of VegasNAP, LLC (ASN 53340). The range was delisted on December 24th 2016 and shouldn't exist in the current, up-to-date version of the signatures.

Let me know if the problem persists or if there's any other related issues.

Thanks.

Kind regards,
Caleb.

*Edit: Typo.*

**Comment by DanielRuf** [comment]
@mattgconnor you are a cloud hosting provider and not a normal ISP for private customers, right?

```
… including (but not limited to) traffic from non-human access endpoints, cloud services …
```

So generally most hosting providers are blocked by default.

The IP range is already delisted like @Maikuolan already wrote. See the following diff between the commits https://github.com/Maikuolan/CIDRAM/commit/a246f6428d939c61afcfc2244b649214c7553d81 and https://github.com/Maikuolan/CIDRAM/commit/0a9a93048d17643eebe07ca4c76d0d548f4a35ca.

https://github.com/Maikuolan/CIDRAM/compare/0a9a93048d17643eebe07ca4c76d0d548f4a35ca...a246f6428d939c61afcfc2244b649214c7553d81#diff-72def2f081122e828a69f7c80c53d32dL7224

**Comment by Maikuolan** [comment]
Although this is an old, closed issue now, I'm replying again to add some new information, and because I've noticed that this range (`172.93.48.0/21`) seems to have been relisted during a recent update to the listings for Incero LLC (AS54540), due to that we've already been maintain listings for this ASN for some time now and this range seems to now be being announced by this ASN.

Taking in mind that due to the way that CIDRAM works, it only blocks standards HTTP(/S) requests, and any listings here won't affect anything else (email, FTP, etc). The intention of our cloud listings (i.e., anything listed in the `ipv4.dat` or `ipv6.dat` files) is to block unwanted/undesirable requests from cloud services, due to that requests from cloud services, when not specifically solicited/requested from a website owner, often tend to be originating from spambots, hacktools, etc. Due to that such services don't tend to usually contain human endpoints (i.e., aren't providing direct domestic internet connectivity), it isn't generally expected that blocking such listings should have any negative effect on end-users, and so, the bar/criteria for being listed with our cloud listings tends to be somewhat lower than the bar/criteria for our ISP listings, for example.

In the case of Incero LLC, there's both historical and current listings on numerous blacklists/databases elsewhere demonstrating spam events to forums, blogs, Wordpress sites, Joomla sites, etc. Some of these spam events originate from IPs from within the range in question, actually (**[172.93.54.79](https://cleantalk.org/blacklists/172.93.54.79)** is an example of one such IP, among others).

It is not the intention of these listings to block benign services (for example, cloud APIs, analytics tools, or anything actually requested/solicited by website owners), and when we become aware of these, upon request, usually, we can write bypasses or exemptions for such services. Unidentified or unverifiable services, when originating from a listed range, are usually assumed to be unwanted for safe measure, but, if there are any specific services from within this range that you think should be bypassed or exempted, let us know.

Thanks again.
