### ISSUE TITLE
CIDRAM wordpress plugin v 2.4.2 problem after update

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#180]
ubuntu 20.04
php 7.4.7
CIDRAM version used: 2.4.2
wordpress 5.4.2

problem only with cidram WordPress and not with standalone cidram install

I notice a few problem after updating cidram plugin in word press

logs are normally in var/www/wp-content/plugins/cidram/vault
but now are in 
/var/www/var/www/wp-content/plugins/cidram/vault

also 
update has overwritten all files eg  config.ini and all removed all extra modules

**Comment by Maikuolan** [comment]
> logs are normally in var/www/wp-content/plugins/cidram/vault
> but now are in
> /var/www/var/www/wp-content/plugins/cidram/vault

That particular bug has now been fixed (d3a04499469a96ebb31f8549dfefc49e742f253f). :-)

I've pushed the fix to the main repository here, but haven't yet pushed it to the WordPress SVN system (I'll see to doing that some time tomorrow, I think).

> also
> update has overwritten all files eg config.ini and all removed all extra modules

That particular problem is closely related to #135. Still something I need to figure out properly at some point; Not entirely sure yet the exact best way to go about it. I could try to see about requesting some extra hooks at WordPress (but I doubt they'd approve it somehow). Otherwise.. I'll probably need to consider just building a completely separate version of CIDRAM for WordPress, maybe. Not sure. Anyway, I'll address that at #135 once I can figure something out.
