### ISSUE TITLE
Question about including the script

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#181]
Hello.

This is more a question and not an issue. I'm using CIDRAM with a popular php script. For technical reasons i include CIDRAM via "load.php" file of the script (like the wp-load.php in Wordpress), using Require.

The question is if i gain something using Require Once and not Require. 

Thank you!

**Comment by Maikuolan** [comment]
As a general rule of thumb, I would recommend, for any scripts/packages/etc which only need to execute once per request, to use `require_once`, instead of `require`. In the event that the particular line of code where the `require` occurs is reached multiple times per request (such as, if it occurs within a function, method or procedure, which is called at multiple points or multiple times throughout where implemented), the relevant attached code will execute multiple times. If that code has a noticeable performance footprint (i.e., if it's slow, or uses up a lot of processor cycles), having it execute multiple times will make things all the more slower and less performant. However, using `require_once` means that it will only be executed once, no matter how many times the particular line of code where that `require_once` occurs (until, of course, the next request). That's all as a general rule of thumb.

But.. in the case of CIDRAM, whether you use `require` or `require_once`, actually shouldn't make any difference at all. I would still recommend `require_once` as a general "best practice", but realistically, it makes no practical difference at all for where CIDRAM is concerned. The reason it makes no practical difference is that when CIDRAM is called, before doing anything else, it checks for the existence of a small "flag", which is intended to tell CIDRAM whether it has already executed before for the request at hand. If the flag exists, instead of running through its usual execution chain, CIDRAM just immediately finishes, avoiding any needless processor cycles and time wastage. If the flag doesn't exist, CIDRAM sets it, and then begins its usual execution chain. :-)

**Comment by eurobank** [comment]
Many thanks, crystal clear.

**Comment by DanielRuf** [comment]
In general I would also use auto_prepend_file to load it before all other scripts.

**Comment by eurobank** [comment]
@DanielRuf 

Sure but auto_prepend is already in use for Firewall Ninja in .htaccess. Of cource i could auto prepend an other php file that contains both, still it gets complicated.

**Comment by DanielRuf** [comment]
> Sure but auto_prepend is already in use for Firewall Ninja in .htaccess

This is not a problem. Create a custom file which uses require_once for both paths and use this instead of the NinjaFirewall once ;-)

**Comment by DanielRuf** [comment]
> Of cource i could auto prepend an other php file that contains both, still it gets complicated.

I don't think this is complicated. Just my opinion. And if other stumble upon this issue here they might have solutions thanks to the mention of auto_prepend_file (not everyone uses NinjaFirewall + CIDRAm).

**Comment by eurobank** [comment]
@DanielRuf 

As i said it gets hairy because i control all sites from one Ninja FW installation and all sites from one CIDRAM. So doing all that for each and every site is not practical for me. And for other technical reasons also.

Firewall Ninja also has a prepend option for other scripts but that only created more problems and i'm just a lonely webmaster.

**Comment by DanielRuf** [comment]
Sure, and as I wrote it was just meant as additional input for others ;-)
