### ISSUE TITLE
Yet another API source to possibly use with a module

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#187]
I've mentioned GreyNoise before on Gitter, but just now I wanted to see if they have an API and they do in fact have an API. It looks promising based on the types of requests you can do for such things as 'classification' and 'actor'. It could prove useful for Googlebot, etc whitelisting ability, not too sure. I'm not sure if we could benefit from a free API usage tier or if you'd have to pay for it and how much that would cost which could be a potential deal breaker. I also think it could prove useful where the signature files don't already block a bad actor, etc. Though, AbuseIPDB should fill that in, but I've had IPs even get passed that with a confidence score of 30.

The types of queries can be found here: https://viz.greynoise.io/cheat-sheet/queries

https://greynoise.io/start

Posting this here for everybody's opinion.

**Comment by DanielRuf** [comment]
You can test the API for free for 14 days. But then you have to contact sales. So every user has to buy a license. GreyNoise was never free afaik.

https://greynoise.io/pricing

**Comment by Maikuolan** [comment]
Sorry for the delayed reply. Busy past week or so. I'll try to reply to this properly (plus the other pending issues) later today, after I get back from work. Cheers.

**Comment by 737simpilot** [comment]
If this costs a lot of money then I'll not be interested. I don't know what they charge unless I inquire about it. Though, it may be of interest to others.

**Comment by 737simpilot** [comment]
Hey Caleb, I think you can close this one. It probably costs too much money and I'm already on a tight enough budget as it is. If someone else would like to have the feature perhaps they can chime in. I thought perhaps it could be another layer to add to CIDRAM in detection ability.

**Comment by Maikuolan** [comment]
*In reference to: https://greynoise.io/pricing*
> # API
>
> A 14-day trial is available for all users who register an account. Please contact sales@greynoise.io to find the right paid enterprise or free researcher, academic or developer API license to meet your needs.

The way they've phrased that, suggests to me that they *don't*, *generally* speaking, provide free access to their API (i.e., they're providing an entirely commercial service), but that it *might* be possible, in some cases, for users to obtain free access to their API, *if* they contact GreyNoise personally and are able to demonstrate themselves as fitting the criteria for "researcher" or "academic".

I also can't see any actual prices mentioned anywhere; just the instructions to contact them directly in order "to find the right paid enterprise". Since I haven't yet actually done that myself, I couldn't say with any certainty which way the scales would lean in terms of pricing, whether reasonably cheap, unreasonably expensive, etc. But, given that CIDRAM itself is provided for free, and that there are various other APIs available which are also free, and which CIDRAM already has available modules for, I don't anticipate much demand occurring in the future for a hypothetical module for integrating the GreyNoise API to CIDRAM. Possibly, some users might be able to describe themselves as "researchers" or "academics" and therefore obtain free access, or might be willing to just pay whatever the cost is, but whether to obtain free access or whether to ascertain their actual prices, I imagine that the need to personally contact them in the first place would probably reduce interest in it, since we're talking in the context of optional modules for CIDRAM (i.e., if someone wanted *specifically* to use GreyNoise's services, needing to personally contact them to get necessary information is not unreasonable, and I imagine would not be particularly off-putting, since it's a specific desire, plus provides the ability to obtain additional information which perhaps isn't easily documented.. but when it's not a specific desire, and we're talking in the context of someone just wanting to compliment their CIDRAM installation with some additional modules to improve whatever they're already using, they're probably not going to want to bother contacting the team or developers behind the APIs utilised by specific modules, just for the sake of being able to use those specific modules).

All in all..

> Hey Caleb, I think you can close this one.

Yeah.. I'm leaning the same way.

But, on the flipside: Their API actually has pretty good, clear, well-written documentation, and if there's serious demand for it, it shouldn't be difficult at all to create such a module, I imagine.

So what I'm thinking: For now, we mark this issue as "abandoned" and close it. But, we avoid saying "never, ever". If there's suddenly demand for such a module in the future (which I don't anticipate, but regardless..), we can reopen this issue and I'll see what I can come up with (since it shouldn't be too difficult to write the module anyway). Easiness aside, I don't want to create something like this without the demand for it, since there's a chance users will create new issues to ask questions about it if they install it and discover that they can't use it without paying for it or contacting the API provider, possibly complaining about it wasting their time or griping to us about the costs (which we obviously would have no control over). But, if it turns out there is interest or demand for it, I'll reopen this and start working on it. :-)
