### ISSUE TITLE
Query Command Injection by Googlebot and Bingbot

### ISSUE THREAD

**Issue by jjrueger** [CIDRAM/CIDRAM#188]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.

System information:

    CIDRAM version used: 2.4.3
    PHP version used: 7.3.21
    Extension➡Installed/Available

    Operating system used: Linux cwh910.canadianwebhosting.com 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 #1 SMP Wed May 29 04:37:40 EDT 2019 x86_64

---
## Issue
Query Command Injection blocking both Googlebot and Bingbot - modules_extras line 97 ($Trigger(preg_match('/\((?:["\']{2})?\)/', $QueryNoSpace), 'Query command injection'); // 2016.12.31) this is on a genealogy website where a suggestion form automatically prefills the subject line with information about the person who is the subject of the suggestion.  In the case where the person does not have any birth or death date recorded the program seems to enter the information as () i.e. blank.  The Cidram logs indicate that this is being interpreted as %28%29 and it is rejected by modules_extras as an empty command injection.  If there is any birth or death information the program will show it as for example %281813+-+%29 (in this case born in 1813 and no death information) and modules_extras will accept the query.  Bingbot is pretty darn insistent and will keep retrying the query until that particular IP is banned (Googlebot is not quite as persistent).  I'm not very knowledgeable (yet) on SQL injection attacks and defences so I'm not sure if this would be an expected attack vector and thus legitimately blocked by CIDRAM.

### Relevant log entries (if applicable).
D: 1599860155-013849-1812787888 »
Script Version: CIDRAM v2.4.3 »
Date/Time: Fri, 11 Sep 2020 14:35:55 -0700 »
IP Address: 66.249.68.89 »
Hostname: crawl-66-249-68-89.googlebot.com »
Query: page=lastname%2C+firstname+%28%29 »
Signatures Count: 1 »
Signatures Reference: module_extras.php:L97 »
Why Blocked: Query command injection! »
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »
Reconstructed URI: https://jrueger.ca/TNG/suggest.php?page=lastname%2C+firstname+%28%29 »

**Comment by Maikuolan** [comment]
Thanks for sharing this here. :-)

> I'm not very knowledgeable (yet) on SQL injection attacks and defences so I'm not sure if this would be an expected attack vector and thus legitimately blocked by CIDRAM.

The signature in question matches against a particular query pattern which *was* frequently seen in (as per the block description) attacks involving query command injection, back around the time when the signature was first written and prior to, and there *were* a few popular CMS, frameworks, etc at that time, which *could* potentially be affected by such an attack.

Though, that time was now almost 4 years ago (quite a long time in the world of web development), I haven't seen that particular query pattern in any access logs or live traffic for quite a while now, all the CMS/frameworks/etc that I *knew* about being affected, at least, have now long since been patched and shouldn't be affected anymore (though I can't speak for those that I don't know about, of course, and I'm sure there'll undoubtedly be various obscure scripts/packages/etc that could still be affected, as well as extremely outdated installations belonging to people which refuse to update, which could still be affected, but.. not much we can do about those, anyway), and as demonstrated by your report here, we can see that there *are* real-world cases where that pattern could legitimately occur in queries, as part of the actual design of those systems where it occurs, so.. I wonder whether it might be about time now to consider removing that signature from the module entirely..? I'm leaning towards that, but I'll leave this issue open for a little while, in case anyone else wants to provide their own view on it.

For the benefit of those reading this issue, the signature in question:

```PHP
        $Trigger(preg_match('/\((?:["\']{2})?\)/', $QueryNoSpace), 'Query command injection'); // 2016.12.31
```

Translating from "regex-ese" to English: The signature is looking for the occurrence of completed (i.e., opened and then closed) brackets in the query string of a request, which *may or may not* optionally also include quotes (like `()`, `("")`, `('')`, `('")`, etc).

The theory here is that in some systems, query strings may end up being processed as part of SQL queries without appropriate sanitisation taking place beforehand, and so, by blocking requests whereby parts of the query string look like they may potentially be part of an SQL query, we can prevent said theoretical/potential SQL queries reaching the affected/vulnerable code in the first place, thus preventing the attack from succeeding.

The moment said systems implement measures to appropriately sanitise all user input (in this case, user input via the query string, but of course, this applies to any user input, no matter where it comes from), the signature becomes completely unnecessary (for the system where said measures have been implemented, that is, and assuming that said measures reliable). The signature also isn't necessary for systems which don't utilise query strings at all (e.g., static websites, websites which just rely on POST data and ignore query strings, request URIs, etc). Possibly, some value remains if the signature is to be regarded as *conjunctive* (i.e., used, alongside other triggered signatures, as an indicator of traffic being unwanted or potentially malicious in intent), or for monitoring purposes, but.. that's kind of reaching a bit, and there are other ways to satisfy those needs anyway.

In short: The signature in question could be regarded as a stopgap measure to prevent a specific kind of SQL injection or command injection attack against systems which don't properly sanitise user input and don't already provide such mechanisms themselves natively.

In the absence of any risk of false positives, the signature could probably just be ignored, regardless of its effectiveness and value (or lack thereof). But, with the existing of some risk of false positives, that risk should be weighed against its effectiveness and value, and if the false positive risk weighs more.. then IMO, the signature should be removed. But, the question is which weighs more: The false positive risk, or its effectiveness and value.

Any thoughts from others here..? (CC: @DanielRuf @737simpilot)

**Comment by jjrueger** [comment]
Thanks for the very detailed response! Even though I raised the issue I am actually happy to live with the false positive.  After I raised the issue I delved further into the software I am using to see what might be going on.  Turns out that the software is using the page title as the subject line in the suggestion form - and the page title includes the birth and death years enclosed in parentheses - so for instance if I was in the software with no birth and death info the page title would be Jeff Rueger () - so it seems to me that the entire issue is caused by what I would characterize as mere visual formatting in the page title and actually unnecessary to the functioning of the software.  I will raise the issue with the software developer and see what the response might be :-)

**Comment by 737simpilot** [comment]
I'm really not up to par on SQL injection attack methods. I just rely upon CIDRAM and Ninjafirewall and hope that I don't get owned one day. LOL I do however deploy CloudFlare as well as an additional layer, and in my opinion, security is all about layers. 

If you don't already, check out Ninjafirewall. There is a WordPress plugin, but it doesn't look like your site uses WordPress. I use the hook method along with CIDRAM, but in order to hook both you have to create a PHP file to do so. Also, if you use Ninjafirewall, you should place it in test mode for lack of the proper term and make sure you disable any false positives that may arise. If you want to roll Ninjafirewall as well as CIDRAM, let me know and I'll tell you how to do it right. 

I believe I asked Maikuolan way back when to incorporate some of ZBblock's signatures in CIDRAM and that is where the extras module came about.  It's one of those things that really need to be updated and to know what's out there. When Zap ran ZBblock he spent days researching this stuff as what he told me on the phone. 

I tried to do some research on brackets being used in SQLi and the StackExchange hits I got were quite old. So it may be that this Sig is outdated as indicated.

You may be interested in a OWASP scanner of some sort. I do recall watching a YouTube video on Zed Attack Proxy and you could run that to note any possible attack vectors. Here are a whole list of scanners. https://owasp.org/www-community/Vulnerability_Scanning_Tools

Keep in mind, you may want to inform your host if you run one of these.

**Comment by jjrueger** [comment]
I was running Ninjafirewall along with CIDRAM for a year but didn't renew my subscription for Ninja Pro.  In that year Ninja caught very little.  I used a single php file to load CIDRAM first and then Ninja - I know others run everything through Ninja first and then CIDRAM.  Personally I found that CIDRAM does catch pretty much everything.  I'm running Joomla on three sites (I hate Wordpress ... ) and now use Akeeba AdminTools inside each Joomla site and keep CIDRAM as the frontdoor bouncer.  Akeeba has a WAF in addition a bunch of other useful tools so I thought it was a more worthwhile tool than NinjaFirewall.

That said the software that I use for the genealogy site is a standalone PHP package that doesn't officially use any CMS. It sits in a subdirectory of public_html and is guarded only by CIDRAM.  This setup works very well for me.

**Comment by DanielRuf** [comment]
NinjaFirewall Pro (free) has the same rules like the Pro+ version. It just adds a few helpful extras.

**Comment by 737simpilot** [comment]
Yeah, it's the free NinjaFirewall that I use.  I have CIDRAM execute before NF.

**Comment by mikeruss1** [comment]
IMHO this is a valid block. Queries with brackets etc are unsafe. I would let this through with a custom mod or Auxiliary rule.

**Comment by DanielRuf** [comment]
> Queries with brackets etc are unsafe

This would be new to me, as these are so far often arrays.

**Comment by Maikuolan** [comment]
Since this seems to be resolved for now, I'm going to leave this as is for the moment, I think. We can reopen this issue to look at it again at a later date if the problem occurs again.
