### ISSUE TITLE
how to whitelist useragent

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#192]
how to i white list a useragent ?

eg: WordPress/5.5.1

**Comment by Maikuolan** [comment]
There are a number of different possible ways to whitelist a user agent in CIDRAM, but the easiest, most straight-forward way to to do so, if you've got the front-end enabled at your installation, would be to create an "auxiliary rule" via the "auxiliary rules" page. Next easiest solution from that, would be to do so via a custom module.

---

**Auxiliary rules solution:**

First, click the link to the auxiliary rules page:

![1](https://user-images.githubusercontent.com/12571108/96359239-1e136280-1143-11eb-9e64-83ab613dfe25.png)

Once at the auxiliary rules page, you'll need to click "Create new rule":
![2](https://user-images.githubusercontent.com/12571108/96359138-b6a8e300-1141-11eb-8d27-9df7821b21f6.png)

In the menu where it defaults to *"if the following conditions are met, block the request"*:
![3](https://user-images.githubusercontent.com/12571108/96359139-b6a8e300-1141-11eb-8cba-48cc2c1e5866.png)

Set the "whitelist" option:
![4](https://user-images.githubusercontent.com/12571108/96359140-b7417980-1141-11eb-9c26-b7fa02ce5e87.png)

Give the rule a name (anything is okay, but it should be something simple, which makes sense to you, so that you'll know what it is in the event that you need to revise your rules at a later date), and where you see "IP Address":
![5](https://user-images.githubusercontent.com/12571108/96359141-b7da1000-1141-11eb-99de-a52fd1eeb3a5.png)

Set the "User Agent" option:
![6](https://user-images.githubusercontent.com/12571108/96359142-b872a680-1141-11eb-90c5-bc33ede244f8.png)

Enter the user agent you want to whitelist, and then click "Create new rule":
![7](https://user-images.githubusercontent.com/12571108/96359143-b872a680-1141-11eb-8150-daafb554934f.png)

All the other options should be left as they are by default. For example, since we're matching against a *literal* user agent (i.e., not a pattern, and with no wildcards), we'll want to use "direct string comparison", the "any equals conditions" option, and everything else as it is.

The user agent in question should now be whitelisted. :-)

---

**Custom module solution:**

The `ZeroOutBlockInfo` closure is what's used internally by CIDRAM to perform the whitelist action.

As an example, something like this, as a PHP file, to act as a module, will result in whitelisting the user agent provided in the initial question:

```PHP
<?php
/** Prevents execution from outside of CIDRAM. */
if (!defined('CIDRAM') && !defined('CIDRAM-L')) {
    die('[CIDRAM] This should not be accessed directly.');
}

/** Safety. */
if (!isset($CIDRAM['ModuleResCache'])) {
    $CIDRAM['ModuleResCache'] = [];
}

/** Defining as closure for later recall (no params; no return value). */
$CIDRAM['ModuleResCache'][$Module] = function () use (&$CIDRAM) {

    /** Confirm whether the current user agent is the user agent we want to whitelist. */
    if ($CIDRAM['BlockInfo']['UA'] === 'WordPress/5.5.1') {

        /** Confirmed. Whitelist action happens here. */
        $CIDRAM['ZeroOutBlockInfo'](true);
    }
};

/** Execute closure. */
$CIDRAM['ModuleResCache'][$Module]();
```

After creating your new custom module, you'll need to save it to your vault, and then add the name of that file to the "module" directive in your configuration (`signatures➡modules`).

Once that's done, the user agent in question should be whitelisted. :-)

---

It can also be achieved through "Run" rules in custom signature files and some other solutions which are a little more tricky, but I would recommend one or the other of the above two mentioned solutions.

**Comment by bigalownz** [comment]
Thanks 
I ended up using auxiliary rules options
I could not find any thing in the Docs about it
