### ISSUE TITLE
OVH IP address range is not fully dedicated to the cloud !

### ISSUE THREAD

**Issue by brouillon** [CIDRAM/CIDRAM#196]
They are also an ADSL access provider ;)

Just a message because I'm blocked on a website using your code CIDRAM v1.17.4

**Comment by mikeruss1** [comment]
might be my website!
Why Blocked: Cloud service ("OVH Systems", L1175:F4, [CA]), Suspected bot detected!! »
User Agent: XenForo/2.x (https://ww2aircraft.net/forum) »

havent seen that UA before. The host is 
Hostname: bhs-2.ww2aircraft.net »

**Comment by brouillon** [comment]
It's not my user agent ;)

```
La version du script : CIDRAM v1.17.4
Date/Heure : Wed, 27 Jan 2021 09:14:04 +0100
IP Adresse : xx.xx.xx.x
Nom d'hôte: xx-xx-xx-xx.dsl.ovh.fr
Referrer : http://xxxxx
Signatures Compte : 1
Signatures Référence : xxx.xxx.x.0/16
Raison Bloquée : Cloud service ("OVH Systems", L1389:F0, [FR])!
Agent Utilisateur : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Reconstruite URI : https://xxxxx
```

**Comment by Maikuolan** [comment]
Thank you for bringing this to my attention. :-)

Normally, when such a situation arises (i.e., a network is identified by the CIDRAM signature files as solely providing cloud services, or some other kind of single-play service without any human endpoints, and it is then discovered that the network has human endpoints, is actually multi-play, provides ADSL, etc), I would reassess the relevant signatures and the reasons for their inclusion, and if it still weighs towards including them, then I would try to perhaps identify which ranges belong to which parts of the network, and if possible, delist the human endpoints while continuing to list the non-human endpoints, provide bypasses, or some other kind of similar mechanism.

Unfortunately, in the case of OVH, their BGP announcements don't make it entirely clear which ranges are human endpoints versus non-human endpoints, and I can't see any obvious way to statically distinguish between the two at the time of updating the signatures. The amount of spam, hack attempts, and other unwanted activity coming from the VPS, cloud, and webhosting parts of their network are also still far too much at this time to risk delisting the entire network. So, in an attempt to correct the problem, while still being able to block as much as possible, I've done something a little different this time.

Firstly, I've moved the OVH signatures out from the default cloud signature files (`ipv4.dat`, `ipv6.dat`), over to the default ISP signature files (`ipv4_isps.dat`, `ipv6_isps.dat`), meaning that anyone that chooses to not use the ISP signature files with their CIDRAM installation won't be affected by those signatures anymore.

Then, I've marked the signatures for use with reCAPTCHA, so that anyone with reCAPTCHA enabled at their CIDRAM installation should have that option appear whenever those signatures are triggered.

Finally, I've changed the signatures from "Deny" signatures to "Run" signatures, pointing them to the "extended rules" file (one of the "default bypass" files), and written some code to that file which, when those signatures are triggered, should then perform a hostname lookup for the IP address of the inbound request, deciding whether to mark the block reason as "cloud" or as "spam" on the basis of whether that hostname is known to be associated with those ADSL services (currently, just `*.dsl.ovh.fr` and `*.ovhtelecom.fr`; there could be others which need to be added, but I'm not aware of them yet). That should mean that, along with the above two considerations, when those blocks occur, it should at least now identify them correctly (i.e., not as cloud when not cloud).

It's not a perfect solution, but should be a little more balanced than it was before. However, for any CIDRAM installations at websites aimed towards French, francophone, or European users more generally, I would still strongly recommend including "OVH Systems" in their `ignore.dat` file, in order to just ignore those signatures entirely (in terms of that "balance", for those particular websites, the remaining risk of false positives most likely outweighs any gains of blocking OVH, meaning it would probably be better to just ignore those signatures and allow OVH in, whereas on the other hand, for other websites, which aren't aimed towards French, francophone, or European users, or which don't anticipate such users, the remaining risk of spam, hack attempts, and other kinds of unwanted traffic most likely outweighs any potential false positive risk, meaning it would be best for those websites to continue blocking OVH). Of course, such decisions could only be made by whoever installed CIDRAM at the websites in question in the first place, but is worth mentioning here for the sake of clarity regardless, I think.

(Signature files and bypass files will need to be updated at the affected websites in order for the fix to have effect).
