### ISSUE TITLE
Proposal for blocking floods

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#198]
have had several instances where I get hundreds of GETS from a Cloud service in a very short time. Generally they have the same UA. The idea is that CIDRAM should monitor Cloud blocks and when it detects more than a specific number in a specific time from the same Cloud service, future GETS from that Cloud go straight to 403 without logging.
There could be parameters like:
number of blocks before automatic blocks start
window time to reach this limit  before initiating
time automatic blocking remains
only for one URL or any URL
only applies to one UA or any
send an email to admin to notify

maybe a record should be kept of the event, such as start and end time, and number of automatic 403s.

**Comment by Maikuolan** [comment]
I could try coding something like that into CIDRAM, and in theory, it shouldn't be particularly difficult to achieve, but I would warn that such a feature wouldn't be entirely invulnerable to race conditions, especially given that by default, CIDRAM's logging mechanisms utilise just plain-text flatfiles (i.e., if CIDRAM ends up encountering hundreds of requests a second, it'll likely take a few being processed before CIDRAM is able to register when a specific number has been reached or exceeded, meaning that, although we could reduce unwanted logging, and the overall intention of the feature should still be easily honoured, it mightn't necessarily honour the exact specific number provided). Still interested..? '^^

**Comment by mikeruss1** [comment]
yep, as it stands CIDRAM cant deal with the race condition anyway, I was hoping this idea would reduce the load. You can bail out of all the other module checks as soon as you detect this case, and deliver a 403 with no need to log

**Comment by Maikuolan** [comment]
Sounds good. :-)

I'll have a play around with the idea at my end at some point later this week, to try to figure out the best way to approach this (got a few different ideas in mind; not sure which idea would work best yet though).

**Comment by mikeruss1** [comment]
thats great, thanks

**Comment by 737simpilot** [comment]
I don't understand this. I had CIDRAM setup where if there's three hits you are perma banned and no further logging happens. 

Now I've had to raise the perma ban due to Recaptcha. For some reason with that if it's only three they get a perma block. 

But the thing here is that CIDRAM already provides the functionality of not logging at a certain number of hits. Unless these are numerous IPs all from the same ASN, it shouldn't be an issue. If it was from the same ASN, and it was just some cloud provider, and I wasn't using CloudFlare to out right block the ASN, I'd be apt to block the CIDRs in htaccess. But depending on how many there are that could be an issue for site speed.

What cloud service?

**Comment by mikeruss1** [comment]
many, Google, AWS and Hetzner the most common. Flood events are more one-off and will have a different IP address for each block.

**Comment by 737simpilot** [comment]
Your only choice to prevent a DDoS or layer 7 DDoS or a syn flood, etc is to use a reverse proxy like CloudFlare which will do it for free, though layer 7 protection isn't free. 

This type of thing can't be handheld via a PHP script. The script its self would cause a flood. Has to be done at the network layer.

**Comment by mikeruss1** [comment]
it wasnt that bad, 1 every 3 or 4 seconds for 30 mins, all from the same UA and Cloud service, but different IP each time

**Comment by Maikuolan** [comment]
Have played around a bit.. The results haven't been particularly impressive, in regards to additional load, processing required, etc. Any gains made by not logging are negligible against the cost of determining whether the request should be logged in the first place, so I wouldn't worry about that much. The only real benefit is in user convenience, in not needing to read through multiple similar log entries, saving time when reviewing the logs.

That in mind, I'm thinking it might be better instead to handle this after the event, rather than during; i.e., rather than worrying about whether or not to log a particular request, just providing appropriate filtering options to the front-end logs page, allowing, for example, to group together similar log entries rather than displaying each one of them individually.

Omitting to log a blocked request entirely also messes up with tallying a bit, since the current way that the front-end logs page tally feature works is by literally counting the number of entries in the log file being read in accordance to the criteria available within that log file (e.g., user agent, IP address, whatever), in order to generate the tallies (meaning that omitted logs would reduce the counts for the affected criteria).

The statistics shown on the statistics page should be fine though, since that information is recorded by internal event handlers, separate to the logging mechanism entirely.

Thoughts?

**Comment by mikeruss1** [comment]
For me thats a very limited benefit, at the cost of extra work for you. Suggest forget it. I was hoping we could effectively deal with the event with a blanket 403, allowing other users to continue OK. If thats not achievable, improving log handling is not worth it. IMHO.
thanks anyway.

**Comment by Maikuolan** [comment]
No problem, and sorry we couldn't (yet) figure out a way to make this work.

I'll go ahead and mark this issue as abandoned and close it for now. Maybe we can reopen it and explore it again if we can figure out a way to work the idea into something a little more viable in the future. Right now, I'm not sure how, but maybe I'll think of something later, or someone else will. We'll see, I guess. ^^
