### ISSUE TITLE
Baidu blocker error

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#205]
since the last update on 21/3
[23-Mar-2021 09:40:55 Europe/London] PHP Fatal error:  Uncaught Error: Function name must be a string in /xxx/xxx/public_html/cidram/vault/module_baidublocker.php:39
Stack trace:
#0 //public_html/cidram/vault/module_baidublocker.php(54): {closure}()
#1 public_html/cidram/vault/outgen.php(208): require('/...')
#2 [internal function]: {closure}('module_baidublo...', 2)
#3 /public_html/cidram/vault/outgen.php(211): array_walk(Array, Object(Closure))
#4 /public_html/cidram/loader.php(95): require('/.')

#6 //public_html/index.php(20): include('/..')
#7 {main}
  thrown in //public_html/cidram/vault/module_baidublocker.php on line 39

**Comment by Maikuolan** [comment]
Investigating now.

**Comment by Maikuolan** [comment]
I don't seem to be able to replicate it at my end. Might be because of a faulty update, maybe..? From the front-end updates page, try firstly updating the CIDRAM core (if an update is available), then try running repair on it, then try updating the Baidu blocker module (if an update is available), and then running repair on that. Try then testing again, and let me know how it goes. :-)

**Comment by mikeruss1** [comment]
done, couldnt update baidublocker as there wasnt one, but repair worked. Need to wait for Baidu to appear, usually get a few a day

**Comment by mikeruss1** [comment]
confirmed whatever was causing it has gone away
thanks

**Comment by Maikuolan** [comment]
Glad to hear. :-)
