### ISSUE TITLE
Different times shown in log and IP tracking

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#206]
very minor, IP tracking event times are shown as +1, logs are shown as +0.

a small issue if you are trying to correlate the two

**Comment by Maikuolan** [comment]
Not quite sure I fully understand this one. Could you show me some examples? Cheers. :-)

**Comment by mikeruss1** [comment]
from tracking .....
35.210.104.101 | Tracking – 1 | Sat, 03 Apr 2021 08:04:57 +0100
-- | -- | --

from log
ID: 1616828697-789120-6024258992 »
Date/Time: Sat, 27 Mar 2021 07:04:57 +0000 »
IP Address: 35.210.104.101 »

**Comment by mikeruss1** [comment]
oddly the Instaban tracking entries are different

175.44.42.132 | Banned – 1,000 | Tue, 22 Mar 2022 14:49:55 +0000
-- | -- | --

**Comment by Maikuolan** [comment]
Ah, okay. IP tracking times show when the ban *expires*. Log times show when the particular event being logged *occurred*. So, since the two times refer to two different things, it makes sense that they'd be different. :-)

Currently, IP tracking doesn't show when a logged event occurs, nor does logging show when a ban expires.

I *could* modify the currently logging procedure, so that ban expiries will show in logs, but the problem is that each individual log entry is, by design, static (meaning, log entries shouldn't be modified once added; if new information needs to be logged, a new, separate log entry should be added for that information), whereas ban expiries are not. Let's say, a request triggers a signature which causes the IP address of the request to be banned, but not "insta-banned". An entry will appear, which has a particular ban expiry, which isn't too far away into the future. But then, a new request appears from that same IP address, which is much more serious, triggering a signature which causes it to be consequently "insta-banned". The IP tracking entry needs to then be updated accordingly, with a new expiry much further into the future. Or, alternatively, after a ban expires, if that same IP address is then subsequently banned yet again; the new ban will have a new, different expiry time (since the old expiry time would've been in the past). Meanwhile, our static log entries will remain the same, reflecting times and dates that'll eventually be in the past, once the relevant, related bans have expired and so on. So, there's a risk that showing that information in logs might actually end up making it even *more* confusing and difficult to cross reference.

BTW, on a side note.. I'm seriously considering removing any mention or reference to "insta-ban" from all modules and replacing it with something else. Too much confusion from too many users about exactly how it works (in particular, users remembering how "insta-banning" used to work with ZB Block, how it was absolutely permanent, and could never, ever be revoked, unless an admin/webmaster manually deleted all the files related to the bans, cleared out the old databases, was not automated, etc, whereas CIDRAM never does truly permanent bans, because of the risk of eventual false positives, and because it just isn't necessary to do anyway). Just haven't removed it yet, since I haven't quite yet decided what to replace it with. But regardless, it should only affect modules, since there already aren't any references to it in the main codebase at this point anyway.

I'll have a think about the problem though and try to come up with something to help.

**Comment by mikeruss1** [comment]
its simpler than that ... the entry in IP tracking shows a +1 time, the entry in the log shows a +0 time. Its not significant, I was just trying to trace a problem and was looking for an entry in tracking with the same time as the log. And the entry in tracking if its instabanned shows a +0 time.

**Comment by mikeruss1** [comment]
re Instaban, could you replace it with an Auxiliary function allowing infractions and expiry date to be set

**Comment by Maikuolan** [comment]
> its simpler than that ... the entry in IP tracking shows a +1 time, the entry in the log shows a +0 time.

Oh..! You mean the timezone specified (`+0000` versus `+0100`)? I totally missed that before. Sorry, my bad! Was looking at the dates themselves, thinking.. +1.. +0.. what could that mean.. just somehow didn't notice that part (I've been reading a lot of webnovels recently, so my heads been a bit full of that.. can I blame that, maybe..? eh, whatever.. got it now). >.x

Yeah.. That definitely isn't normal, at all. The timezone specified there *should* always be in accordance with whatever is specified by the `general➡timezone` configuration directive. Since the two are showing two different timezones there.. at least one of them must be doing something wrong somewhere.

I'll look into that now and reply again shortly. Cheers.

> re Instaban, could you replace it with an Auxiliary function allowing infractions and expiry date to be set

That's definitely doable.. and actually, I quite like the idea of setting an exact expiry date, since I wasn't quite sure before about exactly how I'd implement an insta-ban equivalent to the auxiliary rules system, and setting an exact expiry date isn't something easily doable yet through any other means in the GUI (strictly speaking, you could math your way to an exact time via a custom module.. but that's far more of a PITA than I'd be willing to recommend to general users to go through). I'll have a go at that tonight. :-)

**Comment by Maikuolan** [comment]
Actually, thinking on it a bit.. I think I might have an idea about why it's showing `+0000` for some, but `+0100` for others. Maybe.

Does your timezone, by any chance, follow daylight savings..? Since those numbers (`+0000`, `+0100`) represent the number of hours to offset from UTC in order to obtain the given date/time, and since UTC doesn't follow daylight savings.. I'm thinking that, if a specified timezone has daylight savings, maybe it's just adjusting that offset accordingly..? I haven't tested nor investigated this thoroughly though, so I can't be 100% sure yet. But it would make sense, I reckon.

(I also haven't been able to find anything in the codebase which could explain the problem).

**Comment by mikeruss1** [comment]
re daylight saving ... I did wonder if it was related, but I dont think it is. We have just gone to daylight saving and tracking entries created today are still showing as +1.
Also the time setting in config refers to Timezone, not UTC? So that should auto adjust to daylight saving?

**Comment by Maikuolan** [comment]
> So that should auto adjust to daylight saving?

That's what I'm thinking.

> re daylight saving ... I did wonder if it was related, but I dont think it is. We have just gone to daylight saving and tracking entries created today are still showing as +1.

Oh well, it was an idea. I'll do some more testing and research during the course of tomorrow.

**Comment by Maikuolan** [comment]
Hrm.. I had forgotten about this issue, back when implementing the new "enforce extended IP tracking options" to the auxiliary rules a few days back. Not entirely sure now how setting specific expiries would play along with that (since "enforce extended IP tracking options" is setting the time automatically, whereas setting specific expiries would be setting it manually, and automatic plus manual.. yeah.. it would need to be just one or the other, I think, else it'll get confusing).

Worth still pursuing this idea or not worry about it now (i.e., the other newly added options being sufficient)? What do you reckon @mikeruss1? Also, if worthwhile, any further ideas/thoughts? Cheers.

**Comment by mikeruss1** [comment]
not important - only if working there anyway and an easy change
