### ISSUE TITLE
No log with blocked search engine verification

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#208]
I just noticed that if search engine verification fails (in this case a fake bot request from a Googlebot UA) there is no log and no IP tracking for that IP that triggered the rule. I think this might be something that should be fixed in an effort to record any possible bad IPs that aren't already being blocked.

**Comment by Maikuolan** [comment]
Regarding IP tracking: This is, strictly and technically speaking, not a bug, and expected behaviour. (Because search engine verification is not a module, but a distinct part of CIDRAM in its own right).

Referring to the documentation for the `signatures➡track_mode` configuration directive:
> ##### "track_mode"
> - When should infractions be counted? False = When IPs are blocked by modules. True = When IPs are blocked for any reason. Default = False.

When `signatures➡track_mode` is `false`, and CIDRAM encounters a request, blocked due to faking as Googlebot (but not due to any other reasons at all), no new entry is added to IP tracking. However, when `signatures➡track_mode` is `true`, and CIDRAM encounters that same request, a new entry *is* added to IP tracking.

However, I do kind of agree with the sentiment. Maybe rewriting/redesigning the options for IP tracking could be something we earmark for v3? Maybe instead of a simple binary true/false switch, I could do something similar to what I've done for error logging, with checkboxes corresponding to specific parts of the execution process (e.g., checkbox for signature files, for modules, for search engine verification, for auxiliary rules, etc and etc). What do you reckon?

Regarding logging: I haven't encountered that particular problem at my end. Replicating the scenario locally, CIDRAM seems to be able to log such requests, regardless of settings (as long as, of course, search engine verification is enabled, and there is something specified to the relevant logging directives, so that CIDRAM knows *where* to log to).

Do you have any non-standard logging mechanisms or customised logging events at your installation at all? (If you don't know what I'm talking about when I mention "non-standard logging mechanisms or customised logging events", then the answer is most likely *no*. Since it's definitely doable, but would require some actually coding to do, and since the possibility of it isn't documented anywhere, nor how to do it, and no options are provided for it in the configuration, I'm assuming it isn't a commonly done thing. But, asking anyway, just in the spirit of looking for things that might potentially subvert or interfere with the standard logging mechanisms).

**Comment by 737simpilot** [comment]
Sorry for the late reply. After my other reply to the other issue I had to do some things. 

My track mode is actually set to yes and it's been that way ever since. So that's really odd. The logging is nothing added code wise or anything like that. It's just the standard issue logfiles with names pertaining to date and time. 

Redesigning the IP Tracking ability sounds prudent. I guess it would enable a user more fine grained control if they wish.

**Comment by Maikuolan** [comment]
*Note for issue tracker management: #211 partially related, due to planned `track_mode` changes. Keeping both issues open though, since not identical (#208: Possible bug..? Not replicated yet, further investigation needed).*

**Comment by 737simpilot** [comment]
What I may do on my end is either temporally pull the auxiliary rules for testing and/or try a temp fresh install of CIDRAM and see what happens there as well. 

I can create a fake the Google bot UA and see if it logs. Now that I think of it, I could have sworn it did in years past. It's been a while since I ever saw a fake search engine bot.  Traffic like that typically doesn't even make it passed my very elaborate firewall in CloudFlare.

**Comment by mikeruss1** [comment]
have had fake search bot in the log recently

technically track mode should be "true" - maybe it ignores "yes"

**Comment by 737simpilot** [comment]
Well, so much for testing a fake Google bot. I changed my UA in the browser, went to my site and got an intimidate 403 from the host its self, not from CIDRAM.  The host seems to have stopped it before I hit CIDRAM.  I tried about three or four times and all 403s. Then when I went to log into the FTP I was denied. I also couldn't log into cPanel. I tired my VPN and was able to open the FTP directory and go to cPanel.  In cPanle I wanted to see if Immunify had anything to do with the block, but that's just an active anti-virus, not a WAF. It appears my host's WAF blocked the shenanigan before I did. SO I was about to open a ticket with my host to have them unblock my IP when I discovered I was able to get back in my FTP and cPanel. So the block must be temporary. 

I've had this happen before where my IP got blocked by my host. I was using Nmap on my site looking for vulnerabilities and their firewall didn't like that so I got on the ban list. After going back and fourth trying to figure out why I couldn't access my own damn website, FTP and cPanel, a higher tier tech told me my UA was the reason. I was like, "my UA?!" I said to the guy give me the UA. Sure enough it was the default UA for Nmap.  So after that crap I looked up how to change the UA for Nmap. You can do it temporally as the issued command in Nmap or permanently. I did it permanently so now I look like Chrome. But I have to update that to the latest Chrome version. I'm sure besides the types of requests your making with Nmap there are some other tall tell signs you're using it beyond the UA. But seen as how I can change the UA I just do it.

**Comment by 737simpilot** [comment]
You know what I can do? Throw my CIDRAM install in XAMPP and try that way. I can also try a fresh CIDRAM install in XAMPP for comparison. Whether it logs or not would be a moot point now I guess based on what my host did when it saw my bogus UA.  Though, I may want to try this in XAMPP anyway to rule out anything I may have configured or some bug that needs to be reported.

**Comment by Maikuolan** [comment]
Earmarking the `track_mode` changes for v3, since the changes I have in mind aren't quite compatible with existing configuration for v2.

**Comment by 737simpilot** [comment]
Will v3 require > PHP 7.2.*? I'm stuck at the moment and it's due to the AWS extension I use to offload attachments.

**Comment by Maikuolan** [comment]
Yep. :-)

I don't plan to increase the minimum required PHP version with v3.

**Comment by Maikuolan** [comment]
(I mean, the requirements will stay the same, i.e., will still require PHP >= 7.2).

**Comment by 737simpilot** [comment]
Okay, thanks.

**Comment by 737simpilot** [comment]
Okay, thanks.

![tenor](https://user-images.githubusercontent.com/16517998/119361335-c86adf80-bc68-11eb-9e91-958daf804704.gif)

**Comment by Maikuolan** [comment]
I've removed `track_mode` entirely for v3, and the originally intended changes have been implemented via adding some additional labels for the new `stages` directive (65f6b43cf6ad049eb193fbfb8bb77cea4d727e38). With that done, everything here should be resolved now, so I'll go ahead and close this issue. :-)

**Comment by 737simpilot** [comment]
Thanks. V3 looks good. 

Question: I forked CIDRAM a long time ago for my own repository and kinda a "backup" of all backups so to speak. But I'm unable to fork V3. If I hit the fork button it says I already forked CIDRAM.

**Comment by Maikuolan** [comment]
> Question: I forked CIDRAM a long time ago for my own repository and kinda a "backup" of all backups so to speak. But I'm unable to fork V3. If I hit the fork button it says I already forked CIDRAM.

If it's just a matter of updating a branch that you've already got at your fork (whether for CIDRAM or for any other repository), you can sync it up with its upstream source by using the *"🔄 Fetch Upstream"* link at the main page for your fork:

![upstream](https://user-images.githubusercontent.com/12571108/157436851-33196545-c680-4ced-ad13-4cf234ac626e.png)

Using that, you can sync an already existing branch with its upstream source (which would most likely be the case for both v1 and v2 at your fork of the CIDRAM repository). But, it won't be of any use for branches which you *don't* yet have at your fork (seeing as it always fetches according to the currently viewed branch at the fork, and you naturally can't view something which doesn't exist yet).

So, in order to add a v3 branch at your repository, the two most obvious approaches I can think of are:
1. Delete the fork entirely and then recreate it again afresh from the upstream source (thus acquiring a fork containing all currently existing branches at the upstream source).
2. Create the new branch using Git bash by way of something like `git checkout -b v3 UpstreamRemote/v3;git pull UpstreamRemote v3 --tags;git push DownstreamRemote v3 --tags` (where `UpstreamRemote` is the remote added to your local copy of the repository corresponding to the `CIDRAM/CIDRAM` upstream, and `DownstreamRemote` is the remote added corresponding to the downstream fork at your account; relatively easy if you're familiar with command-line Git, but not so easy otherwise).

There are probably other, less obvious approaches too, but anyway, those are the two that immediately come to mind. It might be possible to create a new branch by opting to edit a file at the branch you don't have, prompting the message from GitHub about not having permission to edit at the upstream with the option to edit the file at your own fork, thus forking the branch in question, after which, you could cancel the edit (seeing as you're not really wanting to edit anything), but hopefully leaving the newly created branch behind at the fork, after which, you could rename it to the appropriate name (e.g., `v3`) via the branch page at your fork. I think I might've done that before, but it's been a long time now since I bothered committing anything through any means other than Git bash that I'm starting to forget the little tricks I learned in the past for when committing through those other means.

**Comment by 737simpilot** [comment]
> Delete the fork entirely and then recreate it again afresh from the upstream source (thus acquiring a fork containing all currently existing branches at the upstream source).


This is what I did. Just simple enough to do that rather than mess with a CLI and what have yo9u. 

Thanks.

And yes, I'm aware of the fetch upstream option. :small_airplane:  :smiley_cat:
