### ISSUE TITLE
Increased I/O Operations after using CIDRAM

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#215]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.
Shared CloudLinux, LiteSpeed web

### CIDRAM version used (if known, please also include the exact commit hash).

Cidram 2.5.1

### PHP SAPI used 
LITESPEED ~ 7.3.27 

### PHP version installed 
7.3.x

### Operating system used 
CloudLinux 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64
---
## Issue
Since i installed and used CIDRAM to control 9 websites with ONE Cidram instance, the Cpanel I/O Operations woke up and sometimes hits limits. I use the script as PREPEND script to .htninja (because i can't prepend two scripts in .htaccess).

### Expected behavior
Was almost zero before. Check the **weekly** capture. While the CPU and DB went down and no more peaks. 

### Actual behavior
Check the weekly capture.

Any ideas why this happens?

![Screenshot](https://user-images.githubusercontent.com/4467158/115127809-370dab00-9fe2-11eb-92ab-8af824ce2acb.png)

**Comment by eurobank** [comment]
I would like to add that all 9 websites have less than 1000 hits pers day. Low traffic.

**Comment by eurobank** [comment]
Ok, i think we found the cause or we are on the right path to solve and understand this. Probably not related to CIDRAM.

I'm writing what we (think) we found in case somebody will benefit from it.

For some reason when using some Wordpress Caching plugin that uses mod_rewrite method to serve the pages, it doesn't work well with Firewall Ninja prepended CIDRAM (via .htninja). I have no idea why and what exactly happens.

We found this randonly, because the Home pages of the "protected" WP sites didn't seem to have CIDRAM checks. While other pages did. 

We solved (we hope) this issue by using some other WP Caching plugin that uses **PHP** to server the pages. And until now it seems to work fine.

Still we must wait a few days, since Cpanel resource usage is NOT realtime.

**Comment by Maikuolan** [comment]
Sorry about not replying earlier! Super busy past few days with work, and pretty tired after getting home.

I'm glad to hear you've discovered the culprit behind the issue (hopefully, at least; time will tell, I guess), and appreciate the details being shared here. Since there are quite a few others using CIDRAM to protect their WordPress sites, the details will probably benefit other users at some point or another, I imagine.

Definitely a strange issue, and even having found the culprit, TBH, I'm not sure I fully understand the technical implications of it.

If the problem appears again, or if you learn anything more, feel free to share. :-)
