### ISSUE TITLE
 Error at functions.php

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#220]
Please use this template when reporting bugs, problems, issues, etc.

### CIDRAM version used (if known, please also include the exact commit hash).
2.6.0 

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
Litespeed

### PHP version installed (`<?php echo phpversion(); ?>`).
PHP 7.3.27

### Operating system used (`<?php echo php_uname(); ?>`).
Linux s2.*****.com 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64 #1 SMP Wed Oct 2 07:53:12 EDT 2019 x86_64

---
## Issue
Error ln Error.log:

[2021-05-07T00:11:48+03:00] Error at functions.php:L1767 (error code 2): "unlink(/home/public_html/path***/vault/30-04-2021.log): No such file or directory". Eep.. Something went wrong during "Output".

**Comment by Maikuolan** [comment]
> [2021-05-07T00:11:48+03:00] Error at functions.php:L1767 (error code 2): "unlink(/home/public_html/path***/vault/30-04-2021.log): No such file or directory". Eep.. Something went wrong during "Output".

The source of the error seems to be the log rotation closure. The specific line of code in question is where it attempts to delete old files. Since there's already a check a few lines earlier in the code to first confirm whether the file actually exists, before attempting to delete it, I suspect that the error, in this case, most likely occurred due to race conditions: Multiple instances of CIDRAM executing at the exact same time, both attempting to perform log rotation at exactly the same time, each instance confirms existence of the file in question, both then try to delete it, one of them gets to it first, then the other, upon attempting to delete the file which already doesn't exist anymore, causes the error to be raised.

Not sure there's much I can do about this, but I'll keep the issue open for a while, see whether I can find/think up any ways to further optimise the code to reduce the occurrence of these errors, and reply back a little later.

**Comment by eurobank** [comment]
Probably a race issue as you say, since i use **ONE CIDRAM instance** for 9 Websites.

**Comment by Maikuolan** [comment]
Have some ideas, but haven't had time to test them today. I'll reply again tomorrow.

**Comment by Maikuolan** [comment]
I pushed some minor changes just now which should resolve the problem. :-)
