### ISSUE TITLE
CIDRAM MODE for Just logging?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#221]
Is there a way to just use for a while the script for just logging the issues/attempts and NOT block them?

**Comment by Maikuolan** [comment]
*Related: #98.*

Yes and no. With some fiddling around, it's technically possible to do this through the API, or by modifying a few lines in the output generator. But, there isn't currently any convenient switch or configuration directive available for this.

I'll get something sorted out for this soon though.

**Comment by eurobank** [comment]
The reason for this is Amazon blocks. I see so many Amazon (AWS) blocks. But the result of the blocks have limited some income of mine for some reason. Maybe advertizers use AWS for several check and caclulations.

So i want to be able to run CIDRAM and check the logs for a months or so, and after than to be able to customize things and IPs.

**Comment by 737simpilot** [comment]
Be careful with a broad sword approach though. If you can confirm AWS or some other cloud provider is limiting the income it would be wise to just whitelist based on a UA or IP or CIDR. I'd probably apt for a UA to CIDR or IP. So the UA and the IP or CIDR and UA has to match and then a 200. There's lots of crap in AWS et al so opening that wide open means you let the _Time Warner owned Guy Fawkes mask_ wearing hacker penetrate your defense. 

I'd have to know more about your revenue tactic to help understand why your numbers are going down. Are you a content creator for Brave Rewards by chance? Brave is a so-called privacy focused browser that uses the Basic Attention Token.

**Comment by eurobank** [comment]
@737simpilot Just using Google adsense, nothing else.

**Comment by 737simpilot** [comment]
Just a thought here. I don't see how this is possible, but it might be. What could be happening is that the Ads are hosted from AWS and perhaps CIDRAM is blocking their clickability. But those are internal requests in your website code so CIDRAM wouldn't have any bearing on that. As far as I know, CIDRAM handles external requests. 

I'd need to see the IPs and UAs being used. 

I looked it up, and it looks like the Kevel website is on AWS which _may_ mean they use AWS for the Ads. I don't see an SDK from them though. https://www.businessofapps.com/ads/ad-servers/

Google on the other hand should be dishing out their Ads via Google cloud.

**Comment by 737simpilot** [comment]
What if our fearless leader put an Ad in the block pages of all of CIDRAM? LOL! 

"HAHA, you've been blocked, now see my Ad." :dancers:

**Comment by eurobank** [comment]
@737simpilot I don't mean that ads can't be clicked. No.

I mean that some advertizers use AWS to check, evaluate (or whatever they do) my site.

**Comment by 737simpilot** [comment]
I see. Then we're back to the UA to IP/CIDR thing like I mentioned. Can you share some IPs and UAs that got blocked you suspect as being part of the advertiser?

**Comment by Maikuolan** [comment]
> and perhaps CIDRAM is blocking their clickability. But those are internal requests in your website code so CIDRAM wouldn't have any bearing on that.

CIDRAM doesn't interfere at all with the output from other scripts/CMS/etc. CIDRAM either produces its own output (e.g., when a request is blocked) and then ends the request before anything else can produce any output, or it doesn't produce any output (e.g., when a request is *not* blocked). After that point in the execution (i.e., CIDRAM has determined whether or not to block a request, and has either produced output, or not produced output), CIDRAM should remove itself from the memory of the current active request, and the request should continue exactly as normal, just the same as if CIDRAM wasn't there at all.

The *only* exception there, is when CIDRAM's rate limiting feature is enabled. When CIDRAM's rate limiting feature is enabled, an event is registered to [register_shutdown_function](https://www.php.net/register_shutdown_function) for the purpose of calculating the amount of bandwidth consumed by the request (the event to be executed after everything else has finished executing, when PHP is ready to "shut down" the request at hand).

> What if our fearless leader put an Ad in the block pages of all of CIDRAM? LOL! 
>
> "HAHA, you've been blocked, now see my Ad." :dancers: 

Yeah.. That'll definitely never happen, lol. The potential legal implications (revenue gains from putting up advertising on websites which I do not own, which I might or mightn't have permission from website owners to do, censorship laws in different countries, uncertainty about who's liable for the content advertised, whether I might owe part of that revenue to website owners due to those adverts potentially consuming their bandwidth, etc), technical and security implications (API keys, advertiser IDs, etc appearing in publicly available source code, the risk of malware infections via malicious advertisements, etc), irritation and potential backlash from users (most people don't particularly like unexpected and unsolicited advertising, regardless), and the likelihood of my reputation taking a nosedive, is seriously not worth any potential (and likely very small) revenue gains I could make by doing that. XD

Of course, if someone *else* (i.e., not me, but a CIDRAM user), wanted to insert advertising into *their* CIDRAM's block page, at their *own* websites, then they're more than welcome to do so (but either way, I won't need to know about it, since it wouldn't be any of my business).

**Comment by eurobank** [comment]
> 
> 
> I see. Then we're back to the UA to IP/CIDR thing like I mentioned. Can you share some IPs and UAs that got blocked you suspect as being part of the advertiser?


Yes i can:

34.212.72.245 & 54.245.43.208 both belong to AWS.

**Comment by 737simpilot** [comment]
I asked for the user agents as well...

**Comment by eurobank** [comment]
> 
> 
> I asked for the user agents as well...

User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 »
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 »

**Comment by 737simpilot** [comment]
So that's an old UA if it's legit. I don't see anything for those two IPs other than both being listed at Spamhaus for what ever reason. I have no idea what they're for.

**Comment by Maikuolan** [comment]
Implemented for v3 (8d5f2a3fea197611f6cde32c25ba5aa0843ab06b). :-)

![dry](https://user-images.githubusercontent.com/12571108/158070288-0f5051f0-bd10-4e22-b2b0-b2eec48419e7.png)
