### ISSUE TITLE
Extended tracking rules conflict with Disable IP Tracking

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#223]
These auxiliary options work independently, but if you set both, IP tracking is disabled but Extended tracking does not work so $instaban is not available and I get the Access Denied page..

I suspect this is intentional as I suppose little point in setting $instaban tracking options if IP Tracking is off?

What I am trying to do is detect $instaban, produce 403, and dont track, because the majority of cache.dat is instaban tracking which is pretty pointless.

Maybe what I need to do is just set the status code to 403?

**Comment by Maikuolan** [comment]
> I suspect this is intentional as I suppose little point in setting $instaban tracking options if IP Tracking is off?

Yep, correct. :-)

I wouldn't necessarily describe them as being in "conflict", but rather that extended tracking simply doesn't come into play when IP tracking is disabled. It's like, if someone gave you two instructions. The first instruction, "when you enter the house at address X, go to the kitchen and make some coffee." The second instruction, "never enter the house at address X." It's technically possible to correctly follow both instructions simultaneously, since the first is "*when* you enter", rather than the more simple alternative of "go make some coffee" (i.e., conditional), and just means that we'll never end up seeing that coffee being made, since the prior condition thereof is never fulfilled.

I could add some warning or notice to the auxiliary rules page to that effect, if others reckon it might be helpful to do so. Though, it's probably better to avoid adding *too* many of the *"warning! coffee is hot!"* variety of warnings and notices to the UI if at all possible, since it usually ends up being seen as merely additional unnecessary overhead by users more broadly in the long run anyway (there are a few such warnings and notices in CIDRAM already, mostly as legal precautions, like the cookie warnings for CAPTCHAs and for when logging into the front-end, that the users gives permission for cookies to be set by virtue of attempting to log in and such, though there's already been a few requests to remove those from various users in the past).

But anyway, TL;DR, you've surmised correctly. :-)

> What I am trying to do is detect $instaban, produce 403, and dont track, because the majority of cache.dat is instaban tracking which is pretty pointless.

Are we talking about *existing* "instabans" (i.e., follow-up requests from addresses already being tracked in such a state), or about *newly* "instabanned" requests (i.e., not yet being tracked, but something having triggered extended tracking already for the request at hand)?

If the former, I imagine that the easiest way to detect it via auxiliary rules would be to add "infractions" as one of the conditions you're checking against, and just check whether the request returns an infraction count of 1,000 or greater, since it's the same thing anyway. If the latter, I'm not entirely sure how we could do that at the moment, since the execution stage for auxiliary rules occurs earlier than the execution stage responsible for updating or adding to IP tracking.

**Comment by mikeruss1** [comment]
the objective is not to track it, so if it were possible it would always be the second case.

not important, maybe backburner
