### ISSUE TITLE
Cloud service is blocked but the module is inactive

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#226]
Some blocks from Cloud services.

But both ipv4/6 cloud services module are inactive. I have only TOR blocks, IPv4/6 (spammy ISPs) and IPv4/6 (proxies, VPNs, etc).

ID: 1621187572-058334-6502045102 »
Date/Time: Sun, 16 May 2021 20:52:52 +0300 »
IP Address: 178.32.98.98 »
Referrer: removed »
Signatures Count: 1 »
Signatures Reference: 178.32.0.0/15 »
**Why Blocked: Cloud service ("OVH Systems", L15072:F1, [FR])! »**
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0; Firefox 52.7.3 - 111512-1801120036-1.44 »

ID: 1621188069-417236-3860946762 »
Date/Time: Sun, 16 May 2021 21:01:09 +0300 »
IP Address: 91.134.248.230 »
Hostname: gwc.cluster024.hosting.ovh.net »
Referrer: removed »
Signatures Count: 1 »
Signatures Reference: 91.134.0.0/16 »
**Why Blocked: Cloud service ("OVH Systems", L15059:F1, [FR])! »**
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0 »

**Comment by Maikuolan** [comment]
Might need to disable the `block_cloud` directive in order to fully achieve the desired results here, I think.

Unfortunately, because OVH is a multiplay network, reaching quite extensively into various cloud services, as well as *also* into domestic and commercial connectivity alike, provides public WiFi, VPNs, and a bunch of other stuff, it doesn't quite fit perfectly into an *either-or* classification between cloud versus non-cloud.

Since the signatures, if we're to include them at all, need to go *somewhere*, I opted to keep the OVH signatures in the ISPs file, rather than in the cloud signatures file, because the likelihood of someone wanting to block cloud services without blocking ISPs is generally going to be higher than the likelihood of someone wanting to block ISPs without blocking cloud services, and keeping them in the ISPs file rather than the cloud signatures file is generally going to make it easier to cater to that more likely scenario.

I'm thinking about somewhat reorganising the signature files (among other things) for when I start working on v3 though, so hopefully this situation will be a little easier to deal with at that point.

**Comment by Maikuolan** [comment]
*Marking this issue as "QA", since it isn't exactly a "bug", nor a "feature request", but definitely concerns the "quality" of the package and implies/suggests room for improvement.*

**Comment by eurobank** [comment]
Well i'm not a programmer, so i can't tell where that issue belongs. I just want to be sure (as much as i can) that i do not block something i shouldn't.  Because that would reflect loss of money for me and i'm not rich....  :)

**Comment by Maikuolan** [comment]
QA work done. The originally cited problem should hopefully not occur too often anymore. :-)
