### ISSUE TITLE
Auxiliary option to send email

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#231]
just added a rate limiting detection and it would be useful if there was an option to send an email in the event of a given event.

nice but not important.

**Comment by mikeruss1** [comment]
also - just tested it, its delivering a http standard 429 page, I was expecting a standard CIDRAM block?
And there is no tracking so I guess it will never be completely blocked? But it is logged normally.
The latter might not be a problem as I was thinking of $instaban anyway. But will Auxiliary rules or custom mods pick it up if its not going through tracking?

**Comment by Maikuolan** [comment]
> just added a rate limiting detection and it would be useful if there was an option to send an email in the event of a given event.
> 
> nice but not important.

Might be possible in the near future. I've had some similar (but not identical) ideas recently too, which may also play into this. Haven't yet started trying to implement any of them though.

> also - just tested it, its delivering a http standard 429 page, I was expecting a standard CIDRAM block?

Ah.. Just double-checked over the existing code now, and it seems to be doing that. I guess, I said the wrong information before at Gitter. My bad.

I could work on it to provide an option to still provide the usual block page, I guess. Worthwhile..?

> And there is no tracking so I guess it will never be completely blocked?

Currently, that's correct. I'll be changing the way that tracking is configured soon though, so we should be able to adjust that soon enough. :-)

> But will Auxiliary rules or custom mods pick it up if its not going through tracking?

Custom modules should be able to pick up on it. Auxiliary rules though.. Doubtful. CIDRAM's rate limiting feature actually has its own files to track usage, separate from modules, separate from auxiliary rules, separate from tracking, etc (so, probably best right now to think of rate limiting as its own subsystem within CIDRAM, separate from those things).

**Comment by mikeruss1** [comment]
good news re email
429 - not important, 429 basically says the same thing, consistent though (grin)
tracking I think is important, otherwise it will never 403
auxiliary rules - custom mods is a workround - see previous re (grin)

**Comment by Maikuolan** [comment]
I know this issue is kind of old now, but I've been revisiting the idea of sending emails via auxiliary rules recently. I'm a little stuck between two opposing ideas though for how a receiving email address would be known by the auxiliary rules.

One idea I had, there would be a new configuration directive added where an email address could be specified, and a dropdown menu added to the auxiliary rules page in the same flavour as the "reCAPTCHA", "HCaptcha", "Suppress output template", "Suppress logging", etc menus for enabling/disabling email for any given rule (like an "Email:" label with "Leave it as is" versus "Send an email to the configured address when the rule is triggered" options).

The other idea I had, there'd be no new configuration directives added, and instead of a dropdown menu, a new text input field would be added to the auxiliary rules page in the same flavour as the "A name for the new rule", "The reason given to the user when blocked" etc text fields, where an email address could be specified directly per each rule (like an "If you want an email to be sent when the rule is triggered, specify the address here:").

Each idea has its own pros and cons.

First idea (new directive + dropdown) | Second idea (new text field only)
---|---
Pro: Don't need to retype the same email address over and over again into any rules wherever it's used, seeing as auxiliary rules would just be pulling the information from the configuration, where it would only need to be typed once (and then the option just enabled/disabled via the dropdown on the auxiliary rules page). This also means that if an email address ever needed to be updated, it would only need to be updated once (at the configuration). | Con: Would need to type the email address in for every rule wherever it's used, which could add up to a lot of extra typing. It would also need to be updated at each rule individually whenever the email address needed updating (which poses some risk of potential human error, e.g., if one of the rules is accidentally missed while updating, one of the rules has a typo in the address, etc).
Con: Pulling from the configuration would mean less versatility in the sense that all pertinent auxiliary rules would be forced to be sending to the same, singular email address. If we wanted to have one rule use one address, and another use another, that wouldn't be possible if they're all pulling from the same data. | Pro: Writing the information to the rules themselves means more versatility in the sense that if we wanted to have one rule use one address, and another use another, it wouldn't be a problem at all, because the rules would just be specifying to themselves whatever information is needed (e.g., the intended outbound address).
Pro: Keeping email addresses out of the auxiliary rules file means that sharing it doesn't pose the risk of those email addresses being leaked via whoever the file is being shared to. | Con: Keeping email addresses in the auxiliary rules file itself means that sharing it poses the risk of those email addresses being leaked via whoever the file is being shared to.

Probably other pros/cons too, but anyway, we don't need a full TL;DR report or anything, so that'll do. :-)

Which do you reckon would be better, from your own perspective?

**Comment by mikeruss1** [comment]
Option 1, simpler, cleaner, little value in multiple email addresses.
(completely forgotten about this !)

**Comment by Maikuolan** [comment]
Support for sending emails via auxiliary rules has now been added. :-)

From my testing prior to pushing the changes, it does as advertised and works properly. However, for the moment, I would caution against using it for anything beyond personal testing, or using with it with rules likely to be hit with any regularity, because I haven't yet implemented any limits, message digests, or safeguards against email flooding, which means.. if, for example, a particular rule was to be hit a few dozen times in as many seconds, you'd end up receiving as many emails in as many seconds, too (for now, at least). I'll work on doing something about that soon. But yeah; We've now got support for it, in any case.

**Comment by mikeruss1** [comment]
just testing, the labels for Aux Rules are {label.aux.mode_view} {label.aux.mode_edit} and applies in the page as well for example  label.aux is in front of the field names for a new rule 

something wrong with the display of rules

eg I have

Dont log cloud service 2:
 Method: "WinEx"
 Logic: "All"
 Don't log:
  If matches:
   WhyReason:
    - "*Cloud service*"

its just showing

 * Dont log cloud service 2–(||||||||||||||)
     o
       Why blocked≈|*Cloud service*|
     o 

I see its using PHP Mailer (naturally)

I havent installed it so I dont want to rush into testing

if this can be fixed I will see if I can run it from my desktop 

production seems to be working OK but I suspect modifying rules is not a good idea ?

**Comment by mikeruss1** [comment]
PHP 8.1.8
Deprecated: Optional parameter $Blank declared before required parameter $Data is implicitly treated as a required parameter in C:\wamp\www\cidram4\vault\events\phpmailer.php on line 65

**Comment by Maikuolan** [comment]
Whoops.. Good spotting. Pushed a fix for that deprecation notice just now. Cheers. :-)

**Comment by Maikuolan** [comment]
Still looking into the other issue.

**Comment by mikeruss1** [comment]
It's a while since I updated, 3.4.1 maybe

**Comment by mikeruss1** [comment]
Re email limit, maybe 2 in a minute from a particular UA, with a total limit of 5 in 5 minutes. Or the ability to set your own limits on a similar basis.

**Comment by mikeruss1** [comment]
applied that update and all working fine now. Aux rules look as they should. Email generation working fine.

thank you

**Comment by mikeruss1** [comment]
if you are bored sometime you could left align the email, centered is untidy IMHO

**Comment by Maikuolan** [comment]
Center alignment removed. :-)

Still trying to figure out the best way to sort out some of the other details.

**Comment by mikeruss1** [comment]
Indeed it is :-)

**Comment by Maikuolan** [comment]
Trigger notifications bundling has now been implemented. I still need to implement a mechanism to trigger it manually to enable cron integration and such. Almost done with this issue now.

**Comment by Maikuolan** [comment]
Mechanism to trigger it manually has been implemented.

Because I haven't yet documented it anywhere (and TBH, I'm not entirely sure where the best place to document it would be, within the documentation, or anywhere else), the API for the mechanism (for those that want to integrate it with cron or whatnot, and as to not leave them completely in the dark) is:

```PHP
$CIDRAM = new \CIDRAM\CIDRAM\Core();
$CIDRAM->manuallyTrigger();
```

Documentation aside (which I'll get around to eventually, and probably don't need to track via this issue anyway), I think that's everything in this issue now. :-)

**Comment by mikeruss1** [comment]
Excellent, thank you
