### ISSUE TITLE
[Question] IP tracking and Infractions

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#234]
Are there any more details and explanations about IP Tracking and Infractions?

What is the difference on a BAN from a module and from IP Tracking?

I would appreciate if someone could explain this in brief.

**Comment by Maikuolan** [comment]
The entire purpose of the IP tracking mechanism in CIDRAM is to be able to track bad/unwanted behaviours from IP addresses, which aren't necessarily related to the identity of the IP address itself (e.g., if an IP address is blocked due to requesting a protected resource, due to a blocked user agent, blocked hostname, etc, rather than merely due to the IP address itself belonging to a blocked CIDR), across different requests. So, let's say an IP address isn't blocked by any signature files, but does something we don't want, and ends up being blocked because of a module, once. We may think, "it's only once, so maybe it was a fluke, or something which won't happen again, so we'll just block it once, and then not worry about it anymore". But then, that same IP address does other unwanted stuff multiple times. Eventually, we'll think, "okay, this IP address is doing all these bad things, so maybe we should just outright block that IP address now". IP tracking provides a way to do that automatically, by counting those block events, and then, when a sufficient number of infractions occur, "banning" that IP address.

Worth noting that this is more of a "soft" ban, rather than a "hard" ban: When the tracking entry for that IP address expires (or, if IP tracking is cleared, or the specific entry manually cleared), the IP address becomes no longer banned anymore.

IP tracking is the mechanism which actually enforces the ban, but doesn't directly make any decisions about when to add new entries. Modules, on the other hand, don't directly enforce any of the bans, but make decisions about when to add new entries. So, the two are closely related, and work together.

At the front-end, when it's displayed that the IP address is "banned", it simply reflects that the number of infractions for that address exceeds the configured limit, after which, any offending addresses should be considered as "banned". IP addresses *without* any infractions aren't, strictly speaking, being "tracked", and are therefore not listed.

In the context of CIDRAM, the difference between being "blocked" versus being "banned", could be regarded as similar to the difference between continuous versus non-continuous in that, being "banned" simply means that the IP address is marked by IP tracking as being "banned", therefore meaning that the IP address should *continue* to be blocked into the future, for any future requests (until the ban expires), whereas if an IP address is merely *blocked* by a module, it doesn't necessarily mean that it will continue to be blocked into the future, and will most likely be allowed through, as long as it doesn't continue whichever behaviour caused the block event to occur in the first place.

This difference is really only applicable in the context of those things *other* than "signature files" (e.g., modules, auxiliary rules, search engine verification, etc), because "signature files" already block on the basis of CIDRs and IP addresses, which means that they're already "continuous" (not really much point in tracking the "behaviour" of something, when that "behaviour" is the identity of that "something" itself). So, a block event occurring directly because of the CIDR or IP address from which the request originates, could be considered as both "blocked" and "banned" in the traditional sense of those words, but CIDRAM avoids the term "banned" in such cases, in order to differentiate more clearly when IP tracking does/doesn't have anything to do with it.

**Comment by eurobank** [comment]
Crystal Clear! Please include the above somewhere in your manual or faq.

cheers !
