### ISSUE TITLE
IP Tracker Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#236]
As you can see in the capture, it can't be right. Banned for 1.000s and expiration a year later. That IP had only one infraction. I can't find 1.000s anywhere. And a year later !!!

![Screenshot](https://user-images.githubusercontent.com/4467158/122668773-613a3f80-d1c2-11eb-8a67-ac8fbb0d815b.png)

**Comment by mikeruss1** [comment]
thats $instaban - under defined circumstances you can set the block time to a year. Its a setting in auxiliary rules or its a custom_mod. In auxiliary rules its "Enforce extended IP tracking options"

**Comment by eurobank** [comment]
@mikeruss1 I can't find that anywhere? Where is it? Also I haven't set anything like this ever.

I have no custom_mod or aux rules.

**Comment by mikeruss1** [comment]
waits for Caleb !! Are you using ver 1. It was covered in one of the doc files in the distribution.

**Comment by eurobank** [comment]
@mikeruss1 I use 2.6

**Comment by Maikuolan** [comment]
> thats $instaban

True, except that I'm not calling it that anymore. I removed all references to "`$instaban`" from CIDRAM a while back, in order to avoid any potential confusion with the way "instabanning" works for other WAFs and other software elsewhere. Internally, for any modules which used it, those references have been replaced with "`$ModifyTracking`" (seeing as "modifying tracking" is what it's actually doing, therefore less likely to cause any confusion). ;-)

*Example (as seen in the code for some of the modules):*
```PHP

    /** Sets tracking time to 1 year and infraction count to 1000. */
    $ModifyTracking = ['Options' => ['TrackTime' => 31536000, 'TrackCount' => 1000]];
```

**Comment by Maikuolan** [comment]
> It was covered in one of the doc files in the distribution.

Actually, I don't think I've covered that particular point in the documentation yet. The section of the CIDRAM documentation for modules ("[7.4 BASICS (FOR MODULES)](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#74-basics-for-modules)") explains in quite a bit of detail information about how to write custom modules, what they're for and so on, but it doesn't currently mention about extended tracking or about how to modify tracking. I'll probably get around to writing about it eventually, but TBH, it's priority is quite low compared to other things I want to get done for CIDRAM, so I'm not sure exactly when it'll happen.

**Comment by eurobank** [comment]
So still a mystery to me. Why the ban happened and what must i do?

**Comment by eurobank** [comment]
This is coming from two modules i use as you can see. I have nothing custom or modified:

![2021-06-20 14_02_43-Window](https://user-images.githubusercontent.com/4467158/122671629-5686a700-d1d0-11eb-9c24-bbf5bfcfd5b4.png)

**Comment by Maikuolan** [comment]
Generally, such bans should only occur for signatures regarded as more "severe" (e.g., signatures intended to match against indicators of malware, direct hack attempts, etc). But, I'm thinking I'll try to implement some new configuration options to better control things like this. Easier than messing around with customised modules to counter it and such things.

**Comment by mikeruss1** [comment]
re doc file 
its all in moduletemplate.txt

**Comment by eurobank** [comment]
@Maikuolan 

This is the ONE log for the ban i posted:


ID: 1624145611-297976-1937060102 »
Date/Time: Sun, 20 Jun 2021 02:33:31 +0300 »
IP Address: 27.69.215.140
Hostname: localhost »
Referrer: https://www.google.com/ »
Signatures Count: 1 »
Signatures Reference: module_badhosts.php:L265 »
Why Blocked: Spoofed/Fake Hostname! »
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15 »

**Comment by Maikuolan** [comment]
Ah.. Yep. That makes sense. :-)

The specific signature in question (`module_badhosts.php:L265`):
```PHP
    $Trigger(preg_match('/^localhost$/', $HN) && (
        !preg_match('/^(?:1(?:27|92\.168)(?:\.1?\d{1,2}|\.2[0-4]\d|\.25[0-5]){2,3}|\:\:1)$/', $CIDRAM['BlockInfo']['IPAddr'])
    ), 'Spoofed/Fake Hostname', '', $ModifyTracking); // 2018.06.24
    $Trigger(preg_match('/\.local$/', $HN), 'Spoofed/Fake Hostname'); // 2017.02.06
```

The signature in question is intended to catch any hostnames which falsely claim to be `localhost` (i.e., the signature in question shouldn't ever trigger for any requests which are *actually* originating from localhost, but *will* trigger for any non-local requests falsely claiming to be from localhost).

The reason why this signature warrants a heavier response than usual, is that localhost spoofing is a tactic we've encountered before in attempts to hack into software, scripts, frameworks, routers, and other such things, which typically provide a different response to localhost requests than other requests, and which don't themselves always have sufficient checks in place to ensure whether a supposed localhost request is *actually* what it claims to be, and in attempts to avoid security policies which some networks have towards non-local requests.

In this particular case, the requests seems to originate from Viettel, a Vietnamese ISP which has had its hostnames configured as "localhost" since as long as I've known about them now (quite a number of years now). The problem seems to be at the ISP level, and nothing to do with any specific, individual customers at their network. I'm honestly not sure why they haven't yet fixed that misconfiguration, or why they chose to configure it that way in the first place, but it isn't anything new for them. Definitely unusual though, and a practice which the majority of ISPs around the world avoid.

**Comment by Maikuolan** [comment]
> But, I'm thinking I'll try to implement some new configuration options to better control things like this.

Done. :-)
