### ISSUE TITLE
Question about IP Tracking

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#238]
Yesterday we had 200+ IP tracked.  And two with score 1000.

Today we have 27, all ending at 1st of July and no IPs with 1000.

Is that normal and if yes, why this happened?

**Comment by 737simpilot** [comment]
First and foremost, I'd encourage you to join the chat at Gitter. https://gitter.im/CIDRAM/Lobby

To answer your question. A score of 1000 is created by CIDRAM if that IP is very naughty. Thus a permaban. 

Do I have that right @Maikuolan ?

**Comment by eurobank** [comment]
So a permaban should NOT have been lifted if i get this right.

As for the Gitter, i understand that here is not the right place to ask questions or report things?

**Comment by Maikuolan** [comment]
> Thus a permaban.

Probably better to just think of it as an "extended ban", rather than a "permaban" (seeing as it extends the ban from the default length of time according to `signatures➡default_tracktime`, typically, to a year, rather than indefinitely). But basically, yeah; that's the right idea.

> So a permaban should NOT have been lifted if i get this right.

Correct.

However, there are, unfortunately, some known, specific conditions and situations which can cause it to happen (seeing as all IP tracking data is treated by CIDRAM as cache data, i.e., stored in CIDRAM's cache, that data is subject to `supplementary_cache_options`; depending on whether you've customised any of the configuration under `supplementary_cache_options` or whether you're using all the defaults, the exact conditions/situations may be slightly different, but there unfortunately exists such conditions/situations no matter the case).

In the case of the defaults (which read/write from/to actual files), file race conditions are the primary and most likely culprit. In this case, sometimes (but rarely), if there are multiple system processes or threads at the server, each/all attempting to operate on CIDRAM's cache data at the exact same time, causing the resources to become temporarily "locked" from further access, and at that exact same time, CIDRAM attempts to access its own cache data, but is unable to properly read it due to it being "locked", CIDRAM may consequently behave the same way as when it normally behaves when there doesn't yet exist any cache data (e.g., new installations running for the first time), preparing and creating a new cache file to be used for future requests (and in this case, overwriting all the old cache data, seeing as it was "locked", therefore causing CIDRAM to think it doesn't exist).

In the case of using PDO settings, if the total size of the IP tracking data exceeds the maximum allowed field size for the table which CIDRAM uses for its cache data, the moment something new is then added to IP tracking, the IP tracking data can become corrupted, unreadable, and similarly be completely reset and overwritten upon the next subsequent request (see #162). I hope to be able to resolve that problem soon enough, though.

In the case of some of the other options provided (e.g., Memcached, Redis, APCu, etc), seeing as all those, as cache mechanisms, hold data only as long as the process/thread remains alive, in the event that the host decides to shut down or restart any of those processes/threads for any reason, any contained cache data would be lost, with CIDRAM's cache data being consequently reset upon the immediate next request.

So definitely, such bans should *not* be lifted until such times. But, there unfortunately is no guarantee that they wouldn't be lifted early, due to those conditions/situations.

> As for the Gitter, i understand that here is not the right place to ask questions or report things?

Generally, either here or there is fine. The issues page here is the best place for questions, for support, for reporting things and etc. The Gitter channel is the best place for any off-topic discussion, general social interaction/discussion/chat which isn't strictly related to CIDRAM.

If someone wanted to share something like, *"Hey guys, check this out! I found this really funny cat video, which I think you'll all like, because it's funny. But it has nothing to do with CIDRAM at all, sorry"*, that would *not* be appropriate for the issues page, and would *definitely* be better kept to just the Gitter channel, because we really don't want to clutter up the issues page with completely unrelated stuff like that, such things would make the issues page less usable, and would most likely really annoy other users, too. But, within reason (i.e., as long as not spammed like crazy, and as a natural part of the conversation there, rather than as an obnoxious interjection or something like that), it would be okay at the Gitter channel. In short: The issues page is for issues, whereas the Gitter channel provides an avenue to let off a bit of steam, and for anything else unrelated to issues, which those in the community or using the issues page may otherwise like to share/discuss/whatever.

Sometimes issues are also discussed at the Gitter channel too, though. That's also okay, if it's something brief, a one-line question, general comment, or something like that. The main problem with using Gitter for issues, is that it's effectively like a chatroom, content eventually becomes lost, or very difficult to find, the older that content becomes, as new content appears and eventually pushes the older content further into the history of the Gitter channel. So, for more long-term issues, or issues which require extensive discussion, a long period of time to resolve, or very close monitoring, it's definitely better to just use the issues page here at GitHub, because it would be difficult to effectively do those things at Gitter. Using the issues page here at GitHub means we have a recorded history of old, previously resolved issues too, which makes it easier to refer back to those old issues if very similar or related new issues appear in the future, whereas it's very difficult to find and refer back to really old Gitter content, because we would need to manually search through everything until we find it, and it may eventually be deleted by Gitter anyway if it becomes too old. But, if the issue is something which can be easily resolved in less than 5 minutes, which we won't likely ever need to refer back to, won't need to discuss extensively, or won't need to track, then Gitter should be okay for that, since the negatives of using it won't matter much in that case.

The Gitter channel is used quite a bit for discussing potential new additions to the signature files, too (e.g., someone discovers a new IP/range/CIDR/UA/etc which should be investigated for possible addition to the signature files or modules).

I don't think we need to be strict about how we approach it, but we have both available, seeing as each has slightly different pros and cons, benefits, considerations, etc (useful to have both available, for each to be able to cover whatever the other isn't entirely able to, or entirely well-suited for).

**Comment by eurobank** [comment]
There is a discussion area here at github also.

As for the issue of permaban:

1.  I do not have any caching on the server. 

2. NO PDO or anything, just flat files.

3. It seems that when the weekly ban was lifted, the permaban also did.

Now i have again 4 permabans. I wait for the normal banned to be cleared to see if the permabans will be lifted also (again).

**Comment by eurobank** [comment]
This seems fixed.
