### ISSUE TITLE
Possible wrong block for msnbot?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#242]
ID: 1626034641-598639-4643493328 »
Date/Time: Sun, 11 Jul 2021 23:17:21 +0300 »
IP Address: 157.55.39.76 »
Hostname: msnbot-157-55-39-76.search.msn.com »
**Query: d477b »**
Signatures Count: 1 »
Signatures Reference: 157.55.38.0/23 »
Why Blocked: Cloud service ("Azure", L35642:F0, [US])! »
User Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0) »
Reconstructed URI: https://web site . com /wp-content/litespeed/cssjs/0a6f5.js?**d477b** »

The "query" is actually a merged litespeed cache file. And the IP doesn't seem to be malicious, i have found some blocks for it, still looks legit.

**Comment by eurobank** [comment]
not an issue.

**Comment by eurobank** [comment]
Is that an issue ?

ID: 1627506494-824359-4293473811 »
Date/Time: Thu, 29 Jul 2021 00:08:14 +0300 »
IP Address: 157.55.39.30 »
Hostname: msnbot-157-55-39-30.search.msn.com »
Query: b90e4 »
Signatures Count: 1 »
Signatures Reference: 157.55.38.0/23 »
Why Blocked: Cloud service ("Azure", L35925:F0, [US])! »
User Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0) »
Reconstructed URI: https : // web site . com /wp-content/litespeed/cssjs/3567c.js?b90e4 »

**Comment by Maikuolan** [comment]
The main problem there, is that when Bingbot/MSNBot (or for that matter, any other search engine which *has* its own official, self-declared, and clearly documented user agent) sends a request, it should *use* that user agent, in order to clearly *identify* itself. CIDRAM has mechanisms in place to identify, verify, and prevent the blocking of search engines, but in this case, those mechanisms didn't trigger, because Bingbot/MSNBot failed to utilise its own user agent in order to properly identify itself (or least, what I *assume* is Bingbot/MSNBot, based on the hostname, but we're also assuming here that nothing *else* is operating from that hostname, seeing as, although based on that hostname, it may *appear* to quite *obviously* be Bingbot/MSNBot, based on Bingbot's *own official instructions* regarding how to identify Bingbot, which state, first and foremost, to check the user agent, it *shouldn't* be).

But, because Bingbot/MSNBot is kind of dumb, and has repeatedly done this kind of thing over the years, I'm going to go ahead and assume that it *is* Bingbot/MSNBot, and that they're yet again, just completely ignoring their own standards and own instructions. Accordingly, I've gone ahead and improved the default bypasses for Bingbot/MSNBot (see referenced commits), so that this particular block shouldn't occur again.

**Comment by eurobank** [comment]
Well you are right in one thing, msnbot is the very very very stupid (along with duckduck bot). Not only for what you mention, but in general. 

**Go go go Msoft, see how google does it.**

**Comment by 737simpilot** [comment]
I've seen this UA being used by Bingbot many times myself. `Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)`

At least DuckDuckGo goes by a set of IPs with a UA. The biggest pain in the a$$ is HSTS preload checking by Google or Mozilla ( I think it's via Google) with their use of a crap ton of IPs within a hosting ASN I block and they use a crap UA. So the UA to IP ratio is gone and thus makes it hard for verification purposes to let it on through one's security. 

Why on Earth would I allow some Google ASN that's rife with crap? I think I mentioned this on the Github page for at least a UA unique to the task at hand, but I don't recall any feedback from my posted issue from Google.

So what I end up having to do to make sure my domain stays on the HSTS prload list in mainstream browsers is every once in a while allow the whole damn ASN and check my domain here: https://hstspreload.org/
