### ISSUE TITLE
Possible Redditbot wrong block?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#243]
ID: 1626044558-078914-1123784498 »
Date/Time: Mon, 12 Jul 2021 02:02:38 +0300 »
IP Address: 54.163.182.147 »
Hostname: ec2-54-163-182-147.compute-1.amazonaws.com »
Signatures Count: 2 »
Signatures Reference: 54.160.0.0/12, module_badhosts.php:L237 »
Why Blocked: Cloud service ("Amazon.com, Inc", L11485:F0, [US]), Amazon Web Services! »
User Agent: Mozilla/5.0 (compatible; redditbot/1.0; +http://www.reddit.com/feedback) »

**Comment by Maikuolan** [comment]
It seems that redditbot uses AWS, but not any specific IPs, and could potentially come from any IPs from within AWS. I guess, I may need to write a generic bypass for redditbot against the AWS signatures. Not ideal, since it would mean that any *other* bots from within AWS could potentially bypass the AWS signatures simply by changing their UA to match redditbot's, but I don't see any alternative solutions, unfortunately.

*References:*
- *https://www.reddit.com/r/redditdev/comments/glbqpx/hostname_or_ip_of_reddit_bot/*
- *https://udger.com/resources/ua-list/bot-detail?bot=redditbot*

Maybe I should make it so that this soon-to-be-created bypass, and some of the other, already existing bypasses, will be configurable? Might help maybe, given that some users might be thinking, "yeah, we definitely don't want to block redditbot, so please let it in", while other users might be thinking, "nah, not worth it, I don't want to allow AWS access no matter what, so just keep it blocked".

Anyway, I'll start working on this a little later today.

**Comment by eurobank** [comment]
Tricky situation since AWS is a huge source of crappy bots and other hacking tools.

**Comment by mikeruss1** [comment]
default the bypass to off maybe?

**Comment by Maikuolan** [comment]
I'll do that. I'll make it configurable, and have it turned off by default.

**Comment by Maikuolan** [comment]
Fixed by a37dc62b0c46181c8c0f020ca61cb2ea252f3254 and 4ce6685cff0d612ae82007299f80b09c2cc1145e. :-)

**Comment by eurobank** [comment]
Guys how do i enable that bypass? I can't find it in cfg....

**Comment by mikeruss1** [comment]
if you look in the config / bypasses - Redditbot is the last one

**Comment by eurobank** [comment]
oh... a checkbox list i missed. Appreciated.
