### ISSUE TITLE
badtlds module not working ?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#247]
I have "badtlds" module activated but i haven't seen a single block due to that. I monitor 7 websites with one installation.

Isn't that strange or i'm missing something ....

**Comment by Maikuolan** [comment]
I'm pretty sure I saw some unwanted traffic blocked as a result of the module a few years ago, around the time I'd first started using it, but I don't recall anything recent at any of my own installations either.

The module was created based on information from some third-parties a long time ago, regarding the ratio of actual normal, proper hosts utilising those TLDs versus dangerous, garbage, malware-infested hosts using those TLDs, whereby the latter would attempt to support botnets and spread malware via requests to other hosts/websites. I should have the information still available on one of my harddrives somewhere, in order to be able to share it here, but I'll need to look for it and dig it up, or maybe I can try finding it again by searching for it online. I'll post it here if I'm able to find it.

Anyway, probably best to regard the bad TLDs module as a precautionary module; a module intended to block unwanted traffic which *might* occur (but which isn't guaranteed to occur, or might occur only very rarely), with it usage being a low priority, but also something with a very low risk of false positives.

**Comment by Maikuolan** [comment]
BTW.. For anyone curious, the module only contains two signatures, so it isn't a particularly complicated module:

```PHP
    $Trigger(preg_match(
        '~\.(?:bid|click|club?|country|cricket|date|diet|domain|download|fai' .
        'th|gdn|gq|kim|link|men|museum|party|racing|review|science|stream|to' .
        'kyo|top|webcam|website|win|work|xyz|yokohama|zip)$~i',
        $CIDRAM['Hostname']
    ), 'Disreputable TLD'); // 2018.04.08

    $Trigger(preg_match('~\.onion$~i', $CIDRAM['Hostname']), 'Anonymous/Unroutable TLD'); // 2017.12.28
```

From those two signatures, the total TLDs actually blocked there are as follows:

```
bid
click
clu
club
country
cricket
date
diet
domain
download
faith
gdn
gq
kim
link
men
museum
onion
party
racing
review
science
stream
tokyo
top
webcam
website
win
work
xyz
yokohama
zip
```

(Note that by "TLDs actually blocked", what's being referred to here is just any ordinary HTTP/S requests, made to a website where the bad TLDs module is installed/active, where said requests originate from IP addresses which resolve back to an affected/blocked TLD).
