### ISSUE TITLE
Rate Limiting question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#251]
Rate limit is set at 12 in 1min and 12 secs

got a block after 9 in 4 secs

not saying this is wrong, I guess it is doing some extreme pro rata validating ?

looked in more detail and I suspect there are some GETS missing from the log, possibly due to the volume?

so please ignore !!

**Comment by Maikuolan** [comment]
It counts back over every request encountered by CIDRAM over the specified period, so yeah.. definitely all validated. :-)

Not sure about logs. Could be due to volume, or maybe race conditions affecting logging, or something like that..? Not sure.

**Comment by mikeruss1** [comment]
got another sequence of something like 30 GETS in 5 seconds not detected by rate limiting. Noticed that rl.dat is a hard file in the vault even though memcached is turned on. It may not make much difference but probably worth changing if easy ?

**Comment by Maikuolan** [comment]
Yeah.. I might look into that. Could maybe be a worthwhile idea. I'll need to do some testing and benchmarking to confirm any potential performance differences, of course (I haven't done any related testing/benchmarking for CIDRAM's rate limiting before, so I don't have any guesses offhandedly). But yeah; Could be worthwhile. :-)

**Comment by mikeruss1** [comment]
had a go at coding memcached based rate limiting for very short term rate limits, currently 4 in 5 seconds. Its very efficient as you can use the expiration time at 5, and the IP address as the key, first 2 quartets only so it catches IP variations. Search engines dont matter as they shouldnt be using such high data rates anyway.

no prize for guessing which search engine keeps tripping it.

**Comment by Maikuolan** [comment]
Looking into implementing this now.

Thinking about whether we need extra configuration directives for this (e.g., specific directives to configure whether to continue using `rl.dat`, to instead use APCu, Memcached, etc), or whether it'd be better to instead just streamline it all as such that rate limiting can utilise the values already provided by the supplementary cache options.

On one hand.. Providing extra configuration directives would provide additional control, allow cache to use one thing, whereas rate limiting could optionally use something else entirely if so desired, and would also be backwards compatible (in the sense that current behaviours could be retained if so desired). I'm generally a big fan of maintaining backwards compatibility between minor releases, just earmarking backwards-incompatible changes for future major releases. However, I'm also a little concerned about bloating up the configuration with a huge number of new configuration directives when we don't necessarily absolutely need them, making it more complicated/confusing for new users to configure CIDRAM properly and so on (if, for the sake of the argument, hypothetically speaking, rate limiting were to provide all the same features that the supplementary cache options does, e.g., APCu, Redis, Memcached, PDO support, etc, while still retaining distinct directives.. that's potentially about 13 directives to duplicate for rate limiting, which is kind of a huge number).

On the other hand.. If I were to just streamline rate limiting as such that it uses the values provided by the supplementary cache options, rate limiting would always be locked into using whatever the cache uses (which might mean a little less control than the former option, but would still, strictly speaking, be better than things stand right now anyway, seeing as rate limiting currently is locked into using a `rl.dat` file anyway, with no alternative options currently available, and I also doubt that many users would want to use distinct, separate mechanisms between rate limiting and caching anyway). It would also potentially be a *slightly* breaking change, at least, for those users already actively using rate limiting, which've also set non-default values for the supplementary cache options (e.g., in order to enable APCu, Memcached, Redis, etc for caching), in the sense that rate limiting's behaviour would be immediately changing between updates from using `rl.dat` to using whatever has been specified by the supplementary cache options, without needing to set any new values anywhere. But, such a small breaking change is unlikely to be a big deal for the vast majority of users, and given that I anticipate that most users don't use rate limiting anyway.. one we could probably safely ignore. However, the major advantage of this approach is that I wouldn't need to bother adding even a single new configuration directive, which entirely avoids the risk of bloating up the configuration, thus avoiding making things more complicated/confusing for new users. When there's no particular need to complicate things beyond a certain point.. simpler is often nicer.

Thoughts?

**Comment by mikeruss1** [comment]
my feeling is that this is an internal change and there is no reason why it should be a config item. If you are confident its working then go for it, as long as older versions are easily available. So, if using cache then info ex rl,dat is in cache. Just one thought, the rate limiting period should really allow for easier fine tuning. Mine triggers with 4 items in 5 seconds which is clumsy to set with current parameters. Maybe offer a period selection - hours, mins or seconds ?

I think you said some time ago that if cache is reset, then the parameters are auto rebuilt in cache?

**Comment by Maikuolan** [comment]
> my feeling is that this is an internal change and there is no reason why it should be a config item. If you are confident its working then go for it, as long as older versions are easily available.

Excellent. I'll go for it then. And cheers for the feedback. :+1:

> Maybe offer a period selection - hours, mins or seconds ?

Might be possible. I'll have a play around with it and see what I can come up with.

> I think you said some time ago that if cache is reset, then the parameters are auto rebuilt in cache?

You mean as in what's set at the configuration? Or something else? Configuration won't ever be touched by a cache reset, although naturally, the actual contents of the cache would be.

**Comment by mikeruss1** [comment]
> You mean as in what's set at the configuration? Or something else? Configuration won't ever be touched by a cache reset, although naturally, the actual contents of the cache would be.

loss of cache means its emptied, but processing restarts as normal?

**Comment by Maikuolan** [comment]
> loss of cache means its emptied, but processing restarts as normal?

Yep. :-)

**Comment by mikeruss1** [comment]
the other things I remember were there was no logging, and no blocking?

**Comment by Maikuolan** [comment]
Implemented. :-)

**Comment by Maikuolan** [comment]
(Rate limiting should now use whatever the cache uses, according to whatever is set for the supplementary cache options).

> the other things I remember were there was no logging, and no blocking?

When someone is "rate limited", they'll be blocked, and the block event logged accordingly. :-)

**Comment by mikeruss1** [comment]
> When someone is "rate limited", they'll be blocked, and the block event logged accordingly. :-)

great thank you
blocking - is it using the same rules as normal signatures, like 3? blocks and you are blocked for the defined time

**Comment by Maikuolan** [comment]
> is it using the same rules as normal signatures, like 3? blocks and you are blocked for the defined time

Yep, same rules. :-)
