### ISSUE TITLE
Tracking cloud service

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#257]
The problem with trying to track cloud service is the IP gets rotated so we end up trying to track thousands of addresses. So generally it's pointless.

However in most circumstances it's only the last 2 quartets that vary, so it might work to track just by the first 2 quartets?

**Comment by Maikuolan** [comment]
Possibly so. The problem there though, is being able to readily identify those IPs which belong to cloud services, versus those which don't, in the context of those requests which aren't already blocked by existing signature files. If the blocked IPs are already listed by the CIDRAM signature files under reason of being cloud addresses, generally speaking, those signatures will already encompass a rather wide range, rather than merely single IP addresses or smaller such ranges, thus meaning we don't really need to track them regardless of whether it's the entire address or just the first two octets. On the other hand, if they're *not* already listed by the CIDRAM signature files, then they're most likely being blocked due to a module or an auxiliary rule, and in such cases, we can't always guarantee, or programmatically offer a reliable opinion, as to whether or not those addresses belong to cloud services (thus making it difficult, in this scenario, to determine whether we should block by the entire address or just the first two octets).

I am considering though, possibly for v3, the possibility of completely rewriting how "track mode" works, so that rather than simply being a boolean configuration option, it can instead offer a range of options, such as whether to track specifically for modules, for auxiliary rules, versus for signature files, or for which kinds of signatures it could be enabled/disabled for (e.g., "Cloud", versus "Spam", versus "Generic", versus "Malware", etc). I'm not entirely happy with how it currently works for v2 anyway.

**Comment by mikeruss1** [comment]
yep - agreed - thanks

**Comment by Maikuolan** [comment]
> ... so that rather than simply being a boolean configuration option, it can instead offer a range of options, such as whether to track specifically for modules, for auxiliary rules, versus for signature files ...

That part has been implemented to v3 now, and is working as intended (the new `shorthand` directive).

But..

> ... or for which kinds of signatures it could be enabled/disabled for (e.g., "Cloud", versus "Spam", versus "Generic", versus "Malware", etc).

..I'm not *entirely* sure what would be the best way to go in that regard. Bit of a question concerning configuration logic and user-friendliness, I guess..?

What we have currently for `shorthand`:

![1](https://user-images.githubusercontent.com/12571108/179028449-78c52e97-07c7-44bd-b63e-97b2fc4aa3ad.png)

I was *thinking* about maybe adding another column, to either enable tracking or disable tracking on the basis of the shorthand word used (whether it should be to enable or disable, I'm not sure either, but that's a little less important anyway). Something like this:

![2](https://user-images.githubusercontent.com/12571108/179029000-464ba1d8-a6ac-4e2e-9a9a-00f5fd2b003c.png)

But *if* I did that, the question then, would be regarding how *this* particular checkbox should behave:

![3](https://user-images.githubusercontent.com/12571108/179029087-12e99ebe-c2e3-43f1-b7ab-3e8bfeef5529.png)

Given that currently, the particular checkbox in question already enables or disables IP tracking for signature files, but as a whole, rather than on a per-shorthand basis, it might run up against something newly added to `shorthand` to deal with tracking.

Any ideas? Reckon I should ditch the idea of configuration tracking per-shorthand and just stick with doing things as a whole as per is the case currently? Keep the idea but implement it differently maybe?

(Although this concerns the original intent of this issue, to be able to not track cloud services, we could resolve that either through this, or through some other means; I'm not meaning to abandon the original intent of this issue). '^^

**Comment by mikeruss1** [comment]
I think I dont quite understand what is meant by "this stage" ...

if I dont want "Attacks" tracked, then any other infractions for that GET are irrelevant, and dont affect track counts. I may or may not want the item logged, so may or may not want to see other errors, depending on whether logging is turned off.

is that an answer?

**Comment by mikeruss1** [comment]
after some dabbling I understand the question at last ....
my view is that in general I want things tracked and logged. There are specific circumstances where I seek to turn off tracking and/or logging, but this requirement generally does not sit neatly with a coarse turn off like Attacks, or signatures.
For instance I use aux rules to turn off tracking and logging for cloud and attacks where signatures = 1, as this could be a VPN, and I get lots like this which fills up the database with waste.
Usually bulk attacks, which I would like to ban, have 1 IP and lots of signatures, so it makes sense to try tracking.
Just my view, others may differ.

**Comment by Maikuolan** [comment]
I don't think there's anything left to do regarding this particular issue anymore..? Should be okay to close, I think.
