### ISSUE TITLE
Auxiliary question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#259]
I currently only offer recaptcha if there is one signature block which is "Cloud service" thus allowing VPN users to access.

the test is a profile with block reason not equal to Cloud service, disable recaptcha

I want to also allow old browsers to get recaptcha but I obviously cant add another profile with block reason not equal to "Your browser is old", disable recaptcha, as each will likely disable the other?

can we include OR and AND commands like ...
block reason not equal to "Cloud service" OR "Your browser is old" disable recaptcha

or is there another way?
thanks!

**Comment by Maikuolan** [comment]
It's possible to chain profiles together, if we want.

That's how I'd do it: Separate profiles for each scenario, plus a third to enforce that reCAPTCHA be disabled (e.g., rule 1, if signature count is exactly 1, *and* the block reason includes "Cloud service", then profile the request, "Single-hit cloud service request"; rule 2, if signature count is exactly 1, *and* the block reason includes "Your browser is old", then profile the request, "Single-hit old browser request"; rule 3, if the profile matches "Single-hit cloud service request", *or* the profile matches "Single-hit old browser request", then profile the request, "reCAPTCHA disabled by aux", with the aux. rule option for "forcibly disable reCAPTCHA" selected). :-)

Of course, you don't need to do it exactly like that; Adjust as per your own tastes and your own needs. But, that's the best way currently to utilise complex AND/OR expressions through auxiliary rules to have CIDRAM enforce whatever various effects might be wanted.

(Of course, the exact execution order of profiles becomes important in this case: Any profiles, which we intend to leverage themselves as conditions for further rules, would need to occur *before* the rules which leverage them, due to that we'll need to invoke a positive hit for any given profiling rule before it can become a potential valid value for any rule conditions intended to match against those profiles; i.e., if C is looking for A or B, in order for C to be able to successfully find A or B, A or B must occur before C; A or B occurs, they become visible, C can find them; if C occurs first, it'll never find A or B, because A or B would effectively not exist yet in the memory of the current request).

**Comment by mikeruss1** [comment]
thank you - but the test is the wrong way round, I only want to enable recaptcha if its Cloud Service or Old Browser

I have set profile 3 to turn on recaptcha, and changed the recaptcha config option to
Only when not blocked, or specially marked for use

is that right ?

**Comment by Maikuolan** [comment]
Sounds right to me. :-)

Note though, that the two *"Only when not blocked"* options ([*docs link*](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#usemode)) will raise a CAPTCHA challenge to requests which aren't blocked (i.e., not in signature files, not blocked by modules, etc), which is effectively having CIDRAM put up a page in front of the normally requested webpage, similar but distinct from the usual *"access denied!"* page: Such CAPTCHA challenges, when raised, are not regarded by CIDRAM as a "block event" (because nothing was triggered, no signatures raised, etc), and therefore, just like any other non-blocked request, won't be logged, and won't be recorded by IP tracking or anything else. If using either of the "invisible" CAPTCHA APIs, the end-user most likely won't notice it either, but something I figure worth mentioning anyway.

**Comment by mikeruss1** [comment]
OK thats the wrong one ...
Only when blocked, specially marked for use ....

**Comment by Maikuolan** [comment]
Yep. :-)

**Comment by mikeruss1** [comment]
and works ! - re captcha logging - I did get confirmation of passed captchas with ....
Only when not blocked, or specially marked for use

**Comment by Maikuolan** [comment]
Glad to hear that it's working. :-)
