### ISSUE TITLE
Reason for this block?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#261]
I have ONLY the TOR block module active (at the moment) and nothing else. What is the reason for the block below? 

Have i done something wrong?

ID: 1632641125-884712-4533723440 »
Date/Time: Sun, 26 Sep 2021 10:25:25 »
IP Address: 69.171.251.20 »
Hostname: fwdproxy-ash-020.fbsv.net »
Signatures Count: 1 »
Signatures Reference: functions.php:L1583 »
Why Blocked: Fake Googlebot! »
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »

**Comment by Maikuolan** [comment]
The `fbsv.net` domain is owned by Facebook, and typically is used as the origin for their bot when it fetches content from websites for when something from those websites is shared to their platform, but can also be used by app developers as a proxy for any apps they write for Facebook. The request here originates from that domain, but claims to be a Googlebot request. However, Googlebot should only ever originate from Google's servers, and Google doesn't use `fbsv.net` for anything at all. So, I'm guessing, someone is using Facebook's servers as a proxy for an app which pretends to be Googlebot, most likely for scraping purposes. Because it isn't a real Googlebot request, CIDRAM has flagged it accordingly and blocked the request. :-)

**Comment by eurobank** [comment]
So even if NO modules or signatures are enabled, CIDRAM still blocks things? Do iget this correctly?

What exactly does it block? Is that information available anywhere?

**Comment by eurobank** [comment]
or to better word the above, how can i have CIDRAM block ONLY TOR (via module) and nothing else?

**Comment by Maikuolan** [comment]
All the block events with a *"Why Blocked"* containing *"Fake (this or that)!"* (like this one, which has the *"Fake Googlebot!"* message) are controlled by the [`search_engine_verification`](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#search_engine_verification), [`social_media_verification`](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#social_media_verification), and [`other_verification`](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#other_verification) configuration options. If those three options are disabled, these particular kinds of block events shouldn't occur anymore. :-)
