### ISSUE TITLE
Auxiliary suggestion

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#266]
the GUI allows a rule to be moved to the top or bottom. It would be more flexible if the interface provided a move up or down slider. Not urgent, maybe next major version?

**Comment by Maikuolan** [comment]
I didn't code support for that particular functionality in the past, back when I was first creating the GUI, due to some technical difficulties at that time, related to the way that CIDRAM processed auxiliary rules at the front-end at that time, but there's been a lot of changes and refactoring done since then, so it might be much easier to code in now. I'll take a look and see what I can do. :-)

**Comment by Maikuolan** [comment]
Implemented. :-)

**Comment by mikeruss1** [comment]
Neat, thank you
