### ISSUE TITLE
Cloud service x 2

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#268]
Maybe once a day I get 2 signature blocks for Cloud service ... example is
Hostname: 172.247.34.176 »
Query: - »
Referrer: - »
Signatures Count: 3 »
Signatures Reference: 172.247.0.0/16, 172.247.34.0/23, mcm_bobuam.php:L121 »
Why Blocked: Cloud service ("CNSERVERS LLC", L13397:F4, [US]), Cloud service ("Zenlayer Inc", L9170:F4, [US]), 

is this correct ? Only issue is I only offer recaptcha on 1 signature

**Comment by Maikuolan** [comment]
Sorry for the delay. Busy past few days. I'll investigate this now.

**Comment by Maikuolan** [comment]
Interesting.. According to BGP records, both networks are claiming the range as their own.

"CNSERVERS LLC" (ASN 40065) claims it via 172.247.0.0/16 ("CloudRadium L.L.C"), while "Zenlayer Inc" (ASN 21859) claims it via 172.247.34.0/24 ("80 HOST"), and both claims are marked as "IRR valid" in BGP records.

Seems kind of weird, and intuitively, I would normally suggest that just blocking it through one, singular signature alone should be sufficient, with multiple signatures indicating something being out of date, erroneous, etc. But, in this case, since both networks are claiming it, and both networks are already supposed to be blocked by the default CIDRAM signature files, and since both claims are apparently "valid" (according to BGP records), I guess, in this *particular* case, keeping both signatures makes the most sense. Probably.

Still feels kind of weird to me, but I'm not sure about getting rid of one or the other signatures, since we do still want to block that range regardless, and it's difficult right now to say whether one of the signatures is currently more or less valid than the other. Sometimes I'll merge two different signature sections together to resolve the problem, if it so happens that the two signature sections in question have a significant amount of interlacing or ranges in common. In this case though, I don't think the two networks share many ranges, other than the particular range in question in this case.

..Unless there are other suggestions? I'm all ears, if there are any.

**Comment by mikeruss1** [comment]
maybe Cnservers subcontracting the range to Zenlayer?
I guess the general point is this sort of thing is happening, I suppose we have to live with it.

**Comment by mikeruss1** [comment]
this seems a different problem, a couple more examples from today
3.81.105.156 - aws_cidram and Cloud service Amazon,com
20.58,187.30 - Azure and msaz_cidram
