### ISSUE TITLE
Cloud service?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#274]
got a lot of these today ....
ID: 1639588559-470649-4056496415 »
Date/Time: Wed, 15 Dec 2021 17:15:59 +0000 »
IP Address: 40.77.185.182 »
IP Address (Resolved): - »
Hostname: msnbot-40-77-185-182.search.msn.com »
Query: - »
Referrer: - »
Signatures Count: 2 »
Signatures Reference: mcm_bobuam.php:L112, functions.php:L2016 »
Why Blocked: Suspected bot detected!, Aux invalid UA! »
User Agent: - »
Reconstructed URI: https://www.xxx.php »
CAPTCHA State: Disabled. »

blocked because the UA is empty - however this is MS network and I reckon should be a Cloud service block too. Its very strange as it reports as hostname  msnbot, but it looks like a nasty bot to me, There is one bingbot IP in the 40.77 range, 40.77.167.6. Maybe its being let through as CIDRAM thinks its a search engine?

**Comment by mikeruss1** [comment]
its also using IP addresses in the range 40.77.185, 40.77.250, 40.77.175 and so on.

**Comment by Maikuolan** [comment]
40.77.185.182 belongs to AS8075 Microsoft Corporation (40.76.0.0/14). CIDRAM doesn't block that ASN, because there are too many different platforms/services/etc (e.g., Bingbot) which rely on that ASN to operate properly, most of which are too difficult to verify properly while blocking that ASN (although, CIDRAM *does* block Azure, which has a number of ranges belonging to that ASN, so I could say that it's *partially* blocked in that sense, but under the definition of Azure rather than of that ASN in the signature files). I agree, it looks like it's probably a bot of some kind (if it's Bingbot, it *should* be reporting its own UA, or at least *some* kind of UA, rather than nothing at all). But, blocking that ASN in entirety would likely result in a number of false positives against *actual* Bingbot requests, unfortunately.

**Comment by mikeruss1** [comment]
it seems Bing have released a list of Bingbot ips at https://www.bing.com/toolbox/bingbot.json, could CIDRAM use this as a base?
{
  "creationTime": "2021-11-10T10:00:00.121331",
  "prefixes": [
    {"ipv4Prefix": "157.55.39.0/24"},
    {"ipv4Prefix": "207.46.13.0/24"},
    {"ipv4Prefix": "40.77.167.0/24"},
    {"ipv4Prefix": "13.66.139.0/24"},
    {"ipv4Prefix": "13.66.144.0/24"},
    {"ipv4Prefix": "52.167.144.0/24"},
    {"ipv4Prefix": "13.67.10.16/28"},
    {"ipv4Prefix": "13.69.66.240/28"},
    {"ipv4Prefix": "13.71.172.224/28"},
    {"ipv4Prefix": "139.217.52.0/28"},
    {"ipv4Prefix": "191.233.204.224/28"},
    {"ipv4Prefix": "20.36.108.32/28"},
    {"ipv4Prefix": "20.43.120.16/28"},
    {"ipv4Prefix": "40.79.131.208/28"},
    {"ipv4Prefix": "40.79.186.176/28"},
    {"ipv4Prefix": "52.231.148.0/28"},
    {"ipv4Prefix": "51.8.235.176/28"},
    {"ipv4Prefix": "51.105.67.0/28"}
  ]
}

**Comment by Maikuolan** [comment]
> could CIDRAM use this as a base?

Possibly. Also, nice find! I wasn't aware that Bing supplied its own json list like that. In terms of whether we *could* integrate and utilise data like that: That shouldn't be a problem at all. We're already doing the same thing for DuckDuckGo and GrapeShot, seeing as those two services have similar such lists provided to describe which ranges/addresses they're expected to be sending requests from, and the recommended practice to verify such requests is to check whether they originate from those ranges/addresses.

In terms of utilising such data specifically for Bingbot: My main concern when it comes to *any* data either supplied directly from Bing, or directly related to Bing, is how reliable that data is. In terms of using this for verifying Bingbot requests: The other considerations are whether such a strategy should *replace* or *supplement* the already existing strategies utilised for Bingbot, and the implications for that (e.g., risk of other services on the same network being blocked, false positives, missed detections, etc). I'll investigate this a bit further and get back to you on that when I've next got a free day. :-)

**Comment by mikeruss1** [comment]
I understand your concerns re Bing. I did check a few hours of the log and all the GETS are from that list. My perspective is I want traffic from the MS network not on that list to be stopped. We wont know there is a problem until its implemented. I guess any bingbot traffic from other IPs will get an error log so we should know reasonably quickly.

**Comment by 737simpilot** [comment]
In reference to Bingbot, see and follow my conversation in the Gitter channel [here](https://gitter.im/CIDRAM/Lobby?at=61962df76104ea63b6a0b943).

This _was_ implemented via a module that Macmathan provided, but it's my understanding he's not maintaing this anymore. Thus I set out to do it myself. 

As to the question of any possible false positives. Hardly any right now that I can see. But every once in a while an apparent "Bingpreview" bot shows up using an Azure IP and gets blocked. Since anyone can spin up a server on Azure and forge the UA, I'll just leave it blocked. The PTR doesn't even check out! There's no PTR. If this is Microsoft they have no consideration of a WAF once so ever.  In fact, that whole damn AS8075 is full of crap. I see TONS of it in my Cloudflare firewall logs. I have massaged everything both in Cloudflare and in CIDRAM so that most Bing bots get a 200. It's a real pain and I'm seriously considering just blocking the whole damn ASN in Cloudflare. I don't even see a lot of Bing search engine traffic hits to my site anyway. Most use Google, DuckDuckGo, Startpage, and Ecosia in that order.

**Comment by mikeruss1** [comment]
I also get a ton of trash off MSAZ. Seems to have really changed in the last 3 months and is now a big irritation. I dont use CIDRAM for some of my traffic so its blocked in .htaccess. 
Re Bing - its not far behind google on my site, the rest is just noise.

**Comment by Maikuolan** [comment]
Tried contacting Bing support a few times to ask for their advice regarding the ranges provided by their toolbox (linked above) versus performing forward-reverse lookups to verify Bingbot (as per what we're currently doing): No response from them at all, whatsoever (unsurprisingly).

Not really sure whether it's worth worrying about this too much at this point TBH. Thoughts?

**Comment by mikeruss1** [comment]
I guess, the problem has gone away for now so no priority from me

**Comment by Maikuolan** [comment]
Seeing as the problem seems to have gone away for now, and doesn't seem to have come back yet since the past month, I'll go ahead and mark this as resolved and close the issue for now. I don't think there's anything for us to do regarding this issue currently. If the problem comes back, or if we find some more work to do regarding this issue, we can reopen it at that time. :-)
