### ISSUE TITLE
HeadlessChrome UA

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#275]
getting a lot of these ...
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/96.0.4664.45 Safari/537.36, Incidentally they all come off MSAZ.

I think the HeadlessChrome means its a scripted version of Chrome which runs without a UI - in other words its a bot.

recommend adding to the bot signatures ?

**Comment by Maikuolan** [comment]
> I think the HeadlessChrome means its a scripted version of Chrome which runs without a UI

Yep, that's the case.

It's actually kind of interesting, if it's something you hadn't read about before:

> Headless Chrome is shipping in Chrome 59. It's a way to run the Chrome browser in a headless environment. Essentially, running Chrome without chrome! It brings **all modern web platform features** provided by Chromium and the Blink rendering engine to the command line.
>
> Why is that useful?
>
> A headless browser is a great tool for automated testing and server environments where you don't need a visible UI shell. For example, you may want to run some tests against a real web page, create a PDF of it, or just inspect how the browser renders an URL.

*Excerpt source: https://developers.google.com/web/updates/2017/04/headless-chrome*

In other words.. I don't think it would be unfair to say that Headless Chrome somewhat blurs the boundary between how we'd define a bot versus how we'd define a browser, which is kind of annoying for us, but also not something too easy for us to argue or complain about (plenty of reasons why it could be bad, due to the benefits such a feature could provide to potential hackers or attackers, but also plenty of benign, legitimate uses for such a feature, too).

I also don't think that Headless Chrome should necessarily be outright regarded as malicious, or as the kind of traffic we'd unconditionally regard as unwanted (e.g., if one of your legitimate users happens to be browsing your website one day, and decides they want to save a PDF copy of one of your pages, so that they can look at it offline or something like that). However, that said, in theory, my PDF example (plus any other cases where the user is using their browser in such a way) should only really be valid when the request originates from an ISP or some other kind of human endpoint. When those requests are originating from Azure, from a webhosting provider, a server farm, cloud service or similar, such as with the cases you've mentioned, then regardless of whether or not the scripting behind those requests is using an actual Chrome instance as its core, or whether it's an independently executing script, bot, or whatever just faking the the Headless Chrome user agent, either way, it's bot-like behaviour, clearly not ordinary human traffic, and something which, assuming we've neither consented to it nor are aware of its nature, we'll probably want to be blocking.

> recommend adding to the bot signatures ?

Honestly not sure. If it doesn't come from an ISP, I would block it. But, if it comes from an ISP (and as long as the request in question isn't already being blocked for whatever reason), I'd be inclined to let it through. But that's just me. Different websites, different owners, contexts, etc, different views to be had regarding what to block/allow. But, if CIDRAM is already aware, or has some kind of idea as to whether or not the request originates from an ISP by the point that the modules are being executed, then it's most likely either because the request has already been blocked by one of the signature files, and there's a profile attached to the triggered signatures to identify it as such, or because one or more of the modules have performed a lookup somewhere to find that out, which somewhat removes the uncertainty there as to whether we should block it (seeing as those other lookups or triggered signatures would most likely already be causing the request to be blocked). On the other hand, if nothing is triggered and no lookups performed, and CIDRAM thus has no idea as to whether or not the request originates from an ISP, then by the time we'd in theory be wanting to block such a UA, we probably won't have any way to find out anymore anyway (or at least, by the time we do, that particular module would've already finished its execution and be no longer able to raise a block event for the request in question anymore).

One way to resolve those issues (or, at least, to avoid the responsibility of deciding about such a thing directly ourselves) might be to go ahead and add the signature for it to the bots UA module, but to also include a new configuration directive with the module, so that users can easily enable/disable the signature in question. That way, users can decide for themselves whether they want to utilise that signature (and this is something we're already doing for a small handful of other signatures already anyway, so not an unprecedented thing).

Another way might be to implemented it as an auxiliary rule instead. However, seeing as auxiliary rules aren't something installable via the updates page, but something which CIDRAM users need to add in themselves (thus specific rules not being standardised), I'm not sure how ideal that is either.

Anyone else have any thoughts or ideas about it?

**Comment by 737simpilot** [comment]
I've had this in my auxiliary rules for some time LOL

```
Headless Chrome:
 Method: "WinEx"
 Logic: "Any"
 Reason: "F OFF"
 Forcibly disable reCAPTCHA: true
 Forcibly disable HCaptcha: true
 Block:
  If matches:
   UA:
    - "*HeadlessChrome*"
```

**Comment by mikeruss1** [comment]
I think you are right, its probably best left to users to block with an auxiliary rule. If required it could only comes into force if signatures = 1.

Personally I think I will block it anyway and see what happens.

I have a feeling I have already suggested an auxiliary option to generate an email if the given event occurs? V3 maybe?
Also how about a library of auxiliary rules we can all contribute to?

**Comment by Maikuolan** [comment]
> I have a feeling I have already suggested an auxiliary option to generate an email if the given event occurs? V3 maybe?

Yep ([#231](https://github.com/CIDRAM/CIDRAM/issues/231)). Currently, I'm thinking v3 for that, too. The way I have in mind to implement that changes a few things at the configuration, so yeah; I'm thinking v3, currently.

> Also how about a library of auxiliary rules we can all contribute to?

I definitely like that idea. I've also been considering whether maybe we should deprecate Gitter in favour of GitHub Discussions instead at some point, seeing as that would centralise everything a bit more, Gitter is somewhat limited in what it can provide and do, whereas GitHub Discussions seems to work quite similar to forum systems we're all already familiar with. I hadn't yet created an issue to discuss that idea yet, but had been thinking about doing so soon. Maybe GitHub Discussions might be the best way to go insofar as providing us an avenue to share auxiliary rules, too?

**Comment by mikeruss1** [comment]
my first thought was it would be something more formalised and implemented with the front end. So the library is basically a set of options that could be reviewed and pulled in.
This implies a lot more development and ongoing management that may not be worthwhile.

In any event it would be a useful resource particularly for new users.

**Comment by 737simpilot** [comment]
I do like the Github Discussions idea and the open sharing of Auxiliary rules. As of this post, you can have ten categories. I guess an "Ideas" category would be well suited for the sharing of Auxiliary rules.


https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository

**Comment by Maikuolan** [comment]
I just tried creating a __[test discussion](https://github.com/CIDRAM/CIDRAM/discussions/279)__ at the discussions section here, to see what it'll look like. Anyone mind quickly attempting to reply there, and also, if possible, attempting to create a new discussion there at one of the categories (for now, it doesn't matter which category, because we haven't formalised anything yet regarding how we'll use the discussions feature anyway), to confirm whether it's possible under current settings to do those things, and to test how easy/difficult it is to do those things? Cheers. :-)

**Comment by Maikuolan** [comment]
The original discussion (whether to block the UA in question) having already come to a close, the ability to share auxiliary rules via the backups page having been recently implemented to CIDRAM (not linked at this issue, but documented elsewhere), and with the remaining question about the ability to send an email via auxiliary rules covered by #231, I'm going to go ahead and close this issue now.
