### ISSUE TITLE
Block or Allow with timeframe of an IP

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#276]
If is possible to Block (or allow) an IP or a range, for some limited time?

**Comment by Maikuolan** [comment]
Through signature files, it's possible.

Let's say, for example, if you had a signature file with some signatures like so (arbitrary example):

```
1.1.1.0/24 Deny Cloud
2.2.2.0/24 Deny Cloud
3.3.3.0/24 Deny Cloud
Origin: XE
Profile: Foo;Bar
Tag: Foobar
```

You could add an "expires" tag onto the end of that section of signatures, in order to instruct CIDRAM to no longer block on the basis of those signatures (although, the signatures are still considered as valid, and therefore, attached tags, like the "profile" tag, will continue to work normally). For example, to have those signatures "expire" from today onwards (30th December, 2021):

```
1.1.1.0/24 Deny Cloud
2.2.2.0/24 Deny Cloud
3.3.3.0/24 Deny Cloud
Origin: XE
Profile: Foo;Bar
Tag: Foobar
Expires: 2021.12.30
```

Before (not expired):

![1](https://user-images.githubusercontent.com/12571108/147740684-55bae052-0443-4055-9c6e-e1a67c8b19a3.png)

After (expired):

![2](https://user-images.githubusercontent.com/12571108/147740688-9b710e53-215f-4389-896a-4c1cdd553221.png)

Through modules, it's also possible (but such functionality would need to be coded into the module in question itself).

Through auxiliary rules, it's not *currently* possible. But, I'm thinking, that might be a feature worth adding. I'm going to look into that shortly.

**Comment by eurobank** [comment]
@Maikuolan I was looking (or hoping) for something i could put in custom.dat like

1.1.1.1 Deny Reason_X 10 days (or 1 month or 24 hours)

You got the picture ...

**Comment by Maikuolan** [comment]
The problem with specifying an amount of hours/days/months/years/etc (without anything else), is the lack of a reference point. I could code in support for something like that, so that CIDRAM can enforce a signature for a specific amount of time, but probably not with just the amount of time by itself. It would need to be something like:

```
1.1.1.1 Deny Reason_X for 10 days starting from yyyy.mm.dd
```

Or:

```
1.1.1.1 Deny Reason_X until yyyy.mm.dd
```

That, or I'd need some other way to determine a reference point from which to measure the amount of time specified.

**Comment by Maikuolan** [comment]
Any further thoughts about this? I'm thinking this would be a good thing to try to implement, a worthwhile improvement, but we probably should try to come to some kind of consensus about the best syntax (or, in this context, could also say, the best "grammar", I suppose) to use, so that usage will feel as "natural" as possible.

Aside from the above.. Could also do something like:

```
1.1.1.1 Deny Reason_X from yyyy.mm.dd until yyyy.mm.dd
1.1.1.1 Deny Reason_X from yyyy.mm.dd to yyyy.mm.dd
```

I'm thinking I'll definitely implement something to the auxiliary rules soon, seeing as there isn't currently any way to link an auxiliary rule to a specific timeframe yet anyway. Could be good do to something more for standard signature files too though. We already have "expires" tags, which can be used to apply an expiry to an entire section of signatures, but nothing yet for just specific individual signatures.

**Comment by eurobank** [comment]
If you ask me, the above is ok.

**Comment by Maikuolan** [comment]
Implemented. :-)

As of this update, it's now possible to now specify an exact range of dates for signatures in signature files. This is achieved by implementing one or both of two specific keywords ("from" and "until"), at the end of the signature, followed by the dates in question (formatted according to ISO 8601; `yyyy-mm-dd` or `yyyy.mm.dd`), like so:

```
1.2.3.4 Deny Some reason here from 2022.01.01 until 2023.01.01
1.2.3.4 Deny Some reason here from 2022.01.01
1.2.3.4 Deny Some reason here until 2023.01.01
```

- When the current date is earlier than the specified "from" date, the signature will be disabled.
- When the current date is later than the specified "until" date, the signature will be disabled.

Auxiliary rules have also been updated, so that this same feature can be used there, too.

**Comment by Maikuolan** [comment]
(I haven't yet updated the documentation to reflect these changes. I'll get that sorted out soon).

**Comment by eurobank** [comment]
Great news, many thanks
