### ISSUE TITLE
Duplicate Amazon Cloud blocks

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#277]
thanks for the Macmathan offer ...

a lot of the Amazon blocks seem to have duplicate ranges ... like this one

ID: 1641162121-419509-6005355476 »
Date/Time: Sun, 02 Jan 2022 22:22:01 +0000 »
IP Address: 54.202.28.119 »
IP Address (Resolved): - »
Hostname: ec2-54-202-28-119.us-west-2.compute.amazonaws.com »
Query: - »
Referrer: - »
Signatures Count: 2 »
Signatures Reference: 54.192.0.0/12, 54.200.0.0/13 »
Why Blocked: Cloud service ("aws_cidram.inc-IPv4", L690:F1), Cloud service ("Amazon.com, Inc", L11075:F4, [US])! »
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 »
Reconstructed URI: https://xxxxx/ »
CAPTCHA State: Disabled. »

it generates 2 X Amazon Cloud service signatures - which I code to disqualify Captcha. So if its a VPN I loose the chance for some traffic. I doubt if this applies very often so not a big issue anyway.

**Comment by Maikuolan** [comment]
In the past, I had the default signature files written in such a way that, when the AWS signatures provided by Macmathan were available to CIDRAM and active, the AWS signatures provided by the default signature files would defer to those provided by Macmathan (thus avoiding duplication). I removed the deferment from the default signature files shortly after Macmathan's blocklists became deprecated (November 2021), seeing as they wouldn't be updated anymore. TBH, although they were good blocklists, good modules, and good signatures, seeing as they're now deprecated and won't be updated anymore, at this point, I would recommend ditching the `aws_cidram.inc` signature file, because it'll likely become increasingly outdated and prone to false positives as time moves forward (as is the case for any such signature files, and thus the need for regular updates).

I don't normally tend to update the AWS signatures in the default signature files as frequently as Macmathan was updating his AWS signatures back when they were being actively updated, due to how many signatures I'm maintaining in the default signature files and the practical and time management considerations of that, but the difference shouldn't be too severe, and just the default signature files should generally be able to keep you covered, I think.

**Comment by mikeruss1** [comment]
done - thank you

is msaz also in the default sigs now?

**Comment by Maikuolan** [comment]
Yep. :-)

**Comment by mikeruss1** [comment]
OK - what about the Cloud Services Bypass module. Do we still need that to work with the default sigs?

**Comment by Maikuolan** [comment]
Nope, won't need it anymore. The "cloud services bypass" module is needed when using the AWS or MSAZ blocklists, but isn't needed for anything else, so, when those blocklists are ditched, the cloud services bypass module can be safely ditched, too. :-)

(Worth noting, though: Although having a very similar name to the "cloud services bypass" module, the "default signature bypasses" module, which is included with CIDRAM by default, is something entirely different, and will need to be kept in order to prevent some specific potential false positives from occurring as a result of the default signature files).

**Comment by mikeruss1** [comment]
well thats saved a few nano seconds today!

**Comment by Maikuolan** [comment]
Always good. :-)
