### ISSUE TITLE
Captcha issues

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#293]
Have multiple issues with captcha with both HCaptcha and Recaptcha. First, I always have to set the signature limit to 7 otherwise if you pass captcha you get a blank, white page which shows up as a 403 in the web console. If I set the limit to 7 (I found this through trial and error) I'm allowed to pass captcha and be on my way. However! If I click another link at the website I have to solve the captcha yet again. So you have to solve captcha twice (2) in order for perma access. After completing the captcha a second time I'm now free and clear. The ipbypass.dat and captcha log file do record the captcha passes twice. 

Because of these issues I switched to HCaptcha as a test, but I'm having the same issues here as with Recaptcha. Only this time I see this repeating error:

```
Error at classes/HCaptcha.php:L251 (error code 2): "Header may not contain more than a single header, new line detected". Eep.. Something went wrong during "CAPTCHA".

```

The other issue I'm having is with the auxiliary rules while testing captcha capability. I have this:

```
test:
 Logic: "Any"
 Reason: "test"
 Mark for use with HCaptcha: true
 Block:
  If matches:
   IPAddr:
    - "1.2.3.4"
   UA:
    - "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:97.0) Gecko/20100101 Firefox/97.0"

```

This _should_ captcha my connection based on my IP and UA combination, but it appears it only invokes with the IP only. I know because I can forge my UA in the browser  My true UA does show up in CIDRAM's home page so we know CIDRAM sees my UA for what it is. I did use the auxiliary rule option of UA and not the lower case UA option. I don't think that should be an issue since the UA isn't lower case anyway.

And finally, the captcha code you made for me to work with BOBUAM is only for Recaptcha. It would be nice if it'd work with HCaptcha as well. Here's the code:

```
<?php
$CIDRAM['Events']->addHandler('triggered', function ($Module) use (&$CIDRAM): bool {
    if ($Module === 'mcm_bobuam.php') {
        $CIDRAM['Config']['recaptcha']['enabled'] = true;
    }
    return true;
});

```

I'd like to eventually migrate to nothing but HCaptcha instead of Recaptcha. Trying to part ways all things Google. Next order if business is Google fonts which I tried to offload to AWS but I think CORS got in the way. I don't even use Google Analytics. There's an alternative called Matomo that I'd like to check out.  Anyway... Sorry about this huge mess here. I'm aware that your busy coding your butt off for v3.

Question: What captcha does SFS use? Would it be both if both were turned on? HCaptcha and Recaptcha? I had a user get blocked from SFS, but it was probably a false positive since they were using a cell Internet connection. They stopped short at solving the captcha and I'm wondering if they could have been caught up in captcha errors from the jump. No captcha log was created or anything in ipbypass.dat. I had a user in the past have issues with an old UA, BOBUAM, and solving captcha. I had to turn off outdated UAs in BOBUAM. 

Speaking of BOBUAM, I see this now. Could have sworn it was a simple YES or NO option. I suspect some code on your end and incompatibility with BOBUAM?

![img](https://i.postimg.cc/bvTrD2PF/fgrthr.jpg)

**Comment by Maikuolan** [comment]
> Speaking of BOBUAM, I see this now. Could have sworn it was a simple YES or NO option. I suspect some code on your end and incompatibility with BOBUAM?
>
> ![img](https://camo.githubusercontent.com/6b50324195f9e2424fc112483aabd326525526fcc3ffcae681edff5638a2ed1c/68747470733a2f2f692e706f7374696d672e63632f62765472443250462f6667727468722e6a7067)

That's something interesting you've spotted there.. I hadn't noticed that before. XD

But yeah.. you're right; it definitely displayed as a simple YES/NO option before.

That in mind.. I had a quick look at the latest version of BOBUAM just now, and it took me about all of ~3 seconds there to realise what's gone wrong here. Strictly speaking, you're correct in thinking that some recent code changes of mine have introduced an unintended compatibility break with BOBUAM, but.. said code changes aren't part of the CIDRAM core itself. Rather, said code changes are part of the YAML handler (bundled as part of the "Common Classes Package"; basically, because it's a set of classes I wrote, which I use for CIDRAM, but also several other projects as well, bundling them together as a separate component makes for easier/simpler maintainability).

What said code changes were: Since v2.8.0 of the Common Classes Package, I'd been aiming to bring the YAML handler a little closer to the official YAML specification, implementing some more of the features/syntax/etc specified by the specification. Part of that includes implicit type coercion for [booleans](https://yaml.org/type/bool.html), which includes coercing unquoted `yes` and `no` values to `true` and `false` booleans respectively. Prior to v2.8.0, unquoted `yes` and `no` values were treated as string literals. ([*Relevant parts of the diff*](https://github.com/Maikuolan/Common/commit/465c1eba2e3691571cd1b7c4c3adb04921ae121c#diff-c8b1cb28d4896a5214b4a2f3ab757becfe09fee937bbfde062f937a81855938cL529-R531)).

All in all, in its own right, not a problem, and it works great. However, what I didn't realise at that time (and where our problem is), is that the *configuration defaults* for BOBUAM utilises unquoted literals `yes` and `no` for a number of its configuration directives, in *exactly the way* which these changes to the YAML handler would be incompatible with.

*Excerpt*:
```YAML
Config Defaults:
 bobuam:
  sanity_check:
   type: "string"
   default: yes
   choices: 
    yes: yes
    no: no
```

If Macmathan was still maintaining BOBUAM, I'd simply send him a quick message about the problem and ask him to push a quick fix to resolve it. However, because BOBUAM (as well as his other blocklists and various modules) are now officially EoL and not maintained anymore, that won't work. That means BOBUAM users will need to fix their copies themselves manually. However, on the bright side, the fix is quite simple and easy.

1. To fix the problem, open `mcm_bobuam.yaml` in Notepad++ (or an equivalent plain-text editor), and open the "replace" dialog (`Ctrl+H`).
2. In the "replace" dialog, set the "search mode" to "Regular expression" (`Alt+G`).
3. In the "Find what" field (`Alt+F`), write `(?<!\w|")(yes|no)(?!\w|")`.
4. In the "Replace with" field (`Alt+L`), write `"\1"`.
5. Perform a "Replace all" (`Alt+A`).
6. Save the file and reupload/update.

Using the above excerpt as a basis, the file should now look something like this:
```YAML
Config Defaults:
 bobuam:
  sanity_check:
   type: "string"
   default: "yes"
   choices: 
    "yes": "yes"
    "no": "no"
   allow_other: false
```

After doing that, the problem should be fixed.

**Comment by Maikuolan** [comment]
> I'd like to eventually migrate to nothing but HCaptcha instead of Recaptcha. Trying to part ways all things Google. Next order if business is Google fonts which I tried to offload to AWS but I think CORS got in the way. I don't even use Google Analytics. There's an alternative called Matomo that I'd like to check out. Anyway... Sorry about this huge mess here. I'm aware that your busy coding your butt off for v3.

No problem at all. :-)

Worth noting: I've already completely removed support for Google Fonts entirely from v3, so there won't be much need for an alternative to it at that point (seeing as v3 will just rely on the user having any specified fonts already installed at the system-level, or else fall back to whatever they have available to their browser at the time, no lookups to Google Fonts or elsewhere to be performed regardless).

I think, getting away from Google Fonts et al is a very called-for move for CIDRAM and other similar such projects, especially seeing as a number of the predictions we made back in 2018 when the GDPR/DSGVO first came into effect, with particular note to those in regards to the legal risks of using Google Fonts (#66) [*has ironically come to fruition in at least some form or another*](https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html). Not really a risk at all for yourself given that you live and operate from within the US, but at the same time, given that CIDRAM's userbase is from various different countries throughout the world, I don't want to put anyone at risk, legal or otherwise, if I can help it at all.

> Question: What captcha does SFS use? Would it be both if both were turned on? HCaptcha and Recaptcha?

The SFS module just marks the *both* of them for use with, so as to which of the two will ultimately appear for the end-user would depend on the specific configuration of the CIDRAM installation in question.

*Excerpt from `module_sfs.php`:*
```PHP
    /** Marks for use with reCAPTCHA and hCAPTCHA. */
    $EnableCaptcha = ['recaptcha' => ['enabled' => true], 'hcaptcha' => ['enabled' => true]];
```

So, strictly speaking, you could say that *both* would be "turned on". However, CIDRAM should still only ever display just one or the other (never both at the same time), so in cases where both are enabled and turned on, priority would be given to whichever one has checks occurring earlier in the codebase than the other, and currently, that's ReCaptcha. Therefore, in order to ensure that HCaptcha is displayed all the time, you'd probably have to ensure that ReCaptcha is disabled or turned off for those particular requests.

> I had a user get blocked from SFS, but it was probably a false positive since they were using a cell Internet connection. They stopped short at solving the captcha and I'm wondering if they could have been caught up in captcha errors from the jump. No captcha log was created or anything in ipbypass.dat. I had a user in the past have issues with an old UA, BOBUAM, and solving captcha. I had to turn off outdated UAs in BOBUAM.

Seeing as you've mentioned getting caught up in it yourself, possibly. I'd need to look into it, I think. Though, in theory, no CAPTCHA log should mean no attempts made to complete any of said CAPTCHAs, since in theory, any/all attempts should always be logged (as long as the relevant logging has been enabled).

**Comment by Maikuolan** [comment]
> ```
> test:
>  Logic: "Any"
>  Reason: "test"
>  Mark for use with HCaptcha: true
>  Block:
>   If matches:
>    IPAddr:
>     - "1.2.3.4"
>    UA:
>     - "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:97.0) Gecko/20100101 Firefox/97.0"
> ```
> 
> This _should_ captcha my connection based on my IP and UA combination, but it appears it only invokes with the IP only. I know because I can forge my UA in the browser My true UA does show up in CIDRAM's home page so we know CIDRAM sees my UA for what it is. I did use the auxiliary rule option of UA and not the lower case UA option. I don't think that should be an issue since the UA isn't lower case anyway.

Just need to change that "Any" to an "All". ;-)

> And finally, the captcha code you made for me to work with BOBUAM is only for Recaptcha. It would be nice if it'd work with HCaptcha as well. Here's the code:
> 
> ```
> <?php
> $CIDRAM['Events']->addHandler('triggered', function ($Module) use (&$CIDRAM): bool {
>     if ($Module === 'mcm_bobuam.php') {
>         $CIDRAM['Config']['recaptcha']['enabled'] = true;
>     }
>     return true;
> });
> ```

Try this:

```PHP
<?php
$CIDRAM['Events']->addHandler('triggered', function ($Module) use (&$CIDRAM): bool {
    if ($Module === 'mcm_bobuam.php') {
        $CIDRAM['Config']['recaptcha']['enabled'] = true;
        $CIDRAM['Config']['hcaptcha']['enabled'] = true;
    }
    return true;
});
```

> Have multiple issues with captcha with both HCaptcha and Recaptcha. First, I always have to set the signature limit to 7 otherwise if you pass captcha you get a blank, white page which shows up as a 403 in the web console. If I set the limit to 7 (I found this through trial and error) I'm allowed to pass captcha and be on my way. However! If I click another link at the website I have to solve the captcha yet again. So you have to solve captcha twice (2) in order for perma access. After completing the captcha a second time I'm now free and clear. The ipbypass.dat and captcha log file do record the captcha passes twice.
> 
> Because of these issues I switched to HCaptcha as a test, but I'm having the same issues here as with Recaptcha. Only this time I see this repeating error:
> 
> ```
> Error at classes/HCaptcha.php:L251 (error code 2): "Header may not contain more than a single header, new line detected". Eep.. Something went wrong during "CAPTCHA".
> ```

Cheers. I'll look into that now.

**Comment by Maikuolan** [comment]
The problem with HCaptcha should be fixed now. :-)
