### ISSUE TITLE
Require

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#308]
I just wanted to check what happens after calling the require() to CIDRAM.

am I right in thinking that if processing returns to the line after the require then the transaction has been accepted. Presumably in the event of a rejection  CIDRAM calls exit() ?

basically I want to use session handling to track CIDRAM has accepted something, once that happens it doesnt bother to call CIDRAM again for that session. I think its fairly safe because most bad guys dont remember sessions anyway.

**Comment by Maikuolan** [comment]
> am I right in thinking that if processing returns to the line after the require then the transaction has been accepted. Presumably in the event of a rejection CIDRAM calls exit() ?

Yes, that's 100% correct (for v2 and earlier, at least). :-)

For v3 (at least, once it reaches beta/stable), there'll be a small, extra line of code needed after the require statement to kick the ball rolling (in order to facilitate my idea about giving CIDRAM users the ability to create and control their own entrypoints, to determine whether or not an entrypoint allows access to the front-end, whether or not it engages the usual CIDRAM protections and so on, for v3, the require will load what's needed, but not actually *do* anything right now, the extra line of code telling it basically "do your thing now", whether loading the front-end, the standard execution chain, etc).

Anyway, for now at least, with v2, your thinking is correct, and what you're wanting to do should work fine as you're intending it.
