### ISSUE TITLE
Pinterest Blocked (and banned)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#322]
I think this is wrong to block:

ID: 1656581796-594768-2838048588 »
Date/Time: Thu, 30 Jun 2022 12:36:36 »
IP Address: 54.236.1.22
Signatures Count: 1 »
Signatures Reference:
Why Blocked: Banned! »
User Agent: python-requests/2.27.1 »

__

crawl-54-236-1-22.pinterest.com

--

**Comment by Maikuolan** [comment]
According to the [official documentation for Pinterest's crawler](https://help.pinterest.com/en/business/article/pinterest-crawler), that request is *not* from their crawler, but it *is* from their crawler's range. That being the case though.. I'm not entirely sure what the nature or purpose of that particular request is.

Is Pinterest messing around at their end, experimenting with some new code which utilises the Python requests user agent, which they haven't changed the UA to something else for yet? Is it just Pinterestbot using a wrong/unofficial user agent, and their documentation is wrong, or hasn't been updated to reflect that user agent usage? Has an endpoint at one of Pinterest's servers been compromised, and someone else is using it for their own purposes? Do they actually allow other people to operate their own bots from their servers? I don't know.

Because the request isn't using an official Pinterestbot user agent in the first place, social media verification isn't triggering at all in the case of that request and others likewise not using official user agents, so changing something at search engine or social media verification won't necessarily fix the problem of that range being banned.

The range itself *is* listed by the default signature files due to being a part of the Amazon/AWS ranges, but bypasses are already implemented as part of the default signature bypasses which should bypass the particular signatures in question regardless, as long as a corresponding permitted user agent is used (e.g., Pinterestbot, Redditbot, Feedspot, Embedly, etc). Unfortunately, not only does the request *not* utilise such a user agent, but it *also* happens to be using `python-requests/2.27.1`, which is blocked by the `bot user agents module` as "Scraper UA" due to that there are many website scrapers built based upon the Python requests module, which happen use that exact user agent as their user agent when attempting to scrape websites.

The combination of using a user agent blocked by that module as well as a range which is blocked under the Amazon/AWS ranges, without any of the default bypasses being able to trigger, means such a request is likely to incur at least 2 infractions per request even before reaching a number required for it to become banned.

I might need to implement some additional measures or bypasses based on hostname, I guess. I'll investigate a little more shortly to try to figure out whether that's the best approach or something else.

**Comment by eurobank** [comment]
Can we simply ask them?

**Comment by mikeruss1** [comment]
FWIW anything with python or curl in the UA I block at server level

**Comment by Maikuolan** [comment]
> Can we simply ask them?

Not sure. They have a [contact page](https://help.pinterest.com/en-gb/contact), but it's somewhat convoluted, and doesn't have any options which suit our reasons for contacting them. Might be other ways to contact them which I'm not aware of currently. Might be worth a shot if we can figure it out.
