### ISSUE TITLE
138.201.36.87 - Spam UA

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#323]
This is NOT a Spam UA but a bad bot.

User Agent: serpstatbot/2.1 (advanced backlink tracking bot; https://serpstatbot.com/; abuse@serpstatbot.com)

**Comment by Maikuolan** [comment]
Thanks for spotting this. :-)

I've updated the affected module just now to have the bot in question be detected by that module's "Backlink/SEO/Scraper UA" signature now instead of its "Spam UA" signature (seeing as the bot in question is allegedly used for "backlink tracking", the newly detecting signature is probably a little more appropriate than the old one).
