### ISSUE TITLE
New search engine ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#330]
not seen this UA before ...
"Timpibot/0.8 (+http://www.timpi.io)"

its not well behaved, it tripped my rate limiting

**Comment by Maikuolan** [comment]
I've never seen that nor heard of those guys before, either.

Though, "decentralized search engine".. I've heard that phrase mentioned a few times before by other organisations, and in one particular case a number of years back, one such organisation was mentioned back at Spambot Security (back when Zaphod was still actively maintaining ZB Block), because their bot was behaving very poorly, flooding both Spambot Security plus various users' websites with garbage requests, sniffing around for vulnerabilities, etc, and within the same week of being mentioned, someone claiming to be the "CEO" of said organisation registered there, starting abusing Zaphod, threatening legal action (on grounds not actually supported by law, so.. yeah.. not something particularly worrying, albeit annoying at the time), practically having a conniption at half the users there simply due to the existence of the discussion happening at the time. Which is the reason behind why, from that point onward, any time said org would be mentioned, they would be addressed simply as "the one that shall not be named" or similar.

Keeping to that spirit, I won't mention the name of that organisation here and now, either. Though I'm about ~99% sure it's *not* the same organisation as the one behind the UA you've mentioned here just now, so no worries in that regard. I just bring up that story now, to explain the reason why, when someone says, "here's this new UA which neither of us have ever seen before, it's been behaving badly, and has been tripping up my rate limiting", and when I investigate it, I see "decentralized search engine" listed at their homepage, my gut feeling about said UA isn't particularly great. ;-)

Anyway, I'll try to investigate this new presumed search engine in a little more detail soon. TBH, there's a lot of information at their homepage, I'm not entirely sure I understand all of it offhandedly just now, and I don't immediately see any way to actually use their search engine (not saying there isn't a way, but it wasn't immediately obvious to me, so I guess, I would need to dig a little further and look around to find that way properly).

Anyone reading that already knows a little more: Feel free to share. :-)

**Comment by eurobank** [comment]
**No business or serious search engine website will be hosted at:**

ISP | Contabo GmbH

Data Center/Web Hosting/Transit
vmi360447.contaboserver.net

I mean, most Contabo and Contaboserver.net IPs are banned all over the Internet.

**Comment by Maikuolan** [comment]
UA should be blocked by the bot UAs module as of now. :-)
