### ISSUE TITLE
Attacks from LAN IP

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#332]
getting a variety of attacks from variations on 192.168.134.117 - obviously forged

maybe we should block these by default, or I guess I can add to auxiliary rules? That needs a bit of caution, is it possible to match against the first 2 quartets only ?

**Comment by Maikuolan** [comment]
> That needs a bit of caution, is it possible to match against the first 2 quartets only ?

Yep. :-)

You could use either regular expression matching, or Windows-style pattern matching against the IP for the new rule, something like:

```
^192\.168\.
^192\.168\.\d+\.\d+$
```

(Or whatever flavour of regular expression is preferable).

Or for Windows-style matching:

```
192.168.*.*
```

You could also instead use direct-string comparison, but match against the range instead of the specific IP address, checking for this specific range:

```
192.168.0.0/16
```

(Which encompasses all IP addresses from 192.168.0.0 through to 192.168.255.255, which is.. basically the same thing as matching the first two octets).

So, there's a few different ways to achieve the same thing there. :-)

Worth noting: *Technically*, all addresses within the entire 192.168.0.0/16 range are bogons (which means we should *never* see external traffic from any of those addresses). However, the bogon signature files included with CIDRAM by default don't contain that particular range, specifically because I've had reports in the past about false positives generated at *some* installations as a result of blocking that range, due to the affected websites in question relying on communication between various different services, APIs, etc all hosted at the same server in order for those websites to work correctly. Seems easier to just not block it by default rather than needing to deal with multiple false-positive reports from the affected users as a result of blocking it by default. However, it should be perfectly safe to block that range, as long as your website isn't such a website (i.e., doesn't rely on communication between such services, APIs, etc at the same server).

**Comment by mikeruss1** [comment]
thanks .. (regex stretches my head!)
