### ISSUE TITLE
abuseipdb: lookup_everything ?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#337]
```
abuseipdb: lookup_everything:
Perform API lookups when CIDRAM detects requests for sensitive pages
(e.g., login pages, registration forms, etc), or for every request? False = Sensitive page requests only.
True = Every request. Default = False.

```
How CIDRAM knows what a sensitive page is for so many scripts?

**Comment by Maikuolan** [comment]
CIDRAM guesses, based on the request URI. If the request URI matches the expression defined at `isSensitive`, the request will be regarded as a request for a sensitive page.

https://github.com/CIDRAM/CIDRAM/blob/2fc9c8ba6896befe34d1c11774a156f04b391b95/vault/CIDRAM/CIDRAM/Core.php#L2723-L2732

The expression is based on known URIs usually encountered when using various known CMS, frameworks, and some other PHP-based open-source software, but isn't exhaustive. If the sensitive pages at a website have non-standard URIs, paths which don't match the defined expression due to being obfuscated, being asynchronous, or not being based at specific URIs, or just due to being something which isn't used elsewhere and hasn't been encountered before, then the expression will most likely fail to identify it as a sensitive page.

But, if I become aware of something new, which it isn't currently detecting, but should be detecting, I can always modify the expression to account for it. :-)

**Comment by Maikuolan** [comment]
Or for v2 (same strategy, same expression, just defined at a different location):

https://github.com/CIDRAM/CIDRAM/blob/1a8aeb58906596d970a5ed7f07d4dff2570225d1/vault/functions.php#L2537-L2545

**Comment by eurobank** [comment]
Thank you.

Do i get this right, that Contact pages are not included?

**Comment by Maikuolan** [comment]
Currently, that's the case. I wonder whether maybe that should be changed though, given that generally, contact pages are still points at which a user could interact with systems beyond just viewing a page (e.g., triggering an email being sent to a webmaster, something being saved to a database, etc)?

**Comment by eurobank** [comment]
Well half of our spam comes from Contact pages, that are protected with some kind of captcha. Manual spam? Who knows.

I would "vote" to include contact pages check against abuseipdb.

**Comment by Maikuolan** [comment]
> I would "vote" to include contact pages check against abuseipdb.

Expression now updated to include contact pages. :-)

The updated expression *should* now detect most contact pages, but if you notice it failing to catch yours or any others, let me know and I'll take another look.

**Comment by eurobank** [comment]
I see:

[14/Sep/22:20:36:21 +0300] - 107.172.50.162 "GET /contact/"
[14/Sep/22:20:36:28 +0300] - 138.128.44.189 "POST /contact/"

in my website logs.

Both were not blocked (or checked?) but they are listed at AbuseIPDB.

Any ideas?

**Comment by Maikuolan** [comment]
Updated again. :-)

**Comment by eurobank** [comment]
This last update seems to work fine. I will monitor and update if something is missing.

Thanks

**Comment by eurobank** [comment]
The "contact" / abuseIPDB works like a charm. Blocks so so so many crap ....

Thank you !
