### ISSUE TITLE
Request - Manually REPORT to AbuseIPDB an issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#338]
Hi,

It would be nice if we could DIRECTLY from the blocked list, report the issue at AbuseIPDB.

Thanks

**Comment by eurobank** [comment]
To explain better my request, it could just open a window for us to fill the reason and submit.

**Comment by Maikuolan** [comment]
I'll see what I can come up with. :-)

**Comment by Maikuolan** [comment]
Working on this now. Just to confirm: When you mention "blocked list", do you mean the IP tracking page, the logs page, the IP testing page, all of them, or something else? Should be no more/less easy/difficult to get it working for one as for any of the other pages, but I ask in order to avoid cluttering. Got a small clickable reporting icon working at my dev copy at the moment, which isn't too obtrusive, but would still need to appear at each occurrence of each listed IP address at any page where it's desired to appear in order to be usable, thus visible enough to potentially be aesthetically annoying if it were to appear on any pages where it isn't actually desired.

**Comment by Maikuolan** [comment]
For the moment, I've included the icon at the IP tracking page. Let me know how it goes and whether I should add it to the other pages. :-)

**Comment by eurobank** [comment]
I think the best is in the log files. Because in there you know exactly what violation it is and if you should report it. In the tracking page you have no idea what violation it was but or/and if it was already reported (by extras).

I will check this update and let you know ...

**Comment by eurobank** [comment]
For some reason i'm forwarded to AbuseIPDB but UNLOGGED, while i'm logged in.

**Comment by Maikuolan** [comment]
> I think the best is in the log files. Because in there you know exactly what violation it is and if you should report it.

Agreed. I've now added it to the log files. :+1:

> For some reason i'm forwarded to AbuseIPDB but UNLOGGED, while i'm logged in.

Haven't yet been able to replicate that problem but looking into it.

**Comment by eurobank** [comment]
>
> > For some reason i'm forwarded to AbuseIPDB but UNLOGGED, while i'm logged in.
> 
> Haven't yet been able to replicate that problem but looking into it.

I think AbuseIPDB doesn't like the referer? or something like that?

**Comment by Maikuolan** [comment]
Able to replicate it now. Tried preventing the referrer from being sent, but it didn't seem to have any effect for me, but I'll implement that change anyway, because it would be good to do so from a privacy perspective regardless. Will continue to experiment to try to figure out what's going on.

**Comment by Maikuolan** [comment]
Experimenting at my local dev server, trying to figure out what differences the server might be seeing between requests generated by clicked links versus requests generated via bookmarks, via typing URLs into the address bar, etc, I'm wondering whether the problem might be due to how they respond to the browser's `Sec-Fetch-Site` header. When accessing the reporting page via clicking on a link at the CIDRAM front-end, `Sec-Fetch-Site` would normally show `cross-site`, whereas accessing the reporting page by manually typing the appropriate URL into the address bar, or when clicking on a bookmark, `Sec-Fetch-Site` would normally show `none`. I am, of course, only speculating, as I'm not privy to whatever code might be running at their end nor anything else that might provide certainty, but if they don't allow serving pages as a logged in user when encountering `cross-site`, that would explain what we're seeing.

(And if I'm right about that, I'm not too sure what I could do about it, unfortunately. Other than perhaps porting the entire reporting page as a local page at the CIDRAM front-end itself, to avoid needing to go to their website entirely, and just submitting the reports via their API, which.. would work.. but would also mean that "manually" reporting would consume API quota, which reporting from their actual report page doesn't do, and would also mean creating an entire front-end page dedicated to just reporting to just one service. Could do it easily enough, of course, but would also be nice if it wasn't necessary to do it, given the purpose of the original idea, to make reporting just that little bit easier, auto-filling in the IP address we're wanting to report and such).

**Comment by eurobank** [comment]
I was about just to reply here, the same idea, Report using their API. Quotas are not an issue, reporting more than 5000 manually or automated can't be easily be reached.
![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/a50ac1e1-3449-45e5-8561-cb63091c6ac6)

**Comment by Maikuolan** [comment]
Done. We now have an integrated reporting page. :-)

**Comment by eurobank** [comment]
That is GREAT news !!
