### ISSUE TITLE
More checks necessary if ONE is met?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#339]
Hi,

See this:

Why Blocked: AbuseIPDB Lookup, TOR Project exit node, Access from what looks like a TOR Project exit node.

Why check for an other signature if AbuseIPDB is positive? Just an example.

I mean continuing to check against other signatures if one is met, doesn't delay?

**Comment by Maikuolan** [comment]
Modules, in general, would still need to be able to execute, for in the case that some later-executed modules contain bypasses, due to the configuration value set for the infraction limit, CAPTCHA settings (e.g., maximum infractions for allowing CAPTCHAs to be served), any auxiliary rules which might potentially rely on the signatures count, etc and etc. That said though, too many additional lookups to external APIs would *definitely* delay the request, and should be avoided when at all possible.

For all the modules that I wrote which perform such external API lookups (e.g., the AbuseIPDB module, the SFS module, etc), lookups are guarded, and won't be performed if at least one signature has been already triggered, as long as the signature count is greater than the signature limit for the currently used CAPTCHA service, or if one isn't used. Modules which don't perform any lookups aren't guarded in the same way (because it isn't necessary in the same way).

The tor module is one of MacMathan's modules though (i.e., I didn't write it), so I don't think it implements the same or any similar such guards. I haven't looked at it for a while now though, so I'll double-check over the code in a moment and reply back after.

**Comment by Maikuolan** [comment]
Yeah.. Just double-checked; Not guarded. I'll need to update it to work properly with v3 anyway, so I'll see what I can do for it.

**Comment by eurobank** [comment]
Here is an other example:

Why Blocked: AbuseIPDB Lookup, googleusercontent.com!

The first is a check from AbuseIPDB that is possitive and the second is from Aux Rules of mine. Are those modules written from you or somebody else?

**Comment by Maikuolan** [comment]
> Are those modules written from you or somebody else?

Most of them, yes. Some of them, no. The AbuseIPDB module, I wrote.

**Comment by eurobank** [comment]
I think this is happening everywhere.

For example:

Why Blocked: Banned, contaboserver.net!

If it is Banned, why check also the Aux Rules?

--

Why Blocked: ovh.com (ns*.eu), *.ip*.eu - ONLINE SAS!

The first Aux Rule is met, why check the rest aux rules also?

**Comment by mikeruss1** [comment]
some of my checks work differently depending on the number of blocks, so stopping at one would mess up for me. A lot of the additional checks are going to be very marginal in overhead, so the approach of only doing one external read that results in a block looks good, especially as v3 could add more external fetches.

**Comment by eurobank** [comment]
Great. Thank you!

**Comment by Maikuolan** [comment]
Tor module done (for v3).

**Comment by Maikuolan** [comment]
Just rechecking over old issues at the moment. I think this issue is probably resolved now..? Not sure if there was anything more needed to be done from here.

**Comment by eurobank** [comment]
probably so.
