### ISSUE TITLE
New bot

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#340]
Increasing number of this UA recently .... Worth blocking. 

labjs.pro/bot

**Comment by eurobank** [comment]
@mikeruss1 You know ... i have found a better way to block all that crap. Just by using the Aux Rules.

Checking the Agent. Works miracles. OR if the bot has a real HOST name, with the Host name. Wildcards also work (Windows mode). EASY.

Aux Rules are Gold. Right now i only use TOR block, Aux Rules, Abuse IPDB and some custom file for some IPs.

The other signatures blocked a lot of IPs that i needed.

**Comment by mikeruss1** [comment]
you might find this aux block useful - it blocks any UA with a length of less than 15 characters via a regex

Aux invalid UA:
 Method: "RegEx"
 Logic: "Any"
 Reason: "Invalid UA - 004"
 Block:
  If matches:
   UA:
    - "[^.{0,15}$]"

**Comment by Maikuolan** [comment]
> Поисковый робот LabJs загружает и индексирует контент со всего Интернета. Цель такого бота — узнать, о чем (почти) каждая веб-страница в Интернете, чтобы можно было получить информацию, когда она понадобится.

*"The LabJs crawler downloads and indexes content from all over the web. The purpose of such a bot is to find out what (almost) each webpage on the Internet is about, so that you can get information when you need it."*

Meanwhile, at their homepage: "Админ Панели Для Сайтов И Приложений" ("Admin Panel for Sites and Applications"). So, I'm guessing, they're not a search engine, directory service, or anything like that. That being the case.. why would they have any need to "find out what each webpage on the internet is about"? Sounds to me like just another scraper bot. I'm thinking I'll have the bot UAs module cite it as a scraper, accordingly.

**Comment by Maikuolan** [comment]
> you might find this aux block useful - it blocks any UA with a length of less than 15 characters via a regex

Sounds like a good idea to me. Most *legitimate* browser UAs are *much* longer than that nowadays (often upwards of a few hundred characters), so should be safe from that. Even CIDRAM's own UA (which, of course, is unlikely to be ever seen by anyone, unless someone is using its webhooks feature to point somewhere, or somehow has access to the server logs at GitHub or at any of the API providers it uses) only sits at approximately ~41 characters (give or take a byte depending on the length of the version string at the time), so blocking anything less than 15 characters should be pretty safe AFAICT in terms of the risk of blocking something legitimate by mistake, while being able to block a significant number of bad bots and other unwanted stuff.

**Comment by Maikuolan** [comment]
Done. :-)
