### ISSUE TITLE
Question about IPDB

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#346]
Hi.

Shouldn't this:

https://www.abuseipdb.com/check/15.197.142.173

be blocked? Because it is not (spam contact forms)

:)

**Comment by eurobank** [comment]
forget about it. I have disabled the IPDB for 1 day and the API key was deleted (why?)

**Comment by Maikuolan** [comment]
> and the API key was deleted

Do you mean deleted from your configuration file?

For v2 and earlier versions, it's possible that configuration values could be lost if the source of those values is disabled, and then, while disabled, the configuration is updated. That problem is due to v2 and earlier not handling orphaned values properly (those versions, whenever updating the configuration, rebuild the entire configuration file based upon the available configuration directives at the time of updating).

That problem doesn't exist for v3 though. From v3 onward, a checkbox is provided at the configuration page to allow users to choose whether to keep or to delete orphaned values. In the case of opting to delete, the configuration file will be rebuilt based upon available directives, much the same as with v2 and earlier. But, in the case of opting to keep (not opting to delete), the configuration file will instead be rebuilt based on itself, updating only where values have changed, and otherwise keeping the file exactly as it already was.

Although already fixed for v3, seeing as there didn't yet exist any issue for that particular bug, I guess I'll label this issue here accordingly.

**Comment by eurobank** [comment]
I have no idea if it was deleted in the files, it was empty in the configuration.

v3 ? where is that? I see vs 2 in my installation.

**Comment by Maikuolan** [comment]
The current latest available v3 version is `v3.0.0-beta2`. Technically still "beta", but should already be safe to use. I haven't yet marked it as having moved out of beta, because there are still some more things on my to-do list which I hope to be able to accomplish before that time (there are some other open issues here describing some of those things, such as creating v3-compatible versions of the current existing v2 modules; for most modules, that's already been done, but there are a few which it hasn't been done for yet), but there aren't any critical bugs in the current latest version (at least, AFAIK, and hopefully, by writing that here, I don't jinx anything), and no significant backwards-incompatible items on the to-do list remaining, so, should be safe. Just might see some new features suddenly appear in it between now and then. :-)

Because v3 is not backwards-compatible with v2, and because of the numerous changes implemented for v3, the updater won't be capable of updating from v2 to v3 automatically, so, updating from v2 to v3 will require a fresh installation (the installation instructions for v3 are also a little different than v2; in particular, the way that websites are "hooked" to CIDRAM; so, when updating from v2 to v3, it would be good to double-check the "how to install" instructions at the README before doing so).

Worth noting: Support will continue for all existing major versions for at least a while yet. I haven't yet decided on an exact date to end support for older versions, but at the very least, there are too many things to do first before I can think about that, and I'll want to give everyone at least a few months notice before that happens too, so given I haven't decided on the date yet, support should continue for at least a while yet. ;-)

**Comment by eurobank** [comment]
ok, so how can we get/install v3 (should we?).

**Comment by Maikuolan** [comment]
v3 can be downloaded directly from the main page of the repository:

![Untitled](https://user-images.githubusercontent.com/12571108/199053820-7cc95d65-8e2b-41bf-8485-ef0a50da733f.png)

(__[Link to the current installation instructions](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#SECTION2)__).

Also, when looking for a specific version (whether v3 or any other), all versions are listed, and can be downloaded from, the __[tags](https://github.com/CIDRAM/CIDRAM/tags)__ page.

> should we?

v3 definitely has many improvements over v2, but seeing as v2 is still actively maintained as well and still viable, upgrading isn't something urgent, I think. I wouldn't do it while super busy or while in a rush, but if you've got enough spare time to look over it to get a feel for it and feel like trying it out, I'd recommend doing so. :-)

**Comment by mikeruss1** [comment]
I run it on my desktop testing system, and in a limited way in prod -just a couple of pages. It is stable with only a few odds and end to tidy. If you have a look at #328 you can see whats being discussed. The only installation issue I remember was a hack to the auxiliary file to make it port. Configuration has changed fairly significantly,
