### ISSUE TITLE
v3 installation

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#347]
I'm abit worried. I consider myself an advanced webmaster and i use cidram for a long time along a custom script, still i do not understand the installation part of v3.

In v2 i just auto prepend the loader.php in htaccess.

In v3 it seems a mixture of prepend, loader.php and entrypoint.php. And also some special setup also for the front end.

I can't understand all that, not clear to me. But maybe i'm not that talented :)

**Comment by Maikuolan** [comment]
I probably need to improve the documentation somehow at some point, because you're not the first person to mention it not being very clear to them. Sorry for the confusion. '^.^

So, compared to the v2 instructions, the v3 instructions are a little more technically formal, talking about "entrypoints" instead of "hooks", and the two terms may have slightly different technical definitions, but from a practical perspective, it's the same thing (so, don't worry too much about the change of terminology). Basically, when we talk about "hooks" for v2 and earlier, we meant the place where CIDRAM can "hook into" the website or system at hand, and when we talk about "entrypoints" for v3, we mean the "point" where CIDRAM can "gain entry to" the website or system at hand (so, different words, but same thing).

Where it says "entrypoint.php", the name of that file is written only as example (because, when talking about the file which serves as an entrypoint, *something* needs to be written, but we don't necessarily always know what the real name of the real file at the user's system is actually going to be named as), so we won't go searching for some existing file with that name.

For v2 and earlier, we would either "prepend" or "require" a "loader.php" file. Strictly speaking, we're still doing that for v3 too, but where the process has changed for v3, is that v3 also needs to be "instantiated" (creating an "instance" of). For v2 and earlier, that would be handled automatically by the "loader". The main benefit of doing it automatically is that the user needn't do it themselves, but has the downside that the user also doesn't have much control over the process either. Also, because v3 and earlier had a singular, unified entrypoint for everything, whether for protecting the website, for accessing the front-end, for accessing CLI, etc (which was done that way in order to make it easier for users).. doing it automatically also enforced the restriction that CIDRAM v2 and earlier had to be installed within the public root (because the front-end wouldn't be accessible unless its entrypoint was within the public root somewhere), which is theoretically less secure (there aren't any specific vulnerabilities or weaknesses known about at this time, but thinking ahead, if any are discovered in the future, keeping CIDRAM's files outside the public root entirely should, in theory, help the situation, at least a little). Having it done manually for v3, although a little more work, means the user can decide for themselves where their entrypoints should go, which removes such restrictions and allows for that theoretically slightly more secure setup.

---

When our usual "entrypoint" (or "hook") for protecting our websites since v2 uses the "require" strategy, all we would need to do for v3 is add one extra line. So, where before, for v2, we would've had something like this:

```PHP
require_once '/blah/blah/whatever/loader.php';
```

We'll instead, for v3, now have something like this:

```PHP
require_once '/blah/blah/whatever/vault/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();
```

Because the entrypoints aren't unified anymore, for accessing the front-end for v3, instead of accessing the "loader" *directly* (which was the strategy for v2, and done that way in order for CIDRAM to know whether it just needs to protect the website or needs to load up the front-end), we'll create a new file (this new file, can be named anything, and placed anywhere we want, but is the file that we'll instead want to access in order to load up the front-end for v3, so ideally, the location should be something which only we know, but the general public doesn't know). The entire content of this new file can be as simple as this:

```PHP
<?php
require_once '/blah/blah/whatever/vault/loader.php';
(new \CIDRAM\CIDRAM\FrontEnd())->view();
```

(That required path pointing to the loader file inside the vault for v3).

Or, if we also want the front-end to be protected by CIDRAM as well, this instead:

```PHP
<?php
require_once '/blah/blah/whatever/vault/loader.php';
$CIDRAM = new \CIDRAM\CIDRAM\FrontEnd();
$CIDRAM->protect();
$CIDRAM->view();
```

---

The `auto_prepend_file` strategy is still a good strategy to use when it comes to protecting our websites, because it means we don't need to mess around with the files of any CMS, frameworks, or whatever else we have at our websites in order to get our entrypoints working properly. Without `auto_prepend_file`, we would need to put our entrypoints into those CMS/frameworks/etc directly, but with `auto_prepend_file`, we can just create some new, empty PHP files to put our entrypoints into, and then `auto_prepend_file` those new files.

Unfortunately, because `auto_prepend_file` literally just prepends a file, and doesn't do anything else, it isn't enough to "instantiate" anything, which is why we would still need to create some new files in this manner (so in that sense, we could argue that for v3, it's a little like a "mixture" of both the strategies from v2 and earlier), but still has its own valid place in the sense that it provides a way for us to avoid touching other, unrelated things at our websites.

Because the front-end is always accessed from the same place, we won't need `auto_prepend_file` for the front-end (we'll basically just be using `auto_prepend_file` to ensure we can protect all the PHP files at our websites without needing to edit them all).

---

I hope that helps explain things a little better. :-)

Let me know if there's anything which needs to be clarified or any confusion and I'll answer as best I can.

**Comment by eurobank** [comment]
Thanks, it is more clear now. Still a bit complicated for my setup (nothing to do with CIDRAM or you).

I'm using one instance of CIDRAM for several sites, this is one "complication".

But the "worst" of all is that i actually use also Ninja Firewall pro+ for them also, and i use the extra ".htninja" for CIDRAM. I hope you do follow :) So i will need to work on this.

**Comment by eurobank** [comment]
I have done the initial loader part. Outside the website(s), in the main root.

BUT ....

The front-end file, can't be anywhere i think? 

Because everything outside a website can't be accessed. Am i missing something?

**Comment by Maikuolan** [comment]
> Because everything outside a website can't be accessed.

Correct (and, because we don't want *other* people poking around the vault without our permission, provides an additional safeguard for that, useful in case `.htaccess` or other control mechanisms ever unexpectedly fail in the future for some reason, maybe the hosting provider upgrades to different server software in the future without telling us, and the newly upgraded server software doesn't support our old mechanisms like `.htaccess` or whatever else). But, because *we* still want to be able to access the front-end *ourselves*, we'll now want to create a separate entrypoint for the front-end, so that we'll be able to do that. CIDRAM and its vault exists outside the main root, but the separate entrypoint we're creating will exist inside the main root, at a location of our choosing (something we know, but hopefully, others won't know). That way, the *only* way to access the front-end will be specifically by using the entrypoint that we're creating (so providing a way for us to "guard the border", per se).

Although accessing the loader from the directly from the browser won't be possible by doing it this way, the front-end will still be accessible for us, because we'll access it via the newly created entrypoint for the front-end, which'll "require" the loader and "instantiate" the front-end as needed. :-)

**Comment by eurobank** [comment]
So the font-end loader must be inside a "website" root (public_html or whatever). Not at the root as you say, because the plan's root can't be accessible in any way from the Internet and shouldn't of cource.

**Comment by Maikuolan** [comment]
Yeah.. When I mention "root", I mean the "website root" (e.g., `public_html`). Definitely not talking about the server root or plan root. I should've clarified that earlier. '^.^

Before I continue: I would mention that, although I strongly *recommend* storing "outside the root" for v3, it *isn't mandatory*. If the server is configured in such a way that it turns out that doing things this way simply *don't work* at the server in question for whatever reason, we *can* still install everything *inside* the root, just as we did with v2 and earlier. But, one of the main reasons for decoupling the instantiation process from the loader, and our need to create entrypoints like this now, is in order to allow us to do it outside the root like that due to the potential security benefit. So, if this turns out to not work, it isn't a dead-end for us, but, as to how I envision this, if what we can see at the server were to look something like this (again, just as an example):

```
/server
/server/bin
/server/logs
/server/tmp
/server/system
/server/domains
/server/domains/foo.bar.tld
/server/domains/www.hello.world.tld
/server/domains/lorem.ipsum.tld
/server/domains/a.website.we.want.to.protect
/server/domains/a.website.we.want.to.protect/bin
/server/domains/a.website.we.want.to.protect/ftp
/server/domains/a.website.we.want.to.protect/tmp
/server/domains/a.website.we.want.to.protect/public_html
/server/domains/a.website.we.want.to.protect/public_html/wordpress
/server/domains/a.website.we.want.to.protect/public_html/laravel
/server/domains/a.website.we.want.to.protect/public_html/magento
/server/domains/a.website.we.want.to.protect/public_html/...
```

Previously, for v2 and earlier, everything would've been stored looking something like this:
```
/server/domains/a.website.we.want.to.protect/public_html/cidram
/server/domains/a.website.we.want.to.protect/public_html/cidram/loader.php
/server/domains/a.website.we.want.to.protect/public_html/cidram/vault/...
```

And we would've accessed the front-end by requesting "loader.php" from the browser, and protected our websites by either requiring in or prepending that same file.

But, for v3, everything would be stored looking something more like this:
```
/server/domains/a.website.we.want.to.protect/vault/...
/server/domains/a.website.we.want.to.protect/public_html/frontend-entrypoint.php
/server/domains/a.website.we.want.to.protect/public_html/protection-entrypoint.php
```

And we would access the front-end by requesting the "front-end entrypoint" from the browser, and protect our websites by either requiring in or prepending the "protection entrypoint" (with the `require_once` call written in earlier examples here pointing, per the above directory structure example, to `/server/domains/a.website.we.want.to.protect/vault/loader.php`, or could write it as `require_once __DIR__ . '../vault/loader.php';` at the entrypoint, for example, to tell PHP to "look for the file in the `vault` directory which is located one directory above the current directory").

**Comment by eurobank** [comment]
ok, let's see what i have now with v2 and works great.

1. The vault inside a website root, with a very complicated folder name.
2. Nothing related to CIDRAM v2 in my .htaccess
3. A "required_once + path of the vault" in .htninja in the root of the PLAN so it can be used in all websites

https://blog.nintechnet.com/ninjafirewall-pro-edition-the-htninja-configuration-file/

Nothing else.

-- 

Now for version 3:

1. Just the vault folder in the **PLAN** root (nothing else from your archive, not the tests.php and the rest)
2.  The 

```
require_once '/blah/blah/whatever/vault/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();

```
in the .htninja
3. (i haven't done this yes). Create a whatever php file in some website root with the 

```
<?php
require_once '/blah/blah/whatever/vault/loader.php';
(new \CIDRAM\CIDRAM\FrontEnd())->view();
```


Is that all? What do i miss?

**Comment by Maikuolan** [comment]
LGTM. :-) :+1:

**Comment by eurobank** [comment]
ok, let see if also works ....

**Comment by eurobank** [comment]
Questions:

1. Do the log file name has the v2 options? (day, month etc etc)
(scrap the above, uses the same as v2 but not documented)

3. Where can i exclude the server IP? i see no custom4.dat

**Comment by eurobank** [comment]
Ok, installed outside of the website root and it is working fine until now. 

I willl have to replicate some settings, add the "deny" or "allow"custom ips, ad some aux rules and spend some time to learn it. 

Different from vs2. Definitely simpler to install of what was described in the docs. I was terified by the guide ... honestly ....
:)

**Comment by eurobank** [comment]
Any ideas what this is:

**IPv4-Other – Failed to activate!**

(maybe i was refreshing the page and resend the activation)

**Comment by Maikuolan** [comment]
> (maybe i was refreshing the page and resend the activation)

It'll give that message when trying to activate an already activated component, so that's possibly the case. Does it currently show as active or something else?

> 1. Do the log file name has the v2 options? (day, month etc etc)
>    (scrap the above, uses the same as v2 but not documented)

Yep. Documenting that is one of the things on my to-do list. '^.^

> 2. Where can i exclude the server IP? i see no custom4.dat

I need to reintroduce some kind of template for custom signature files at some point; I haven't gotten around to that for v3 yet. But, the syntax and format for signature files hasn't changed between v2 and v3, so if you still have copies of your custom signature files from v2, it should be possible to copy/paste them directly into the `vault/signatures` directory for v3, list them at the appropriate places within the configuration, and have them work the same as they did before. (Of course, modules are a completely different story. Many changes have been made to the way that modules work for v3, and any custom modules from v2 would need to be heavily rewritten before being able to safely use them with v3. But, copy/pasting signature files should be safe).

**Comment by eurobank** [comment]
The v2 custom signature work well with v3, so i lost nothing.

All in all everything seems to work just fine until now.

**Comment by Maikuolan** [comment]
Glad to hear. :-)
