### ISSUE TITLE
over eager block

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#349]
Signatures Reference: 92.40.168.0/23 
Why Blocked: Attacks ("[Hutchison 3G UK Limited]

I know this because its the SIM from Three in my car which provides mobile Wifi.

**Comment by Maikuolan** [comment]
> I know this because its the SIM from Three in my car which provides mobile Wifi.

That's true, but according to reports, there's still a lot of unwanted traffic being seen from that particular range:

https://www.abuseipdb.com/check-block/92.40.168.0/24
https://www.abuseipdb.com/check-block/92.40.169.0/24

So I'm a little wary of outright removing that particular range at the moment.

What might be better would be to write a bypass using auxiliary rules to match if signatures count is >= 1 and profile matches "Mobile ISP". That should prevent that particular range, plus others like it in the same situation (dedicated mobile connections blocked due to just the default signature files only) from being blocked in that way.
