### ISSUE TITLE
Selective BGPView ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#353]
I have a particularly annoying bot which visits my site and pounds it using a defined page. Its always from the same country but the IP address keeps changing.

I was wondering if there was a way of using auxiliary rules to call BGPview to block a defined page and country?

**Comment by Maikuolan** [comment]
Should be possible. Just make sure that the BGPView module is activate, and create a new rule, using "country code" for the country and "reconstructed URI" for the defined page. :-)

**Comment by mikeruss1** [comment]
thank you - the code for UK would presumably be "UK" - the config page says 2 digit rather than 2 character which might be worth changing.

if I do the aux rule in the sequence URI then country code, would it only look up BGPView if the first test succeeded?

**Comment by Maikuolan** [comment]
> thank you - the code for UK would presumably be "UK" - the config page says 2 digit rather than 2 character which might be worth changing.

Based on __[ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table)__ codes, so we'd want to be using "GB", the "officially assigned" code for "Great Britain" ("UK" refers to the "United Kingdom", but is classified as "exceptionally reserved", and not actively used per ISO 3166 at this time; probably because they wanted both codes registered to cover both names, but any particular specific geographic region tends to only use just one code at any given time, so.. pick one and reserve the other, I guess..?). Anyway, BGPView's API, CIDRAM's signature files, and basically everything else of consequence here will use "GB".

> if I do the aux rule in the sequence URI then country code, would it only look up BGPView if the first test succeeded?

Currently, the BGPView module will always perform lookups for an IP address if it hasn't seen it before and doesn't have anything cached for the address in question, so it should perform the lookup regardless of the order of the conditions, as long as the module is active.
