### ISSUE TITLE
How can i solve pinterest block from AbuseIPDB?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#357]
This was blocked. How can i solve this? Bypass it for Pinterest? 

Thanks
![2022-11-14 14_43_05-CIDRAM – Logs — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/201663487-f00285d9-1467-48c5-b333-78fcbdf5a579.png)

**Comment by Maikuolan** [comment]
Normally, when a request is blocked due to an external API lookup, such as the case with this request, I'd recommend performing a bypass, but.. in this case, Pinterest being blocked due to the results of an AbuseIPDB lookup.. I imagine that this is something that most users wouldn't want blocked, so.. currently investigating whether I can do anything from my end, so that it won't affect other users either.

**Comment by eurobank** [comment]
I have added an aux rule to bypass it? Am i doing this correctly? (if hostname = *pinterest.com* whitelist it).

**Comment by Maikuolan** [comment]
Sounds about right. Might want to add a wildcard at the front of the hostname though, to catch any subdomain stuff tacked onto the front of the hostname (e.g., the `crawl-xx-xxx-x-xx.` part), and accordingly set the matching method to accept wildcards.

**Comment by eurobank** [comment]
yes. i did add one * before and one after * .....

:)

**Comment by Maikuolan** [comment]
Due to 92c318999cb764dc2fe3a7d13d97f5cafa185086 and d22c8a6e024728411aa46f9dbd3af9f0f2927f03, this problem should be resolved now. Marking as fixed.
