### ISSUE TITLE
BGPview

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#358]
we had a discussion a while ago about the response time implications of running BGPview.

I have been running some tests on a variety of services and getting almost a second on BGPview, this is measuring response purely internally on my server from the point the call to BGPview is initiated to getting the return. (not using CIDRAM, just a vanilla API)

other services such as abuseipdb and ipinfo are about a tenth of a second, so its not related in any way to my server.

just mentioning !!

also somewhat related, if CIDRAM does a country lookup would it be worth considering returning the country so the site could use it?

**Comment by mikeruss1** [comment]
looking into what abuseipdb offers, it also has country code and usage type. Where usagetype defines:
Commercial
Organization
Government
Military
University/College/School
Library
Content Delivery Network
Fixed Line ISP
Mobile ISP
Data Center/Web Hosting/Transit
Search Engine Spider

I dont know how well defined they are, but maybe this is a quick way to distinguish Cloud and ISP, and achieve BGPview functions?
The free plan is 5000 checks a day for webmasters which is certainly OK for me.

**Comment by Maikuolan** [comment]
CIDRAM will actually populate the usage type returned by the AbuseIPDB module into the request profile (when lookups are performed), so, it's possible to leverage by the usage type returned by AbuseIPDB with auxiliary rules and such by checking whether *profile = intended usage type* (of course, keeping in mind that lookups mightn't necessarily be performed for every request, depending on configuration, quota limits, etc). :-)

**Comment by Maikuolan** [comment]
> also somewhat related, if CIDRAM does a country lookup would it be worth considering returning the country so the site could use it?

Possibly. One thing to be wary about though, is that if CIDRAM's ability to determine the country code for a request (which relies on things like the BGPView module in order to work correctly) were to ever fail for any reason (e.g., if quotas/limits at the installation in question are reached, if maybe the API's provider were to ban the IPs of the websites in question at their end maybe due to perceived excess usage or whatever other reasons; BGPView's documentation doesn't clearly specify what limitations exist, whether there are any quotas, etc.. but given that it's the case for the majority of such APIs/services out there, I'm *assuming* that some kind of quota or limit probably *does* exist for it, but that we just simply don't know exactly what that quota/limit happens to *be* due to it not being documented), then that information would suddenly not be available to the website anymore either. If the data which potentially isn't available anymore is used purely as a bells-and-whistles kind of feature at the website (e.g., to display country flag to look pretty at a page somewhere, to automatically select some localisation options which can be manually changed to whatever the user actually wants, something like that), and isn't something essential, it's not too bad, but if used for something critical or essential to the workings of the website (e.g., displaying entirely different content depending on the country of origin, maybe region locking of some kind, maybe serving emergency service announcements and that kind of thing, with no means for the user to manually change it to how they want it or need it to be), it could potentially pose a risk for the website in question.

**Comment by Maikuolan** [comment]
Just rechecking over old issues at the moment. I think this issue is probably resolved now..? Not sure if there was anything more needed to be done from here.
