### ISSUE TITLE
Aux rules moving up down issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#364]
Hi,

Take a look at this please:

![2022-12-10 21_43_20](https://user-images.githubusercontent.com/4467158/206872741-7ababef0-db6c-436b-9833-841377bc4ed7.png)

**Comment by Maikuolan** [comment]
I haven't yet been able to properly get to the bottom of this problem or replicate it in any way, though I *suspect* the problem is most likely a browser cross-compatibility issue with the way that CIDRAM [currently leverages XMLHttpRequest](https://github.com/CIDRAM/CIDRAM/blob/cb7dc6de143a7c33309808e00dd66fb9a2bbd17b/vault/assets/frontend/default/scripts.js#L2) (i.e., different browsers implementing XMLHttpRequest in slightly different ways, and maybe I need to code something in to account for that). Haven't entirely confirmed it yet though. Currently, that uncaught type error doesn't appear at my end, at my dev copy or elsewhere. Still looking into it though.

**Comment by eurobank** [comment]
I have tried to make it happen again and again, i failed. 

Maybe it is Firefox playing games, who knows. 

Since this is not something that breaks CIDRAM, it is not that important. Put it at the very botton of your list.
