### ISSUE TITLE
Request - MemcacheD use with sockets

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#366]
Can we have at some point use of sockets instead of tcp with memcached? 30% faster.

thanks

**Comment by Maikuolan** [comment]
I haven't tried it before, but *in theory*, it *should* be possible already to use sockets instead of TCP as things are.

Based on what I see at the PHP __[documentation](https://www.php.net/manual/en/memcached.addserver.php#refsect1-memcached.addserver-parameters)__ for the specific method used by CIDRAM for connecting to Memcached servers (the values for CIDRAM's `memcached_host` and `memcached_port` configuration directives are passed directly into said method):
> ### Parameters
> #### host
> The hostname of the memcache server. If the hostname is invalid, data-related operations will set __Memcached::RES_HOST_LOOKUP_FAILURE__ result code. As of version 2.0.0b1, this parameter may also specify the path of a unix socket filepath ex. `/path/to/memcached.sock` to use UNIX domain sockets, in this case port must also be set to 0.
>
> #### port
> The port on which memcache is running. Usually, this is 11211. As of version 2.0.0b1, set this parameter to 0 when using UNIX domain sockets.

I'm thinking, if you were to set `memcached_port` to `0`, and for `memcached_host`, rather than the hostname (as one would normally use), instead setting the path to a socket file, CIDRAM should start using the socket as specified by that socket file instead of TCP. In theory. (But I haven't yet confirmed that it works as expected).

**Comment by eurobank** [comment]
I will try this weekend what you suggested and update here. 

Also how do we know it is working or not?

**Comment by mikeruss1** [comment]
I think I use what you describe - memcached itself works fine, host points to a sock file, port is zero
have had some issues with memcached and v3 accessing stored data, be interesting to see if yours works

**Comment by eurobank** [comment]
How would i know if it works or not?

**Comment by Maikuolan** [comment]
After you've changed it, try logging out and logging back in again at the front-end, and then checking the cache data page at the front-end. Because v3 onward stores login sessions in the cache, if it's successfully communicating with Memcached, then at the very least, there should be an entry listed there corresponding to the login session, and probably some other entries there too if anything else has happened by that point since after changing it (e.g., block events, statistics changes, etc), and with "Memcached" shown at the top of the list of entries (same as how it'll show "APCu" when using APCU, "PDO" when using PDO, or the path to the cache file when using flatfile caching and such).

**Comment by eurobank** [comment]
I wanted to test this, so i did.

After enabled and put the 2 settings, i was logged out automatically and then after login i was IMMEDIATELY logged out. I had to manually ftp and false the settings.....

**Comment by eurobank** [comment]
The socket path i used is:

/home/mydomain/memcached.sock

**Comment by mikeruss1** [comment]
our setups may be different, but my routing is from the root of the server

**Comment by eurobank** [comment]
The socket i posted is from the root of my plan. Not the root of the sites, above that. 

The socket info comes from my hosting provider, so it is correct since i can see also the socket name (like a "file") in my root.

**Comment by mikeruss1** [comment]
different setups, my hosting provider gives me access to what looks like a shared service memcached ....

/opt/memcached/run/mydomain/memcached-1.sock

**Comment by mikeruss1** [comment]
does it work from your own php code, without using CIDRAM

try
 $memcache->set($key, $data);
$data1 = $memcache->get($key);

**Comment by eurobank** [comment]
@mikeruss1 I can't test any code you suggest, but since i'm on a shared account, my Wordpress site and memcacheD works well.

On the other hand some other script we use, it doesn't. So i guess it is a matter of the script/plugin to work or not.

**Comment by mikeruss1** [comment]
are you able to just initiate memcache
the code for that is
$memcache = new Memcached();
$cacheAvailable = $memcache ->addServer('path to sock file', 0);

**Comment by eurobank** [comment]
@Maikuolan & @mikeruss1 

I did it. How?

1. I edited manually the /cache.php and changed 'localhost' with my socket and 'port' with zero. 
2. Went to the cfg of cidram and enabled memcached and also added the socket and port zero.
3. Updating created an error but everything worked after that and i can't replicate the error updating again.

The error:

`[14-Dec-2022 19:54:13] PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected end of file, expecting ']' in /home/domain.com/cdr3/vault/CIDRAM/CIDRAM/Updater.php:783
Stack trace:
#0 [internal function]: {closure}('CIDRAM\\CIDRAM\\U...')
#1 /home/domain.com/cdr3/vault/CIDRAM/CIDRAM/FrontEnd.php(16): spl_autoload_call('CIDRAM\\CIDRAM\\U...')
#2 /home/domain.com/cdr3/vault/loader.php(39): require('/home/domain.com/...')
#3 [internal function]: {closure}('CIDRAM\\CIDRAM\\F...')
#4 /home/domain.com/public_html/fe_cdr3.php(3): spl_autoload_call('CIDRAM\\CIDRAM\\F...')
#5 {main} in /home/domain.com/cdr3/vault/CIDRAM/CIDRAM/FrontEnd.php on line 16
`

No errors anywhere, seems to work. I can't see any information that works but i i guess it is. 

More on this later ......

**Comment by mikeruss1** [comment]
good stuff - take a look at 368 pl

if nothing has been blocked yet, then generate a GET thats blocked and then check IP tracking in the front end to see if its there
also, anything in statistics?

**Comment by eurobank** [comment]
@mikeruss1 5000+ blocks so far

![2022-12-14 20_40_49-CIDRAM – Logs — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/207688108-1d6c5b4d-8e3a-4e55-83d7-8395bc0aaf1e.png)

I will check the stats, thanks for the tip.

**Comment by eurobank** [comment]
@mikeruss1 Stats are zero unfortunatelly. So something is not working right, i guess. No errors apparently doesn't mean it is working right.

**Comment by eurobank** [comment]
Still i see:

![Screenshot(1)](https://user-images.githubusercontent.com/4467158/207690694-56db7092-f7ec-4ac6-9bad-6f466431ebfa.png)


![Screenshot (2)](https://user-images.githubusercontent.com/4467158/207691037-fd146ace-7adc-4efe-915a-fa7384755459.png)

**Comment by mikeruss1** [comment]
I reckon that blocking is working but it's not reading anything back from memcache, so stats is empty and IP tracking will also be empty

**Comment by eurobank** [comment]
@mikeruss1 Blocking definitely works. Stats, IP Tracking empty. Yes.

**Comment by eurobank** [comment]
Rate limiting also report / status is empty. No data available.

**Comment by eurobank** [comment]
@Maikuolan Not sure if you said :not fix: for this, if so, you can close it.
