### ISSUE TITLE
PHP Notice: ob_end_flush():

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#367]
Today, i see this in the Wordpress debug log (!) protected by CIDRAM script (NOT WP plugin of Cidram). Not sure how this is possible, but it happened. 

I think i was during Rate Limiting.

[14-Dec-2022 11:54:38 UTC] PHP Notice: ob_end_flush(): Failed to delete and flush buffer. No buffer to delete or flush in /home/cdr3/vault/CIDRAM/CIDRAM/Protect.php on line 424

**Comment by Maikuolan** [comment]
Yeah.. It's definitely something to do with rate limiting. I haven't seen this problem occur before, but rate limiting is the only thing in CIDRAM which uses `ob_end_flush()`, so it wouldn't be anything other than rate limiting.

I'll look into this shortly.

**Comment by eurobank** [comment]
@Maikuolan Does the use of Memcached has something to do with Rate Limit also?

**Comment by Maikuolan** [comment]
> @Maikuolan Does the use of Memcached has something to do with Rate Limit also?

As of v3, storage and retrieval for rate limit data is handled by the cache handler (for v2 and prior, rate limit data was stored directly in its own file, handled as simple file I/O, not touching the cache at all). This change is mostly due to the potential for race conditions and loss of data when trying to do everything as simple file I/O.

To the extent that the cache handler can be configured to use Memcached, yes. But, beyond that, there isn't anything to do with it (i.e., no interactions with it unique to just rate limiting; just the same interactions as anything else handled by the cache handler).

**Comment by Maikuolan** [comment]
Also, looking into this now. (Delayed yesterday due to work).

**Comment by Maikuolan** [comment]
I've added a guard to the `ob_end_flush()` call just now, which should fix the problem. :-)
