### ISSUE TITLE
Mixed aux rule

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#371]
I wanted to create a rule which used a regex for one line and a Windows string for another. Specifically a regex on the UA and a Windows string for a URL. Seems not possible?
I guess I could use regex on each line but that's beyond my skills.
Not important.

**Comment by Maikuolan** [comment]
Not currently possible, but I'll investigate potential solutions.

**Comment by Maikuolan** [comment]
Whoops.. Forgot to tag and update this issue when I committed some relevant changes recently (71e1a8d6f2ca70c794854122c0c3fdd434b7ebe3). Well, two weeks ago, but better late than never. '^.^

Anyway, it's now possible to do this. :-)

When creating or editing an auxiliary rule, for the dropdown menu for the method to test the conditions, select:

*"Detect the method for testing the conditions automatically."*

Then, when adding conditions, for the condition values, if the condition value begins with any valid, non-alphanumeric, non-space, non-control character (e.g., `!#$%&()/@{|}~`), and ends with that same character, or that same character followed by any valid PCRE flag (e.g., `imsxADSUun`), the entirety of that condition value will be treated as a regular expression (because those constraints would have it resemble the boundaries of a typical regular expression). Failing that, any value containing an asterisk (`*`) will be treated as containing Windows-style wildcards, and any other value will use either direct string comparison, or, if the condition value is numeric, or is prefixed by numeric operators, numeric comparison.

**Comment by mikeruss1** [comment]
thats great, thank you so much
I saw the change and was going to ask you what it did!
will give it a runout (when I remember what I wanted it for) !
