### ISSUE TITLE
BGPView and V3

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#373]
Trying to test a bit the BGPView module, it doesn't seem to work for me.

I add a few countries 2 digits CCS, including mine for testing, and i can browse everything.....

Am i missing something?

**Comment by Maikuolan** [comment]
I've committed a patch for this module just now. Let me know whether it fixes the problem. :-)

**Comment by eurobank** [comment]
I will as soon as an update becomes available.

**Comment by eurobank** [comment]
What is the format we should follow? One CCS per line? Comma separated?

Because it seems to me that only the first CCS is blocked, when using one CCS per line.

**Comment by eurobank** [comment]
Blocking countries with the bgpview doesn't work right. Sometimes it is blocked, sometimes not. I can't tell if this is an issue of CIDRAM or of the api service from bgpview.

I'm testing RU and the results are random.

**Comment by Maikuolan** [comment]
Are the results showing the correct country when checking directly via the __[BGPView website](https://bgpview.io/)__? Could probably compare results between what their website reports and what CIDRAM reports to confirm whether it's an issue originating from CIDRAM or from the API service itself, I think.

**Comment by Maikuolan** [comment]
> What is the format we should follow? One CCS per line? Comma separated?

v2 had required commas, whereas v3 had required one CC per line, but the commit which I pushed out earlier today modified it so that either way should work just the same, as well as with any kind of spacing, tab, linebreak, etc. (I'd suspected that formatting might've been a potential issue, so updated accordingly). So, currently, either way should be fine.

**Comment by eurobank** [comment]
Well i don't know what it means ... I have used US to easily test and again sometimes it works and sometimes not.

Checking some IPs at bgpview.com i get (example)

![2023-01-03 17_20_57-Mozilla Firefox](https://user-images.githubusercontent.com/4467158/210387192-970871d4-2a02-4d1c-98f6-1f7887eae171.png)

**Comment by eurobank** [comment]
An other test:

https://bgpview.io/ip/172.255.48.133

Shows Canada. I have CA as blocked country (6 countries each one in one line) and it is NOT blocked by CIDRAM.

![Screenshot](https://user-images.githubusercontent.com/4467158/210388500-2aa49182-3987-494e-b5ee-0ed163dea482.png)

**Comment by eurobank** [comment]
Ok, some more information: The CCS settings IN Cidram are working (as above) from what i see in the logs but not always blocking.

So the issue is not in the settings.

**Comment by eurobank** [comment]
Also bgpview reports wrong information about countries.

https://bgpview.io/ip/188.166.209.65

This is Singapore and not US as bgpview reports. So that module should be removed. Bgpview.io and their infor/api is apparently not working. I tried to email them via their contact and it failed with some insecure connection error from their part. Go figure.

**Comment by Maikuolan** [comment]
Definitely something very weird going on with their service there. I'm seeing the *"Sorry, the page you are looking for ..."* message intermittently for some IPs at my end too, though I've no idea why their page is doing that. Seems totally random; Some addresses do it, while others don't. Haven't discerned any reason or pattern to it yet.

**Comment by Maikuolan** [comment]
If it's detecting the wrong country, that *might* explain why it's not blocking the intended countries. Still investigating at my end to get a clearer idea about exactly what's going on though.

**Comment by eurobank** [comment]
You should check what the API replies for "page not found ips"....

**Comment by 737simpilot** [comment]
I think I mentioned this in the Gitter channel, but might be worthwhile to mention again. https://ip-api.com/

**Comment by eurobank** [comment]
@737simpilot Doesn't that (ip-api.com) needs a rewrite of the addon (bgpview) ?

And the "non-commercial" usage is a bit unclear. What are the limitations? Displaying ads for example is a commercial use?

**Comment by Maikuolan** [comment]
> I think I mentioned this in the Gitter channel, but might be worthwhile to mention again. https://ip-api.com/

Looking pretty good. I'll aim to get something up and running using their API shortly. (Also good to have more than one source to rely on regardless, seeing as there's no guarantee any either particular one will always remain available, and good to not have all eggs in the one basket per se).

**Comment by Maikuolan** [comment]
> And the "non-commercial" usage is a bit unclear. What are the limitations? Displaying ads for example is a commercial use?

From their documentation alone, it doesn't seem particularly clear. We may need to contact them to clarify, I think.

**Comment by eurobank** [comment]
From their site:

> How many requests can I do?
> 
> Our endpoints are limited to 45 HTTP requests per minute from an IP address. If you go over this limit your requests will be throttled (HTTP 429) until your rate limit window is reset.

**Comment by Maikuolan** [comment]
There's still localisation data to sort out, but I've committed an IP-API module to CIDRAM v3 just now. :-)

All the configuration directives for it are the same as the BGPView module (though under its own heading, of course).

It should work as a good replacement for the BGPView module. Both modules will remain available, in case someone prefers one or the other, but I would recommend against using both at the same time, because using both at the same time would mean performing lookups to both providers at the same time, which would be a waste of time, and also, because both write data to the same fields of the block event, using both at the same time could have unexpected results in the log data and interfere with auxiliary rules. So, just use one or the other.

Let me know how it goes, and whether there are any problems and such. :-)

**Comment by Maikuolan** [comment]
(Probably won't commit any new modules for v2 or v1 I think, because it takes time away from working on v3 stuff, and once v3 has its first non-beta tag/release in the near future, I'll probably see to eventually scaling back a lot of v2/v1 stuff, to make it easier to eventually drop v2/v1 support at some point, after enough users have migrated to v3).

**Comment by eurobank** [comment]
From some limited tests with IP-API new module, it seems to work just fine everytime and also i think it is a bit faster. Propably their server responds faster.

**Comment by 737simpilot** [comment]
@Maikuolan Thanks for implementing. 

Glad it works. :thumbsup:

45 lookups per minute should _probably_ be enough for most I think. That's almost one hit/lookup per second. 

@Maikuolan Is the API set to not lookup anymore based on an already lookup result? Like an established country to IP result? That would reduce the need to fetch all the time. Maybe some kind of caching could be used for say a certain time limit of 12 hours or what ever? What do you think?

**Comment by Maikuolan** [comment]
> Is the API set to not lookup anymore based on an already lookup result?

Yep. Currently, each successful IP-API lookup is set to be cached for a week (the same is true for the BGPView module, too), and each failed IP-API lookup is set to be cached for one hour (the same, in this case, is not true for the BGPView module).

Because lookups to the BGPView API would return all matching BGP announcements for any given IP address (e.g., A.B.C.D might have A.B.C.0/24, A.B.0.0/16, and A.0.0.0/8 all as known BGP announcements across potentially different ASNs or networks), each of those returned announcements would be cached for the designated time, and then, each subsequent time the module executes, the entire set of factors for the IP address being checked would be checked against the cache, to fetch any relevant cached entries, each cached entry being iteratively parsed, from largest to smallest factor, against the configured blocked/whitelisted ASNs and country codes. (Anything large enough to encompass the entire first octet would just be ignored though, as such large ranges would generally be far too wide to be meaningful or actually useful for us).

Because lookups to the IP-API API return specific values for specific datapoints (i.e., it doesn't matter whether there's only one or a hundred plus registered BGP announcements; the results of a lookup to their API will contain exactly one country code, one ASN, one of whatever else, etc), the way results are cached and subsequently fetched by the module is much simpler: The module will treat all IPv4 results as a /24 and all IPv6 results as a /48 (wide enough to hopefully avoid hammering the API with too many unnecessary lookups, while being narrow enough to avoid being overly presumptive about the request and to sufficiently avoid most false positives, as IPv4 ranges smaller than /24 and IPv6 ranges smaller than /48 are reasonably rare, and when adjacent to similarly small ranges, are rarely actually registered to different countries or different ASNs). We then only need to check the cache against those specific factors to see whether some appropriate results have been cached.

(And of course, lookups for either module would only need to be performed when something usable hasn't been cached yet).

**Comment by Maikuolan** [comment]
I quite like the fact that the IP-API API provides a mechanism to specify exactly *which* datapoints we want returned, too. Given that the modules only bother with ASNs and country codes, I can specify those datapoints, and have the API ignore everything else, providing less bloated, more concise results. BGPView doesn't provide any similar mechanism, unfortunately.

**Comment by 737simpilot** [comment]
👍
