### ISSUE TITLE
Stats for Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#374]
Hi,

Is it possible to have some stats on Aux Rules?

**Comment by Maikuolan** [comment]
Should be possible. Though, it would also depend on what kind of stats we're talking about, I guess. Do you mean things like, how many block events occur due to auxiliary rules, how many redirects occur, how many things whitelisted, things like that?

**Comment by eurobank** [comment]
Actually something simpler. Number of times a rule was used to block and when that happened last time (date).

So we can delete old and unused rules.

**Comment by Maikuolan** [comment]
Done. :-)

Tracking statistics for auxiliary rules can now be enabled/disabled per rule via the auxiliary rules page (wedged between the menus for *"Values for IP tracking"* and *"Disable this rule"*).

**Comment by eurobank** [comment]
you are kiding, right? i don't believe you did it ...

**Comment by eurobank** [comment]
Great, need some small tuning for screen sizes.
![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/dd184c6c-b303-4bee-9b15-45aed796d85a)

**Comment by Maikuolan** [comment]
Good catch. :+1:

(My current monitor's resolution is rather large, so it's easy to miss things like that for me, when I forget to check different resolutions sometimes). I'll work on that tomorrow.

Glad to see it's working properly. :-)

I think I'll keep it as a v3 feature though, not backporting it to v2 or earlier; Due to the differences in how the statistics system works in v3 compared to previous major versions, backporting might be a bit tedious, I think.

Also have just realised that the "copy to clipboard" feature isn't including the new auxiliary rules statistics yet (oops), so I'll need to work on that tomorrow, too.

**Comment by Maikuolan** [comment]
Word wrapping and clipboard issues should be fixed now. :-)

**Comment by eurobank** [comment]
yeap.
