### ISSUE TITLE
Aux rules priority

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#378]
more of a clarification - 2 aux rules, one a regex on the UA, the other prevents tracking for Cloud service blocks.

if both occur tracking is taking place. I guess this is because the regex is higher in priority than the Cloud service.

if I put the regex at the bottom I will get the required behaviour, which is no tracking ?

**Comment by Maikuolan** [comment]
Mind sharing the entirety of the two rules in question here? I'm wondering whether something else might be going on, because simply being regex-based in itself shouldn't affect the priority of rules.

**Comment by mikeruss1** [comment]
OK its me ...
the rule to turn off tracking only takes place when signature count = 1, which in this case it doesnt.

so can I ask a general question, how does it decide to apply tracking instructions, when there are 2 rules involved, only one says dont track?

**Comment by Maikuolan** [comment]
A key to understanding the priority between different rules with contradictory CAPTCHA options set could be found in the wording of the provided options.

"Forcibly disable" is.. forcibly disabling it, and when selected, will always take priority over contrary options.

"Mark for use with" isn't strictly "enabling" anything, but in the case that one or the other of the available CAPTCHA systems (ReCaptcha or HCaptcha) has been enabled via the configuration, but with `usemode` set as such that a CAPTCHA should only be provided if a particular signature or block event has been "marked" for usage with, said option provides the "mark".

In mechanical terms, a "motor" could be "turned on" or "turned off" via the configuration, but just because it has been "turned on", doesn't necessarily mean the motor has been "put into gear" yet. So, when "turned on", to "forcibly disable" could be seen like an "emergency shut-off switch" (to ensure it won't engage into gear), and to be "marked" to "put it into gear" (which, if "turned on", causes the CAPTCHA to appear, but naturally will still not do anything at all if the entire "motor" is turned off), with `usemode` dictating if and when the "motor" could be automatically "put into gear" under whichever particular conditions as per desired. :-)

**Comment by Maikuolan** [comment]
(This is also where the "Leave it as is" option can become important: Sometimes, you might have some rules where you don't necessarily want to disable it, but also don't want to immediately mark it, either).

**Comment by mikeruss1** [comment]
So forcibly disable always has priority over leave as is.

**Comment by Maikuolan** [comment]
Yep. :-)
