### ISSUE TITLE
Report Back to AbuseIPDB

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#379]
Hi
I have a question: How and what exactly do you report back to AbuseIPDB?

For example if a block to a register or login page is issued due to AbuseIPDB, do we report back? If yes, i dont' see it in my reports.

If not, why not?

**Comment by 737simpilot** [comment]
Perhaps that's something that should be in the reports. What I always did was check my AbuseIPDB profile at their website. Sometimes while testing things my own IP was reported so I had to delete my IP address from my AbuseIPDB submissions. LOL

**Comment by Maikuolan** [comment]
> For example if a block to a register or login page is issued due to AbuseIPDB, do we report back? If yes, i dont' see it in my reports.

If blocked due to that reason alone, then nope; it doesn't report back.

> If not, why not?

I've intentionally avoided reporting back to an API in cases where the block event has occurred solely due to the IP address already being present at the API in question for a few reasons:

1. In cases where something has been reported to the API erroneously in the past (regardless of whether by us or by someone else; the point here being IP addresses listed when they shouldn't be), but the mistake hasn't been detected and the IP address as of yet not delisted by the time that we check the IP address in question against the API, re-reporting due to the listing may exacerbate the problem of false positives, and what starts off as a single mistake, could spiral potentially into thousands upon thousands of listings for an address, which doesn't help the platform, nor any of us, which use the platform to make decisions about whether to block an address.

2. Although AbuseIPDB doesn't seem to stipulate any rules anywhere in regards to when to submit reports and when to avoid submitting any reports AFAICT (or at least, I haven't noticed any links at their website anywhere linking to any kind of page listing such rules), there are various other similarly purposed blacklists, platforms, APIs, etc which provide such rules, so, for the purposes of being a "good netizen" and ensuring our contributions are more beneficial than detrimental for the platform overall, there are some basic ideas we can adapt from rules listed elsewhere for when deciding what to report or what not to report. The most notable of these ideas being to report something only when we detect actual occurrences of the things that the platform is intended to track, and we're able to confirm with reasonable certainty that what we think we've detected is what we think it is.

So, taking that idea in mind, to only report actual occurrences of something, block events which occur due solely to an IP address matching against a signature in one of the default signature files are not reported, because something being listed at the default signature files is generally because we've experienced something bad from there in the past, or we anticipate that any future traffic from there will be of a nature that we don't want accessing our websites, but precedence and anticipation alone isn't any kind of proof in its own right regarding the nature of the traffic occurring at any given moment in the present time. Even if our judgment is correct, it isn't necessarily proven.

Likewise, just because an IP address is already listed at their platform, even if traffic from that IP address provides nothing but useless, dangerous, and unwanted requests, and even if our judgment to block the IP address in question is 100% correct, it still doesn't necessarily mean we're experiencing a provable occurrence of the specific things that their platform tracks, and so, in its own right, isn't necessarily grounds for re-reporting the IP address.

Basically, the only times where something *is* reported by CIDRAM back to their API are times when a block event has occurred due to a signature from a module being triggered by the request at hand, whereby the signature in question is intended to detect one of those specific that the platform is intended to track (e.g., user agents matching known hacktools, spambots, scrapers, etc, or other fingerprints of the request suggesting that the request at hand is an attempt to hack into the website, to hack into a webapp, or to do some other kind of activity which the platform is intended to track), or when a block event has occurred due to failed search engine verification (because something masquerading as a search engine is a known sign that the thing sending the request is most likely some kind of hacktool, spambot, or some other kind of dangerous thing we don't want at our websites, and which we have justified reason to report to the API about).

Of course, sometimes the modules get it wrong, or sometimes verification might fail when it shouldn't (e.g., standard verification procedure fails due to bad DNS configuration at the search engine's servers), which is why we've sometimes had to go back and delete our old reports on the odd occasion. And sometimes there might be requests where there is justification to report the IP address at hand and CIDRAM fails to catch it, or fails to report: Perhaps the fingerprint hasn't yet been coded into any of the modules, or it's just something we haven't seen before. In general though, better to err on the side of caution, I think. If we're convinced that something should've been reported, we can always go back and report it ourselves manually, or update the modules, if we know exactly what needs to be updated. But yeah.. Better not to report something if we're not convinced that we're justified in reporting it.

**Comment by mikeruss1** [comment]
I have some PHP code which runs through the cidram log once a day and uploads to abuseipdb. It ignores cloud service and attacks. Can share if anyone interested.

**Comment by eurobank** [comment]
Ok, understood. So back to my other request to have an option to Report an IP from the logs of Cidram, in there. I mean by not going to AbuseIPDB.

**Comment by eurobank** [comment]
An other idea is to report back to AbuseIPDB for Aux Rules, since the reason is already filled. And maybe an option if we enable this in aux rules or not.

Because right now we do not help much AbuseIPDB in reporting.

**Comment by 737simpilot** [comment]
While that may sound like a great idea, Maikuolan's input already on this about erroneous reporting means reporting back from some user's auxiliary rules defeats that purpose. 

I have auxiliary rules that I would never want to report back to AbuseIPDB. One rule states that if you make a POST request at a certain part of the site where that part should never get a POST request it's blocked. But, sometimes it's been noticed with certain devices like Apple for example they make a POST request for some reason at that specific URL. I also have other rules way beyond the scope of this discussion that would have no business reporting back to the public.

Can it be done where a certain rule can be added to report back to AbuseIPDB? Probably, but if we want to mitigate erroneous reporting and clog up AbuseIPDB with possible junk, then allowing the ability to report back to AbuseIPDB by someone's auxiliary rule isn't going to accomplish that.

**Comment by eurobank** [comment]
@737simpilot I get it, but keep in mind that apart from CIDRAM, anyone can report whatever he/she wants to AbuseIPDB without ANY kind of verification of the actual issue. 

You can report fake things as much as you like anyways .....
