### ISSUE TITLE
PDO caching option

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#383]
I'm continuing here, since poluting other non related issues topics is not that good.

So:

PDO with PHP 7.4.x Stats work, Cache page works, IP Tracking expiration dates don't show (no data available)

PDO with PHP 8.0.x: Stats work, Cache page works, IP Tracking expiration dates don't show (no data available)

PDO with PHP 8.1.x I can't test unfortunatelly because of sites not ready for that for now. I see that @Maikuolan has php 8.1 for his tests

**Comment by Maikuolan** [comment]
I can test at my current dev machine going back as far as PHP 5.4.45 (versions older than that don't run properly at my current dev machine), and have at least one reasonably up-to-date version of PHP at each branch from 5.4 until 8.2, but my default go-to version at the moment is PHP 8.1.13 (until I next update everything again). I'll typically test locally with that version, and test other versions if there are specific problems that need investigating, but otherwise normally rely on GitHub workflows to ensure nothing unexpectedly becomes broken at some point. :-)

(I'd love to be able to upgrade my default go-to version to the 8.2 branch, to test some of the latest features that PHP has to offer, but unfortunately, many of the extensions I need, and which CIDRAM needs, don't yet have Windows binaries available for PHP 8.2, so I'm stuck with PHP 8.1 at the latest at least until the devs responsible for those extensions release some Windows binaries for PHP 8.2).

**Comment by eurobank** [comment]
I can also test whatever you want (some snippet or something) that could shed some light ....

**Comment by eurobank** [comment]
@Maikuolan Question for PDO Ip Tracking: What "No data available." means? Tracking doesn't work or Tracking doesn't simply show on that page?

I mean does the tracking work actually?

**Comment by Maikuolan** [comment]
Tracking should still work fine. The expiry data should still be there, should still exist at the database, and so, entries should still expire when expected, as per normal; it just means that the IP tracking page wasn't able to fetch the expiry information properly, and so, rather than showing an incorrect expiry, or showing nothing at all, it'll just show the "no data available" message. :-)

**Comment by eurobank** [comment]
@Maikuolan Does a copy of the DB help? I can email a backup to you ....

**Comment by Maikuolan** [comment]
Another user spotted something at #390 which *might* be the cause of the problem here. I'm going to test it out a little later today and will reply back here when done. :-)

**Comment by eurobank** [comment]
@Maikuolan How can that be a bug that doesn't work for us but works for you. I don't think this can happen.

**Comment by Maikuolan** [comment]
I'm thinking that it's possible that some database systems *might* be casting the data into the wrong type (e.g., string instead of integer). *Maybe*. But it's not something so easy to confirm, given the number of different types of database systems out there, and us being not able to know ahead of time which database system exactly a user might be using.

If it's the case, then that, in combination with the `is_int()` check in the code, would likely explain why it isn't working. So, as an experiment, I'm going to change `is_int()` to `is_numeric()` (because the latter will still accept data, even if it's not an actual integer, as long as it *looks* like a number, and so, might be more permissive and appropriate in the case that some database systems might be casting to the wrong type). Anyway, we'll see. The change shouldn't hurt anything, and as a means to fix this bug, it'll either work, or it won't, and I'll just need to keep digging. Fingers crossed.

**Comment by Maikuolan** [comment]
Changes pushed. Let me how how it goes. :-)

**Comment by eurobank** [comment]
> Changes pushed. Let me how how it goes. :-)

Just switched to PDO to test, and it seems to be working now (IP Trackin/Expiry).

**Comment by Maikuolan** [comment]
Awesome. :-)
