### ISSUE TITLE
Possible IP Tracking bug ?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#387]
I have a custom aux rule for reconctructed url containing "*.env*".

This:

ID: 1674372286-938353-9890634094 »
Date/Time: Sun, 22 Jan 2023 09:24:46 +0200 »
IP address: 3.99.170.78 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246 »
Signatures count: 2 »
Signatures reference: Core.php:L2129 »
Why blocked: Banned, reconstructed URLs! »
Reconstructed URI: https : // www . ***** . ** /apis/.env »
Infractions: 30 »
Request method: GET »
Hostname: ec2-3-99-170-78.ca-central-1.compute.amazonaws.com »

The IP 3.99.170.78 is not showing anywhere in the IP Tracking page. is that normal? Am i missing something?

**Comment by mikeruss1** [comment]
Server restart?

**Comment by Maikuolan** [comment]
Not really normal. If an IP address is being tracked (and particularly, with enough infractions to be banned), it should definitely show up at the IP tracking page. Unless it expired, maybe? But the block event shown above was from only two days, so, assuming that `default_tracktime` hasn't been configured to something really tiny, it probably isn't that.

If PHP restarted, that would cause the cache to disappear if using APCu, due to that an APCu cache runs at the PHP instance itself, so, when PHP dies, so does the cache instance. But, I know you're using Redis at the moment, and I don't think the same applies to Redis, as Redis normally runs at its own Redis server instance (similar to how Memcached connects to a Memcached server, and PDO to whichever database system is specified by the DSN). If the server for the cache mechanism in use (whether Redis or Memcached) was to restart though, that could cause the cache to disappear. But, in any case, if the entire cache were to disappear, the IP tracking page, statistics, and everything else would be totally empty, rather than just having one specific IP missing from the IP tracking page, so.. it's probably not that, either.

**Comment by Maikuolan** [comment]
Maybe an indexing issue at the Redis instance? Not entirely sure offhandedly how I would be able to debug or confirm that though.

**Comment by eurobank** [comment]
Funny that is, the IP appeared today with 78 infractions. Anyways this is apparently impossible debug. 

Just mentioning it.

**Comment by eurobank** [comment]
@Maikuolan Are IPs blocked due to custom_ip4 dat entries been counted in infractions and added in IP tracking?

**Comment by Maikuolan** [comment]
> @Maikuolan Are IPs blocked due to custom_ip4 dat entries been counted in infractions and added in IP tracking?

Whether infractions incur (and so, whether tracking applies) due to signature files can be configured more broadly via `general➡stages`, but I haven't yet implemented any means of changing behaviour per specific individual signature file (I had considered, some time back, to implement something like that, but hadn't yet worked through all the potential theoretical pitfalls, and hadn't decided on anything concrete yet), so for now, it's basically all or none.

![Untitled](https://user-images.githubusercontent.com/12571108/214468531-f440a76b-693e-40b3-be0a-b43fa274fc42.png)
