### ISSUE TITLE
ip address in cidram v3 logs

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#391]
why does ip address show as eg: 192.168.1.X etc and not 192.168.1.1 or 192.168.1.2 etc
same for both ipv4 and ipv6 
in cidram v3 logs

thanks

**Comment by Maikuolan** [comment]
You'll want to toggle the `legal➡pseudonymise_ip_addresses` configuration directive in order to show the full IP address in logs. :-)

[IP address pseudonymisation](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#935-ip-address-pseudonymisation) exists as a feature in CIDRAM primarily due to GDPR concerns (if interested, you can refer to #66 for the much longer, more detailed discussion about that). As long as you're not operating from within the EU, and your website/business/service/whatever isn't targeting primarily an EU userbase, you most likely won't need to use the feature, but as caution towards potential legal concerns (and because I really don't want to put anyone which uses code I write at potential legal risk due to said code), the feature is turned on by default for all new installations (as a "just in case", on the chance that a business or some other large organisation from the EU decides to use CIDRAM and unknowingly gets into some kind of trouble due to not anonymising or pseudomising logged IP addresses, due to that the EU regards IP addresses as PII, or "personally identifiable information").

FYI: At all the installations at all the various websites which I currently manage and maintain at this time (which admittedly, is a pretty small number, most are based in Australia, and some are based in the US), I've turned the feature off, in order to show the full IP address (and because properly debugging false positives can become a little difficult at times without the full IP address). There are also exceptions within the legislation that state that data, in some cases, doesn't need to be anonymised or pseudonimised if retaining that data, in its complete state, is absolutely necessary for the proper functioning of the system in question, and it could be argued that logging IP addresses fits that description (e.g., in order to be able to properly debug when false positives occur). But, I'm not a lawyer, and when the law is actually put to the test, who is considered "right" and "wrong" often comes down to which side can put forward a more convincing argument, and there's also the question of whether one side can actually "prove" that the other side is/isn't doing something, or cares enough to bother putting forward a case in the place first, so.. I leave it up to users to decide whether or not they need to use the feature.
