### ISSUE TITLE
V3 Edge Browser ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#399]
I think this is Edge ?
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edge/96.0.1054.34 
its getting blocked by  bobuam.php:L171 and reported as Outdated Browser as also does V2

if I put the UA into IP test in v3 its reported as Error – modules/extras.php (1)

there isnt an Edge category in Bobuam EOL so its all confusing ~?

**Comment by Maikuolan** [comment]
<strike>Yes, it is Edge. It's currently reporting as outdated due to the Chrome token though (currently, the EOL value that BOBUAM recommends for Chrome is 97, and the major version cited by the user agent in question is 96).</strike>

*Edit: Not Edge, after all. See details further down at this issue.*

Because Edge, like Chrome, is based on Chromium, both Chrome and Edge should generally be in lockstep in regards to their major version numbers, which is why, for all but the most obscure of cases, for any such user agent (assuming it's a real one, and not something faked by a bot) where both Chrome and Edge tokens are cited together, the major version part should be the same (though I still stand by the opinion of how ridiculous it is that they all insist on lumping all their tokens in together for all their browsers, rendering modern user agents as almost useless when it comes to actually being able to identify which browser, or agent, is actually being used most of the time).

I *could* add a separate, distinct option for Edge, but do we need it? If we're going to specify different major version numbers between Chrome and Edge, I guess we probably do, because having a separate, distinct option for Edge would be the only way we would be able to meaningfully differentiate between different major version numbers for Edge and Chrome in such an event. But, is there a need to specify different major version numbers? Given that they're generally in lockstep, I imagine the intended EOL values would be the same for the most part.

**Comment by Maikuolan** [comment]
Not sure what would be causing the error with the extras module though. I tried, but failed to replicate the error just now. Is your copy of the extras module up-to-date at the moment?

**Comment by mikeruss1** [comment]
I think there is more to it - my Chrome EOL is 51.
extras is up to date and verifies OK - 2022.315.0
and noticed something else, my bobuam block reason is Other, Your browser is old and not secure. Please update.
it reports as Outdated Browser

**Comment by Maikuolan** [comment]
> I think there is more to it - my Chrome EOL is 51.

Okay.. Just set my own to 51 and retested, and can confirm: Seeing the same thing at my end. Reinvestigating now.

**Comment by Maikuolan** [comment]
Found the problem. Working on a fix now.

**Comment by mikeruss1** [comment]
I don't really have a few on Edge. Few genuine visitors have it, and in any event I use EOL because bad guys tend to have very old UAs.

**Comment by Maikuolan** [comment]
Should be fixed now. :-)

**Comment by mikeruss1** [comment]
false positive fixed, but IP Test still producing Error – modules\extras.php (1)

**Comment by Maikuolan** [comment]
I've since been discussing this particular issue here (the BOBUAM issue) with MacMathan and JamesC, and.. they've each spotted a small detail in the user agent you'd cited above, which I'd somehow managed to completely miss when looking over it before: That the user agent contains an "Edge" token, as opposed to an "Edg" token (note the "e" at the end of the cited user agent, and the absence of it in all major versions of Edge over the past few years).

For reference and comparison, the current user agent for my own copy of Edge (the current latest available version):

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70
```

So.. It may, after all, in fact be a fake user agent (maybe a bot, scraper, spammer, or maybe someone using a browser with a cloaked user agent; no idea). So, I may need to "unfix" the changes I'd made before. :-/
