### ISSUE TITLE
IPv4 (cloud and hosting services) signature

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#404]
This

IPv4 (cloud and hosting services)

should be marked as Medium risk and not Low.

**Comment by Maikuolan** [comment]
In the past, when the signature files were smaller, I think marking it as "low" was correct and appropriate. But, the signature files have consistently become larger and larger over time, due to more data being consistently added which needs to be maintained over time. This consistent adding of more data does somewhat increase the risk of false positives, as it takes more time to cycle through all the data over time as I try to update it all, and the more time it takes, the greater the risk that data becomes stale, which directly increases the risk of false positives.

Currently, at this time, the least recently checked/updated signatures are just 10 days shy of it being an entire year now since they were last checked/updated, which frankly speaking, is not so good, but is about as good as it can be without either spending much more time on it, getting a second set of eyes on it, or stripping back a lot of the data overall to make it more manageable (this same time one year ago, the least recently checked/updates signatures were only about 6 months behind, rather than almost an entire year behind).

So.. yeah. I agree; it would probably be best to mark it as "medium" now. I won't mark it as "high" right now, seeing as there are very few complaints about actual occurrences of false positives due to the signature files, and overall, block events are still producing far more "correct inferences" than "false positives". But yeah; "medium" would be fair, I think.

**Comment by Maikuolan** [comment]
Done. :-)
