### ISSUE TITLE
Aux Rules Page after update

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#407]
What happened? Can't switch back to something visible .....

![Screenshot](https://user-images.githubusercontent.com/4467158/216993309-829ad736-cd9b-44d0-80e5-215caebbe6cb.png)

**Comment by Maikuolan** [comment]
Okay.. It definitely isn't supported to look like that, at all. o.0

For comparison, what it looks like at my end (no huge gaps between rules like at your end):

![x](https://user-images.githubusercontent.com/12571108/216995825-0d83691b-63cb-4c59-b2c2-6e5f2348932b.png)

I wonder whether it might be a browser compatibility issue? Which browser are you currently using, and what's the browser's version?

**Comment by eurobank** [comment]
Right. Firefox latest shows that issue, with Chrome it shows ok.

**Comment by Maikuolan** [comment]
I think I know what's happening, in that case.

Since the latest update, in the CSS for the front-end, `max-height:1lh;` is being applied to the options provided for the auxiliary rules, but it seems that Firefox doesn't support the "lh" unit yet.

https://caniuse.com/?search=lh%20unit

I wasn't aware of that until just now, when I checked, due to this issue.

I guess, I'll need to adjust the CSS to use a different unit for that style declaration.

**Comment by Maikuolan** [comment]
Should be fixed now. :-)

**Comment by eurobank** [comment]
It should and it is.

Thanks
