### ISSUE TITLE
Wrong block because of fake twitterbot

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#409]
Today i got an email from a friend, in my country, saying that he tried to access some pages and got a block.

From his IP, i found the block

> User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0
> Why blocked: Fake Twitterbot!

Could be a wrong block? There was nothing malicious with his visits.

**Comment by mikeruss1** [comment]
I get a lot of these as well, on going back through the log there is a pattern. I get a request for a page, it finishes, then instantly there is a Twitterbot request for the home page, from the same IP. They have the same UA as eurobank gives, the UA for the valid request is normal. No idea what is generating this, or whether it has any value to me.

**Comment by eurobank** [comment]
Maybe some browser addon is doing that?

**Comment by Maikuolan** [comment]
I did some searching, but it seems a little difficult to find any authoritative information (couldn't find any official documentation from anyone which says, *"this is our user agent, which we use for doing X/Y/Z.."*).

Udger's information says that it's Facebook, which is clearly wrong (the user agent for Facebook's bot "Facebot", AFAIK, doesn't announce with the "Twitterbot" token; at least, I've never seen nor heard of it doing so). Aside from that, the fact that the request originates directly from one of your user's machines is enough to tell us that it isn't Facebook (Facebot requests should only ever originate from Facebook's servers).

It obviously isn't Twitter either, given that it doesn't originate from any of Twitter's own servers.

Any chance at all that your user is using Firefox? I did find __[this issue](https://github.com/mozilla-mobile/firefox-ios/issues/12660)__ and also __[this issue](https://github.com/mozilla-mobile/firefox-ios/issues/12617)__ posted at the Firefox for iOS repository, both which cite the exact same user agent, and suggests that Firefox attempting to sync the user's bookmarks with the Firefox servers *might* be responsible that particular user agent, based on some users seeing that user agent in their logs corresponding to the time of Firefox requests (and if such is the case, kind of weird to know that Firefox might possibly be using Facebook's FacebookExternalHit library to perform HTTP requests instead of just using its own Quantum engine, or at least replacing the user agent for whatever they use with a standard Gecko user agent or something like that, which would certainly make things a little easier for us, too).

Some comments there *also* point out that the user agent apparently doesn't appear anywhere at all in the Firefox codebase, and that Firefox thus *couldn't* be responsible for the user agent in question (due to it apparently not appearing anywhere in the codebase). But the correlation between when Firefox requests occurred and when the user agent appeared in logs is still there (according to the comments there).

I personally have no idea though. I don't use Firefox myself, nor have for many years due to some persistent problems I encountered with it at my previous machine.

I guess, it might be possible to confirm this..? From memory, some of you are using Firefox, I think..? Do any of you use Firefox's bookmark synchronisation feature? If so, maybe try bookmarking your own sites and then using that feature, and then checking to see whether there's anything in your access logs or CIDRAM logs which match your own IP address from around the time that Firefox attempts to perform the sync?

If it's the case, I might need to adjust the user agent pattern that CIDRAM uses to identify Twitterbot, so as to avoid this false positive from occurring.

The problem, of course, is the lack of authoritative information. I'm only speculating based on what I can see posted at those two issues, and haven't found any formal documentation or such anywhere. Also, whether the problem persists, or has since been resolved at their end (assuming they were even responsible to begin with), I don't know. The issues have since been closed, and marked as fixed (though whether that's relevant to us, I don't know, given that the main concern of the issues was to address Firefox apparently flooding servers and effectively acting like a DDoS tool, rather than any particular concern about the user agent itself).

The user agent *could* also potentially appear as a result of iMessage (__[see here](https://webmasters.stackexchange.com/questions/137914/spike-in-traffic-from-facebot-twitterbot-user-agent)__), but when you mention, *"saying that he tried to access some pages and got a block"*, I assume you mean that he tried to access some pages through a *browser*, as opposed to through a phone messaging app. If that's the case, I doubt iMessage is responsible in *this* particular case, given that it's a phone messaging app, rather than a browser.

**Comment by mikeruss1** [comment]
the related page request always comes from Mac DuckDuckGo/7. The fact that the Twitterbot UA comes immediately after DuckDuckGo/7 would seem to confirm its a browser addon. Considering letting it through with an aux rule.

**Comment by eurobank** [comment]
ID: 1675974204-083682-3085370409 »
Date/Time: Thu, 09 Feb 2023 22:23:24 +0200 »
IP address: 174.193.132.255 »
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0 »
Signatures count: 1 »
Signatures reference: Core.php:L1317 »
Why blocked: Fake Twitterbot! »

Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: 255.sub-174-193-132.myvzw.com »


ALL are from Mac

**Comment by eurobank** [comment]
and this is a double issue, because CIDRAM is also reporting that to AbuseIPDB. If wrong, then we contribute into something we shoudln't.

**Comment by Maikuolan** [comment]
Twitterbot verification, although still supported, has now been turned off by default, and a warning added to the configuration page regarding iMessage false positives.
