### ISSUE TITLE
CIDRAM Debug Mode?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#412]
Not sure if v2 had this. maybe i'm confusing this option with something else.

Could a "debug" mode be available? In that case everything would work, especially the logs but NO ACTUAL BLOCK happens. Nothing is blocked but logged as it would.

Usefull for debugging CIDRAM and also to update some scripts we use and could be blocked by mistake (Wordpress etc etc).

**Comment by Maikuolan** [comment]
There *was* an option for that in v2 and earlier ("maintenance mode"), but we don't need it for v3 anymore, due to other options which've been added since v3. :-)

At the configuration page, under `general➡stages`, if you disable the stage labelled as *"Terminate the request"*, CIDRAM will effectively do everything it's supposed to do aside from actually blocking anything (i.e., things should still be logged as if blocked, but no actual block events will occur).

![1](https://user-images.githubusercontent.com/12571108/218092852-ffd20559-0ed7-45a3-a7a4-44d2a2e6092c.png)

After doing that, you'll also notice this appear at the front-end for subsequent requests (to warn about that stage being disabled):

![2](https://user-images.githubusercontent.com/12571108/218092939-c23f77f8-a379-4e2b-99c2-1f28e7b7bfeb.png)

Depending on your exact configuration, you *may* want to also disable the two stages labelled as *"Deploy CAPTCHAs"*, as there could be some specific situations where CIDRAM may normally ask a user to complete a CAPTCHA without it necessarily being treated as a "block event".

**Comment by eurobank** [comment]
Oh, i see. I don't have any captchas anywhere (i don't like to torture people), so disabling that single option will do the job.

What i want to do, is enable EVERYTHING (all modules) and run for a few days in that "dry run" mode. And check the logs to see if anything shouldn't be blocked or whatever ....

Thank for the tip.
