### ISSUE TITLE
Firefox browser

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#413]
would you mind checking this block pl?
ua - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Signatures reference: bobuam.php:L65 
Why blocked: Malformed UA (FF)! 

have looked it up and seems to be OK?

**Comment by Maikuolan** [comment]
It *looks* reasonably legitimate, as the current latest version for Firefox, but normally, the "rv" version and "Firefox" version should be the same. I.e., instead of:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
```

Having something more like:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:110.0) Gecko/20100101 Firefox/110.0
```

Though, just seeing this only just now, and replying at 2:30 AM, so.. I'll sleep on it, and look into it a bit better later, after I wake up.

**Comment by mikeruss1** [comment]
Have seen examples of both 109/110 and 110/110 on the ua sites.

**Comment by mikeruss1** [comment]
Have just received an email from the guy using that ua, looks most likely it's genuine. Long time user.

**Comment by mikeruss1** [comment]
have had several today from different sources so suspect its a recent update
there is also a windows version
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

**Comment by Maikuolan** [comment]
> Have just received an email from the guy using that ua, looks most likely it's genuine. Long time user.

Well.. That pretty much confirms it; Mozilla has, at least for the current latest version of Firefox, seemingly broken the symmetry between the `rv` and `Firefox` version tokens in the Firefox UA. When an actual known, long-time user emails you to confirm that they've been erroneously blocked, and confirms that the UA in question is their actual current UA, it becomes a little difficult to justify it as being anything other than just that.

(Of course, among some of the others I would normally discuss these issues with outside of GitHub, I'm pretty sure that at least one of them would probably point out to me that the long-time user *could*, in theory, be lying, and that I shouldn't believe something just because someone else says it is so, but in matters such as these, I'm strongly inclined to give the benefit of the doubt, unless given specific reasons to do otherwise or specific information suggesting otherwise, neither of which I've seen at this point, though all the information I've seen so far indicates that what this long-time user says is, in fact, correct).

I've pushed a commit just now which modifies the offending signature as to also check whether the specific `rv` token in the UA matches the one we're seeing right now ("109.0"), and if it does, to *not* trigger the offending signature. That should effectively bypass any UAs using the "109.0" token (I'm thinking, in case this turns out to be a *temporary* asymmetry between the `rv` and `Firefox` version tokens, which disappears when Firefox 111 or onward eventually emerges in the future). If it turns out to *not* be temporary, but permanent, I might need to see to either modifying the signature more heavily, or if it seems no longer viable, removing it from the module entirely. But, we'll see how the current changes hold up for now.

If, after updating the module, the problem still continues to occur (i.e., the specific offending signature continues to cause false positives), it would suggest that the changes likely don't go far enough, and I'll need to do something more.

**Comment by mikeruss1** [comment]
you can add me to the long time users having a problem, my Firefox has just updated and its 109/110. Fix confirmed working. Thanks. Hope I didnt disturb your night!
