### ISSUE TITLE
Strange issue a few hours now

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#414]
Any ideas what this is?

![Screenshot](https://user-images.githubusercontent.com/4467158/219158089-16f57de5-4e28-4aa5-80b9-82e6580eb27e.png)

**Comment by eurobank** [comment]
Laster 1-2 hours, now it seems ok.

**Comment by Maikuolan** [comment]
Possibly caused by this (because the upstream for updates is at GitHub)? Just a guess though; I'm not entirely sure.

[![Untitled](https://user-images.githubusercontent.com/12571108/219260128-03e89ac5-2014-41e1-8361-f9368a13d5f1.png)](https://www.githubstatus.com/history)

That said.. Normally, when GitHub becomes unavailable for whatever reason, no matter whether permanently or temporarily, CIDRAM *should* try falling back to the [backup repository at BitBucket](https://bitbucket.org/Maikuolan/cidram/commits/). It's good to see that the problem seems to have quickly resolved itself and that it appears to be working normally again now, but regardless of why the updater temporarily couldn't connect to GitHub in this case, it appears that it also didn't try connecting to anything else in consequence, which indicates a bug. I'll look into that now.

**Comment by Maikuolan** [comment]
Found the bug. Committing a fix now.

**Comment by Maikuolan** [comment]
Done.
