### ISSUE TITLE
Checksum error! File rejected!

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#415]
Trying to update today:

theme/slate – assets/core/captcha_slate.html – Checksum error! File rejected!
Actual – ff648323dd2df66bf8c386f5e49327b89b64527794e3ff6154c8d9b39f308a8d:1959
Expected – "ff648323dd2df66bf8c386f5e49327b89b64527794e3ff6154c8d
theme/slate – Failed to update! +0 bytes | -0 bytes | 0.011

**Comment by Maikuolan** [comment]
That definitely doesn't look right.

The current latest checksums for that file show as the same for the as expected:

https://github.com/CIDRAM/CIDRAM/blob/357c1bccf5a20fb077e376ee5554236720391f38/vault/installed.yml#L1217

Is the problem persisting, or did it disappear on its own? If it disappeared on its own, I can only speculate it might've been some kind of glitch from when the updater attempts to fetch the latest components metadata, causing the actual received upstream metadata to be mangled somehow. If the problems still persists, currently, I have no idea, but I'll double-check over all the code in case there's something weird in the updater's code capable of causing edge-case shenanigans.

**Comment by eurobank** [comment]
No it doesn't go away.

![Screenshot](https://user-images.githubusercontent.com/4467158/219338752-966cd859-a68b-4dd4-a402-fa36842457a1.png)

**Comment by 737simpilot** [comment]
I just updated now as of a couple minutes ago and always do a verification check afterwards and have no such issue. I have in the past in v2 though. 

It may help to manually copy that specific file over and then recheck. Or it's in the YAML file for the hash I think it is...

BTW, see how most of the SHA256 is exact except the last part? What are the astronautical odds of that given the math of SHA256? Maybe there's something else at play here. 

Edit- Yeah, it's cut off there. Something code wise is funky.

**Comment by eurobank** [comment]
@737simpilot I already re-uploaded this theme but it didn't change anything.

**Comment by Maikuolan** [comment]
I think I might've figured out what caused the problem. From memory, you're currently using PDO for caching, yeah?

Currently, by default, when using PDO, when the cache handler detects that the cache table doesn't already exist, it'll try to automatically create it, and __*[uses "TEXT"](https://github.com/CIDRAM/CIDRAM/blob/511c3eb95ac7342722ae9f37f811bbc786fa9922/vault/Maikuolan/Common/Cache.php#L379)*__ as the type of data for the data column of the cache table:
```SQL
CREATE TABLE `Cache` (`Key` VARCHAR(128) PRIMARY KEY, `Data` TEXT, `Time` INT)
```

The problem: The "TEXT" data type in SQL has an upper limit of 64KB. Normally, that *shouldn't* be any problem at all, as we really don't normally expect any cache entries to be larger than that, but unfortunately, without my really noticing the problem until just now, the components metadata file had recently surpassed that size (the components metadata file is currently 69.1 KB in size), and because the components metadata file is cached in order to avoid hammering the upstream with excessive numbers of requests, when reading it back from the cache (through PDO), what we're getting is truncated down to that 64KB limit (I suggest this, because the exact point where the problem seems to be happening, where we're seeing that data cutoff, seems to be around the ~64KB mark in the file).

At least, I can now confirm this as a bug. I'll investigate possible solutions and reply back when I can think of something.

**Comment by Maikuolan** [comment]
(Of course, the simplest and most direct short-term solution would be if I'm able to just reduce the size of the components metadata file in order to get it below 64KB. I'm going to try looking into doing that now, and fingers crossed, I'll be able to do something there. Not really a long-term solution by itself though, as new files or components may be added in the future, which might just bloat it back beyond the limit once again when that happens).

**Comment by eurobank** [comment]
Yes right now i use PDO.

**Comment by Maikuolan** [comment]
I pushed some changes just now which should resolve the problem. But, for the changes to take effect, the Common Classes Package will need to be updated. Try updating that particular component first, then check the cache data page, look for an entry labelled as `https://raw.githubusercontent.com/CIDRAM/CIDRAM/v3/vault/installed.yml`, and delete that particular entry. After deleting that particular entry, return to the updates page, and try updating everything else as would normally happen. Let me know how it goes. :-)

**Comment by eurobank** [comment]
Ok, now the error has been moved to

theme/primer – Failed to update! +0 bytes | -0 bytes | 0.000

and

CIDRAM Front-End – Verification failed! Component could be corrupted.

**Comment by Maikuolan** [comment]
If you click on the *"CIDRAM Front-End – Verification failed"* message (and similarly any other such messages whenever verification fails), it should open up a table of all the files connected to the component in question, showing exactly which files passed/failed verification, marking those that passed in green, and those that failed in red.

When you've got a moment, mind checking and listing which specific files it's failing on? Cheers.

**Comment by eurobank** [comment]
Sure:

assets/frontend/default/_logs.html – Integrity check: Failed – Sanity check: Skipped
Actual – efed6fcb3775531aea96c38c253a27ec08d059ba93af26d4f2a7978e80cd8edb:528
Expected – 8d909e4030e26eca62b7e35cf1503b4422a37e59e310f539709786c12cb1a97c:487

**Comment by eurobank** [comment]
But that is probably because i have touched that file.

**Comment by eurobank** [comment]
I think this is ok now.
