### ISSUE TITLE
Firefox again!

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#416]
here we are again
Mozilla/5.0 (Android 10; Mobile; rv:109.0) Gecko/110.0 Firefox/110.0

have looked it up and I think its OK

it seems they are going to keep rv109 up through Firefox version 120, in order to avoid confusion with IE
https://www.ghacks.net/2023/01/01/mozilla-changes-firefoxs-user-agent-because-of-internet-explorer-11/

this looks like a more general fix is required ?
no rush - have added an aux rule

**Comment by Maikuolan** [comment]
Well.. With those plans of theirs, I don't anticipate the "FF" signature (which targets malformed Firefox UAs), which was falsing before, continuing to cause any problems (at least up until Firefox version 120 is released, at which point, as it is, it'll probably start causing problems again), due to that the changes implemented the other day work with the "rv" token, to check whether it matches "109.0". However.. I tested that UA just now, and it seems the "MZ" signature (which targets malformed Gecko UAs) falses with it, so.. frustratingly, it seems likely that, as all these different browser vendors continue to mess around with things like this all the time, as times goes on, we're likely to be pushed towards implementing more and more changes to accommodate.

2:10 AM as I'm replying right now, which has been historically shown to be a terrible time to push new commits/changes due to the increased risk of making mistakes which break stuff due to tiredness, so I'm going to get some sleep for the moment, and I'll look at this again with fresh eyes after I get up later. :-)

**Comment by Maikuolan** [comment]
According to: https://wiki.mozilla.org/Release_Management/Calendar

> Quarter | Soft Freeze | Merge Date | Nightly | Beta | Release Date | Release | ESR
> ---|---|---|---|---|---|---|---
> Q1 2023 | 2023-02-09 | 2023-02-13 | Firefox 112 | Firefox 111 | 2023-02-14 | Firefox 110 | Firefox 102.8
> 2023-03-09 | 2023-03-13 | Firefox 113 | Firefox 112 | 2023-03-14 | Firefox 111 | Firefox 102.9
> Q2 2023 | 2023-04-06 | 2023-04-10 | Firefox 114 | Firefox 113 | 2023-04-11 | Firefox 112 | Firefox 102.10
> 2023-05-04 | 2023-05-08 | Firefox 115 | Firefox 114 | 2023-05-09 | Firefox 113 | Firefox 102.11
> 2023-06-01 | 2023-06-05 | Firefox 116 | Firefox 115 | 2023-06-06 | Firefox 114 | Firefox 102.12
> Q3 2023 | 2023-06-29 | 2023-07-03 | Firefox 117 | Firefox 116 | 2023-07-04 | Firefox 115 | Firefox 102.13; 115.0
> 2023-07-27 | 2023-07-31 | Firefox 118 | Firefox 117 | 2023-08-01 | Firefox 116 | Firefox 102.14; 115.1
> 2023-08-24 | 2023-08-28 | Firefox 119 | Firefox 118 | 2023-08-29 | Firefox 117 | Firefox 102.15; 115.2
> 2023-09-21 | 2023-09-25 | Firefox 120 | Firefox 119 | 2023-09-26 | Firefox 118 | Firefox 115.3
> Q4 2023 | 2023-10-19 | 2023-10-23 | Firefox 121 | Firefox 120 | 2023-10-24 | Firefox 119 | Firefox 115.4
> 2023-11-16 | 2023-11-20 | Firefox 122 | Firefox 121 | 2023-11-21 | Firefox 120 | Firefox 115.5
> 2023-12-14 | 2023-12-18 | Firefox 123 | Firefox 122 | 2023-12-19 | Firefox 121 | Firefox 115.6

..I guess, we can expect the unexpected again around November 2023.

**Comment by Maikuolan** [comment]
Fixed (for now). :-)

**Comment by Maikuolan** [comment]
*Related: #413.*
