### ISSUE TITLE
QUESTION: ASN Lookup in aux rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#428]
Hi,

How this ASN lookup works? Where does it get the information?

**Comment by Maikuolan** [comment]
Auxiliary rules doesn't perform any additional external lookups, and only leverages data already available to CIDRAM by the time the auxiliary rules are being processed. For the ASN lookup or country code lookup fields to be effective with auxiliary rules, those fields will need to be already populated by a module capable of looking up ASNs and country codes (e.g., the IP-API module or the BGPView module). If at least one of those two modules are enabled, those fields should be populated, and accessible to the auxiliary rules. If neither of the modules are enabled, the fields will remain at their default values, and basically not be useful at all for the auxiliary rules.

**Comment by eurobank** [comment]
Ok, got it. 

What do we put in the form, just the number or  AS prefix and the number? And what compare type?

**Comment by Maikuolan** [comment]
> just the number or AS prefix and the number?

Just the number.

> And what compare type?

In theory, any comparison type should work fine. But, given that ASNs, unlike like user agents, referrers, etc, tend to not really permutate (i.e., requests coming from the same ASN, should always show the same ASN number, whereas an attacker might mess around with their user agent, change a letter or word here or there, in order to attempt to avoid being blocked, and a different ASN number would mean something is coming from a different ASN), we probably don't have much need, or any real use-case for using patterns, regular expressions, wildcards, etc to match against ASNs, so.. theory aside, in practice, it's probably going to be better to just use direct-string comparison, I think.

Potentially some miniscule performance improvement that way, too (likely in the realms of nanoseconds, so effectively unmeasurably small, and not generally worth worrying about, but in the absence of any cost, use-case, or reasons to the contrary, may as well still take it)

**Comment by eurobank** [comment]
@Maikuolan One more question.

When multiple conditions are set, what compare type should be used?

For example if we have one ASN number and also a hostname (for example: `*your-server.de`) ?

Windows wildcards probably but how the numbers are set? Just the numbers? Or `*number*` ?

**Comment by Maikuolan** [comment]
> For example if we have one ASN number and also a hostname (for example: `*your-server.de`) ?

If any of the conditions need Windows-style wildcards, I'd just set it to that. Other conditions, which doesn't need any patterns or wildcards (i.e., where we'd normally use direct string comparison), should still produce the same results when matched by Windows-style wildcards, so, it should be safe to set it to that.

> Windows wildcards probably but how the numbers are set? Just the numbers? Or `*number*` ?

Better to set just the numbers. Using wildcards with ASNs could pose a false positive risk. If, for example, you wanted to block AS701 (Verizon Business), so set something like `*701*`, you'd also catch requests from AS7018 (AT&T Services, Inc), because the number "701" can be found in the number "7018". Dropping the wildcards will effectively have CIDRAM treat the condition the same as if it were using direct string comparison, and so, should avoid those particular kinds of false positives.
