### ISSUE TITLE
Request: Aux Rules CONDITION met in log

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#430]
If would be great if when a block occurs for an Aux rule, to log also the condition met (if multiple conditions are set). So we know which of all the conditions met for the block.

**Comment by Maikuolan** [comment]
I'm working on this currently.

The below block event is totally faked, something I generated by requesting a protected page at my local dev copy, faking the IP address to an arbitrary Russian address by manually setting `$_SERVER['REMOTE_ADDR']`, for the purpose of testing the changes I'm currently working on, with the reconstructed URI munged a bit.

Looking at the below block event, if something similar were to appear in the logs at your end, would it be easy enough to understand and interpret, with the way that the auxiliary rule conditions which CIDRAM has attempted to check are listed and marked as either "satisfied" or "not satisfied"?

```
ID: 1678807159-313707-1268576800
Script version: CIDRAM v3.1.1
Date/Time: Tue, 14 Mar 2023 23:19:19 +0800
IP address: 95.152.41.131
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69
Signatures count: 3
Signatures reference: 95.152.0.0/18, projecthoneypot.php:L190, auxiliary.yml:AS block test
Why blocked: Spam risk ("PJSC Rostelecom", L5700:F2, [RU]), Project Honeypot Lookup, AS block test!
Reconstructed URI: hxxp://localhost/CIDRAM-v3/xxx.php
Infractions: 4
ASN lookup: 12389
Country code lookup: RU
Request method: GET
Conditions inspection: ↓
- Non-strict – Profile (Comment Spammer) ≠ Blacklisted: Satisfied.
- Non-strict – Profile (Domestic ISP) ≠ Blacklisted: Satisfied.
- Non-strict – Profile (Spam) ≠ Blacklisted: Satisfied.
- Non-strict – Profile (Suspicious) ≠ Blacklisted: Satisfied.
- Non-strict – Profile (Tor endpoints here) ≠ Blacklisted: Satisfied.
- Non-strict – Profile (Comment Spammer) ≠ Redlisted: Satisfied.
- Non-strict – Profile (Domestic ISP) ≠ Redlisted: Satisfied.
- Non-strict – Profile (Spam) ≠ Redlisted: Satisfied.
- Non-strict – Profile (Suspicious) ≠ Redlisted: Satisfied.
- Non-strict – Profile (Tor endpoints here) ≠ Redlisted: Satisfied.
- Non-strict – Profile (Comment Spammer) = Amateur Radio: Not satisfied.
- Non-strict – Profile (Domestic ISP) = Amateur Radio: Not satisfied.
- Non-strict – Profile (Spam) = Amateur Radio: Not satisfied.
- Non-strict – Profile (Suspicious) = Amateur Radio: Not satisfied.
- Non-strict – Profile (Tor endpoints here) = Amateur Radio: Not satisfied.
- Non-strict – Profile (Comment Spammer) = Domestic ISP: Not satisfied.
- Non-strict – Profile (Domestic ISP) = Domestic ISP: Satisfied.
- Mark non-strict for use with CAPTCHA – Signatures count (2) ≤ 1: Not satisfied.
- Don't block search engines – Verified identity () = ~^.+$~: Not satisfied.
- Don't block search engines – Profile (Comment Spammer) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- Don't block search engines – Profile (Domestic ISP) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- Don't block search engines – Profile (Non-strict) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- Don't block search engines – Profile (Spam) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- Don't block search engines – Profile (Suspicious) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- Don't block search engines – Profile (Tor endpoints here) = ~^Search Engine(?: Spider)?$~: Not satisfied.
- AS block test – ASN lookup (12389) = 24940: Not satisfied.
- AS block test – ASN lookup (12389) = 213230: Not satisfied.
- AS block test – ASN lookup (12389) = 14618: Not satisfied.
- AS block test – ASN lookup (12389) = 12389: Satisfied.
Hostname: host-95-152-41-131.dsl.sura.ru
CAPTCHA State: Disabled.
```

In my own opinion, it's kind of somewhat bloaty, and in its current form, isn't something I'd want to leave turned on *permanently*, but as a *temporary* measure to debug tricky problems related to auxiliary rules, it *does* show *exactly* which conditions are and aren't being matched, where, in which specific order the matches occur, as well as, by omission, which conditions aren't being checked at all. So, bloaty, but functional.

I *could* reduce the bloat by sacrificing the verbosity a bit (e.g., by showing the rule name only when it changes instead of for each condition, by maybe compressing fields like "profile", where multiple values to be checked can exist and thus can require multiple checks against the same condition, etc; though, as well as reducing bloat, compressing values may also somewhat reduce readability, or may result in it being less obvious which specific value is being matched in the event that some are matched while others aren't). Or not worth worrying about (the bloat)? What do you reckon?

**Comment by eurobank** [comment]
Yes, it is too much. It could be optionally enabled? 

For example Level 1 and Level 2, Level 1 to be as it is now and Level 2 something like the above?

**Comment by Maikuolan** [comment]
> Yes, it is too much. It could be optionally enabled?

I've set it as disabled by default, optionally enableable via the fields directive at the configuration. :+1:

Existing work done has now been committed and pushed. Not finished yet though; More work still needed (i.e., getting rid of the bloat, improving appearing/readability/etc).

**Comment by eurobank** [comment]
One small request. When something IS satisfied, please make the "Satisfied" RED.

**Comment by Maikuolan** [comment]
> One small request. When something IS satisfied, please make the "Satisfied" RED.

Done. :-)
