### ISSUE TITLE
Trying to get Cronable to work

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#432]
Cronable worked fine with v2, but with v3 it doesn't and I think it's due to the now used entrypoint file. I had originally pointed the path in the Cronable file directly to the CIDRAM vault outside of public_html but then thought the path in Cronable had to point to the entrypoint file **inside** public_html. So I changed the path in Cronable to reflect that and when the cron fired off I got an email with a CIDRAM block page (first I ever saw something like that before) coded in non-parsed HTML. Upon looking at the why reason for the block in the non-parsed HTML in this email, Cronable was blocked due to the HTTP version and the UA. So I said, "ah ha! I'll just whitelist the Cronable UA in the auxiliary rules and all will be fine." To my dismay that still didn't fix the issue. Still getting emails indicating an error with Cronable. Actually two different types of errors depending on the commands used for the crontab. 

`php -f ~/Cronable.php` Yields an email that says: 
>"[CIDRAM] This should not be accessed directly."

And if I use this command:

`/opt/cpanel/ea-php73/root/usr/bin/php -f ~/Cronable.php` Yields an email that says: 
>"Cronable v1.2.2
>Time: Tue, 07 Mar 2023 03:47:01 +0000
>
>===
An error occurred while attempting to update at [CIDRAM@/home/username/public_html/entrypoint.php]. :-(
>
>===
>
>Time: Mon, 06 Mar 2023 20:47:02 -0700"
>
>
This same email is sent if I change the path in the Cronable file to access the vault directly without the entrypoint file:
>
> "Cronable v1.2.2
>Time: Tue, 07 Mar 2023 03:06:03 +0000
>
>===
An error occurred while attempting to update at [CIDRAM@/cidram/vault/loader.php]. :-(
>
>===
>
>Time: Tue, 07 Mar 2023 03:06:03 +0000"
>

What can be done to solve this? Thanks.

**Comment by Maikuolan** [comment]
Might be related to Maikuolan/Cronable#9, maybe? Is the file pointed to by Cronable definitely the front-end entrypoint for CIDRAM v3?

**Comment by 737simpilot** [comment]
Ah, I failed to see the update. I'll give that a shot soon and let you know. 

Question: what is the difference between

`(new \CIDRAM\CIDRAM\FrontEnd())->view();`

and

`(new \CIDRAM\CIDRAM\Core())->protect();`

I don't know PHP. It's looking like protect doesn't work but view does in reference [here](https://github.com/Maikuolan/Cronable/issues/9#issuecomment-1416726868).

**Comment by Maikuolan** [comment]
![viewprotect](https://user-images.githubusercontent.com/12571108/223411914-08940a0e-20e7-4313-8b0f-943c5e3ae86b.png)

The "protect" method is what tells CIDRAM that it needs to "protect" the page where that method is called (basically, in order to actually block something, you'll need to call "protect").

The "view" method is what tells CIDRAM that you're wanting to "view" a front-end page, and that it needs to generate the output necessary for viewing a front-end page.

You *can* use both *together*, and you *can* use *either* of them *separately*. Whether you use them together or separately is entirely up to you.

For clarity: In PHP terminology, a "method" and a "function" are very similar. If a "function" were to be written inside of a "class", and belonged to that "class", it would be described as a "method". Inversely, if a "method" were to be written *outside* of a "class", belonging to nothing beyond the global namespace, it would most likely be described as a "function". There are also some other relevant terms, like "procedure", "closure", etc.. but they're not really related to the question asked, so we can come back to them later if needed.

The "Core" class defines the core functionality for CIDRAM v3. Strictly speaking, without it, nothing will work. The "FrontEnd" class defines most of the front-end functionality for CIDRAM v3 (with most of the various other PHP files under `vault/CIDRAM/CIDRAM` being "traits" which belong to the front-end; I can get into that later if needed, but as to what, exactly, a "trait" is, doesn't really affect the question asked either).

The reason I wrote "strictly speaking": The "FrontEnd" class directly "extends" the "Core" class (basically, "extending" a class means to inherit the entirety of that class, all its functionality and so on, into some other class, without the need to rewrite or duplicate its code, because PHP will automatically treat the code in question as belonging to both classes). That means that anything that the "Core" class can do, the "FrontEnd" class can *also* do, which means that the "FrontEnd" class supports both the "protect" method and the "view" method, and so, can be used to tell CIDRAM to protect a website, as well as be used to tell CIDRAM to display the front-end. Conversely though, the "Core" class does *not* "extend" the "FrontEnd" class, and so, can *not*, in its own right, be used to display the front-end.

A website which doesn't want to ever display the front-end might decide to use only the "Core" class, as it may be a little more performant in some cases due to not needing to load all the code related to the front-end into PHP's memory. A website which *does* want to display the front-end, however, would be better to be the "FrontEnd" class. (Don't go deleting any of the physical files related to any of the classes though, because the "FrontEnd" class is only *able* to "extend" the "Core" class, because the "Core" class exists in the first place; even if it isn't actually used directly, if it gets deleted, everything will break, due to that the remaining classes would be trying to "extend" from something which doesn't exist anymore).

**Comment by Maikuolan** [comment]
(On that note, it's also possible that "protect" might be what's blocking Cronable, too. If it's possible to create a new front-end entrypoint containing *only* the call to the "view" method, i.e., without running CIDRAM's own protections on said entrypoint, that *might* help solve the problem. Would need to test it out to be sure though).

**Comment by 737simpilot** [comment]
Thanks for the explanation, Caleb, but I'm still a little lost on all that. LOL! I get the jest though. 

I have now solved the Cronable issue and everything is working as it should. 

Steps I took:

1) Updated with the new Cronable code.

2) Changed the path in Cronable to the entrypoint file.

3) Had to create another entrypoint file just for Cronable, and that code looks like this:

`<?php
require_once '/home/username/cidram/vault/loader.php';
$CIDRAM = new \CIDRAM\CIDRAM\FrontEnd();
$CIDRAM->view();`

My crontab command looks like this: 

`/opt/cpanel/ea-php73/root/usr/bin/php -f  ~/Cronable.php`

I'll probably have to change it when the PHP version changes from 7.3.* I'm sure `php -f  ~/Cronable.php` will work too.
