### ISSUE TITLE
false positive - iMessage

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#433]
as per this issue https://github.com/CIDRAM/CIDRAM/issues/263

I'm still getting false positives with

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0 »

**Comment by mikeruss1** [comment]
My site gets these and I looked at it a while ago and not able to decide what it is. It comes immediately after a valid page request from the same user IP address. My guess is its some process on the device which is sending a page request labelled as coming from Twitter, which actually is not. Maybe its Twitter, or a Twitter addon, recording what the user is doing?

**Comment by eurobank** [comment]
Yes, probably some addon.

**Comment by Maikuolan** [comment]
Currently, when testing that user agent against my dev copy of CIDRAM at the IP test page, I get this:

```
Yes – Outdated browser (S), Fake Twitterbot
++<Blocked Negative>
```

Given that the user agent in question *does* match the official user agent used by Twitterbot, despite the requesting entity in this case being iMessage, I'm kind of inclined to leave it alone as a `wontfix`, because the only way realistically that I can see resolving this from my end would be to just strip out Twitterbot verification entirely in order to avoid blocking iMessage (which has, for whatever reason, chosen to masquerade with Twitterbot's user agent).

That said, as of v3, it's possible to selectively disable verification of specific platforms/crawlers/etc via the CIDRAM configuration (`verification➡social_media`), so, for those that need to let iMessage through, it might be worth just disabling Twitterbot verification at their installation:

![iMessage](https://user-images.githubusercontent.com/12571108/225965597-2bcb3348-be24-4f17-a05b-8cf54da7dbde.png)

As for the "outdated browser" message, that's due to BOBUAM's outdated browser checks (specifically, the checks for Safari). Setting the minimum major version for Safari (`bobuam➡safari`) to something greater than 0 but less than 9 should resolve that particular block (though would also allow outdated versions of Safari through, in case that's an issue at all). Of course, those that aren't using BOBUAM at all won't need to worry about that.

**Comment by mikeruss1** [comment]
as an experiment I am allowing this through via an aux rule, signature count must also be 1. So far nothing unexpected has resulted.

**Comment by bigalownz** [comment]
how do i add it to aux rule ?

every time i add "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0"

to the aux rules it keeps saving as >
or just Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4

**Comment by mikeruss1** [comment]
try it with just  Facebot Twitterbot/1.0

with leading and trailing asterisks, and Use Windows-style wildcards to test the conditions

**Comment by Maikuolan** [comment]
Seems to be a problem specifically with how the YAML handler deals with sequences which terminate with a folded scalar. Looking into the problem now.

**Comment by Maikuolan** [comment]
Should work correctly now. :-)
