### ISSUE TITLE
Aux Rules Issue - Blocking without RULE

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#434]
Today this attracted my attention:

ID: 1678263409-565496-1922368440 »
Date/Time: Wed, 08 Mar 2023 10:16:49 +0200 »
IP address: 95.152.41.131 »
Query: page=contact »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: ASN China! »

Infractions: 2 »
Country code lookup: RU »
Request method: GET »
Hostname: host-95-152-41-131.dsl.sura.ru »

**Blocked from China ASN but RU hostname.**

https://cleantalk.org/blacklists/95.152.41.131

So i looked maybe for some error of mine for  ASN 24612 in the aux rules:
```

The reason given to the user when blocked:
ASN China
HTTP status code override:
403 Forbidden
If the following conditions are met, block the request.
ASN lookup = 4134
ASN lookup = 4837
ASN lookup = 139220
ASN lookup = 12389
ASN lookup = 8359
ASN lookup = 132203
ASN lookup = 45090
ASN lookup = 17964
Use direct string comparison to test the conditions.
```
There is no such ASN in China ASN of mine, or anywhere else in the rules.

![Screenshot](https://user-images.githubusercontent.com/4467158/223662256-879f928d-a08c-489e-a0c1-20abc243cf49.png)

**Comment by Maikuolan** [comment]
[Cleantalk says AS24612](https://cleantalk.org/blacklists/95.152.41.131).
[Hurricane Electric says AS12389](https://bgp.he.net/ip/95.152.41.131).
[BGPView says AS12389](https://bgpview.io/ip/95.152.41.131).
[IP-API says AS12389](https://ip-api.com/#95.152.41.131).

So that's 3/4 of those saying AS12389, and just Cleantalk saying AS24612. Maybe Cleantalk is serving from incorrect or outdated BGP records?

That said though, regardless of which of the two ASNs is correct, both of them appear to belong to Rostelecom, which is a Russian ISP, so either way, still not a Chinese address.

**Comment by eurobank** [comment]
Ok, so what is the verdict?

**Comment by Maikuolan** [comment]
If the intention of that rule is just to block Chinese ASNs only, then I'd recommend removing the check for AS12389 from that rule (due to that it belongs to a Russian ISP). Aside from that, I don't think there's any other problems with the rule in question, any bugs, problems in the code, etc, AFAICT.

(Haven't properly checked through the other related issues yet though. I'll get to those shortly).
