### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#437]
certainly old, but looks valid  ?

User agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0 
Signatures count: 1 
Signatures reference: bobuam.php:L138 
Why blocked: Suspected bot or scraper probe! 

https://user-agents.net/string/mozilla-5-0-windows-nt-5-1-rv-52-0-gecko-20100101-firefox-52-0

**Comment by Maikuolan** [comment]
The user agent is valid, but also pretty old. "Windows NT 5.1" = Windows XP. And Firefox v52 was released March 2017, replaced by Firefox v53 April 2017. Any idea whether the IP address connected to that block event belonged to something legitimate, like an ISP, or something more like a server farm or webhosting service? Even if it's valid, being that old, there's a good chance that what the user agent is claiming the requesting entity to be, might not be what it actually is.

**Comment by Maikuolan** [comment]
*References:*
*https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox*
*https://en.wikipedia.org/wiki/Firefox_version_history#Firefox_52_through_59*
*https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions*

**Comment by mikeruss1** [comment]
looks OK to me, following a link from a hobby forum.
I do have a few active users with old versions of Firefox which is why I let them through.
We should fix it as we are likely rejecting other versions.

**Comment by mikeruss1** [comment]
this is another one that should be OK. There are recent versions of Waterfox
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2 
Signatures count: 1 
Signatures reference: bobuam.php:L65 
Why blocked: Malformed UA (FF)!

**Comment by 737simpilot** [comment]
The purpose of **bobuam** is to block old UAs, not allow them. If you want users with an old outdated OS and browser that may be infected to connect to your site, then drop **bobuam's** option to block old UAs. Simple as that. 

Waterfox on the other hand is a niche browser, so that would need to be bypassed with a scalpel based on its version history...

**Comment by mikeruss1** [comment]
bit more complicated than that, bobuam is set to reject anything older than FF47, this is FF52

**Comment by mikeruss1** [comment]
could this be fixed when you can pl ?
User agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
the user needs to do CAPTCHA every visit

**Comment by Maikuolan** [comment]
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2

Looks like that user agent is triggering BOBUAM's signature for malformed Firefox UAs due to the Firefox and rv version tokens not matching (`55.0` vs `55.2.2`).

Although a number of much older versions look like they're affected by that problem, most of the more recent **[versions of Waterfox's user agent string](https://explore.whatismybrowser.com/useragents/explore/software_name/waterfox/)** don't seem to be affected by that problem at at all:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 Waterfox/2022.11
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 Waterfox/2022.04
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 Waterfox/2022.04
```

Any chance of that particular affected user being able to update their browser to a more current version? Reworking the signature in question without severely reducing its effectiveness looks like it might be a little difficult, the way it is at the moment, but looks likely to be unnecessary anyway for all current and future versions moving forward.

(Will address the other user agents and other concerns attached to the issue as separate replies, to reduce the potential for confusion about context).

**Comment by Maikuolan** [comment]
On a side-note: If we wanted a broad-stroke bypass for Waterfox entirely, we *could* simply implement a bypass via an auxiliary rule, having that rule check for the presence of "Waterfox" in the user agent string, as well as checking for the presence of the "Malformed UA" message in the block reason for the current pending request (in order to limit the bypass to only bypassing affected requests, and not simply bypassing any request which cites that in their user agent, regardless of reason, in case they might be otherwise blocked for some other, unrelated reason). That would definitely 100% solve the problem for the particular affected user. However, I'd be wary of mainlining such a bypass, as it would effectively allow anyone, or any bot, to use any kind of malformed UA they want, as long as they cite "Waterfox" somewhere in their user agent, making the signature basically useless. It might be necessary approach though, if the affected user isn't able, or isn't willing to update their browser to a current version.

**Comment by Maikuolan** [comment]
Give these a try.

This auxiliary rule bypass will bypass that exact, specific Windows XP user agent, when blocked for that specific reason. It won't affect any even slightly different user agents.
```YAML
Bypass for Firefox on Windows XP:
 Method: "Auto"
 Logic: "All"
 Bypass:
  If matches:
   UA:
    - "Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0"
   WhyReason:
    - "*Suspected bot or scraper probe*"
```

This auxiliary rule bypass will bypass that exact, specific version of Waterfox, when blocked for that specific reason. It may be preferable to the below if the user is unlikely to ever update their browser. It won't affect any other versions, or any other user agents. Try either this auxiilary rule, or the following auxiliary rule, but not both, else you'll risk potentially double-bypassing some requests, creating a "get out of jail free" scenario.
```YAML
Bypass for Waterfox 55.2.2:
 Method: "Auto"
 Logic: "All"
 Bypass:
  If matches:
   UA:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2"
   WhyReason:
    - "*Malformed UA (FF)*"
```

This auxiliary rule bypass will bypass *any* version of Waterfox, when blocked for that specific reason. It may be preferable to the above if there are multiple users on older versions of Waterfox, or if the affected user is amenable to updating their browser at some point. It will, however, unfortunately, allow anyone or any bot to cite a malformed UA of their choosing, of any kind, as long as it cites Waterfox somewhere in the user agent, given that it works by checking for the presence of that token. Try either this auxiilary rule, or the above auxiliary rule, but not both, else you'll risk potentially double-bypassing some requests, creating a "get out of jail free" scenario.
```YAML
Bypass for Waterfox (any version):
 Method: "WinEx"
 Logic: "Any"
 Bypass:
  If matches:
   UA:
    - "*Waterfox*"
   WhyReason:
    - "*Malformed UA (FF)*"
```
