### ISSUE TITLE
Aux rules log changes

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#438]
Apparently some changed code recently, adds some information about aux rules in the logs. But that information doesn't help, it is more or less the same as in "why blocked", for example:

Signatures reference: auxiliary.yml:GLOBAL HostNames_2 »

Why blocked: GLOBAL HostNames_2! »

**Comment by Maikuolan** [comment]
I pushed that change so that the signatures reference for auxiliary rules could cite something other than "Core" (which was what was cited before), in order to be a little more distinct from other mechanisms (e.g., search engine verification, rate limiting, etc) which were likewise citing "Core" when they blocked something. It mightn't help with identifying specific conditions responsible for the block, but it does help in other ways (e.g., eliminating completely different mechanisms as potential causes for a block event).

In terms of being able to identify specific conditions responsible: I'm still trying to figure out the best way to do that without exposing too much information to any would-be attackers. I figure that if I were to include the conditions verbatim directly into the signatures reference, along with the type of information the condition relates to, that could be used by a would-be attacker to work around the rules themselves.

Not too concerned in the case of hostnames or IP addresses, given that such things typically aren't so easy to change anyway, beyond using VPNs, proxies, etc, which is something most would-be attackers, serious or otherwise, are likely try anyway, regardless of whether any information is exposed, so there's limited value in trying too hard to hide it anyway. As for anything blocked by the default signature files or by any of the available modules, any serious would-be attacker, upon seeing that "CIDRAM" is the thing responsible for blocking them, could easily just look it up to find out what it is, then analyse the source code, and figure out how to work around the signatures or modules in question from that anyway, so, although there's no reason to make it easier than necessary, there's also limited value in worrying too much about it.

Auxiliary rules, on the other hand, I'm not sure I want to expose more than necessary, due to that whoever installs/manages a CIDRAM installation is typically the one who creates/maintains the auxiliary rules at that installation, and so, will likely often be very specific to the websites that installation protects rather than generic (so, could potentially contain something sensitive about the websites in question), and aren't something that could be directly analysed by a would-be attacker simply by looking at available source code (given that it won't be found in any upstream source code, given that it's specific to the said websites), and so *could* be at least *somewhat* protected in that regard.

Sure, it won't totally prevent a would-be attacker from simply rotating through all potential data points until they find some combination that allows them through, but I figure there's no reason to make things *easier* for them, either.

I had considered the idea of maybe generating some unique code for each condition of each rule, to act as a kind of substitute for the conditions themselves as something to cite as a signature reference. It could work, but would also likely require CIDRAM users to go back and forth between their logs and their auxiliary rules, in order to cross-reference said unique codes against log entries, in order to be able to know which specific conditions are responsible for block events, which could potentially become a little tedious, and I anticipate someone eventually asking here, *"Isn't there an easier way to do this?"*, or *"What's that funny code at the end of the signatures reference actually mean?"*, so I'm not entirely sure whether that's necessarily the best approach.

Open to ideas if anyone has any.

**Comment by eurobank** [comment]
Right, your concern about exposing information to attacks is correct. Personally i only show a simple "you are blocked" page, or sometimes a 403 page copied from LiteSpeed server 403 page, and absolutelly nothing else. 

If i wasn't using CIDRAM for multiple sites, i would also like to show some email they can use (outside CIDRAM) to report a wrong block. Or some form. But since multiple (6) different sites are served by CIDRAM, i can't.

I don't really understand why CIDRAM must give ANY details to the attackers.

**Comment by eurobank** [comment]
But, what the displayed info to blocked visitors has to do with details in admin logs?

**Comment by Maikuolan** [comment]
> But, what the displayed info to blocked visitors has to do with details in admin logs?

Currently, with all existing supported fields, whether to include them on the access denied page and whether to include them in the logs is configurable (via `general➡fields`), and users might configure it in such a way that any fields containing such sensitive information could be unknowingly exposed on the access denied page. But, thinking on it a bit more over the past few hours.. I could always just create a new field, maybe? And have said new field implemented in such a way that it won't ever be displayed on the access denied page, and can't be configured to do so, only ever appearing in logs and nowhere else.

Given that the `general➡fields` configuration directive was introduced since v3 (replacing the configuration directives from v2 and earlier which controlled which fields to display or to omit from the access denied page and logs; introduced due to limitations with existing configuration directives, and because there were far too many of them for something which could be achieved with just one such configuration directive), and I don't particularly want to be knowingly implementing directives into old major versions which won't continue through to current major versions (which I would need to do if I was to implement any new configurable fields and keep the relevant configuration aligned to how things worked with previous major versions), if I was to implement such a new field, if possible, I don't think I'd want to backport it to v2 and earlier (so, keeping it as something for v3 and onward).

But, in theory, if was to introduce a new field which we knew in advance would never appear on the access denied page, it should be okay to use it to describe conditions verbatim affecting the outcome of the block event.

What do you reckon?

**Comment by Maikuolan** [comment]
(For further clarity: For some websites, due to the workflow at those websites, how false positives are managed and etc, at those websites, displaying a lot of information at the access denied page can sometimes be important, e.g., if logging is disabled entirely at the CIDRAM installations for those websites for whatever reason, maybe due to permissions problems, conflicts with anti-virus software, etc, or if the CIDRAM user generally has no other way to obtain the information necessary to deal with false positives, as a last resort, they can asked the people which are mistakenly blocked to copy/paste the information directly from the access denied page to an email, contact form, etc, to send as needed in order to have false positives dealt with. I have encountered a few such actual cases in the past, so, from experience, I know such cases do exist, and that's the main reason for allowing information to be displayed at the access denied page. Though, such actual cases where someone legitimately can't enable logging for some reason, I think, should be *exceedingly* rare, plus, relying on blocked users to always send the needed information usually isn't a great idea due to that non-technical people and blocked users in general tend to be inherently unreliable when it comes to including all relevant needed information, so I wouldn't generally recommend it, and would instead recommend doing as you do, i.e., reducing as much as possible the information displayed when blocked, thoroughly enabling logging, and when dealing with false positives, utilising the logs. I've also seen cases where there've been to-and-fro emails concerning false positives where there were sometimes ~6, ~7 or more emails exchanged before the correct necessary information was exchanged, with it being very slow to resolve as a result. In short: The option to display information at the access denied page needs to be there in the configuration for CIDRAM users to take advantage of for when needed, but in most cases, it would be better to not display that information).

**Comment by eurobank** [comment]
@Maikuolan I'm not an expert in all that, i strongly believe that YOU can decide what to do. Having said that, what you propose seems ok. But this is a minor issue, so do not spend time for it. Maybe in the future you can think about it.

Still, i don't (generally speaking) understand why ANY information should be given to the visitors/attackers.

**Comment by eurobank** [comment]
@Maikuolan I can understand some (few) situations that extended info could be provided in case of a block. What you could do, is make that totally optional and not default. I mean if some webmaster really want to do that, he will have to enable it himself.
