### ISSUE TITLE
Aux rules question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#443]
is it possible to code an "or" rule, as in ..

Why Blocked = *xxx* or *yyy*

there is an "or" available for the rule as a whole, but its not suitable if there are several lines in the rule

**Comment by 737simpilot** [comment]
You're probably needing to use regex then...

**Comment by Maikuolan** [comment]
I would just use regex for that, too. :-)

(Or, if it's some super long, super complicated rule, maybe split it up into multiple rules which profile the request, then leverage those profiles to perform the final intended action; i.e., a multi-tiered rule).

TBH, if we could switch between using and/or and other matching logic at the condition-level instead of just at the rule-level, I foresee a *lot* of potential confusion happening when it comes to debugging any affected rules whenever something goes wrong, trying to map the overall process in our heads for the rules in question to figure out whether it's doing what we want, or for when trying to create new such things. I'm not quite entirely sure how I would present that information to users at the interface, either.

Splitting the rules up a bit into multiple tiers might result in a somewhat chunkier-looking set of rules, but would also be easier to read and debug, and to see exactly what's going on, I think. That, or just using regex.

At the very least, if we screw up our regexes for any particular rule, it should error out at the IP testing page when testing against auxiliary rules, so we can pick up such errors at that point, at least.
