### ISSUE TITLE
Question about geo caching

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#445]
Both in ip-api and bgpview, there is a stray 429 in the cache. Is that something normal? Not an IP.

![Screenshot](https://user-images.githubusercontent.com/4467158/226548499-572dd289-940c-4c35-9cb2-df958f1b9b5f.png)

**Comment by Maikuolan** [comment]
(Delayed yesterday due to unexpected offline commitments).

Typically, that "429" appears when the lookup service has rate limited the server which is sending the lookup requests (named to reflect the HTTP response code "429 Too Many Requests"), but can also appear if CIDRAM receives an HTTP response code (e.g., "403 Forbidden", "500 Internal Server Error", "503 Service Unavailable", etc) from the lookup service which differs from the response code it expects to normally receive ("200 OK").

CIDRAM won't send any additional requests to the lookup service as long as a "429" exists in the cache (in order to prevent such requests potentially being an inadvertent cause of the website's own IP address being banned or blacklisted by the lookup service).

By default, when the BGPView or IP-API module generates and caches a "429", the expiry for such cache entries is set to 4 hours (so, lookups should normally resume not later than 4 hours after such an event occurs). However, I'll still need to implement some further debugging mechanisms here, because, even if we know when these 429s should normally expire, until we're 100% certain about the initial cause of the problem (i.e., whether it's truly a case of the services rate limiting your website's IP address, or something else, like the requests failing to be sent entirely due to some kind of server problem, maybe some kind of outbound firewall implemented by the webhosting provider, or something else, thus resulting in some kind of unrelated response code which could likewise cause the 429 cache entry to be generated), we can't guarantee that they won't just be immediately regenerated again within a few mere requests of expiring, thus the problem remaining.

Got a few other things to get sorted out this afternoon, but as soon as that's done, I plan to work on the new debugging mechanisms.

**Comment by eurobank** [comment]
Then that is the issue i'm facing. After an 429 appears, no lookups are happening and no ASN is blocked.

I don't think the error in coming from ap-api or bgpview servers. Because when i delete it manually, the service starts again to do the lookups normally.

No problem, no rush. Just trying to help in the debug of this strange ASN aux rules that stop after a while.

**Comment by eurobank** [comment]
Continued here:

https://github.com/CIDRAM/CIDRAM/issues/429

**Comment by Maikuolan** [comment]
Debugging mechanism has been implemented. :-)

After updating, there should be a new configuration directive available, `logging➡outbound_request_log`.

If you populate that with a filename, then clear the cache, and await some more requests to arrive where lookups would normally occur, the results of those outbound requests should be logged at that file, and that should tell us a bit more about what's going on with those outbound requests.
