### ISSUE TITLE
Another old but valid UA

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#446]
User agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 AOLShield/52.4.2
 Signatures count: 1 
Signatures reference: bobuam.php:L138 
Why blocked: Suspected bot or scraper probe!

the referrer was AOL as well so looks OK

**Comment by Maikuolan** [comment]
Hadn't heard of AOL shield before, so I googled it just now. According to [Wikipedia](https://en.wikipedia.org/wiki/AOL_Active_Virus_Shield), it was an anti-virus utility produced by AOL which hasn't been updated nor officially available since 2007 (and 15 years is a *very* long time to be outdated for an anti-virus utility, assuming what I read there is correct, and assuming I'm understanding that user agent correctly).

Almost nothing comes up at Google and elsewhere when searching for the entirety of that user agent verbatim, and none of it seems particularly useful nor conclusive.

Have you checked the IP address associated with that request, whether it comes from an ISP, from a cloud service, whether from a known user or somewhere/someone unknown, etc?

**Comment by mikeruss1** [comment]
I suspect its OK, but never seen before. Suggest forget it, if it comes back I will consider an aux rule. Not worth troubling you I think.

**Comment by Maikuolan** [comment]
*Marking as resolved.*
