### ISSUE TITLE
Infractions Inconsistencies

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#448]
As you see there is a shift in the number of Infractions for the same IP. from 42 then we see 16. 

The newer is a DIFFERNT domain. Does it matter?

(sort descending)

`ID: 1680177812-375176-5792916893 »
Date/Time: Thu, 30 Mar 2023 15:03:32 +0300 »
IP address: 176.58.126.187
Query: rchk »
User agent: Mozilla/5.0 (Linux; Android 11; M2010J19SI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 »
Signatures count: 3 »
Signatures reference: auxiliary.yml:HostNames_2, auxiliary.yml:ASN - Linode Akamai »
Why blocked: Banned, HostNames_2, ASN - Linode Akamai! »
Reconstructed URI: DOMAIN B/wp-content/plugins/ioptimization/IOptimize.php?rchk »
Infractions: 16 »
Country code lookup: GB »
Request method: GET »
Hostname: 176-58-126-187.ip.linodeusercontent.com »

ID: 1680174917-652003-1069753943 »
Date/Time: Thu, 30 Mar 2023 14:15:17 +0300 »
IP address: 176.58.126.187
User agent: Mozilla/5.0 (Linux; Android 11; M2010J19SI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 »
Signatures count: 3 »
Signatures reference: auxiliary.yml:HostNames_2, auxiliary.yml:ASN - Linode Akamai »
Why blocked: Banned, HostNames_2, ASN - Linode Akamai! »
Reconstructed URI: DOMAIN A/wp-content/plugins/ccx/index.php »
Infractions: 42 »
Country code lookup: GB »
Request method: GET »
Hostname: 176-58-126-187.ip.linodeusercontent.com »

ID: 1680174916-867806-0285551959 »
Date/Time: Thu, 30 Mar 2023 14:15:16 +0300 »
IP address: 176.58.126.187
Query: u »
User agent: Mozilla/5.0 (Linux; Android 11; M2010J19SI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 »
Signatures count: 3 »
Signatures reference: auxiliary.yml:HostNames_2, auxiliary.yml:ASN - Linode Akamai »
Why blocked: Banned, HostNames_2, ASN - Linode Akamai! »
Reconstructed URI: DOMAIN A/wp-content/themes/pridmag/db.php?u »
Infractions: 40 »
Country code lookup: GB »
Request method: GET »
Hostname: 176-58-126-187.ip.linodeusercontent.com »`

**Comment by mikeruss1** [comment]
Infractions is the number you see on IP Tracking for that IP. It is the cumulative number of Signature blocks, and is the number used for deciding to block without generating a report or log. Dont know about different domains, suspect it accumulates per domain?

**Comment by eurobank** [comment]
@mikeruss1 I don't follow what you say. I don't understand.

**Comment by mikeruss1** [comment]
do you want to clarify what isnt clear?

**Comment by Maikuolan** [comment]
@mikeruss1 I think @eurobank is referring to how the infractions are at 40 at the earliest of those three block events, then jumps up to 42 at the subsequent block event which occurs 1 second later (and, as the signature count for that subsequent block event was 2, an infraction count of 42 is expected and normal), but then drops down to 16 at the next subsequent block event which occurs approximately 48 minutes later (which isn't really expected, and possibly not normal).

Between the second and and the third/last block event quoted above, were there any other blocked requests from the IP address in question, or was it just those three?

**Comment by eurobank** [comment]
@Maikuolan No other logs between. It is a copy paste with the order logged.

Here is an other one, from 32 to 1:

> ID: 1680181229-915864-3333613671 »
> Date/Time: Thu, 30 Mar 2023 16:00:29 +0300 »
> IP address: 43.133.35.229 »
> Query: rchk »
> User agent: Mozilla/5.0 (Linux; Android 11; M2010J19SI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 »
> Signatures count: 1 »
> Signatures reference: auxiliary.yml:ASN - Tencent »
> Why blocked: ASN - Tencent! »
> Reconstructed URI: **DOMAIN B**/wp-content/plugins/ioptimization/IOptimize.php?rchk »
> Infractions: 1 »
> Country code lookup: SG »
> Request method: GET »
> Hostname: -
> 
> ID: 1680181059-963157-3380897008 »
> Date/Time: Thu, 30 Mar 2023 15:57:39 +0300 »
> IP address: 43.133.35.229 »
> User agent: Mozilla/5.0 (Linux; Android 11; M2010J19SI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 »
> Signatures count: 2 »
> Signatures reference: auxiliary.yml:ASN - Tencent »
> Why blocked: Banned, ASN - Tencent! »
> Reconstructed URI: **DOMAIN A**/wp-content/plugins/ccx/index.php »
> Infractions: 32 »
> Country code lookup: SG »
> Request method: GET »
> Hostname: - 


The infractions change happens when a different domain appears in the log (domain a, domain b)

**Comment by Maikuolan** [comment]
> The newer is a DIFFERNT domain. Does it matter?

It shouldn't. In the cache, tracking entries are just stored like `Tracking-a.b.c.d` (where the `a.b.c.d` is the IP address being tracked), without any particular reference to the domain which initiated the tracking, so, as far as CIDRAM is concerned, tracking at one domain should the same as tracking at any other domain connected to the CIDRAM installation.

The reason I'm wondering whether there were any other blocked requests connected to the IP address in question is, I'm wondering whether maybe, between the second and third block event, something happened to the IP tracking entry for the IP address in question (e.g., the entry expired, or something went wrong with the cache, causing the entry in question to become unavailable, thus CIDRAM then attempting to create it anew at a subsequent block event instead of updating the existing entry), and, if there are consistently 2 signatures being triggered for that particular IP address, if, after CIDRAM attempting to create the entry anew, we had 7 other additional block events occur for that IP address (7 block events * a signatures count of 2 = 14 infractions), then, when that third/last quoted block event occurs, it adds another 2 infractions, bringing the total infractions up to 16. That would explain why the infractions are showing as 16 by the time of the third quoted block event, assuming we have those 7 additional block events hidden away in the logs there somewhere. If not, then, I'm not entirely sure.

**Comment by eurobank** [comment]
@Maikuolan If you wish, i can email you the whole log.

**Comment by Maikuolan** [comment]
> @Maikuolan No other logs between. It is a copy paste with the order logged.

Hm.. Not sure exactly what's going on then, in that case.

> @Maikuolan If you wish, i can email you the whole log.

Might be the best bet. Maybe, looking over the logs, I'll spot something in there which isn't coming to mind right now. Cheers.
