### ISSUE TITLE
IP testing and AbuseIPDB

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#453]
In the past with V2 when I checked an IP at the Test IP page I wound see if it was blocked due to AbuseIPDB.  Now upon checking an IP that is listed at AbuseIPDB the IP test page says it's not blocked. My AbuseIPDB configuration falls well withen the scope of reports, and confidence score. The IP in question is: 50.35.124.70

Using CIDRAM version 3.2.0. 

See if your CIDRAM version shows AbuseIPDB blocking that IP.

**Comment by Maikuolan** [comment]
If I configure `abuseipdb➡lookup_strategy` to perform lookups for *every* request, it says it's blocked. But, if I configure it to perform lookups for *sensitive pages only*, it says it isn't. I'm thinking it's just because the IP test page isn't regarded as a "sensitive page", and currently has no option provided otherwise to treat it as one, so the lookup isn't performed at all in such cases.

Maybe I should include such an option at the IP test page?

**Comment by 737simpilot** [comment]
Fixed it! The remedy was to simply dump the CIDRAM cache. 

Yeah, I always use lookup all requests and still had the issue. I wondered if it was the API limit so I logged into my AbuseIPDB account and I haven't even scratched the surface on API request limits. We're talking some 70 lookups a day. That's it.  I did notice API lookups dropped off on the 6th. I don't know why. But dumping the CIDRAM cache cleared things up for what ever reason. Perhaps an update messed things up in the cache. I should have held onto the cache file for your analysis, but I wasn't sure if dumping the cache would have made a difference or not, just a shot in the dark. I can tell you though that the only thing that updates via Cronable are the signature files, and I did not update anything beyond that on the 6th. I manually update CIDRAM's core via the frontend. The cache file did look a little heavy I guess. Well, "heavy" by my standards. I'd say maybe about 200 - 400 lines worth.  I don't use PDO for the cache. Just flatfiles. 


> Maybe I should include such an option at the IP test page?

That might be prudent I guess. Seen as how if someone had that setting on and only that setting and wanted to see if an IP was blocked based on the sensitive page it may be beneficial to that person.


I'm also wondering about an alert that an API wasn't working. Some kind of API status check verification for modules that use an API indicating whether all is good or not. I'd place the status on the Home page so one can identify a problem right away upon login. Perhaps as soon as the Home page loads it queries the API. I'm not sure if that would have helped me or not, but it _looked_ like the API wasn't even being queried and thus the NO response in the IP Test Page. Had I not tested an IP in the IP Test Page and cross checking at AbuseIPDB, I would have never known AbuseIPDB wasn't working. I use the IP Test Page prior to submitting IPs to you for your blocking consideration in CIDRAM.

Realizing of course to check the status of the SFS API might be a little hard to do unless the SFS Dev allows that per API rules. Though, a future status API indicator would trip via CIDRAM **login** so that would be withen the SFS rules I guess...

**Comment by Maikuolan** [comment]
> Some kind of API status check verification for modules that use an API indicating whether all is good or not. I'd place the status on the Home page so one can identify a problem right away upon login. Perhaps as soon as the Home page loads it queries the API.

Live queries at login might be tricky, but the modules are noting to the cache when a lookup completely fails (e.g., due to rate limiting, connection failure, etc), so I could probably just pull from that, if needed; shouldn't be too difficult. Of course, such a thing wouldn't necessarily tell you whether an API is down *currently*, but *would* tell you whether it appeared to be unavailable at the time of CIDRAM's last attempt to actually use it (up until the relevant cache entry expired). Maybe I do that?

**Comment by 737simpilot** [comment]
Sounds reasonable, Caleb. 

I wish I hung onto the cache now to see what may have caused the API to fail like that.

**Comment by Maikuolan** [comment]
> Maybe I should include such an option at the IP test page?

Done. :-)

**Comment by 737simpilot** [comment]
Cool, I'll check this out. Thanks.
