### ISSUE TITLE
Rate Limiting - Exclude CIDRAM admin

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#457]
Can Rate Limiting counting exclude all traffic from within CIDRAM admin?

**Comment by Maikuolan** [comment]
I'll see what I can do. :-)

**Comment by Maikuolan** [comment]
New option added to the rate limiting exceptions configuration to exempt front-end requests. :-)

**Comment by eurobank** [comment]
Thank you !

**Comment by eurobank** [comment]
I still see my ip in the rate limiting page. Is that normal?

**Comment by Maikuolan** [comment]
The exemption will prevent requests to the front-end from being registered to the rate limiting data, but it doesn't interfere with data which already exists. If you clear it out, it shouldn't be readded (at least, while accessing the front-end).

The reason I worked it that way (preventing new data from being added at the front-end, but not interfering with existing data, and not changing the behaviour of rate limiting for requests which aren't connected to the front-end), is because for installations which protect their front-end using CIDRAM's own protections, those protections would typically execute prior to loading the front-end (given there's not much point trying to protect a page after it has already been served), which means, at the time of any given request (and at the time where we're checking against rate limiting data which already exists), we typically wouldn't actually know whether a request is from an admin until after the execution of those protections has already finished. However, the event hook for writing *new* rate limiting data (i.e., incrementing the total number of requests which originated from a given IP address, and calculating how many bytes a request has consumed) is written into a shutdown function, which means it occurs after everything *else* has already executed (including generating the page, whether a front-end page or a normal website page alike; this is necessary, because we can't know for sure how many bytes a request has consumed until after we're finished with the output buffer for the request, with no more remaining bytes to be written), which means.. although we won't know whether someone is an admin at the time that existing data is checked, we *will* know at the time that *new* data is being written. So, it's a simple enough matter to just avoid writing that new data entirely in such cases. :-)

If we want to also avoid writing any new data for *any* requests from admins (i.e., even those unrelated to the front-end, like normal requests to the protected website, etc), and also to prevent future requests being blocked as a result of any existing rate limiting data (i.e., even when limits are exceeded), the best solution would be to whitelist such requests, either by whitelisting the admin's IP address via an auxiliary rule or similar, and then enabling the rate limiting exception for whitelisted requests.
