### ISSUE TITLE
Botua module

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#461]
Any ideas if this seems correct:

```
User agent: ias-or/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/) »
Signatures count: 2 »
Signatures reference: botua.php:L147, botua.php:L168 »
Why blocked: Banned UA, Banned UA! »

```
2 counts?

**Comment by Maikuolan** [comment]
URLs in the user agent merely direct to a company homepage, and say nothing at all about the purpose of the actual bot itself, and no proper page anywhere announcing the intended purpose of the bot AFAICT otherwise, has been known to send too many requests too quickly, flooding some websites, has been caught sniffing for vulnerabilities, evidence of scraping pages from websites, etc.. so being blocked isn't a mistake. Being blocked *twice* though, is a little unusual. Generally, when at all possible, it's preferable to only be blocked once per module, to avoid complications in the event that someone wants to bypass some signatures in order let something through (which is always possible, and, given the lack of a proper page to describe the intended purpose of the bot in question, while doubtful, it's not completely impossible that perhaps its creators did, in fact, have some legitimate, benign intention for it, an intention which, if it can be clearly documented and demonstrated somewhere, perhaps by said creators in the event that they somehow, per chance, stumble across this discussion at some point in the future and take an interest in it, *might* see it removed from the module).

Looking at the specific signatures triggered though, they don't appear to have any relation to each other. [botua.php:L168](https://github.com/CIDRAM/CIDRAM/blob/06bb9282f17d219035dc3486f82a1c2dff29c81d/vault/modules/botua.php#L154-L168) explicitly blocks a number of different bots, including Admantx, so could be said to be specifically targeting that bot (but, alongside numerous other bots). [botua.php:L147](https://github.com/CIDRAM/CIDRAM/blob/06bb9282f17d219035dc3486f82a1c2dff29c81d/vault/modules/botua.php#L147), on the other hand, simply looks for any user agent which has three or more consecutive spaces in it (because there's a small number of malicious bots which are known to often do that, while permutating their user agent, munging other identifiers, etc, while legitimate, benign user agents don't tend to do that, unless it's by accident, as it doesn't really serve any purpose in a proper, well-formed user agent).

Due to the two signatures not targeting the same thing, I probably won't change anything right now, I think. (Unless it's being used for some legitimate purpose at one of your websites..? The company by the same name as the bot appears to be an advertising company, so perhaps the bot is needed for advertising purposes..? I don't have any confirmed related information about that though, which makes it just speculation on my part. But, if someone tells me, "I need it for some adverts I run at my site", I can act with that in mind). If the user agent is cleaned up a bit (i.e., by the bot's operator), L147 will likely resolve itself anyway. Failing that, those wanting to bypass it could either bypass it twice, or maybe just greylist it instead, to avoid it being blocked. But, for any CIDRAM users which have zero dealings or association with the company by the same name as the bot in question, and particularly for any which don't have any advertising on their websites, regardless of whether the aforementioned speculation pans out as correct or incorect, I can't see any legitimate reason for that bot to be on said users' websites.

**Comment by eurobank** [comment]
right. thank you
