### ISSUE TITLE
Redirect 301 instead of 403 blocked?

### ISSUE THREAD

**Issue by tnovak007** [CIDRAM/CIDRAM#466]
Hi!

I don't know what's wrong, but since yesterday update I'm getting always 301 - moved permanently response (and endless loop till 429) instead of 403 - forbidden:
![image](https://github.com/CIDRAM/CIDRAM/assets/44246865/3870ca7a-2558-4be3-a714-5e070bf2b66f)

Even test auxiliary rule doing it:

ID: 1683656575-584336-1530188772
Script version: CIDRAM v3.2.0
Date/Time: 09.05.2023 20:22:55
IP address: 37.48.43.xxx
User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36
User agent (lower-case): mozilla/5.0 (linux; android 10; k) applewebkit/537.36 (khtml, like gecko) chrome/113.0.0.0 mobile safari/537.36
Signatures count: 1
Signatures reference: auxiliary.yml:test
Why blocked: test!
Why blocked (detailed): test
Reconstructed URI: ---
Infractions: 0
ASN lookup: 13036
Country code lookup: CZ
Request method: GET
Protocol: HTTP/2.0
Hostname: 37-48-43-xxx
CAPTCHA state: Enabled.

![image](https://github.com/CIDRAM/CIDRAM/assets/44246865/2b7666f8-a071-4f45-a09d-a0bd1c9f4ceb)

![image](https://github.com/CIDRAM/CIDRAM/assets/44246865/b5ed7af3-a4e1-4477-8bf1-8b2f7d0a5834)

Returned 301 instead 403:

141.101.96.xxx "09.May.2023_20:22:55_+0200" "37.48.43.xxx" "-" GET "---" "/index.php" "-" "GET / HTTP/2.0" "-" "HTTP/2.0" **301** 0 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36" "---" 0.064 OK ---

Could you please help me?

Thank you.

EDIT:
I've just found it's probably related to "silent mode": If empty, I'm getting this issue.
If I put something there (like *), it starts working.... strange...
Maybe caused by this commit???
https://github.com/CIDRAM/CIDRAM/commit/6ac44f28160ff2c654bead1ed5622960faa26431
EDIT 2:
Positive, reverting this fixed it.
EDIT 3:
Probably just logic error - I think this line in Protect.php should be like this:

```
                /** Append default L10N data. */
                $this->CIDRAM['Parsables'] += $this->L10N->Data;

-->           if ($this->Configuration['general']['silent_mode'] == '') {
                    /** Enforce output template suppression. */
```

**Comment by Maikuolan** [comment]
> Probably just logic error - I think this line in Protect.php should be like this:

Yep, you're correct. The problem was a logic error. Wanted that truthy/falsy check there to be more type-explicit, by checking whether it's an empty string, due to that the configuration directive in question (silent mode) normalises to a string, but got it the wrong way around (wrote `!==` instead of `===`) when I changed it.

A consequence of being distracted every 5 minutes at home while trying to work on it, I guess. Or just not paying close enough attention, maybe. Anyway, in any case, I'll push out a fix for this now. Thanks for spotting and reporting this problem so quickly after the commits introducing it were first pushed. Definitely not the kind of bug I'd like to see appearing as part of a new tag/release.

**Comment by Maikuolan** [comment]
Fix pushed. :-)
