### ISSUE TITLE
Question about best performance strategy.

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#469]
I have a lot of aux rules. I find them very handy. Some of them have several conditions/checks each (for example 10 ASNs).

So i would like to ask if i should make ONE rule for each (each option) or ONE rule containing 10-15 each. 

What is FASTER for CIDRAM? What are the limits?

For example: 2 rules with 20 conditions each, or 40 aux rules (one rule, one condition) ?

**Comment by Maikuolan** [comment]
Sorry for the delay. Bit busy with other commitments the past few days.

We'd probably need to perform some benchmarks to be absolutely sure (I haven't done that for auxiliary rule arrangements before), but I suspect that CIDRAM would likely run faster with less rules (i.e., organising it in such a way that the conditions could be merged, instead of separate rules).

That said, there may be times where you absolutely want separate rules, e.g., when certain conditions should be considered alongside A/B/C other conditions, but not D/E/F other conditions, or some such arrangement, where you might need to utilise profiling, might need different block reasons, different status codes provided, etc and etc.

But, for cases where that doesn't apply (different conditions, but it's all simple like `A or B or C or D` or `A and B and C and D`, nothing complex like `(A or B) and (C or D)` or `(A and B) or (C and D)`; don't need different block reasons; don't need different status codes; and so on), when it makes no practical different otherwise, it's probably better to just have everything combined into the one rule. Probably. But like I said, I haven't benchmarked that yet, and we'd probably need to do so, if we wanted to be absolutely sure.

In terms of the limits: A lot of that comes down to PHP's own configuration (e.g., the value defined for `max_input_vars`, which, if sufficiently small, could potentially impact the usability of the front-end interface for managing auxiliary rules), and any limits that the webserver might potentially be enforcing (which would differ from one host to another, and we probably wouldn't realistically know about anyway, until we either encounter it for ourselves, or until the hosting provider kindly decides to tell us about it, which probably isn't going to happen). As long as PHP's own configuration doesn't enforce any troublesome limitations, and neither does the webserver itself, then there shouldn't, in theory, be any particular limits in regard to how many auxiliary rules, and to how many conditions for any given rule, we're able to sustain at any given time at the auxiliary rules page.

**Comment by Maikuolan** [comment]
Wondering whether it might be worth having CIDRAM actually check what the value defined for `max_input_vars` is when accessing the auxiliary rules page, and actively monitoring the number of inputs on the page at any given time against that value, to be able to tell the user ahead of time whether they might be going over the limit..? Doesn't necessarily fix any potential problems, but should at least prevent them from surprising us. Should be doable.

**Comment by eurobank** [comment]
Are we talking about this:

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/2919d9f8-2028-4ecb-b8e0-fab6c508d958)

**Comment by Maikuolan** [comment]
Yep. :-)

**Comment by Maikuolan** [comment]
3,000 is a very generous number, at that. At that number, I doubt the auxiliary rules page would ever exceed it, so, should be safe in that regard.

**Comment by eurobank** [comment]
Previously it was 1.000 (default). A month ago, some Wordpress plugin complained about this and i had to set it to max (to be 100% safe). I never knew it was even there :)

**Comment by eurobank** [comment]
![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/80b54668-897e-462d-be88-326b1f8fa085)

**Comment by eurobank** [comment]
@Maikuolan How about disabled aux rules? Do they matter? I have around 20-25 of them.

**Comment by Maikuolan** [comment]
Disabled rules shouldn't matter insofar as performance is concerned, but they'll still count towards `max_input_vars` (because, even though they're disabled, the associated input fields are still present on the page).

**Comment by Maikuolan** [comment]
(That said, technically speaking, the existence of any rule, no matter whether enabled or disabled, would still add maybe a few milliseconds to the overall time required to process the auxiliary rules, due to that the YAML data for the auxiliary rules would still need to be processed by the YAML handler, and CIDRAM won't know whether a rule is enabled or disabled until the YAML handler processes the line of data which marks the rule as disabled, and more rules means more data to process. So, if you had thousands upon thousands of rules, it'll likely still have a noticeable negative impact on performance, regardless of whether all those rules are enabled or disabled. However, the code for actually *executing* the auxiliary rules, e.g., to cycle through all the conditions of all the various rules, to match those conditions according to the logic specified by the rules, and to then perform the relevant actions associated with those rules, will skip over all of that for any disabled rules. Whether the rule is disabled is the very first thing that code will check, so that it doesn't need to do any of the other stuff when it finds that a rule is disabled. So, putting aside the reading and processing of the YAML data, disabled auxiliary rules shouldn't have any impact on performance whatsoever at least insofar as actual rule execution is concerned. So, as long as the total number of rules is reasonable, i.e., not thousands upon thousands of them, there shouldn't be any noticeable performance impact whatsoever for disabled rules).
