### ISSUE TITLE
Possible issue with BOBUAM

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#471]
In reference to my discussion topic [here](https://github.com/CIDRAM/CIDRAM/discussions/470#discussion-5221440), the UA came across as: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0`

See how it's malformed? in the past BOBUAM would have put the brakes on that type of UA. Was the cookie command injection Sig a higher priority thus BOBUAM didn't kick in or is BOBUAM not doing what it should in regards to malformed UAs?

**Comment by Maikuolan** [comment]
Do you mean how the `rv` and the `Firefox` tokens don't match? They temporarily froze the `rv` token shortly after Firefox v109 was released ([see here](https://www.ghacks.net/2023/01/01/mozilla-changes-firefoxs-user-agent-because-of-internet-explorer-11/)), and plan to unfreeze it, syncing it back up with the Firefox version token when Firefox v120 is eventually released in the future.

According to their current [release schedule](https://wiki.mozilla.org/Release_Management/Calendar) and according to [whatismybrowser.com](https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox), 113 should be the current latest stable version of Firefox for desktop systems, and the structure of the user agent given matches what [Mozilla says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox) should be the correct syntax for the Firefox user agent, so I don't *think* the user agent is malformed. I've made mistakes before though, so do let me know if I'm missing something there. '^^

**Comment by 737simpilot** [comment]
Oh, wow, very interesting. And I see you coded that into BOBUAM already since it didn't trip. :D
