### ISSUE TITLE
Question for robots.txt

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#472]
I would to know when and if robots.txt file is allowed to everyone, no matter what blocks/rules/signatures are in place ....

**Comment by eurobank** [comment]
I was able to test it myself. Robots.txt is allowed all the time to all, no matter what.

**Comment by Maikuolan** [comment]
Depends somewhat on how your website has been set up. Because `robots.txt` isn't a PHP file, CIDRAM won't typically ever see any requests made to it in the first place, providing no opportunity to have any of those requests be blocked. But, *if* CIDRAM was to somehow have access to those requests (e.g., if such requests were rewritten using Apache rewrite rules in `.htaccess` or similar to have them point to a PHP file responsible for generating the `robots.txt` data, instead of just having the plain-text file be requested and served directly), it should then be able to block them just the same as any other typical request to a PHP page.
