### ISSUE TITLE
Question about exclude some networks

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#473]
How can i exclude some networks or ips or whatever from the ipv4 CLOUD or other **signatures**? With aux rules? With some other custom signatures?

Please give me some pointers. For example i want to exclude AWS from many blocks in ipv4 signature?

Thank you

**Comment by Maikuolan** [comment]
To clarify: Would you be wanting to exclude *every* AWS signature, or just some specific subset of the AWS signatures (or some specific IP addresses within some specific affected ranges only)?

If you're wanting to exclude *every* AWS signature, as long as you're not leveraging them for anything else (e.g., in the auxiliary rules, *"do X/Y/Z action if signatures reference includes references to AWS"*), the easiest and most direct way to exclude them would be to go to the "Sections List" page, search (Ctrl+F) for "Amazon.com, Inc" (without the quotes), and click the "Ignore this" link which appears next to the name for that signatures section:

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/3a9f7c86-4bdb-42d3-b053-851683eab7d5)

After clicking the link, the section should become greyed out, like so:

![Untitled2](https://github.com/CIDRAM/CIDRAM/assets/12571108/4d2178fd-1114-47c7-bae3-5d53d18fd77f)

Telling CIDRAM to "ignore" a signature section will have that signature section treated just the same as if it didn't exist at all in the first place: Although still being present in the signature files, when ignored, none of the affected signatures will ever trigger nor will ever block anything. But, seeing as it does affect the entire signatures *section*, if you were wanting to exclude only *part* of the signatures section (i.e., some AWS ranges, but not all of them, or only some specific IP addresses within some specific ranges), you'll probably want a different approach than telling CIDRAM to ignore them.

In such a case, either custom signatures or auxiliary rules should suffice.

Let's say, for example, if you wanted to allow access from `45.152.134.0/24` (a CIDR belonging to Amazon, registered to the United Arab Emirates).

In a custom IPv4 signature file, you could write this (on a new line, by itself):
```
45.152.134.0/24 Greylist
```

Or this:
```
45.152.134.0/24 Whitelist
```

"Greylist" tells CIDRAM to forget about anything already matched, to reset the current signatures count to zero (preventing anything which might've triggered up *until* that point from being able to block the request), but to continue processing, in case any *subsequent* signatures, modules, or auxiliary rules might be wanting to block the request.

"Whitelist" is a little stronger, and likewise tells CIDRAM to forget about anything already matched, and to reset the current signatures count to zero, but *also* tells it to stop any further processing (i.e., modules and auxiliary rules won't be ran at all), thus preventing the request from being blocked entirely.

For the sake of providing a complete answer, I would mention, too, that if you feel up to writing your own PHP code, you can also use "Run", like so:
```
45.152.134.0/24 Run some_file.php
```

"Run" tells CIDRAM to execute a given PHP file (in the example above, that would be "some_file.php") when the signature in question matches, and can be used to perform bypasses using PHP code, or to do anything else which might possibly require writing and executing some specific custom PHP code for the affected requests. If a user needed CIDRAM to do something which it can't normally do under a normal, clean installation using the standard available features, configuration, available modules, etc, I might recommend this strategy. However, for anyone not confident in writing PHP code, and for anyone not super familiar with CIDRAM's own codebase, I wouldn't generally recommend this strategy.

The default signature bypasses included with CIDRAM as standard are executed via "Run" (because the bypasses involve some code which is very specific to the signatures being bypassed).

For auxiliary rules, just the same as with writing custom IPv4 signatures, you have the greylist, whitelist, and run actions available, and they do the same thing with the latter as they would with the former (although more easily leveraged due to the interface provided for auxiliary rules).

Just the same as with writing custom modules, or as one might do via custom PHP code executed via run, the bypass action is also available for auxiliary rules.

![Untitled3](https://github.com/CIDRAM/CIDRAM/assets/12571108/4ec5f234-6cb6-4e57-b7d9-b8548c9ed7dc)

"Bypass" doesn't tell CIDRAM to forget anything, but tells it to subtract one from the current signatures count (but not from the current infractions count, as that's calculated a little differently), as long as the signature in question (or, the conditions attached to the rule, in the case of an auxiliary rule) matches. Useful if you want to just "bypass" a specific signature for a specific range, but don't necessary want to whitelist the range entirely (e.g., a range might be known for attempts to spam or hack your website, but some of your legitimate users also come from that same range, so you don't want to block requests outright simply due to being from that range, but you still want it to be possible for requests from that range to be blocked in the event that positive matches are produced by some of the modules intended for blocking spam, hacking, or other malicious stuff, or in the event that your auxiliary rules would normally be blocking the requests).

When bypassing, you would typically include conditions which reflect the same conditions expected of the original signature which you're wanting to bypass (because the subtraction from the signatures count is meant to counteract the addition to the signatures count invoked by the signature to be bypassed, and thus, we want the two to be in lockstep).

So, for the example given (an IPv4 range), because it's being blocked by an IPv4 signature, and IPv4 signatures just work with IPv4 CIDRs, the conditions for such a bypass would be simple: We'd just be wanting a CIDR condition to match against the CIDR in question (with a caveat; details to follow).

![Untitled4](https://github.com/CIDRAM/CIDRAM/assets/12571108/47d0e672-9fdd-4bb5-81d4-4b9fa11f27e1)

That is assuming, of course, that we're using "direct string comparison" (or "Windows-style wildcards", which would produce the same effect in this case, given the absence of any asterisk in the condition, and no wildcards present means.. it's just an ordinary string, anyway).

If we're using regular expressions, we'd want to convert that condition to a regular expression to avoid false positives (or I guess, technically, false negatives, given that it's a bypass). Because the decimal is used as a "match any character" in regular expressions lingo, an unescaped decimal in a regular expression could allow it to match characters other than a decimal itself, which.. isn't actually able to produce any valid ranges in the case of the example given, but could possibly do so in some other cases, so.. it's good practice to escape any decimals in a regular expression when not specifically intended to "match any character". We'll also want to confine what the condition can match against by specifying the beginning and end of the string to be matched (so that arbitrary data occurring before or after the specified string isn't matched by the rule), and also specify the bounds of the expression itself.

So, when using regular expressions, instead of `45.152.134.0/24`, we'd be better to use something like `~^45\.152\.134\.0/24$~` (decimals escaped with `\`, beginning of string indicated by `^`, end of string indicated by `$`, bounds of the expression indicated by `~`; that latter character, to specify the bounds of the expression, can be other characters if we want, too; it just needs to be the same at both ends of the expression, and not repeated throughout the expression, so as to avoid confusing the engine).

But, there is a problem with including only the CIDR as a condition: What happens if, eventually, in the future, during an update to the section which the signatures being bypassed belongs to, the specific signature being bypassed is removed entirely? We now have a bypass in effect, for a signature which doesn't exist anymore. This may or may not be a problem.

Because the bypass requires that conditions be met before coming into effect, as long as the request doesn't originate from that range, it won't matter. But, for any requests originating from that range, as long as that range continues to not be blocked outright by any signatures, the bypass is effectively giving requests from that range a "free get out of jail card" for up to at least one offence. How to resolve that problem? If we know the name of the section which the signature to be bypassed belongs to, we can include that as a condition, too. That way, if the signature to be bypassed is removed from the signature files in a future update, the conditions of the bypass won't be able to match anymore.

In the screenshot below, I've included "Why blocked" as a condition to check, with `*Amazon.com, Inc*` as the value for that condition. That, in combination with the CIDR condition, narrows the bypass down to the specific offending signature a little better.

![Untitled5](https://github.com/CIDRAM/CIDRAM/assets/12571108/c5565f93-9763-4c75-bcea-28b6b390da98)

I've also set the matching type to "Windows-style wildcards", so that I can use wildcards with the "Why blocked" condition (because the "Why blocked" field is likely to contain a lot of other information too, which we're not interested in for the purpose of the bypass, but without the wildcards, would prevent the condition from matching). Because of the newly added condition, "direct string comparison" won't be any good for the bypass anymore. Regular expressions could work, but due to the slight increase in visual complexity, I opted to stick with Windows-style wildcards for the example. For regular expressions, instead of `*Amazon.com, Inc*`, we'd probably want something like `~Amazon\.com, Inc~`. Note that in this case, I haven't indicated the beginning or end of the string with `^` or `$`; That's because arbitrary data occurring before or after the string to be matched, in this case, isn't unexpected, so we don't need to bother specifying the beginning or end in this case (though we still specify the bounds of the expression itself).

I've also set: *"In order to trigger the rule, all conditions must be met."* With only one condition to be matched, it doesn't matter whether we specify "any" or "all" (because "any" or "all" of one is still just the one, so it doesn't matter). But, with the addition of a second condition, it now matters. In this case, because we need both conditions to match, I've set "all" (because otherwise, the bypass would match any time a request comes from that range, *or* any time that a request comes from *any* range belonging to that signatures section, which would just make the whole "free get out of jail card" situation even worse).

Anyway, that's that. Sorry for the lengthy read, but I figure, the more complete and more comprehensive an answer I can give, the more likely it is to cover other potential use-cases, other potential situations, and more likely to give a clearer idea about the good, the bad, worse, and better ways to go about solving the problem, depending on the specifics at hand (and decreases the chances of needing to repeat the same thing to other users in the future, because I can just point them back to this issue here if they ask the same thing or something similar). And to anyone just skimming over it, worried about the length potentially indicating the level of difficult: It isn't. It's just providing multiple different ways to solve the problem. :-)
