### ISSUE TITLE
Send blocked users to special page

### ISSUE THREAD

**Issue by DoctorDred** [CIDRAM/CIDRAM#475]
Hello. Is there possibility send all blocked by sidram users to my site special page?
For example https:/site/blocked

Thank you in advance!

**Comment by Maikuolan** [comment]
Yes, that can be done using the **`general➡silent_mode`** configuration directive. :-)

![silent_mode](https://github.com/CIDRAM/CIDRAM/assets/12571108/97e10d95-25fb-466d-adb4-f97597c31af1)

(But, when redirecting blocked requests to a page within the same website, just be careful about the risk of infinite loops. I.e., if the page which they're redirected to is also protected by CIDRAM, the redirection will trigger again, causing it to redirect again, and again, and so on. So, in most cases, you'll want to exempt the page being redirected to from CIDRAM's protection, so that when they're sent to that page, they just stay on that page).

**Comment by DoctorDred** [comment]
Brilliant!
