### ISSUE TITLE
Aux ASN regex possible issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#476]
IP address: 119.110.86.110
User agent: python-requests/2.31.0
Why blocked: Banned, User Agents Regex 1, ASN - Leaseweb!

The User Agent regex is correct. BUT the ASN - Leaseweb is wrong. The IP is not Leaseweb and that ASN (AS38753) in not anywhere.

Any ideas?

The regex of Leaseweb is:

ASN lookup = (396362|60781|396190|15003|395954|30633|205544)
ASN lookup = (394380|19148|7203|27411|393886|133752|8753|59253)

IS the my regex wrong?

**Comment by Maikuolan** [comment]
I think it's matching because of the 8753 (because the regex looks for the occurrence of any of those, from *anywhere* within the source data, and "8753" is the same as the last four digits of "38753", so the pattern is matching).

Instead of..
```
ASN lookup = (396362|60781|396190|15003|395954|30633|205544)
ASN lookup = (394380|19148|7203|27411|393886|133752|8753|59253)
```

Try this instead:
```
ASN lookup = /^(396362|60781|396190|15003|395954|30633|205544)$/
ASN lookup = /^(394380|19148|7203|27411|393886|133752|8753|59253)$/
```

`^` means "beginning of", and `$` means "end of". So, for example `/^(1|2|3|4)$/` would mean, from of the beginning of the string (^), match 1, or 2, or 3, or 4, followed by the end of the string ($). That way, we can confine where it looks for those values (meaning that requests from AS38753 won't successfully match against the pattern anymore, because the presence of that "3" would mean that the "8753" isn't attached to the beginning of the source data anymore).
