### ISSUE TITLE
Blocking country also blocking search engines

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#48]
Today, I was getting some enormous amount of clicks from **Russia**, so I decided to block the whole Russia country. But it surprised me that **Yandex bot** was also blocked!

```
Script Version: CIDRAM v1.3.0-DEV »
Date/Time: Wed, 13 Dec 2017 19:54:07 +0530 »
IP Address: 5.255.253.16 »
Hostname: 5-255-253-16.spider.yandex.com »
Signatures Count: 1 »
Signatures Reference: 5.255.252.0/22 »
Why Blocked: No access allowed from Russia ("RU_cidram.inc-IPv4", L219:F0)! »
User Agent: Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) »
```
I'm not sure, if it's a Bug or features. But I would love to unblock the search engines even the country was blocked! Because the country blocking might be temporary & I do wanna show up in SERP. 

-------

One more thing, you should consider having `module_pinterest.php` enabled by default, many of newbie won't figure out what's wrong.

--------

And does CIDRAM supports **PHP 7.2**?

**Comment by Maikuolan** [comment]
> And does CIDRAM supports **PHP 7.2**?

Yep. Current versions of CIDRAM are 100% compatible with PHP 7.2. Further version compatibility information can be found __[here](https://maikuolan.github.io/Compatibility-Charts/)__. :-)

> Today, I was getting some enormous amount of clicks from **Russia**, so I decided to block the whole Russia country. But it surprised me that **Yandex bot** was also blocked!
>
> I'm not sure, if it's a Bug or features. But I would love to unblock the search engines even the country was blocked! Because the country blocking might be temporary & I do wanna show up in SERP. 

Not technically a bug, due to that Yandex is based in Russia, and therefore, blocking all of Russia, strictly speaking, would include Yandex, too.

Best solution here, I think (assuming that you want to keep Russia completely blocked otherwise), would be to write a bypass to allow Yandex back in again, using either its UA or hostname (the two most clear means of identifying Yandex, due to that its IPs can change from time to time).

> One more thing, you should consider having `module_pinterest.php` enabled by default, many of newbie won't figure out what's wrong.

Hm, something to think about. There was a discussion about Pinterest a while back __[here](http://www.spambotsecurity.com/forum/viewtopic.php?f=61&t=4327)__, and I asked there about whether Pinterest should be allowed in by default, and there were a few others that suggested that it should be kept blocked by default, with an option to allow it in (which has been consequently provided by the creation of the Pinterest module). I understand what you mean though, and definitely, there's a good chance that many newbies won't be able to figure out what's wrong. I'll think on the problem and try to come up with something.
