### ISSUE TITLE
Warning Access to Abuse IPDB api is rate limited

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#480]
I had this message today and didn't go away no matter how i waited.

Now, i cleared all cache (redis) and went away. I see no issues.

Could that be a bug?

**Comment by Maikuolan** [comment]
I'll investigate this later today.

**Comment by 737simpilot** [comment]
I've been getting this for BGPView. I thought I was simply using too many resources which I doubt because I don't have a high traffic website and have been using BGPView for a long time.

**Comment by eurobank** [comment]
> I've been getting this for BGPView. I thought I was simply using too many resources which I doubt because I don't have a high traffic website and have been using BGPView for a long time.

I have seen this some times with IPAPI but after a few seconds it went away. This didn't.

**Comment by 737simpilot** [comment]
Yeah, I don't (yet) see it with IPAPI thus I disabled BGPView thinking I was really being rated limited. Right now I just use BGPView as a backup since I found IPAPI back then and suggested its use.

**Comment by Maikuolan** [comment]
So.. A slight difference between how the AbuseIPDB module detects rate limiting, versus how the other modules (the BGPView module, the IP-API module, etc) detect rate limiting: The AbuseIPDB module checks *specifically* for whether the AbuseIPDB API has returned a 429 status code (the status code for rate limiting), whereas the others just check whether their corresponding APIs have returned something other than 200 OK.

https://github.com/CIDRAM/CIDRAM/blob/91e8daee6fa7e08c43a7266f0787118f801a3b30/vault/modules/abuseipdb.php#L86

https://github.com/CIDRAM/CIDRAM/blob/91e8daee6fa7e08c43a7266f0787118f801a3b30/vault/modules/ipapi.php#L89

https://github.com/CIDRAM/CIDRAM/blob/91e8daee6fa7e08c43a7266f0787118f801a3b30/vault/modules/bgpview.php#L96

So, for those other modules, it's possible that CIDRAM *might* report them as being rate limited, when in fact, there's something else going on, like the service experiencing downtime, a request error, or something else. But, for the AbuseIPDB module, if CIDRAM is reporting that rate limiting has occurred, that's because the AbuseIPDB API has specifically responded as such. Whether what it's being told is necessarily correct or not, I think, we could only really confirm by checking for ourselves, but at the very least, CIDRAM is reporting correctly, per what the API itself is telling it.

As for why the API might be telling CIDRAM that rate limiting has occurred when it hasn't? No idea.

As for why the AbuseIPDB module checks specifically for a 429 status code, whereas the others just check for anything other than 200 OK? It's because the documentation for the AbuseIPDB API explicitly states that it'll send that status code when rate limiting occurs, so we can know for certain how we should *expect* their API to behave in such cases, whereas the others don't explicitly state anything like that, so we can't be certain about what we should be expecting from them in such cases, but it's reasonable to assume that they'll likely respond in some way other than how they'd normally respond (as would most API providers, generally speaking), so checking more broadly for anything other than what we would normally expect feels reasonable as a means of capturing any signs of something not working as expected. CIDRAM is then treating that as rate limiting (the most likely cause for suddenly being unable to use some API or another at any given moment), but "any signs" could, of course, entail other potential problems too, so as to whether it's *actually* being rate limited..? Well.. Some assumptions are being made, but it could also be more broadly interpreted simply as "something went wrong".

In any case, the way CIDRAM should respond to the problem, whether rate limiting or just simply "something went wrong", should be much the same anyway: Wait a while, until the problem should've disappeared, and then try again. So, the reported warning aside, CIDRAM's response to it should still be okay, I think.

**Comment by eurobank** [comment]
That doesn't explain why deleting all caches, the warning went away. Or it does?

**Comment by Maikuolan** [comment]
When CIDRAM receives a 429 status code from the API, it stores a record of the event in the cache, so that it can remember having received it for any subsequent requests. Because of that, clearing the cache should cause the warning to disappear, because CIDRAM will effectively have "forgotten" about the event. :-)

**Comment by Maikuolan** [comment]
(Or, just deleting the `AbuseIPDB-429` cache entry would also achieve the same thing, if we wanted CIDRAM to forget about the event without necessarily losing everything else in the cache along with it).

**Comment by Maikuolan** [comment]
Might be worth adjusting the value configured for `abuseipdb➡timeout_rl` too, if the warning is remaining for extended periods of time, or seemingly isn't disappearing at all. The current default value has it expiring after a day.

![timeout](https://github.com/CIDRAM/CIDRAM/assets/12571108/9eae6ad8-cd18-4f4f-875c-b957f1f6e403)
