### ISSUE TITLE
Regex Question

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#488]
This is not for CIDRAM but for a regex in Cidram that i can't find the problem.

This regex for urls
`
Reconstructed URI = (/back/|/restore/|/old/|/bak/|//mail.|/.env)`

is triggering all kind of strange url blocks. Maybe i miss something in the regex.

an example of a blocked url:

www . domain .  tld /denver-c426832

**Comment by Maikuolan** [comment]
Need to escape the decimals/dots.

Because "." (when not escaped), in "regexese", means "any character", the `/.env` part of that pattern will successfully match against the `/denv` part of that blocked URL (because the "d" is a valid match for "any character").

In cases where a character holds some special meaning in a regular expression (e.g., decimals/dots), when we want to match that literal character, without the regex engine applying any special meaning to it, we'll want to "escape" it. We can escape such characters by prefixing a backslash.

So, if we did this:

`(/back/|/restore/|/old/|/bak/|//mail\.|/\.env)`

We should be able to avoid matching against URLs such as the example given. :-)

**Comment by eurobank** [comment]
@Maikuolan Thank you SO MUCH.
