### ISSUE TITLE
Suggestion for Mozlila User Agent

### ISSUE THREAD

**Issue by dimalif** [CIDRAM/CIDRAM#493]
I had a few hundreds from the start of the year,  and all were hacking attacks. Maybe you want to add something to CIDRAM (or not).

https://trunc.org/learning/the-mozlila-user-agent-bot

**Comment by Maikuolan** [comment]
Thank you for the suggestion. I'll work on this tomorrow. :-)

**Comment by Maikuolan** [comment]
In case anyone is curious, here's some recent excerpts from the logs at some of the websites I maintain where I have CIDRAM installed (requests blocked for various other reasons, but not due to the user agent, as CIDRAM wasn't yet blocking that user agent; I've fixed that as of now).

*[Mozlila.txt](https://github.com/CIDRAM/CIDRAM/files/12309105/Mozlila.txt)*

**Comment by Maikuolan** [comment]
CIDRAM's "bot user agents module" has been updated to now block "Mozlila" user agents.

Seems there's quite a large number of attack tools, rootkits, backdoors, webshells, malware, etc, which all cite "Mozlila" in their user agents. Some examples:

- [Rootinabox's "CMS-Checker-V1.0"](https://github.com/Rootinabox/CMS-Checker-V1.0/blob/a64f9acc40dfe95ab864c9e118748f4f408d44c9/cms.py#L75)
- [Zusyaku's "Termux-And-Kali-Linux-V3"](https://github.com/Zusyaku/Termux-And-Kali-Linux-V3/blob/1fc4c36640a04014e03201719f63c44d1020693f/wp-install.py#L36)
- [kiddenta911's "defjp"](https://github.com/kiddenta911/defjp/blob/1babad2577a806e1daa299ebcef9810b78a7c3ec/defjp.py#L52)

So, rather than having a signature identify it as any one specific thing, the newly created signature identifies it simply as "attack UA".

https://github.com/CIDRAM/CIDRAM/blob/b7d793854042445862233c77247bc763339813a1/vault/modules/botua.php#L411-L421

In any case, it's definitely something which should be being blocked. Thanks again for the suggestion. :-)
