### ISSUE TITLE
AI Scanners the new CURSE

### ISSUE THREAD

**Issue by dimalif** [CIDRAM/CIDRAM#494]
Now we have new fruits on the web, AI scanners.

Here is a new one (new for me)

[09/Aug/23:20:45:09 +0300] - 3.235.77.119 "GET /wp-content/cache/autoptimize/js/autoptimize_bdb21e6a934a6ae791205de28cec3b23.js" "-" "anthropic-ai" "-" 

anthropic-ai OH MY GOD

This is apparently in the user agent part ....

[%time] %name %client "%method %uri" "%referrer" "%ua" "%forward" "%host"

**Comment by Maikuolan** [comment]
> This is apparently in the user agent part ....
>
> [%time] %name %client "%method %uri" "%referrer" "%ua" "%forward" "%host"

On the bright side: The more broken a user agent is, the more typos, mistakes, etc, the easier it is to create signatures based around those typos and mistakes in order to block them. (Usually, anyway). '^^

**Comment by Maikuolan** [comment]
Bot user agents module updated. :-)

**Comment by dimalif** [comment]
@Maikuolan 

I think you missunderstood my

"[%time] %name %client "%method %uri" "%referrer" "%ua" "%forward" "%host"

line. That was NOT from the user agent but from my wordpress plugin variables used to log. 

The user agent was just anthropic-ai

**Comment by Maikuolan** [comment]
Ah, okay. I'll get that adjusted now. Cheers. :-)

**Comment by eurobank** [comment]
That particular bot can also be detected using their Query that is alsways "ver=something". 

Can we block with aux rules a Query like that? I mean is it safe? Is any legit service using that for some reason?

**Comment by Maikuolan** [comment]
*Can* we block it? Yes. Is it *safe*? TBH, I don't know. I've never *seen* "ver=something" appear before for anything legitimate, anything elsewhere, but not seeing it isn't any absolute guarantee, and it's a short enough string to append onto a query that I could foresee it potentially appearing here and there. Having not seen it though, if it's used elsewhere at all, I doubt its usage is particular frequent or widespread. So it's probably *mostly* safe, I imagine (until proven otherwise). Any kind of search functionality, or any kind of web-based software, CMS, frameworks, etc, which utilise GETs or query parameters to do whatever they're meant to do, if they happen to utilise a "ver" parameter at all, could be potentially affected (I don't know how often that would affect anything, though). Could always just try it out and keep an eye on it, I suppose.

**Comment by eurobank** [comment]
The "strange" Queries i see from your Tally Query report:

rsd
3x=3x
author=2 (numbers from 0 to 20 usually)
wall=ZWNobyBhRHJpdjQ7ZXZhbCgkX1BPU1RbJ3Z6J10pOw==  (wall=some token)
ver= (some number)
