### ISSUE TITLE
New Signature file ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#499]
As an experiment I created a new sig file called abuse.inc, and added it to components>ipv4
the format is ...
127.0.0.1 Deny AbuseIPDB
but no block.
However if I add the Deny to an established sig file it works.
so I guess I need to do something else to get it to read my file ?

**Comment by Maikuolan** [comment]
Is the newly created file placed inside `vault/signatures`? For v2 and earlier, signature files would just be placed within the `vault` directory, but as of v3, they have their own dedicated directory, `vault/signatures`.

**Comment by mikeruss1** [comment]
yes its with the other ipv4 sigs like ipv4.dat

**Comment by mikeruss1** [comment]
has worked before, I added my own CN_cidram.inc. Maybe this is because that file is already known?

**Comment by mikeruss1** [comment]
its only an experiment, so no need to make program changes

**Comment by mikeruss1** [comment]
Incidentally, the whyblocked for the abuseipdb test was ..
Why blocked: AbuseIPDB ("Voxility LLC", L19:F2, )! »
whats the second part ?

**Comment by Maikuolan** [comment]
> whats the second part ?

Do you have `Tag: Voxility LLC` anywhere in that file, by any chance?

**Comment by Maikuolan** [comment]
Found the problem. (Sort of, at least).

Duplicating what you did at my end, I've found that, just as at your end, at my end, doing this:

```
127.0.0.1 Deny AbuseIPDB
```

..fails to produce any block event. But, doing this:

```
127.0.0.1/32 Deny AbuseIPDB
```

..successfully produces a block event. So, not specifying the CIDR block size after the IP address is causing CIDRAM to fail to properly recognise the signature, it seems.

The "sort of" part:
- I'm pretty sure I wrote some code into CIDRAM, a *long* time ago, to automatically interpret things like `1.2.3.4 Deny` as `1.2.3.4/32 Deny`, so that we shouldn't *need* to specify the CIDR block size after signatures anyway, as long as it's for exactly one IP address only.
- If I add a bunch of linebreaks before the signature, suddenly, CIDRAM recognises it properly, and a block event is produced. That confirms that yes, I *did* in fact write that code that I thought I'd written, but I guess, there's still a bug in there somewhere, because it shouldn't require those arbitrary linebreaks in order to work as intended.

So.. yeah. I'll need to find and fix that particular bug, at least.

**Comment by Maikuolan** [comment]
On a somewhat related side-note: The signature file fixer can sometimes catch problems with signature files that we mightn't necessarily spot ourselves when eyeballing it directly, which can sometimes be useful when encountering seemingly unexplainable problems with signature files (though, the signature file fixer is just coded to detect some of the most common, easiest to anticipate problems, and mightn't necessarily catch everything, particularly if the problem is something really obscure).

![Fixer](https://github.com/CIDRAM/CIDRAM/assets/12571108/4167271c-e253-47b7-9c56-ecea4ae8864a)

**Comment by mikeruss1** [comment]
voxility - yes I put it into ipv4.dat and its within that group - my bad
the version I am using is from may23 - so that might explain - will advise
anyway no need to do anything else, I can use /32 if needed

**Comment by mikeruss1** [comment]
adding /32 works
updating to latest and trying without /32 - no block
put it into sig tester and it wants to add /32

thank you for help, and v quick response!

**Comment by mikeruss1** [comment]
note that 127.0.0.1 blocked ok in ipv4.dat, but not in abuse.inc?

**Comment by Maikuolan** [comment]
With the bug, it seems, exact placed position with the signature file is having some effect on whether the signature works properly or not (it shouldn't be having any effect at all). Found what's causing the bug now. I'll commit a fix shortly. :-)

**Comment by Maikuolan** [comment]
Done. Everything should be working as expected now. :-)
