### ISSUE TITLE
Failed Requests reported to external APIs

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#502]
The statistics have cleared in 14 of August. Until today i see:

Requests reported to external APIs

--
IPv4 – OK | 80
IPv4 – Failed | 182

I find 182 failed too much. I only report back to AbuseIPDB,

**Comment by Maikuolan** [comment]
I think it's because AbuseIPDB enforces a minimum 15-minute interval between reports for the same IP, and when we see attacks from any given IP address, we tend to see numerous attacks from that same address come in all in quick succession, trying to flood our websites, etc.

I'll need to figure out a way to deal with that, maybe holding all reports after the first or something. I'll experiment a little at my end to try to come up with something.

**Comment by Maikuolan** [comment]
I've pushed some changes just now which should help a little. :-)

**Comment by eurobank** [comment]
Thanks, if you could explain a bit what the new option means :)

`Allow, but only when also blocked.`

**Comment by Maikuolan** [comment]
Prior to the update which introduced that change, I had discovered that it was theoretically possible, in some obscure circumstances, for an IP address to be reported without actually being blocked, due to that the reporter, when determining whether to report an IP address, just accounted for whether any report reasons had been generated for the request at hand, without accounting for the signatures count at hand.

If reporting was enabled, and a signature in a module, which normally would result in a report being generated when triggered, happened to be triggered for a particular request, and that same signature then happened to be bypassed by an auxiliary rule (but without being whitelisted), we could have a situation where report reasons are generated, but the signatures count is zero, resulting in the IP address being reported without being blocked.

The new option is intended to deal with such obscure circumstances by making that behaviour configurable (seeing as that generally, most of us *wouldn't* normally want something to be reported if it hadn't actually been blocked in the first place, but the possibility exists that some users might want that kind of behaviour, if, for example, they're running their CIDRAM installation as a honeypot, trying to gather a lot of data about a particular requesting entity without clueing in its operator to the fact that they're being reported by way of showing them that they've been blocked, etc).

When set to either "deny" or "allow", reporting behaves the same way it did before (either being not allow to report, or allowed to report with this potentially counter-intuitive behaviour in effect, same as before).

When set to "allow, but only when blocked", at the point in the code where reporting would normally occur, it checks first whether there's a positive signatures count for the request at hand, and if there's not, aborts reporting, thus ensuring that the IP address will be reported, only if it's also being blocked. :-)
