### ISSUE TITLE
Question about Caching

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#507]
I have abandoned a long time ago flat text files use with CIDRAM. Now i use Redis, but somehow the results are not that good on a shared server. I'm not an expert in all that.

The last month a Wordpress plugin was suggested by an other webmaster, Docket Cache for Wordpress. That plugin:

> The Docket cache is a persistent WordPress Object Cache that is stored as a plain PHP code. Intends to provide an alternative option for those who can’t use Redis or Memcached server.
> 
> Rather than using [serialize](https://www.php.net/manual/en/function.serialize.php) and [unserialize](https://www.php.net/manual/en/function.unserialize.php) a PHP object to store into flat files, this plugin stores data by converting the object into plain PHP code which results in faster data retrieval and better performance with Zend OPcache enabled.

So that made me thinking, if something like that could be used in CIDRAM. I mean that kind of caching, "plain php code" or whatever that means :)

**Comment by Maikuolan** [comment]
First time for me ever hearing of Docket Cache before. Won't really know whether it's something CIDRAM can do until I figure out what exactly their plugin is doing in the first place, to be able to compare. Looks interesting though, and though I've never used it before, my first impressions about their plugin are positive (lots of good reviews, no bad reviews, code seems to be well-written and clean, at least stylistically, though I haven't actually tried executing any of it just yet, and seemingly fast support AFAICT, etc). Looking into it now. :-)

**Comment by eurobank** [comment]
I'm using their plugin for a while now, with no issues and looks great. It is their idea that i wanted to point out.

**Comment by eurobank** [comment]
I'm running Docket Cache in one WP site i have. See what i noticed in the capture:

![263451366-99126ce5-f9dd-4a24-9926-4c5c00d81cb6](https://github.com/CIDRAM/CIDRAM/assets/4467158/3be2f7da-a629-41d3-8285-dee111133acb)


While CIDRAM is OUTSIDE the Wordpress site, it IS cached by Docket Cache! Apparently since CIDRAM is prepended ......

How about that :) Maybe we gain some more speed for CIDRAM.... who knows ....

**Comment by Maikuolan** [comment]
Interesting.

**Comment by 737simpilot** [comment]
I'd be careful allowing CIDRAM to be totally cached. Because of my use of Cloudflare, I have page rules that exempt CIDRAM's folder...

Off topic, but on the topic of flat files, I have a WP website and want to migrate to a pretty cool flat file CMS called Grav CMS. Reason being is two fold: 1) It doesn't require a database and 2) it's not as sought after by would-be hackers. Lets put it one way about hackers and WP. Every single day I see WP vulnerability scanning bots one after another get blocked in Cloudflare. That's how sought after vulnerable WP installations are. Probably because WP is so popular for everyone's website needs. So migrating to something like Grav CMS will lessen your hack exposure. Especially an SQL injection vulnerability as well.

Docket Cache does look really interesting though.

**Comment by eurobank** [comment]
@Maikuolan The thing is CIDRAM is located OUTSIDE the Wordpress site, still it is cached. Apparently because it has the admin entry point ....

I don't see any issues ... still who knows ...

As for Grav CMS, i have so many plugins and code and things with WP, that i can't switch. But for a new site, i will check ...
