### ISSUE TITLE
AI bot

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#510]
visited by this ..
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.0; +https://openai.com/gptbot
not very smart but generated a lot of GETS - uses Azure so likely blocked anyway but you may want to block the UA

**Comment by Maikuolan** [comment]
Covered by commit 23fcbca06696b5a810465f3d814abc23a3bcbf55 (v3.4.0/2023.08.10). :-)

In order to cover the differing views that CIDRAM users may potentially have about it, and considering that means for verification has already been provided for these bots by their developers, rather than blocking it outright via a module, I opted to instead implement support for it to CIDRAM's verification mechanism, with instructions included at the configuration page for how to block it outright if so desired.

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/38d37118-aa91-4258-ae4e-2d75df2ef2aa)
