### ISSUE TITLE
Question on blocking Proxies with aux rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#511]
@Maikuolan Hi,

Do you think we can make some Aux Rule to have this ? And if yes, how?

Thanks

RewriteEngine on
RewriteCond %{HTTP:VIA}                 !^$ [OR]
RewriteCond %{HTTP:FORWARDED}           !^$ [OR]
RewriteCond %{HTTP:USERAGENT_VIA}       !^$ [OR]
RewriteCond %{HTTP:X_FORWARDED_FOR}     !^$ [OR]
RewriteCond %{HTTP:PROXY_CONNECTION}    !^$ [OR]
RewriteCond %{HTTP:XPROXY_CONNECTION}   !^$ [OR]
RewriteCond %{HTTP:HTTP_PC_REMOTE_ADDR} !^$ [OR]
RewriteCond %{HTTP:HTTP_CLIENT_IP}      !^$
RewriteRule ^(.*)$ - [F]

**Comment by Maikuolan** [comment]
In a standard, vanilla CIDRAM installation? Not currently possible, due to that the conditions for a rule are populated from a list of predefined sources, which are then matched against the values specified for those sources by whoever's writing the rule, and that particular rewrite engine rule is checking whether anything (any value) is defined for a bunch of HTTP headers (or potential sources, per auxiliary rules terminology), none of which currently exist in the list of predefined sources for auxiliary rules.

To change that, I'd need to either add them to the list, or find a way to provide the ability to specify custom sources as an alternative to the list at the auxiliary rules page, which I'm not currently entirely sure how to do.

Though, in theory, the auxiliary rules system *is* extensible by way of the imports system, and if you were planning to use any of those conditions for *multiple* auxiliary rules, it *might* be worthwhile extending the auxiliary rules system at your installation in order to make it possible to use those sources with auxiliary rules. But, if you were to use those conditions for just the one rule only (e.g., to have CIDRAM handle an equivalent of that specific rewrite engine rule instead of leaving it up to the rewrite engine), it would be easier and simpler to just create a custom module for it instead, I think.

Extending the auxiliary rules system isn't *too* complicated to do, but it *would* be *slightly* more complicated than creating a custom module to achieve the same thing in this case (which is why it might be better to extend in the case of writing *multiple* auxiliary rules, because once done, writing the actual rules themselves won't take any longer to do than writing any other auxiliary rule as usual, whereas for modules, you'd be needing to edit the module any time you wanted to change something, or needing to create new modules in some cases, so any extra time spent in extending is likely to be gained back by saving time any time a new auxiliary rule is written due to not needing to mess around with modules instead; on the other hand, if we're talking just *one* auxiliary rule, it would be easier and quicker to just create a module, given it would be a little quicker to write a custom module than to extend the auxiliary rules system, and not reusing it means no time saved via reuse).

Let me know if interested in how to do either of those things (extending auxiliary rules or creating modules) and I'll post more information about it at that time (rather than posting about it right now; to avoid flooding the issue with needless information overload as best as possible '^.^).

**Comment by eurobank** [comment]
Thanks, no more details needed. Not worth it since i can use .htaccess.
