### ISSUE TITLE
Notices in log-file

### ISSUE THREAD

**Issue by eydun** [CIDRAM/CIDRAM#513]
I have a couple of these errors in my log-file:

```
Notice: fwrite(): write of 1262 bytes failed with errno=13 Permission denied in ..\vendor\cidram\cidram\vault\Maikuolan\Common\Cache.php:243
```

In line 243 in `Cache.php` it says: 
```php
if ($Locked) {
243:                        fwrite($Handle, serialize($this->WorkingData));
244:                        flock($Handle, LOCK_UN);
245:                    }
```
I am not sure, if it is anything to worry about?

**Comment by Maikuolan** [comment]
Due to how file locking works in PHP (relying on the underlying operating system), it *possibly* might be a problem with the way the operating system handles locking (e.g., mandatory locking under Windows versus advisory locking under Unix and *most* Linux systems), but I'm not 100% sure (though maybe like.. ~90% sure..?). If it is, not much we can do about it, unfortunately.

If PHP runs on multiple threads or processes (as is the case for a majority of webhosting providers and servers nowadays), it's possible that race conditions might come into effect between different requests being handled by different instances of CIDRAM running on different threads/processes simultaneously. CIDRAM's cache system utilises file locking when using flatfile caching in order to avoid the situation where different threads/processes attempt to write to the cache at the same time, corrupting the entire cache and causing all cache data to be lost, or in the worst-case scenario, writing partial data which CIDRAM then unserialises in the wrong way.

When locking works as intended, if one thread/process has already acquired a lock on the cache file, the other thread/process should be forced to wait until that lock has been relinquished before being allowed to read from or write to the cache file itself, thus avoiding worst-case race conditions concerning the cache file. If the wait exceeds a predetermined limit, the request will simply fail and an error logged that the instance failed to connect to the cache.

Instead, what we're seeing here is the error you've cited above, which (assuming that what I'm thinking is correct, which again, I'm not 100% sure is the case) would suggest that one process is successfully acquiring the lock, but the other process, instead of waiting as it should, is just plowing on ahead and attempting to read from the cache file at the same time, and then, of course, failing, and generating that "permission denied" error, due to the presence of the lock.

A little annoying insofar as error messages are concerned (because of there being very little we can do about it), but not overly concerning, as it doesn't indicate anything wrong with the installation itself, doesn't indicate any kind of security problem, etc.

I doubt the error is caused by CHMOD permissions, because if it was, instead of at the `fwrite()` call, I would've expected the error message to be generated at the `fopen()` call about 15 lines earlier. Not really sure what else could cause the error.

**Comment by eydun** [comment]
Thank you for the thorough reply!

I can confirm this is a Windows Server. The incidents are during high-load periods.
