### ISSUE TITLE
Infractions issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#517]
This can't be right?

ID: 1695078272-879804-2108932806 »
Date/Time: Tue, 19 Sep 2023 02:04:32 +0300 »
IP address: 74.249.244.71 »
User agent: Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36 »
Signatures reference: bobuam.php:L161, botua.php:L411, auxiliary.yml:User Agents Regex 1 »
Why blocked: Banned, Outdated browser (C), Attack UA, User Agents Regex 1! »
Reconstructed URI:    /dropdown.php »
I**nfractions: 80,000 »**
Country code lookup: US »
Request method: GET »
Hostname: - »

ID: 1695078268-662777-7891907745 »
Date/Time: Tue, 19 Sep 2023 02:04:28 +0300 »
IP address: 74.249.244.71 »
User agent: Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36 »
Signatures reference: bobuam.php:L161, botua.php:L411, auxiliary.yml:User Agents Regex 1 »
Why blocked: Banned, Outdated browser (C), Attack UA, User Agents Regex 1! »
Reconstructed URI:             /wp-admin/css/index.php »
**Infractions: 77,000 »**
Country code lookup: US »
Request method: GET »
Hostname: - »

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/ec90fcc6-fe8a-4600-8dad-ca53e0e5c772)

**FIVE MONTHS FROM NOW !!!!!!!!!!!!!!!!!!!!!!**

**Comment by Maikuolan** [comment]
I *have* before, seen some specific IPs which attacked some of my websites so badly, and with such frequency, that they were able to accumulate such large numbers of infractions, due simply to being blocked that many times.

However, in this particular case..? Gaining 3,000 infractions within a 3 second period, definitely does *not* look like a case of being blocked that many times.

Given the 5 months tracking period, given that the infractions seem to be jumping in increments of 1,000, and given also that the affected block events seem to both have a signatures count of 3, I'd wager that "extended IP tracking options" has been enforced for the affected block events.

When "extended IP tracking options" are enforced, instead of the usual 1 signatures count = 1 infraction, the infractions will instead be calculated as 1 signatures count = 1,000 infractions, in order to artificially induce an immediate banned status for the IP address related to the affected block event, and the track time for its IP tracking entry is adjusted against a multiplier, in order to help the ban remain in effect for a longer time than usual.

At the auxiliary rules page, under "User Agents Regex 1", do you see something like this? Either when in view mode:

![1](https://github.com/CIDRAM/CIDRAM/assets/12571108/6ea88b39-b8cf-44d4-92a9-7bf648a38ae4)

Or when in edit mode:

![2](https://github.com/CIDRAM/CIDRAM/assets/12571108/6845f4b6-50b9-4798-b393-0c4c0d1d375c)

If so, then that's likely the culprit here. If not, then.. I could only imagine it's being somehow invoked via some other means, and I'll need to investigate those modules, to check whether it's being invoked from either of those points somehow.

**Comment by eurobank** [comment]
No enforce IP tracking options.

**Comment by eurobank** [comment]
Let's wait to see if it happens again.
