### ISSUE TITLE
Test IP Question

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#518]
Testing an IP, i get

**Blocked: Error – auxiliary.yml (64)**
Tracking: Yes
Banned: No
Status code: 403 Forbidden

Is that "Error" part correct?

**Comment by Maikuolan** [comment]
If it shows *"Blocked: Error – auxiliary.yml (xx)"*, it means that some kind of error occurred while trying to test against the auxiliary rules. The number (in this case, 64) indicates how many errors occurred, or how many times an error occurred for any given test. The most common culprit for such errors, *almost* guaranteed to be the case the vast majority of the time, is an erroneous regular expression somewhere in one of the rules (though, the actual mechanism for detecting such errors isn't looking at regular expressions exclusively, but rather, just captures any errors generated throughout the test more broadly, checking at which stage of the test the errors occurred; e.g., whether during the execution of a module, during the auxiliary rules, or something else; and then, for the given test, if anything is captured, reporting the results of the test back as "error" accordingly, marking the stage where the errors occurred, and the number of occurrences of an error or errors; so, it *could* be caused by something else too).

Any recent changes to any auxiliary rules where regular expressions are being used?

**Comment by eurobank** [comment]
@Maikuolan Errors in some in ALL aux rules or the particular one?

**Comment by Maikuolan** [comment]
Generally, it would be a particular one, but it could be more than one.
