### ISSUE TITLE
Stats question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#521]
trying to reconcile some numbers ...

is there ever a case where a blocked or banned item is not added to the stats. Like maybe tracking or logging is turned off through an aux rule ?

**Comment by Maikuolan** [comment]
If the checkboxes for requests blocked or request banned were unchecked at **`general➡statistics`** under the configuration, that would do it.

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/215830e7-210f-46a6-8bd0-516a373d06cc)

Beyond that though, there shouldn't be. The only option provided by auxiliary rules which relates to statistics is providing an option to track the rule itself, to know how many times that particular rule has been triggered. There isn't anything at auxiliary rules specifically for disabling statistics.

Log suppression shouldn't have any effect on statistics. The order of the stages of execution in CIDRAM also places updating the statistics earlier than writing to the logs, so anything that might potentially happen while writing (or not writing) to the logs shouldn't have any effect on CIDRAM's ability to update statistics due to the statistics having already been updated by that point in the execution chain anyway.

If a particular statistic seems lower than it should be, the most likely culprits that come to mind are:
- Statistics being reset at some point, thus resulting in numbers being lower than expected.
- If flatfile caching is being used, and the server in question has multiple parallel PHP processes running, it's possible that two or more of those parallel PHP processes might be attempting to read from the cache file at the same time, locking each other out, resulting in some of them not being accounted for by the statistics (which currently, are stored in the cache). Something I might possibly need to consider changing for a future v4, maybe.

That's just what immediately comes to mind though, and I can't be certain about the specific cases at hand.
