### ISSUE TITLE
Request: Log match in Aux Rules, if multiple are checked

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#524]
My and my requests ..... :)

Many Aux rules have multiple asns, user agents etc etc, all in one rule. 

Can we have the reason (the match) in the Why Blocked line? So we know exactly why it is blocked.

thks

**Comment by eurobank** [comment]
@Maikuolan Can i have some code i can manually insert? Because i have merged many aux rules and when a aux rule block is triggered, i don't know the detailed reason.

For example something like that:

Why blocked: ASN - Dangerous #1! 

It would be nice to see

Why blocked: ASN - Dangerous #1! Reason: ASN 872643564

**Comment by Maikuolan** [comment]
Not quite sure exactly how I would go about doing that just yet, but I'll think on it a bit and let you know what I can come up with. :-)

**Comment by eurobank** [comment]
I don't mind to manually edit my installation, even after each update. I mean add some line of code myself for the time being.

**Comment by Maikuolan** [comment]
Got something working for this now. Just need to finish off some other, peripheral changes to the code that I'm working on to get it to a stable state and I'll be able to push the changes. Will reply back again shortly.

**Comment by Maikuolan** [comment]
Changes pushed. :-)

No documentation or indication about the changes at the UI yet (haven't had enough time, but I'll get there eventually), but I can describe/demonstrate the changes here.

It's now possible to have bytes matched by capture groups be reflected into an auxiliary rule's name or block reason.

*What are "capture groups"?*
"Capture groups" refers to the bracketed parts of regular expressions capable of capturing bytes. Say, for example, if you have an auxiliary rule which uses regular expressions to test its conditions, and one of the conditions of that auxiliary rule looks something like `/^(123|456|789)|(abc|def|ghi)$/`. In that regular expression, there are two "capture groups". The first is `123|456|789`, and the second is `abc|def|ghi`. When the regular expression matches some bytes according to the capture group, those bytes will be "captured", according to the group number.

*How to reflect that into the name or block reason?*
Firstly, there must be a condition which uses a regular expression with capture groups in it, otherwise nothing will happen. Once we've got that, in the name or block reason, wherever we want the captured bytes to be reflected, just add a "backslash" (`\`), followed by the group number, and update the rule. The next time a match occurs, the bytes will be reflected according to the matches which occurred.

Let's say, just as an example, in our auxiliary rule's name, we have `My rule for \1! And also \2!`. Using the example condition from before, if we have a match for "456", the logged "why reason" should appear as `My rule for 456! And also !`. If we have a match for "def", the logged "why reason" should appear as `My rule for ! And also def!`.

**Comment by eurobank** [comment]
@Maikuolan What about if you have only

/^(123|456|789)$/

and if you have several lines (conditions) in the same rule?

/^(123|456|789)$/
/^(2123|3456|4789)$/
/^(3123|4456|5789)$/

**Comment by Maikuolan** [comment]
Having only one capture group is fine.

When there are several such conditions, the first condition which produces a *match*, and is an *"equal to"* condition, will have its capture groups reflected. Conditions which don't produce any match, and conditions which are *"not equal to"* conditions, won't be reflected. After that first condition which fulfills the criteria, any subsequent such conditions won't be reflected.

**Comment by eurobank** [comment]
Ok, this

Why blocked: ASN - Dangerous 394711!

seems to work fine.

**Comment by eurobank** [comment]
That also seems to work fine!

Why blocked: User Agents # 1 mail.ru!

thanks!!!

**Comment by eurobank** [comment]
@Maikuolan There seems to be some issue with statistics:

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/bc44417f-d436-40c6-a2ea-41d2640e128e)

**Comment by eurobank** [comment]
Solved by moving the " \1" from name of aux rule to Reason

**Comment by eurobank** [comment]
Well, moving the "\1" to the Name brings back teh statistics but then there is no log of the condition met. 

So something is wrong in there.

**Comment by Maikuolan** [comment]
Good spotting. :-)

Haven't investigated yet (long shift at work last night and haven't been up long today), but I suspect I might know what's wrong here. I'll take a look shortly.

**Comment by Maikuolan** [comment]
Pushed a fix just now. None of my installations currently have enough statistical data connected to any of the kinds of rules affected by this bug, so I haven't been able to test the fix thoroghly, unfortunately. It *should* work, in theory. Let me know how it goes when you've got a moment. :-)

**Comment by eurobank** [comment]
I will of cource, as usual.

**Comment by eurobank** [comment]
Sorry to say but the stats are GONE for that specific rule when  \1 is used in the name.

**Comment by eurobank** [comment]
Maybe this helps:

[24-Dec-2023 12:38:59] PHP Warning: preg_match(): No ending delimiter '^' found in /home/xxxxxx/vault/Maikuolan/Common/Cache.php on line 951

**Comment by eurobank** [comment]
[24-Dec-2023 12:38:59 Europe/Athens] PHP Warning: preg_match(): No ending delimiter '^' found in /home/xxxxxx/vault/Maikuolan/Common/Cache.php on line 951

**Comment by Maikuolan** [comment]
> Maybe this helps:

It does. '^.^

PHP warning is due to a small typo in my previous commit (which I hadn't noticed before). Pushed a fix (for the typo) just now. Hopefully that'll see some improvement.

**Comment by eurobank** [comment]
Now it seems to work right. If i see something, i will reopen this.

Thanks
