### ISSUE TITLE
Valid UA

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#527]
I think this is valid ?

User agent: Mozilla/5.0 (Linux; Android 11; Doro 8100 Build/S10A_703) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36 
Signatures count: 1 
Signatures reference: bobuam.php:L83 
Why blocked: Suspected bot or scraper probe!

**Comment by Maikuolan** [comment]
I'm not 100% sure whether that exact specific UA is valid, but I'm treating it as a false positive anyway, for a couple of reasons:
- Searching for it at Google, verbatim and in quotes, produces literally zero results whatsoever, which isn't *usually* a great indicator of a user agent being valid. However, "Doro" *is* a real, legitimate mobile phone manufacturer, and "Doro 8100" *is* a real, legitimate phone model that they produce (cited in the user agent), which *does* use Android version 11 (also cited in the user agent), and, although I'm not super familiar with that specific phone model, nor what user agent any browser running on it might ordinarily produce, all the parts *do* add up to something which I imagine *could* be a valid UA.
- The specific signature in BOBUAM responsible for blocking that UA was written in such a way that any user agent containing "Do" would be blocked ( ...`o(?:|m(?:ain`). That kind of blocking is *way* too wide, as would be *any* kind of blocking when on on the sole basis of any two specific A-Z characters together in a user agent, and it would be almost guaranteed to block things we don't want being blocked ("Doro" aside, one other immediate example that comes to mind for "Do" is "DoCoMo", a popular provider in Japan). As such, considering that specific offending signature was the *only* signature in CIDRAM blocking that particular user agent, regardless of whether or not that specific user agent is valid, it's still reasonable to consider the block as a false positive, given that in any case, it shouldn't have been being blocked by that particular signature.

I've removed the bar from that particular signature so that it can continue to function as it was originally intended, but *without* blocking "Do" anymore. So, fixed. :-)

**Comment by mikeruss1** [comment]
thank you - google was very odd with no results, tried elsewhere and got a lot back. Recaptcha was passed which was the clincher.
