### ISSUE TITLE
VPN access of CIDRAM Protected Sites

### ISSUE THREAD

**Issue by 100percentlunarboy** [CIDRAM/CIDRAM#53]
Hiya,

Finally got a VPN setup at home.

What is the best way to configure CIDRAM when using a VPN from home to access my CIDRAM protected sites.

Right now I am setting block_cloud=false

(Correction: I changed block_cloud=true after watching my logs fill with fear and loathing... )  :fearful:

Is there a way to access my sites using my VPN without opening the gates of hell...

**Comment by Maikuolan** [comment]
Hey,

If you're currently being personally blocked by CIDRAM when attempting to access your website through a VPN, the best way to remain unblocked, I think, would be to either whitelist the specific CIDRs/IPs that you're connecting from (assuming that the CIDRs/IPs in question don't change too much), or to [write a custom bypass](https://github.com/CIDRAM/CIDRAM/blob/master/_docs/readme.en.md#751-bypass) (for example, if there's some special identifiers unique to these requests, aside from just the IP address, like maybe a custom user agent or something like, these could be combined to create a a tighter entry point, which should allow you in, but not others thing that might be connecting from the same CIDRs/IPs and such).

Otherwise, if *others* are being blocked as a result of accessing your website through VPNs, and you don't want them to be blocked, setting `block_proxies=false` should help somewhat to prevent this from happening.

IPs/CIDRs used primarily as proxies, VPNs, and other related types of endpoints will (in most cases) be associated by CIDRAM with the `block_proxies` directive and either blocked or not blocked accordingly.

In general, that's about as much consideration as would be required for setting up CIDRAM on a website that needs to be accessible via VPNs. :-)

Depending on whether specific required VPNs are being blocked via others means and such though, there may occasionally be other considerations.

**Comment by Maikuolan** [comment]
*Marking as "Resolved" and closing.*

If any problems emerge, let me know. :-)

**Comment by 100percentlunarboy** [comment]
Thanks! 

You gave me all the info I need.
