### ISSUE TITLE
Legitimate user being blocked due to ip in DigitalOcean range

### ISSUE THREAD

**Issue by Wormnest** [CIDRAM/CIDRAM#538]
A user of a website I manage in the Netherlands apparently has an ip in the DigitalOcean range. From the screenshot it says 178.62.216.x.

He's visited the website before, so it probably is a recent change. I have asked him if he was using his regular internet connection, but not received an answer yet.

Website (bietschildt.nl) is using Wordpress and atm I do not have customized settings. 

Version of CIDRAM used: 3.4.1

**Comment by eurobank** [comment]
All Digital Ocean Ips seems to be webservers and other NON HUMAN points. 

And what is the EXACT IP? You have anonymized it.

**Comment by Wormnest** [comment]
User said he uses his normal home internet that didn't give problems in the past. IP address is anonymized by CIDRAM.

**Comment by Maikuolan** [comment]
Sorry for the delayed reply, and thanks for your patience. It's been a busy week with work this week for me, with limited time left to get around to everything else afterwards. Spotted this issue when it was first created, but not entirely sure the best way to approach it just yet, in order to provide the best advice.

Like eurobank already mentioned, Digital Ocean ranges, generally speaking, consist of webservers, cloud service providers, etc. For there to be someone using those ranges, perhaps, to operate a proxy for their internet connection (I speculate here, because I of course don't know the specific details about this specific user, but knowing that Digital Ocean is not intended to operate as a typical ISP for typical human internet access, but also knowing that such a thing – setting up a proxy at a cloud service provider's infrastructure to be able to access the internet while avoiding revealing the IP address for one's actual, real home internet connection – is possible, easy, and simple enough to do if one knows how to, and is done often enough to be considered as not totally unreasonable), and for them to then visit or participate at a website, which uses CIDRAM, it would likely be in the interest for something to be done by the website owner at their particular CIDRAM installation to properly facilitate that user's continued access to their website.

But, given the intended nature of those ranges, and given the *significant* amounts of unwanted traffic reported as originating from __[178.62.216.0/24](https://www.abuseipdb.com/check-block/178.62.216.0/24)__ at AbuseIPDB (at the time of writing this reply, 6,434 reports there, with the most recent being from only 38 minutes ago, and no signs of that unwanted traffic diminishing at any time in the near future) and elsewhere (and that's quite a large number of reports for a mere 256-address range), I don't see mainlining any changes at the upstream (e.g., removing that range from the default signature files entirely, to be applied to *all* installations) as viable at all, due to the risk of CIDRAM users more broadly receiving unwanted traffic from that range.

That being the case, that would leave doing something at the downstream (i.e., at your specific installation) as the most likely solution here (e.g., writing a bypass for that range, such as via an "auxiliary rule", or instructing CIDRAM to ignore that signature section via the "sections list", etc). But, such a suggestion would, from the perspective of a CIDRAM installation running on a WordPress-powered website, effectively be a kind of customisation, and as you've mentioned you don't yet currently have any customisations, I'm not sure whether such a suggestion would ultimately be such a comfortable suggestion to be receiving.

With provided instructions, it should be simple enough to write a bypass, to instruct CIDRAM to ignore that signature section, etc; and we can help you with that, by providing advice, suggestions, instructions and so on. But, on the assumption that you're currently updating your WordPress plugins/themes/etc via the usual recommended means (e.g., via automatic WordPress updates, via cron, by way of clicking the update button from the plugins page, etc), in order to ensure that those customisations don't disappear whenever CIDRAM is updated, the workflow for updating CIDRAM would need to change (i.e., updating CIDRAM via the CIDRAM front-end updates page, instead of via automatic updates or via the plugins page, in order to utilise CIDRAM's own internal update mechanism, which is designed in such a way that all customisations should be retained).

Ideally, I would prefer to not overcomplicate any users' workflows, when/if at all possible. Hence being not entirely sure the best way to approach this issue just yet. '^^ Still trying to think up a better solution in the meanwhile.

**Comment by eurobank** [comment]
https://cleantalk.org/blacklists/as14061

**Comment by Wormnest** [comment]
Although it crossed my mind, this user doesn't seem to be the person to *knowingly* use any services that would go through DigitalOcean or similar.

I totally understand that generally disabling this range doesn't seem like a good idea. I have had the separate frontend for CIDRAM enabled in the past with some customizations, but just like you I'm often short on time. Besides that, if I ever felt the need to stop being the webmaster, a replacement would most likely have less knowledge about these things. So, maintenance in that case is also a worry.

So, provided I have some more time, I need to evaluate, which way to go with this. Anyway, I thought it good to open an issue anyway, just so that you are aware of a possible issue in case you get more similar reports.

Also thank you with your efforts in providing this script and keeping it up-to- date.

**Comment by Maikuolan** [comment]
Maybe enabling one of the CAPTCHAs supported by CIDRAM (reCAPTCHA, HCaptcha) could suffice as a solution?

Though still a kind of customisation, unlike other customisations (installed components, auxiliary rules, the ignored sections file, modules, etc), changes to the configuration should still be retained between CIDRAM version updates, even when performed via the usual recommended means. The reason for that being that since more recent versions of the CIDRAM WordPress plugin, the configuration file is backed up to the plugins directory (the immediate parent directory of CIDRAM's plugin directory) as `cidram-configuration.yml`.

Because enabling CAPTCHAs via the configuration is just a matter of a few changes to the configuration (i.e., no new components, special files, etc required), doing *that*, at least, should be retained between updates.

The downsides would be that the user would still need to pass through the CAPTCHA, which could be potentially annoying for the user in question (either needing to complete it, or, if an "invisible" API is utilised, they should be passed through automatically in most cases), that they'd still end up with a blocked request being logged (at least once, but hopefully not twice, once the CAPTCHA has been passed), plus potential A11y concerns in some rare cases (e.g., for vision-impaired users; but unlikely to be a concern for the majority of users).

The upsides would be that there'd be no need to write any custom bypasses, auxiliary rules, etc, that the change, unlike alternatives, should be retained, that it should at least provide a means to regain access to the website again, and slightly better reusability than alternatives (i.e., the potential for it to also provide other users in the same situation a means to regain access, whereas in the case of bypasses, auxiliary rules, etc, other users in the same situation would likely need their own bypasses too, depending on how narrow/wide the hypothetical bypass in question would be).
