### ISSUE TITLE
Wrong Cloud service ("Inter Connects Inc)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#541]
https://ipinfo.io/196.242.131.207

But reported as ("Inter Connects Inc)

same for 

https://ipinfo.io/165.231.24.200

and 196.242.200.201

All those seems to come from Fibergrid

**Comment by Maikuolan** [comment]
I currently have the Inter Connects and Fibergrid ASNs blocked under the same, singular signature section, due to heavy interlacing between their networks. This combined signature section is currently tagged/named as "Inter Connects Inc", due to that the Inter Connects ASNs were added to the signature files before any of the other ASNs combined in that section (thus maintaining a consistent name for that signature section for users). I can see it potentially leading to confusion though (i.e., listing the name for one organisation even though it blocks multiple organisations' ASNs which could suggest there being false positives). Maybe I should rename it to something else to reflect the fact that it's a combined signature section? I'm not sure. What do you reckon?

**Comment by eurobank** [comment]
Nope, leave as it is. Not an issue.
