### ISSUE TITLE
Duplicate Signatures reference: 23.230.0.0/16, 23.230.42.0/24

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#542]
This

Signatures reference: 23.230.0.0/16, 23.230.42.0/24 »
Why blocked: Cloud service ("EGIHosting", L6999:F0, ), Cloud service ("Sprious LLC", L27199:F0, )! »

Seems to be Sprious LLC

https://ipinfo.io/23.230.42.26

**Comment by eurobank** [comment]
Same for 

Signatures reference: 142.252.0.0/16 »
Why blocked: Cloud service ("EGIHosting", L7019:F0,

https://ipinfo.io/142.252.198.102

It is Sprious LLC

**Comment by Maikuolan** [comment]
It seems the range is currently being announced by both networks simultaneously. Not sure whether one of the announces might be invalid maybe, or which would be valid/invalid, but as there are RIR records for the range under both ASNs, although we generally would want to avoid having duplicates as much as possible, the duplicates in this case could *technically* be regarded as not being due to a false positive. (Yeah.. Even while writing this reply, I don't quite like how it sounds myself.. '^^).

Not the first time this has happened, and often, when this has happened before, I've just merged the signature sections together, because, even if multiple ASNs announce the same range, if those ASNs' ranges are aggregated together, we still end up with just the one signature for each affected range anyway, thus solving the problem at our end as far as we're concerned, and an easy enough way to go about it.

Not sure whether I want to do that here though, because both signature sections ("EGIHosting" and "Sprious LLC", or.. since the time of a signatures update which occurred a little after the time that this issue was first created.. now "EGIHosting/H4Y" and "Sprious LLC") are reasonably large, and other than that particular range, don't have a great deal of interlacing, so there's good reason to have them remain as their own distinct signature sections.

Maybe we just ignore this one for a while?
