### ISSUE TITLE
Fake Google bot not blocked as FAKE

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#544]
This

ID: 1701620705-082331-4900461869 »
Date/Time: Sun, 03 Dec 2023 18:25:05 +0200 »
IP address: 185.66.14.133 »
User agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »
Signatures reference: 185.66.12.0/22 »
Why blocked: Cloud service ("Internet Technologies LLC", L39436:F0, )! »
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: - »

shouldn't be reported as fake google bot?

**Comment by Maikuolan** [comment]
Definitely fake, but likely not blocked due to its DNS being unresolvable via CIDRAM (requests with entirely unresolvable DNS being treated simply as non-verified, as there's no way for CIDRAM to easily tell the difference between DNS lookups which simply failed, e.g., due to a timeout or connection failure, versus DNS lookups which aren't possible due to unresolvable DNS, i.e., CIDRAM's way of saying, *"I'm not sure whether this is real or fake, so I'll leave it alone, just in case, to avoid false positives"*, because there are a number of search engines, like Bing, as a notable example, for whom DNS lookups are frequently very unreliable).

**Comment by eurobank** [comment]
correct!
