### ISSUE TITLE
Duplicates signatures

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#546]
Signatures reference: 85.239.36.0/22, 85.239.36.0/22 »
Why blocked: Cloud service ("K SERVERS LTD", L6875:F0, ), Cloud service ("Internet Technologies LLC", L39383:F0, )! »

https://ipinfo.io/85.239.38.61

**Comment by Maikuolan** [comment]
It seems the two signature sections had a significant amount of interlacing between their ranges, so I've gone ahead and merged the "K SERVERS LTD" signatures section into the larger "Internet Technologies LLC" signatures section just now. The "K SERVERS LTD" signatures section only covered a single ASN, whereas the "Internet Technologies LLC" signatures section covered a large number of different ASNs already due to previously discovered heavy interlacing, so it made sense to merge the smaller section into the larger section. :-)

**Comment by eurobank** [comment]
Yes, to be honest sometimes it is really hard to distinguish them ..... IP renting, old data, etc etc
