### ISSUE TITLE
Google Blocked?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#552]
this looks like Google to me ?

Date/Time: Fri, 15 Dec 2023 01:48:07 +0000 
IP address: 66.249.83.85 
Query: - 
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google-PageRenderer Google (+https://developers.google.com/+/web/snippet/) 
Signatures count: 1 
Signatures reference: bobuam.php:L128 
Why blocked: Suspected bot or scraper probe! 
Infractions: 3 
Request method: GET 
Protocol: HTTP/1.1 
Hostname: google-proxy-66-249-83-85.google.com

**Comment by Maikuolan** [comment]
That user agent belongs to the [Google Web Snippets](https://developers.google.com/search/docs/appearance/featured-snippets) service, a feature used by Google Groups and the (former, now shut down and defunct since 2019) Google+ service. Legitimate, though has no bearing on the Google Search engine (different bot, different service).

AFAICT, seems legitimate. I'll modify the offending signature now.

**Comment by mikeruss1** [comment]
thanks, looks like it includes a referral page within a SMS

**Comment by Maikuolan** [comment]
Fixed. :-)
