### ISSUE TITLE
Logging not working?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#558]
something very odd going on, everything working normally until a couple of days ago when I noticed the log file was empty. However it seems the log file had been created at the time the first error should have logged, but no entry. tracking entries are there so processes are working. Tried a GET it should have blocked, logged and track, all correct but no log entry. Tried the same thing on my domestic test machine, all worked fine. Caching is Redis.

nothing has changed since before xmas, apart from signature updates.
I do have several aux rules which turn off logging, tried disabling, tracking works, no log.
Looked back over the last month, there isnt a day where I dont get a log entry and I cant remember it ever happening. 
Looked at the log and the 403s are all there.
recaptcha entries are written to the log

Suggest not spending too much time, will let you know if it starts working again.

**Comment by Maikuolan** [comment]
Could be related to #556, maybe? Any idea whether your hosting provider might be running Imunify360 at your server by any chance?

**Comment by mikeruss1** [comment]
indeed it is and reports like this starting 3 days ago, its the same as 556

<html>
<body>

ran hour ago | Report black hash triggering | /xxxxxxx/cidram3/vault/events/default.php 1 |   | 193.22.152.103 | BLOCK | remove_
-- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by mikeruss1** [comment]
need to do some research, it looks like I can tell it to ignore this detection - what you think ?

**Comment by mikeruss1** [comment]
have whitelisted and all working OK
more generally whats the problem - is Immunify too sensitive, should I raise with my provider ?

**Comment by Maikuolan** [comment]
Ignoring that detection will definitely solve the problem, at least for your own installation.

The situation still annoys me though, because presumably, the problem would be affecting *any* CIDRAM users which happen to also have Imunify360 running at their servers, and unless they decide to visit the issue tracker to seek help on the issue as how eurobank and yourself have done, they'll likely remain entirely in the dark about the problem, and continue to be affected.

While ignoring the detection will solve the problem for the particular servers where that's done, I'd love to be able rectify the problem at a higher level, either by figuring out *why* Imunify360 is falsely flagging that file and making any needed changes accordingly, or finding some way to work around it, but right now, I have no idea how to go about it.

So for now, just ignoring the detection is probably the best we'll be able to do. Fingers crossed to eventually figuring out something better though.

**Comment by mikeruss1** [comment]
will see what hosting folks say

**Comment by Maikuolan** [comment]
> is Immunify too sensitive, should I raise with my provider ?

Unless eurobank and yourself happen to have the same provider (I don't know whether that's the case or not, as I've never asked about that, but statistically speaking, it's probably not; a lot of different providers out there in the world, after all), considering the same problem is affecting both, I would assume that, rather than being the fault of the hosting provider, the fault likely lies with Imunify360's own default detection criteria, signatures, algorithms, etc. (I don't use Imunify360 myself, so I'm not entirely sure what their preferred terminology is, but you get the idea). Assuming that's the case, having Imunify360's people rectify that detection at the upstream, to be eventually synced at any affected servers at their next subsequent Imunify360 update, would be the *ideal* solution. I'll need to look into whether that's actually possible though; I don't know whether they have some point of contact available for such matters or not (haven't yet looked into it).

**Comment by Maikuolan** [comment]
Found the Immunify website. Clicking their Contact Us link just opens a window asking me to create a Windows Live email account, rather than opening any actual contact form or similar such page. No idea what's up with that.

**Comment by mikeruss1** [comment]
How to be helpful!

**Comment by 737simpilot** [comment]
Yep, just came here to see if others had the same issue as me. I went into cPanel and sure enough it was Immunify360. Had to whitelist that path to default.php.

Immunify360 and mod_security must have updated their rules because I also see warnings in the cPanel logs for mod_security all within the past several weeks. Though not related to CIDRAM, but of my website running phpBB.

**Comment by 737simpilot** [comment]
Their e-mail is sales@cloudlinux.com

Your OS configuration is creeping on you... Check out Atlas OS. Not for everyone though... It's  a series of scripts that strip the crap out of 10 and 11. I was pleasantly surprised by it. Not only by getting rid of the crap, by the huge reduction of telemetry as I was watching the NIC in VMware where I ran it. It turns off system restore, but that can be turned back on. Updates are gone too, but i don't pay homage to the patch Tuesday god so there's that... Again, it's not for everyone. 

I believe you also use Chrome. Check out Ungoogled Chromium here at Github... Not for everyone as well. I have that installed for testing Chromium on my website and what not, and Firefox, but my main driver is Pale Moon. It's niche though, again not for everyone... LOL! 

Is your default e-mail client setup up? If the Windows default mechanism doesn't work, I've had great luck with [this](https://defaultprogramseditor.com/).

**Comment by mikeruss1** [comment]
probably doesnt help but this is what its complaining about

`<html>
<body>

Name | Value
-- | --
EF_0_LAST_HASH | ab7cf78d64083339
EF_0_LEN | 12
EF_0_NAME | i:fopen,i:fopen,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace,i:str_replace
PHPAP_GID | 1037


</body>
</html>`

**Comment by 737simpilot** [comment]
E-mail finder websites like [this](https://newapp.anymailfinder.com/search/single) work great too.

**Comment by mikeruss1** [comment]
My hosting has their top people on today

"We think imunify360 is blocking CIDRAM"

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by 737simpilot** [comment]
Thanks.
