### ISSUE TITLE
Module Honeypot

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#562]
I have enabled for the 1st time the honeypot module. I have inserted my api but it doesn't seem to block anything for th elast 24 hours.

How can that be possible.

Do i have to install also a honeypot myself?

Is this my api key?

`
You have been issued an Access Key. The http:BL Access Key tied to your account is shown in the gray box. Only one Access Key is allowed per user. Sharing of Access Keys with other users is forbidden by the Project Honey Pot Service Agreement.
Your http:BL Access Key `

**Comment by eurobank** [comment]
I see a lot if IPs in the cache for project honeypot, so IPs are checked.

**Comment by Maikuolan** [comment]
> Is this my api key?

Yep. The box [where it shows that message](https://www.projecthoneypot.org/httpbl_configure.php) should show your API key. :-)

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/68c2a1db-893e-47ba-94c4-eaff47e225d6)

> Do i have to install also a honeypot myself?

Nope. Installing a honeypot isn't necessary for CIDRAM to be able to perform lookups to the Project Honeypot API.

> I have enabled for the 1st time the honeypot module. I have inserted my api but it doesn't seem to block anything for th elast 24 hours.
>
> How can that be possible.

Lookups worked properly when I tested the module at my end just now to confirm whether anything might've changed or broken at some point, so it seems okay.

Possible reasons I can think of why it mightn't have blocked anything yet:
1. The specific IPs being looked up simply haven't yet been caught by Project Honeypot, and so, from their perspective, there isn't anything to block.
2. Maybe __`projecthoneypot➡lookup_strategy`__ has been configured to *"None"*, or, if it's configured to *"Requests for sensitive pages only"*, maybe there hasn't yet been any requests to any recognised sensitive pages from any IP addresses known to Project Honeypot.

If we visit their [IP Data](https://www.projecthoneypot.org/list_of_ips.php) page, we can see a list of the IP addresses most recently identified by them as being malicious, so if we wanted some IPs to test at CIDRAM's IP testing page to confirm whether the module is working properly or not, that page would be a good place to get those IPs for testing from.

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/51f576cf-5afc-459d-a131-0ed53c6b8bf3)

For example, testing "120.143.36.80":

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/a54248c8-e5bf-4181-8375-83a2a3222eab)

Worth noting: Due to that Project Honeypot's HTTP:BL supports only IPv4, CIDRAM's Project Honeypot module checks whether the IP addresses to be looked up are IPv4 first, before performing any lookups, and it uses a flag set during the signature file tests execution stage to do so, meaning that lookups will never be performed for IPv6 addresses, and also will never be performed in cases where that flag hasn't been set. Because of that, when testing the Project Honeypot module using CIDRAM's IP testing page, as is in the screenshot, both *"Execute signature files tests"* and *"Execute modules"* will need to be selected in order for it to work. Possibly also *"Test as sensitive request"*, depending on how __`projecthoneypot➡lookup_strategy`__ has been configured.

**Comment by Maikuolan** [comment]
Another possible (but unlikely) reason: Some of the options at __`projecthoneypot➡type_of_visitor`__ being deselected.

**Comment by eurobank** [comment]
All settings are correct. 

Could be an issue since CIDRAM is used as one instance but with several sites?

**Comment by eurobank** [comment]
Using the IP you posted, it seems to work fine, still nothing is blocked the last 24 hours, or ever ...

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/4765c764-6596-4fc0-97d1-d4d4ebd15f9e)

**Comment by eurobank** [comment]
btw: the caching period for this module IPs is one hour only?

**Comment by eurobank** [comment]
For some reason it doesn't work for me at all. Nothing is blocked for almost 2 days now and that is not possible.
