### ISSUE TITLE
How to bypass this?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#576]
I have a LOT of similar blocks and i thing they are wrong. How can i bypass them? Lowering the browsers version?

IP address: 74.125.218.193 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 »
Signatures reference: bobuam.php:L161 »
Why blocked: Outdated browser (C)! »
Reconstructed URI: https  : // www domain name here /.well-known/assetlinks.json »
Infractions: 1 »
Country code lookup: US »
Request method: GET »
Hostname: rate-limited-proxy-74-125-218-193.google.com »

Those proxies are usually used from google services and i think they are legit 100%.

**Comment by eurobank** [comment]
Also shoudln't this IP be banned? After 18 infractions?

Date/Time: Sat, 13 Apr 2024 16:40:05 +0300 »
IP address: 35.171.69.89 »
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 »
Signatures reference: bobuam.php:L165 »
Why blocked: Outdated browser (F)! »
**Infractions: 18 »**
Country code lookup: US »
Request method: GET »
Hostname: ec2-35-171-69-89.compute-1.amazonaws.com »


Why the tracking is showing 1?
![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/578b66c2-f834-4ced-bc88-4d612dd5447a)

**Comment by Maikuolan** [comment]
> Also shoudln't this IP be banned? After 18 infractions?

Looking at the code, I've found a bug which *might* be having an effect there (not 100% sure). Working on a fix for that now.

**Comment by Maikuolan** [comment]
Fixed what I found at my end and pushed the changes. Hopefully that'll also resolve what you've found at your end (I think the two things might be related, but I'm not 100% sure).

**Comment by Maikuolan** [comment]
> Lowering the browsers version?

Yep. :-)

Looks like the browser version cited in that user agent is 91, so setting **`bobuam➡chrome`** to 91 should let it through.

**Comment by Maikuolan** [comment]
> Those proxies are usually used from google services and i think they are legit 100%.

Could be; Hard to say for 100% certain though.

According to Google's own [verification guidelines](https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot), that range and hostname matches the pattern for the origin we'd expect to see from their "special case crawlers". Though, that specific user agent doesn't match any of the user agents mentioned at their actual [list of "special case crawlers"](https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#special-case-crawlers).

Does that mean it's fake, then? Not necessarily. They might've just forgotten to list that particular user agent in their list (I've seen that happen plenty of times at the official lists for plenty of different crawlers from plenty of different operators). Does that mean it's real, then? Also not necessarily. That range and hostname pattern definitely *is* used for their "special case crawlers", but I've also definitely seen (plus I recall a few other CIDRAM users mention seeing before) *other* things using that same pattern before too. It's ultimately a bit of a guessing game for us, I think. If you're expecting legitimate traffic from one or more of their "special case crawlers", and/or if whatever is sending those requests doesn't appear to be doing any harm, I'd say it's *probably* legit. If you're totally 100% not expecting any kind of traffic from any of those crawlers at all though, and/or if you notice what seems like potentially harmful or ill-intended traffic, then.. that's a reasonable sign that it's most likely not legit. It's also unfortunately almost impossible to actually ask anyone at Google who might actually know for certain, and rather uncertain whether they would give an honest answer even if we could.

I include a number of such ranges (though definitely not all of them) in the default signature files due to harmful or ill-intended traffic detected from them in the past, either myself, reported in from other users, or reported to various databases where I've seen it (e.g., AbuseIPDB reports), because we generally would want to block such traffic, but as we definitely don't want to be blocking anything legitimate as best as possible, it can be a bit of an annoying balancing act at times, which I can only hope I've gotten as right as possible. Something for me to keep a close eye on whenever I get around to updating the signatures, in any case.

**Comment by eurobank** [comment]
Searching the internet for google proxies, i couldn't find any serious replies. Some say that are used from google stuff "to check things". What things? i ask myself?

On the other hand, google proxies are not for their customers, like googleusercontent crap. 

Anyways, thanks for the tips and the solution.
