### ISSUE TITLE
Aux question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#583]
whats the difference pl between ...
whitelist a request, greylist and bypass

asking because I was trying to negate a block and the only one that worked was to bypass

**Comment by Maikuolan** [comment]
Bypass = Subtracts 1 from the signatures count, but doesn't prevent further checks (subsequent rules can still add to the signatures count).
Whitelist = Sets the signatures count to 0, and prevents any further checks (i.e., if there are any subsequent rules which normally would cause the request to be blocked, they won't cause it to be blocked in the case where the request has been whitelisted).
Greylist = Sets the signatures count to 0, but doesn't prevent further checks (subsequent rules can still add to the signatures count).

If the problem is that there's something (whether that be an IP address, a user agent, or whatever) being blocked, which you absolutely do *not* want to be blocked under *any* circumstances (i.e., you want to ensure that it's always allowed through), use whitelisting (though I would recommend not using whitelisting for anything other than an IP address or CIDR, as things like user agents can, of course, be easily, arbitrarily set by the requesting entity to whatever they want, whenever they want). What I normally tend to use whitelisting for: Myself (if, for whatever reason, I find myself being blocked from my own installations), and for the IP addresses where my cronjobs originate (because these'll usually originate from somewhere within the same network where the website in question is hosted and therefore have a high likelihood of being blocked due to being recognised as originating from a cloud service, and that tends to interfere with whatever I'm trying to achieve with those cronjobs). I don't normally use it for anything else.

By creating a whitelist rule, whatever triggers the rule simply won't be blocked, as everything to that point will be negated and no subsequent rules will be processed.

If the problem is that there's something being blocked, the thing being blocked is being blocked for multiple different reasons or due to several different signatures, and you don't particularly want it being blocked for those particular reasons, but don't 100% trust the requesting entity (e.g., maybe someone is proxying through a hosting provider while simultaneously using an outdated browser and tripping against various different modules at the same time like the SFS or the AbuseIPDB module, causing them to be blocked for multiple reasons, and they aren't technically doing anything malicious and so, as far as you can tell, they should be allowed through, but the number and nature of the "false positives" at hand are a little too complicated to bypass one by one, or doing so could cause problems elsewhere, and the fact that they're connecting to your website in that way is somewhat suspicious in itself, so you want to allow them through on that basis, but you've got a few subsequent rules to catch them out just *in case* they try to do something malicious, and you want them to still be blocked in the event that those subsequent rules are triggered), use greylisting. There isn't anything that I normally use greylisting for personally, and the use-cases for it are rare, but not zero, and so, it remains important that CIDRAM supports the ability to greylist requests.

By creating a greylist rule, you can negate everything which might've caused the request to be blocked *up to that point*, while still allowing subsequent rules to potentially block the request when triggered.

If the problem is more concerned about a singular, specific signature, specific rule, or some known, predictable, and undesirable effect of some combination thereof which could potentially affect any inbound request, and less concerned about the nature of who's being affected, or if the problem concerns a singular problematic signature which can't be simply removed or deleted by any convenient means without unwanted side-effects (e.g., there's a specific signature in the default signature files which you disagree with and think shouldn't be there, perceiving it as erroneous, as a false positive, mistake, or something else, but you nonetheless want to be able to continue using the signature file which contains it because said signature file is still useful for your installation, so simply deactivating the entire signature file isn't a viable means of dealing with the problematic signature), use a bypass.

By creating a bypass rule whose conditions precisely match the conditions of the unwanted signature or rule (typically with a condition to check the signatures count and block reason too, to ensure the bypass isn't triggered by anything other than the specific unwanted signature or rule having been triggered), you can negate the effects of that unwanted signature or rule without otherwise affecting how the request would be processed or the determination for whether it should be blocked.

**Comment by mikeruss1** [comment]
thank you - very helpful

incidentally the rule that has the bypass doesnt come up in the list of rules that were executed in IP Testing
