### ISSUE TITLE
Caching days for BGPview and IP_API

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#589]
Hi,

I get more and more Rate Limited warnings when one the above is active, due to MULTIPLE simultaneous cloud hits from different IPs (from the same network and for the same pages).

And after that nothing is blocked for a few minutes.

I see that the default days for caching that data is 15 days (if i'm not wrong). Could that be configurable at least, since that kind of data (countries, asns) do not change that much.

That way we could improve the issue (but not solve it).

**Comment by Maikuolan** [comment]
Was working on this yesterday, and will continue today, hopefully being able to push out some new commits soon, maybe later this afternoon if all goes well. Had planned on pushing out some new commits before replying, but have been a little delayed due to other things getting in the way a bit with work and home, so replying now briefly to confirm progress. Anyway, should have something up for this soon. :-)

**Comment by Maikuolan** [comment]
Done. It can now be configured via the **`expire_good`** and **`expire_bad`** directives. :-)

(In this context, "bad data" means we either failed to communicate with the API, or we successfully communicated with the API but it returned useless information, e.g., if it says the ASN is unknown, the country is unknown, etc; "good data" means we successfully communicated with the API and it returned data we can use).
