### ISSUE TITLE
Anyone know ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#596]
getting a LOT of traffic from facebook IPs using a UA of facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)

the link doesnt indicate that it would try to rip the whole site which is what its trying to do.

its acting like a site stripper, fetch all the pages then all the images, but not the js or css.

its blocked but still trying

anyone know what is the likely mechanism behind this?

thanks !

**Comment by Maikuolan** [comment]
Can you check the IPs for those requests to see which ASNs they're originating from?

If it's anything other than 32934, it isn't Facebook, because (according to Facebook's own documentation) all legitimate facebookexternalhit/1.1 requests should originate from that specific ASN only.

**Comment by mikeruss1** [comment]
def AS32934  ·  Facebook, Inc.
deny from 173.252.64.0/19
deny from 173.252.96.0/19
deny from 69.171.224.0/20

usually externalhit requests come from the user IP

**Comment by Maikuolan** [comment]
Hm.. I *had* thought that their bot only crawled specific, individual pages when a user shares said specific, individual page at the platform, for the purpose of generating page previews and descriptions for the share. If it's now attempting to rip entire websites, that would suggest that their bot has evolved into some kind of crawler or scraper, or at least, that they're using the same user agent for some kind of crawler or scraper at their platform. No idea *why* they would need such a thing, or would need to crawl an entire website or such. Seems a bit weird.

Worth noting that if any of the platforms which CIDRAM supports verification for become problematic, the same mechanism CIDRAM uses to verify them can be flipped on its head to aggressively block them outright if need be, by changing a few of the checkboxes at the configuration page, like so (unselecting the red-marked checkboxes, and selecting the green-marked checkboxes):

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/364b6497-306a-4c2b-a39f-ec4b2796147a)

Of course, although doing that should prevent any unwanted scraping from their bot, the downside to doing that is that if any Facebook users were to *actually* try sharing one of your website's pages at the platform, the generated page preview and description for the share would most likely just show the CIDRAM access denied page instead of whatever would normally be shown for the page, so.. pros and cons.

In any case.. No idea why their bot would be behaving like that, aside from speculating on the possibility of them experimenting with.. something.. as part of some new idea they might have, like a lot of the various other nonsense they've tried doing in the past. Would just be speculating though.

**Comment by mikeruss1** [comment]
My guess is it is not FB bot. It's some technical facility available to developers which is being abused for hacking purposes

**Comment by eurobank** [comment]
**Lots of hits from FB that look suspicious:**

User agent: Python/3.10 aiohttp/3.9.3 »
Signatures reference: botua.php:L307, auxiliary.yml:User Agents Block aiohttp »
Why blocked: Bad context (Python/AIO clients not permitted here), User Agents Block aiohttp! »
Infractions: 2 »
Country code lookup: US »
Request method: GET »
Hostname: fwdproxy-ldc-006.fbsv.net »
