### ISSUE TITLE
MemcacheD issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#597]
It seems that when memcacheD is used, the expiration doesn't work well or shown empty in IP Tracking.

**Comment by Maikuolan** [comment]
Yeah. The MemcacheD API *does* support including TTLs where applicable (e.g., in the provided functionality for writing *new* entries to the cache), so entries *should* still expire normally and as expected, but unfortunately, it *doesn't* directly provide any endpoint or function for *fetching* TTLs from entries which already exist, which makes it difficult to determine what those TTLs might be for such entries.

It's possible to telnet into a MemcacheD server and `cachedump` all its keys in entirety along with their TTLs directly to the shell ([*reference*](https://stackoverflow.com/questions/2558706/how-can-i-get-the-expire-time-for-the-particular-item-in-memcached)), but that's the only means I've been able to find to do it, unfortunately (and I suspect, most hosting providers nowadays likely neither like nor allow users on shared hosting plans to mess around with telnet from their accounts, in which case, it likely wouldn't be a viable strategy for CIDRAM for most users).

Unless I'm able to figure out a way to do it or find some kind of reliable strategy, any CIDRAM front-end pages where expiries for cache entries would normally be displayed won't be able to display any expiries when MemcacheD is used.

**Comment by eurobank** [comment]
So, i can use it without any problem? Do i get this right?

**Comment by Maikuolan** [comment]
Yep, you can use it without any problem (aside from being unable to view the expiration times for any entries at the front-end). :-)

**Comment by eurobank** [comment]
great. thanks

**Comment by eurobank** [comment]
I see also my statistics are empty/zero. Why?

**Comment by mikeruss1** [comment]
the expiration issue is not a problem on Redis, should that be available to you

**Comment by eurobank** [comment]
> the expiration issue is not a problem on Redis, should that be available to you

Redis for some reason clears my login session AND Log Settings (!) every few hours, not sure why. For now, only pdo seems to work fine, BUT is has grown to some 20.000+ tracking and becoming slower and slower.

**Comment by mikeruss1** [comment]
I had the same problem with the expansion of tracking. The vast majority of tracked IPs for me are Cloud service blocks. I decided not to track them because they just vary the IP for each GET so its a complete waste of time. It runs along in small 3 figures now.

**Comment by mikeruss1** [comment]
one other issue with memcached, if the server restarts the cache is lost. With redis you can do backups say daily, and when it restarts it is automatically restored.

**Comment by Maikuolan** [comment]
Contemplating the idea of being able to split different parts of the cache to different mechanisms, to be able to make the best of all available options wherever they're most suited while hopefully avoiding the downsides of using any particular mechanism wherever not so well suited, but such a thing, I feel, would need to be relegated to the next major version (v4), as it would require a fair amount of BC-breaking changes to implement (and a fair amount of testing to work out any potential kinks and bugs which'd likely arise as a result). Could be something beneficial for the future though.

**Comment by eurobank** [comment]
I think CIDRAM is already complicated.

**Comment by Maikuolan** [comment]
> I think CIDRAM is already complicated.

Yeah.. It has definitely become like that by this point, and I'm wary of making it any more complicated than it already is.

Keeping the idea as a hard "maybe" for now, without locking anything in as a definite plan (because it *would* likely add another layer of complication). Will drop the idea entirely if we end up coming up with something better between now and then, or some other way of resolving these issues ("then" being.. not sure yet; I have plenty of *ideas* for v4; various notes on my machine I've jotted down over the past few months regarding BC-breaking changes that I *could* implement to try to improve CIDRAM further, and I definitely want to work towards seeing some of those ideas implemented *eventually*; but, there's nothing I would regard as being a particularly high priority right now, and I don't feel there's any kind of strong imperative to rush into it right away; minus a few occasional hiccups such as those affecting the cache, IP tracking expiries, non-persistent statistics, etc.. for the most part, AFAIK, everything is already working as intended, without any critical problems, and major version changes always pose at least *some* small level of inconvenience for most people; so.. definitely eventually, but not sure when exactly, and not too soon).

**Comment by eurobank** [comment]
@Maikuolan I think what ALL security scripts and plugins must consider, is the fact that **in 2024 IP based tracking or blocking** is somehow not working any more.

What i see is (for example) 10 simultaneous hits from different IPs and Countries for the same url. Cloud hits probably. Those return an API being limited due to massive usage. That means not working well. 

To be more clear, for example Wordfence for Wordpress (a 5 MILLIONS active installations plugin), messes everything up, when MASSIVE hits happen from the same IP. 

Single IP tracking, blocking. control doesn't work any more as it was 5+ years back. A more clever way must be discovered and implemented.

An other example is AbuseIPDB. So many IPs are reported WRONG and so many IPs are NOT reported (for some reason).

Not sure what works well and what not in 2024......... How to control all those Chinese bots from China, Singapore and HK ? So many things have changed ....

Sorry for thinking loud now .....

**Comment by mikeruss1** [comment]
I think I would incline to determine where exactly we need performance and resilience. Then see if more focused changes would help.  Keep it Simple !

**Comment by eurobank** [comment]
I would also like to be able to share more the blocked attempts with others ....
