### ISSUE TITLE
Bobuam issue?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#609]
Could you check the outdated browser code pl? I have the earliest accepted for Chrome as 62, using latest 2024.174.0

this is accepted
Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.1401.1907 Mobile Safari/537.36

this is rejected
Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.6477.1088 Mobile Safari/537.36

it looks like anything with Android ..... Build/OPD3 .... is accepted regardless of the Chrome version

might be me .. I have a set of Aux rules surrounding these like turning off logging and recaptcha, but the distinction betweem Android/Build and iPhone is odd.

**Comment by Maikuolan** [comment]
The specific part of the user agent causing it to be accepted regardless is the `Build/` part.

The line of code and regular expression in question:

```PHP
if ($Chromium = preg_match('%^(?i)(?!.*edg(?:a|e|ios)\/)(?!.* build\/)(?!.* Favicon).*chrom(?:e|ium)\/(\d+)\.\d+.*$%', $this->BlockInfo['UA'], $rebt)) {
```

Whether that exemption was added due to Android or something else, I don't know for certain, though I doubt it, because if I was to exempt Android, I would be more inclined to actually match against "Android" rather than something peripheral in the user agent like "Build", so I suspect, there's likely some other legitimate, real thing out there which includes "Build" in its user agent, but messes up the Chrome version token enough to justify an exemption else risk false positives. I would need to ask MacMathan about that though, as the exemption has been in place since back when he was maintaining BOBUAM, and if I was ever told what the reason was, I don't remember it, unfortunately. I'll send him a message when I get a moment.

**Comment by mikeruss1** [comment]
looks like the bad guys have found it, a while ago it was a few a day,now its 40-50. Looking very unlike normal users.

**Comment by mikeruss1** [comment]
any idea if and when pl ?
if its going to be a while I can add an aux rule

**Comment by Maikuolan** [comment]
Will be busy with work the next few hours, but I'll push a fix for this later tonight. Still don't know what the exemption was for (haven't had time to reach out or look into it deeply yet), but I should be able to work around it anyway.

**Comment by Maikuolan** [comment]
Fixed and pushed. :-)

**Comment by mikeruss1** [comment]
Thank you
