### ISSUE TITLE
Bug on Updates page

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#610]
CIDRAM core says I am on 3.7 242040. Click hide non updated, says I am on 3.6 241690

Home page says 3.6

**Comment by Maikuolan** [comment]
Haven't been able to replicate the problem at my end. Does it still persist at your end? Wondering whether it might've been some kind of temporary glitch with processing the components metadata or something.

**Comment by mikeruss1** [comment]
still there, unchanged for 3-4 days
should I try updating to 3.7?

**Comment by Maikuolan** [comment]
Hrm.. Give it a try, I guess.

I tried manually setting the version information in the components metadata for my local CIDRAM copy to something earlier, in order to be able to have the CIDRAM core be displayed when the hide non-outdated filter is active (seeing as, if already up-to-date, it would hide it, making it impossible to test for the bug at hand), but I couldn't replicate the bug regardless. That being the case, I'm guessing there might've been some kind of problem in the code prior to the current latest version that I might've just fixed on-the-fly without thinking too much on it, and that the bug could be related to that (which would explain why I haven't been able to replicate it), but I'm not 100% sure. If my guess is right, updating should fix the problem, but either way, once updated, it would be tricky to actually test to confirm whether the bug still persists due to then being up-to-date, and the affected component no longer something to be displayed when the hide non-outdated filter is active (at least, until the next time it's updated again, rendering it once more outdated).

We can always just leave the issue open and on the backburner for the moment, and recheck whether the bug still persists the next time something in the core is updated and a new update available again.

**Comment by mikeruss1** [comment]
I think I understand that !
I dont think it updated the core, updated the front end and common classes. Says core is 3.7 and click hide updated no reference now for core. Home page says 3.6, all the sub pages says 3.6, and CIDRAM folder holds ...
core.php 139,282 26th July - the file says updated 22/7
protect.php also 26th July
