### ISSUE TITLE
Automattic IPs are blocked

### ISSUE THREAD

**Issue by soumsps** [CIDRAM/CIDRAM#65]
Is it required/necessary to block Automattic IPs in default configuration of CIDRAM. As these IPs are used by jetpack plugin, many users won't be able to use Jetpack Photon due to this.
![cidram](https://user-images.githubusercontent.com/17058535/39226807-5e8d84d6-4872-11e8-8bf8-63a80142ce79.png)

**Comment by Maikuolan** [comment]
TBH, I've not seen any unwanted activity from Automattic personally, but they were added consequent to requests from some users via private channels that claimed to be seeing unwanted activity from Automattic, and insisting that they should be blocked. As per usual, whenever considering whether to add new ASNs or new CIDRs to the signature files, I did my research, and did find records at some BLs indicating unwanted activity (most of it via 192.0.64.0/18, on AbuseIPDB, which.. I do take into consideration when deciding whether to add new ASNs or CIDRs to the signature files, but with much less weight, due to that communication channels with the operators of that BL aren't so good IMO, listings don't seem to expire, and they don't seem to have any real vetting process AFAICT, unlike most other BLs; on the other hand though.. BLs like SFS and the Google Malware Dashboard list nothing for Automattic, suggesting that there's been nothing seen by them, at least).

At that point, there was reason, but the need to block Automattic IPs was somewhat sketchy IMO, but at the same time, there wasn't any evidence that they provided any human endpoints anywhere, direct internet connectivity or anything like that, which suggested that the likelihood of false positives should've been very small, if they were to be added, so going on the idea that blocking them would either block unwanted activity, or not, but that either way, there shouldn't likely be any real problems at least if they were blocked, I added them.. on the premise that no eventual problems ended up emerging, of course.

Given that Jetpack being blocked is clearly a problem.. My current thoughts are:
1. If Jetpack provides some clear way to identify itself (maybe Jetpack has its own UA..?), I could use that to write some specific rules to allow Jetpack through, and just block everything else. This would thus resolve the problem at hand, and keep the users that wanted Automattic's IPs to be blocked happy at the same time.
2. If Jetpack *doesn't* provide some clear way to identify itself (no UA or anything), it'll probably be simpler and less problematic in the long term to just remove Automattic's IPs from the signature files entirely, and to tell the the users that wanted Automattic's IPs to be blocked to add the IPs in question to their custom signature files in order to block the IPs in question (due to being removed from the default signature files). This, of course, they probably won't be happy about, but I'm thinking there are probably more Jetpack users around than users specifically wanting to block Automattic, so.. weighing the numbers, I'd rather keep the majority happy, I think. '^.^

That in mind.. Any idea whether Jetpack has its own UA, or some other way to identify it that could be used?

**Comment by Maikuolan** [comment]
*Marking issue as "False Positive" due to Jetpack being blocked.*

**Comment by soumsps** [comment]
@Maikuolan i think jetpack have UA 

User Agent: Jetpack by WordPress.com

```
ID: 9
Date/Time: Wed, 25 Apr 2018 10:03:40 +0530
IP Address: 192.0.91.149
Query: for=jetpack&token=SS9ZC%2352%40tZSS%5E%4047375P55OqOZC4tC2%3A1%3A1×tamp=1524630820&nonce=VL2trVRVJu&body-hash=xFcKh8qr4jJ4rfw3vkhkKNR9sfs%3D&signature=zkx9KjbN1kEIqAmj1vIF9ZqditA%3D
Referrer: https://example.com/xmlrpc.php?for=jetpack&token=SS9ZC%2352%40tZS5E%4047375P55OqOZC4tC2%3A1%3A1×tamp=1524630820&nonce=VL2trVRVJu&body-hash=xFcKh8qr4jJ4rfw3vkhkR9sfs%3D&signature=zkx9KjbN1kEIqAmj1vIF9ZqditA%3D
Signatures Count: 1
Signatures Reference: 192.0.64.0/18
Why Blocked: Cloud service ("Automattic", L19853:F0, [US])!
User Agent: Jetpack by WordPress.com
Reconstructed URI: https://example.com/xmlrpc.php?for=jetpack&token=SS5E%4047375P55OqOZC4tC2%3A1%3A1×tamp=1524630820&nonce=VL2trVRVJu&body-hash=xFcKh8qr4D&signature=zkx9KjbN1kEIqAmj1vIF9ZqditA%3D
reCAPTCHA State: Enabled.
```

BTW i am not sure whether CIDRAM is blocking Jetpack Photon or not.... because my images did not loaded by Jetpack even after putting Automattic in ignore list. I raised this issue quickly i guess. I think my problem is with wordpress or jetpack.

**Comment by Maikuolan** [comment]
Cheers. :-)

That's definitely something I can work with. I'll make a start on that shortly.

**Comment by Maikuolan** [comment]
Latest update should resolve the problem (in regards to Jetpack being blocked). Let me know how it goes. :-)

**Comment by Maikuolan** [comment]
Awesome! :-)

*Marking as "fixed" and closing.*

If you do encounter any problems though, let me know, and we can reopen the issue and do whatever else else needs to be done.
