### ISSUE TITLE
Different "Expires" values

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#85]
As you can see below screenshot that CIDRAM showing 2 different expiration value. Bug? 

![screenshot_9](https://user-images.githubusercontent.com/18257605/44096240-75287e98-9ff8-11e8-9f6f-809aa55b59d3.png)

**Comment by ghost** [comment]
I would suspect the first Expire is the cache.dat file expiry date. As it is constantly updated over time it really never expires.

The second expiry date is for BunnyCDN inside cache.dat, at least that is the way I read it.

**Comment by Maikuolan** [comment]
Sorry for the delay. I'll reply to this properly soon. *Marking as "Attention Required".*

**Comment by Maikuolan** [comment]
Currently redesigning the front-end cache page. The new design should be finished within the next few hours, and should resolve this problem. I'll reply again when it's ready.

**Comment by Maikuolan** [comment]
(Also, I'm thinking I'll label this as QA, rather than as a bug. I would regard the problem more as a somewhat misleading page design, rather than as a bug, in the sense that the page is behaving exactly as originally designed, but that design isn't necessarily ideal and could be misleading. Either way though, good spotting, and something to still be fixed).

**Comment by Maikuolan** [comment]
Implemented via d01ff03766315e1657c80943b7c1e1e6a9e7063d. :-)

Closing.
