### ISSUE TITLE
false positive with google chrome & google bot

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#91]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.
ubuntu18.0
### CIDRAM version used (if known, please also include the exact commit hash).
cidram 1.8.0

### Signatures version (if known).
botbrowsers_cidram.inc:L42  2018.261.820

---
## Issue
Please describe the problem here.

### Actual behavior
blocks google chrome  latest version ( as of 20/09/2018 ) 69.0.3497.100 (Official Build) (64-bit)

### Steps to reproduce the behavior

step 1 update google chrome

```
ID: 2050 »
Script Version: CIDRAM v1.8.0 »
Date/Time: Thu, 20 Sep 2018 22:59:39 +1200 »
IP Address: xxxxxx »
Hostname: xxxx »
Signatures Count: 1 »
Signatures Reference: botbrowsers_cidram.inc:L42 »
Why Blocked: Ambiguos browser ID (SC)! »
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 »
```

also blocks google bot

```
Script Version: CIDRAM v1.8.0 »
Date/Time: Thu, 20 Sep 2018 23:00:18 +1200 »
IP Address: 66.249.73.85 »
Hostname: crawl-66-249-73-85.googlebot.com »
Signatures Count: 1 »
Signatures Reference: botbrowsers_cidram.inc:L42 »
Why Blocked: Ambiguos browser ID (SC)! »
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »
```

**Comment by Maikuolan** [comment]
Thanks for reporting this. :+1: 

The user agents cited by the logged block events above definitely look like legitimate user agents for the latest version of Google Chrome. Just compared them against my own browser's user agent, and aside from the OS component (because I'm running a slightly older OS), they're the same as my own browser's user agent.

Seems to be a false positive in the *Browser blocklist for ancient UA's* module. As per the "signatures reference" (`botbrowsers_cidram.inc:L42`), the signature causing the block:

```PHP
$Trigger(preg_match('%(?i)(?!.*edg(?:a|e|ios)\/.*)(?=.*safari)(?=.*(?:chrom(?:e|ium))).*%',$CIDRAM['BlockInfo']['UA']),'Ambiguos browser ID (SC)');
```

Because that particular module is maintained by @macmathan, I'll tag him here, so that he'll know the issue exists and have the opportunity to respond accordingly.

The signature in question may need to be adjusted slightly.

Also worth noting that for any problems which relate specifically to *his* blocklists and modules, support can be found at his BitBucket repository (**[link](https://bitbucket.org/macmathan/blocklists/issues)**). He may ask that you recreate the issue there, but seeing as I'm tagging him here, he can let you know when he sees this as to whether or not that's needed.

**Comment by ghost** [comment]
Oops.

I have a vague idea over why. 
If my suspicion is correct, I'll have an update out within the next few hours.

In the meantime, and always valid for all my lists and modules, please create an issue over at bitbucket - as specified in the update page of CIDRAM.

**Comment by ghost** [comment]
I have just pushed out a reverted update, in other words the former version's content with a higher version number, as an intermediate solution while I work on this issue.

**Comment by ghost** [comment]
@bigalownz I'd be happy if you open an issue about this at my [issue tracker](https://bitbucket.org/macmathan/blocklists/issues) over at Bitbucket. Feel free to reference this issue when you do it.
@maikuolan You can add a fixed label and close this issue. I'll take it from here in my issue tracker, if needed.

**Comment by ghost** [comment]
Heh, update already out, with a completely changed signature. 
Tested against the reported strings, and all seems OK this time.

**Comment by Maikuolan** [comment]
@macmathan Cheers. :+1: 

*Marking as "fixed" and closing.*
