### ISSUE TITLE
PHP vulnerability warning, false-positive?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#93]
I'm using PHP 7.2.8 Apache + PHP CLI both.
CIDRAM front-end started showing me this error - https://s.put.re/wKNJAfy.png

But as I checked from [cvedetails page](https://www.cvedetails.com/version-list/74/128/1/PHP-PHP.html), I'm not seeing any vuln on 7.2.8

Could be false-positive? 🤔

**Comment by harryqt** [comment]
> updating isn't super urgent in this case, I think.

Okay, then.. 👍

**Comment by Maikuolan** [comment]
That all said, good to always keep an eye on these warnings of course, as there often are quite severe vulnerabilities found, which will prompt warnings like these. Just that in this particular case.. it's not really so bad at all, but the code for producing the warnings doesn't consider severity currently. In any case though.. I promise that I'm not trying to subversively use fear tactics and such to force people into updating, lol. "^.^

But yeah. When in doubt, feel free to ask, and I can clarify the reason why whatever warnings are put in place, and whether it's something really concerning or just relatively minor. :-)

**Comment by ghost** [comment]
@Maikuolan  I always get false warnings on my "work" server, because it runs on Debian stable which backport the security patches rather than change to a newer package version mid-OS-version-release. 
Anyone else also using a *nix server with an OS that uses this approach will have unjustified warnings as well. Just mention it as info to build some knowledge as I really don't care myself due to the fact that I get the needed security updates and it isn't online. ;)

**Comment by Maikuolan** [comment]
Cool cool.. And good to know. Not quite sure how I could approach backports at the moment, as the checks currently just work from version numbers alone, but it might be something I'll need to rethink somehow at some point. Anyway, thanks for sharing. :-)
